### ISSUE TITLE
Sending C2D Message to a Module fails

### ISSUE THREAD

**Issue by shaneholder** [Azure/azure-iot-sdk-node#1007]
Hello,

"name": "azure-iot-device"
"version": "1.17.4"

I am attempting to send a message from a C# process to a NodeJS ModuleClient which uses the MQTT transport.

This is the relevant C# code that is sending the message.  
```
await s_serviceClient.SendAsync("mydevice", "hello", new Message(){MessageId="Hi jody", To = "fred"});
```
A corresponding C# client can receive the message with:
```
s_moduleClient.SetMessageHandlerAsync((m, c) =>
          {
            _logger.LogInformation($"received default message SetMessageHandlerAsync {m.MessageId}");
            return Task.FromResult(MessageResponse.Completed);
          }, null);
```

I am attempting to receive the message in Node using:
```
client.on('inputMessage', (m) =>{})
```

I have turned on debugging 
```
$env:DEBUG="azure-iot-device:* azure-iot-device-mqtt:* "
```

And I am seeing that the message I am sending is making it to the MQTT transport layer but is not matching any of the provided _topics.

The topic being received is:
```
devices/mydevice/modules/hello/messages/devicebound/%24.mid=Hi%20jody&%24.to=%2Fdevices%2Fsah-rfidprinter1%2Fmodules%2Fhello%2Fmessages%2FdeviceBound
```

I am also sending a command from the C# process which is received by the node process.
```
 var response = await s_serviceClient.InvokeDeviceMethodAsync("mydevice", "hello" , methodInvocation);
```
Receiving code:
```
client.onMethod(commandMaxMinReport, commandHandler);
```

I guess my question is how can I send a C2D to a ModuleClient so that it can be received?

In my debugging it seemed that the message topic matched the else condition around mqtt.js:766 so I commented out the else condition so that the message property would be added to _topics which matched.  I then found that when the C2D handler was run an emitter was fired with 'message' which was not emitted by module_client.js so I just replicated the inputMessage code in module_client.js and sure enough I could now catch a 'message' in my node process code.  I'm sure this is not the correct behavior but I just wanted to report what I was able to successfully achieve.

Thanks,
Shane

**Comment by anthonyvercolano** [comment]
@shaneholder Are you saying that the method invocation worked and the c2d did not?

**Comment by YoDaMa** [comment]
@shaneholder I'm curious if you change 

```js
client.on('inputMessage', (m) =>{})
```

to

```js
client.on('message', (m) =>{})
```

are you communicating IoT Hub to Module Client or Edge Hub to Module Client? It looks like with a service client set up in C# you're communicating directly 


Service Client ----> IoT Hub ----> Module Client

**Comment by shaneholder** [comment]
I put together a gitrepo to demonstrate the issue I am seeing

https://github.com/shaneholder/iotDeviceMessageIssues

Hopefully this will illustrate the problem.

**Comment by YoDaMa** [comment]
@shaneholder replying in the other thread, since your questions are converging. https://github.com/Azure/azure-iot-sdk-node/issues/1016

**Comment by YoDaMa** [comment]
closing this issue since it's being addressed in a different thread.
