### ISSUE TITLE
Cannot invoke C2D command with JSON argument when using typescript

### ISSUE THREAD

**Issue by rerkcp** [Azure/azure-iot-sdk-node#1008]
# Context

- **OS and version used:** <Ubuntu 20.04>
- **Node.js version:** <v14.17.2>
- **npm version:** <7.20.2> 
- **list of installed packages:** < 
e2e-test@1.0.0 <path>/e2e-test
├── @azure/event-hubs@5.6.0
├── @types/mocha@9.0.0
├── @types/node@16.4.7
├── axios@0.21.1
├── azure-iothub@1.14.2
├── mocha-junit-reporter@2.0.0
├── mocha@9.0.0
├── ts-node@10.1.0
└── typescript@4.3.5 >

### Problem 1: cannot hand JS object to invokeCommand directly
```
const digitalTwinClient = new iothub.DigitalTwinClient(new iothub.IoTHubTokenCredentials(connectionString));
const argument = { Name: 'test', Config: 'someconfig' };
return await digitalTwinClient.invokeCommand(deviceId, 'command', argument);
```
This fails to compile in typescript, because the typescript bindings only allow the argument to be a string.

### Problem 2: SDK adds a layer of escaping when argument is already translated to string containing JSON.
```
const digitalTwinClient = new iothub.DigitalTwinClient(new iothub.IoTHubTokenCredentials(connectionString));
const argument = { Name: 'test', Config: 'someconfig' };
return await digitalTwinClient.invokeCommand(deviceId, 'command', JSON.stringify(argument));
```
This compiles, but the device receives not the expected argument
```
{ "Name": "test", "Config": "someconfig:" }
```
but
```
"{ \"Name\": \"test\", \"Config\": \"someconfig:\" }"
```
which obviously is not the format the device expects the argument to be.

### Workaround (by falling back to JS behavior):
```
const digitalTwinClient = new iothub.DigitalTwinClient(new iothub.IoTHubTokenCredentials(connectionString));
const argument = { Name: 'test', Config: 'someconfig' };
const dummyClient : any = digitalTwinClient;
return await client.invokeCommand(deviceId, 'command', argument);
```

This works, but is unintuitive and eliminates type safety for the invokeCommand and the response.

If a better workaround is available please state, but maybe this should also be something added to the typescript examples.

**Comment by gabrielSoudry** [comment]
Same behavior for direct command

**Comment by gabrielSoudry** [comment]
Same behavior in direct command :+1:

**Comment by anthonyvercolano** [comment]
Fixed in release 09/09/21
