### ISSUE TITLE
[Technical Question] Appropriate use of ModuleClient vs Client

### ISSUE THREAD

**Issue by shaneholder** [Azure/azure-iot-sdk-node#1016]
I started this out on StackOverflow but when I got down to the actual question i wasn't sure if what I found was a bug in behavior or not.

There are two clients in the azure-iot-sdk-node package, ModuleClient and Client.  They seem to have diverging functionality, ModuleClient can create a client using fromEnvironment() but Client can not.  I accidentally created a client using a connection string with a ModuleId using Client.fromConnectionString() and I was surprised when I was able to successfully send a direct method request.

What are the appropriate uses of ModuleClient and Client, is it expected that I can create a client using Client.fromConnectionString() when the string has a ModuleId in it?

**Comment by YoDaMa** [comment]
Hi @shaneholder, glad you're exploring the SDK. 

ModuleClient is principally for working with a client connected to Azure IoT Edge Hub. See here for a tutorial: https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-node-module?view=iotedge-2020-11

DeviceClient aka Client is for working directly with IoT Hub. 

fromEnvironment is because in the case of Edge Hub the container will have environment variables set up for all the authentication and connection purposes. 

You can create a client from a connection string with a ModuleId. See the api docs here: https://docs.microsoft.com/en-us/javascript/api/azure-iot-device/moduleclient?view=azure-node-latest#fromEnvironment_any__Callback_ModuleClient__

So back to your question, 

> What are the appropriate uses of ModuleClient and Client, is it expected that I can create a client using Client.fromConnectionString() when the string has a ModuleId in it?

ModuleClient is for working with an Edge Hub and Modules.

Client is for working with an IoT Hub and 'Devices'.

**Comment by shaneholder** [comment]
Thanks for the information.  Is it appropriate to use a DeviceClient even if I am using a connection string with a ModuleID in it, this is for non-Edge devices.

Regards,
Shane

**Comment by anthonyvercolano** [comment]
You want to create a module client.

**Comment by shaneholder** [comment]
Thanks Anthony, 


Is sending a C2D message to a Module Client supported?

Thanks,
Shane

**Comment by YoDaMa** [comment]
@shaneholder C2D is not supported in Module Clients. For reference there's no C2D enable in Module Clients in the same way there[ is in Device Clients](https://github.com/Azure/azure-iot-sdk-node/blob/master/device/core/src/device_client.ts#L48). This is a limitation of IoT Hub. Also see here: [Currently, modules can't receive cloud-to-device messages or use the file upload feature.](https://docs.microsoft.com/en-us/azure/iot-edge/module-development?view=iotedge-2020-11) and here: [Question: Cloud to device/module communication with iot-edge #205](Question: Cloud to device/module communication with iot-edge #205).


If you want to send a message to a moduleClient you could use Direct Methods aka Device Methods (not sure why we use two different namings honestly). Here's a [sample of writing using Module Methods](https://github.com/Azure/azure-iot-sdk-node/blob/master/device/samples/simple_sample_module_method.js).

To send the direct method / device method / module method you can use [Azure IoT Explorer.](https://github.com/Azure/azure-iot-explorer/releases) to make your life easier. Download it then in the "Direct Method" tab of the device use for example this JSON for the Payload:

```JSON
{
    "methodName": "reboot",
    "responseTimeoutInSeconds": 200,
    "payload": {
        "input1": "someInput",
        "input2": "anotherInput"
    }
}
```

For more info check out this page: [IoT Hub Devguide Direct Methods.](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-direct-methods)

**Comment by shaneholder** [comment]
@YoDaMa thanks for the information.  Are there plans to expose C2D functionality for module clients?  Given that the message shows up in MQTT on the client side it seems more like an oversight than an intentional decision.

Also, the C# ModuleClient has the SetMessageHandlerAsync which allows receiving of C2D messages.  IMHO this makes the SDK landscape confusing when functionality is available for one language but not another.

Thanks again for your time.

**Comment by YoDaMa** [comment]
@shaneholder let me know if you need any more help beyond what @BertKleewein has already answered.

**Comment by YoDaMa** [comment]
Hey @shaneholder, to close this loop, you said in the other issue: 

> Replying to @YoDaMa here,
> 
> Yes please. There is confusion in the different language SDK's, as I mentioned the C# SDK implies that messaging to Modules is a supported function.
> 
> Regards,
> Shane

We spoke with the C# team and they are not aware of C2D support. There is also a confusion maybe around how you are referring to the SDKs. You said: 

> @BertKleewein when you say "Officially speaking, modules do not support C2D" are you just speaking about the node SDK? The C# SDK clearly has a way to send and receive messages to a module.
> 
> The ServiceClient has:
> 
> ```
> public abstract Task SendAsync(string deviceId, string moduleId, Message message);
> ```
> 
> Thanks again for your help.


Are you speaking about the C# Service Client, which is different than the Module or Device Client? Are you referring to the [Module-to-Module API in C# Module Clients](https://github.com/Azure/azure-iot-sdk-csharp/blob/322b574d2c19c71241b52060263fc6cca5d81a53/iothub/device/src/ModuleClient.cs#L572)?

Regardless, it is an Edge Hub policy that C2D is not supported over Module Clients. This is not a Node.js specific decision.

**Comment by shaneholder** [comment]
First let me thank you for the continued dialog on this because this is very confusing for me.

Have you had time to review the github repository I created demonstrating the issue.  I just added a C# client  demonstrating receiving messages messages with a ModuleClient, including messages when the client is offline.  

https://github.com/shaneholder/iotDeviceMessageIssues

Thanks again for your patience on this matter.

Regards,
Shane Holder

**Comment by shaneholder** [comment]
Additionally, I just checked out the generator for YeoMan at: 

https://github.com/Azure/generator-azure-iot-edge-module

The [app.js](https://github.com/Azure/generator-azure-iot-edge-module/blob/master/app/templates/app.js) it includes has the following code:
```
client.on('inputMessage', function (inputName, msg) {
          pipeMessage(client, inputName, msg);
        });
```
is that not a message from Azure IOT to an edge module?

That same code is also in the azure-iot-sdk-node/device/samples/simple_sample_module.js

Thanks,
Shane

**Comment by YoDaMa** [comment]
hey @shaneholder, thanks on your patience with understanding the API. Your feedback is invaluable.

https://github.com/shaneholder/iotDeviceMessageIssues/blob/master/client/client.js#L29 demonstrates you've got code focused on communicating from IoTHub to the Module Client.


 ┌────────────────┐              ┌───────────────┐
 │  ModuleClient                  ├────►│    IoTHub                        │
 │                                          │◄────┤                                       │
 └────────────────┘              └───────────────┘

This is different than the use case where you are working with an Edge Hub. If you're using IoT Hub, you can send messages from IoTHub and have the ModuleClient subscribe on the `inputMessages` topic to handle those messages.

**Comment by YoDaMa** [comment]
you're running into some very legitimate confusion. "inputs" are a routing concept.  In Edge, you can route events module to module and also hub to module and module to hub. There are also "outputs".  Both inputs and outputs are named message channels, though the word "channel" is never used in the doc, so it's hard to describe what they are because AFIAK they don't have a name.

Edge has concept docs you can refer to: https://docs.microsoft.com/en-us/azure/iot-edge/module-composition?view=iotedge-2020-11.

**Comment by YoDaMa** [comment]
Additionally Edge Hub has implemented a limited MQTT Broker capability for Pub / Sub, which will circumvent alot of this current confusion. It is in Preview: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-publish-subscribe?view=iotedge-2020-11

**Comment by BertKleewein** [comment]
With the limited broker capability, I would say that it will _eventually_ circumvent this confusion.   There are two heavy caveats that you need to consider:
1. Our client libraries don't support the pub/sub functionality, so you'll need to go to a more generic MQTT library to take advantage of this.  This could involve some challenges, especially around authentication.
2. Because it's in preview, it's likely to evolve, perhaps considerably, before it's generally available.

**Comment by YoDaMa** [comment]
We will go through an update for the [docs in Microsoft API Docs](https://docs.microsoft.com/en-us/javascript/api/azure-iot-device/moduleclient?view=azure-node-latest) too to make the _use_ of Module Clients more clear, as they differentiate from regular `Client` objects.

Other than that, I think we can close this Issue. @shaneholder if you have further questions on C2D or Module To Module, please open another Github Issue so we can continue helping you out.
