### ISSUE TITLE
[Technical Question] : Impact of TLS certificate changes on applications which are using service-sdk.

### ISSUE THREAD

**Issue by rajaggrawal** [Azure/azure-iot-sdk-node#1038]
Regarding **Azure TLS certificate changes**

We have already adapted this change in our IoTAgent application which is using device sdk.

But doubt is w.r.t applications which are using **service-sdk.**
We are not doing certificate pinning in our applications source code which are using service-sdk. 
Does [TLS certificate changes](https://docs.microsoft.com/en-us/azure/security/fundamentals/tls-certificate-changes) shall impact to applications which are using service-sdk ? 
Please let me know if we need to upgrade service-sdk due to this change.

**Comment by anthonyvercolano** [comment]
There should be no impact.

**Comment by rajaggrawal** [comment]
Thanks @anthonyvercolano
