### ISSUE TITLE
[Technical Question] Programmatically declare a parent-child relationship between the devices in IoT Hub using Node SDK

### ISSUE THREAD

**Issue by salomi9** [Azure/azure-iot-sdk-node#1040]
Using the Node SDK, I have programmatically created devices in IoT Hub. I wish to know if the Node SDK provides me the capability to set a device as a child of another device.

Looking at the documentation, I didn't find a way (using SDK). Is there any other way to achieve the same ?

**Comment by anthonyvercolano** [comment]
This would typically be done setting the capabilities of the device
```
deviceIdentity.capabilities.iotEdge = true
```

and setting the deviceScope on the soon to be created child device to the deviceScope of the already created "parent" device.

Sadly I don't have a sample available, but if you squint real hard, you could see what we do in this e2e test:
[end to end test for scoped device](https://github.com/Azure/azure-iot-sdk-node/blob/5450e7a2620b31e642c60a7fb0156d88c588c2fe/e2etests/test/registry.js#L236)

**Comment by danhellem** [comment]
@anthonyvercolano if we think this is worth putting together a sample, let me know, and I can do so

**Comment by salomi9** [comment]
@anthonyvercolano thanks ! Did a bit of research and was able to achieve the same.
According to the REST API there is the deviceScope property
You can find the value of the deviceScope of your Edge Device in its Device Twin.

`
  var device = {
    deviceId: '<MY DEVICE ID>',
    deviceScope: 'ms-azure-iot-edge://<MY EDGE DEVICE ID>-xxxxxxxx'
  };

  registry.create(device,{...});
`
