### ISSUE TITLE
mqtt_translate_error.js unhandled exception 

### ISSUE THREAD

**Issue by ProgrammingPescador** [Azure/azure-iot-sdk-node#106]
# Context
- **OS and version used:**
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
- **Node.js version:** 8.5.0 
- **npm version:** 5.4.2 
- **list of installed packages:**
 ─┬ azure-iot-device@1.1.19
│ ├── azure-iot-common@1.2.0
│ ├─┬ azure-iot-http-base@1.2.0
│ │ ├── azure-iot-common@1.2.0 deduped
│ │ ├── debug@2.6.9 deduped
│ │ └── uuid@2.0.3
│ ├─┬ azure-storage@2.6.0
│ │ ├── browserify-mime@1.2.9
│ │ ├── extend@1.2.1
│ │ ├─┬ json-edm-parser@0.1.2
│ │ │ └── jsonparse@1.2.0
│ │ ├─┬ md5.js@1.3.4
│ │ │ ├─┬ hash-base@3.0.4
│ │ │ │ ├── inherits@2.0.3 deduped
│ │ │ │ └── safe-buffer@5.1.1 deduped
│ │ │ └── inherits@2.0.3
│ │ ├─┬ readable-stream@2.0.6
│ │ │ ├── core-util-is@1.0.2
│ │ │ ├── inherits@2.0.3 deduped
│ │ │ ├── isarray@1.0.0
│ │ │ ├── process-nextick-args@1.0.7
│ │ │ ├── string_decoder@0.10.31
│ │ │ └── util-deprecate@1.0.2
│ │ ├─┬ request@2.81.0
│ │ │ ├── aws-sign2@0.6.0
│ │ │ ├── aws4@1.6.0
│ │ │ ├── caseless@0.12.0
│ │ │ ├─┬ combined-stream@1.0.5
│ │ │ │ └── delayed-stream@1.0.0
│ │ │ ├── extend@3.0.1
│ │ │ ├── forever-agent@0.6.1
│ │ │ ├─┬ form-data@2.1.4
│ │ │ │ ├── asynckit@0.4.0
│ │ │ │ ├── combined-stream@1.0.5 deduped
│ │ │ │ └── mime-types@2.1.17 deduped
│ │ │ ├─┬ har-validator@4.2.1
│ │ │ │ ├─┬ ajv@4.11.8
│ │ │ │ │ ├── co@4.6.0
│ │ │ │ │ └─┬ json-stable-stringify@1.0.1
│ │ │ │ │   └── jsonify@0.0.0
│ │ │ │ └── har-schema@1.0.5
│ │ │ ├─┬ hawk@3.1.3
│ │ │ │ ├─┬ boom@2.10.1
│ │ │ │ │ └── hoek@2.16.3 deduped
│ │ │ │ ├─┬ cryptiles@2.0.5
│ │ │ │ │ └── boom@2.10.1 deduped
│ │ │ │ ├── hoek@2.16.3
│ │ │ │ └─┬ sntp@1.0.9
│ │ │ │   └── hoek@2.16.3 deduped
│ │ │ ├─┬ http-signature@1.1.1
│ │ │ │ ├── assert-plus@0.2.0
│ │ │ │ ├─┬ jsprim@1.4.1
│ │ │ │ │ ├── assert-plus@1.0.0
│ │ │ │ │ ├── extsprintf@1.3.0
│ │ │ │ │ ├── json-schema@0.2.3
│ │ │ │ │ └─┬ verror@1.10.0
│ │ │ │ │   ├── assert-plus@1.0.0
│ │ │ │ │   ├── core-util-is@1.0.2 deduped
│ │ │ │ │   └── extsprintf@1.3.0 deduped
│ │ │ │ └─┬ sshpk@1.13.1
│ │ │ │   ├── asn1@0.2.3
│ │ │ │   ├── assert-plus@1.0.0
│ │ │ │   ├─┬ bcrypt-pbkdf@1.0.1
│ │ │ │   │ └── tweetnacl@0.14.5 deduped
│ │ │ │   ├─┬ dashdash@1.14.1
│ │ │ │   │ └── assert-plus@1.0.0
│ │ │ │   ├─┬ ecc-jsbn@0.1.1
│ │ │ │   │ └── jsbn@0.1.1 deduped
│ │ │ │   ├─┬ getpass@0.1.7
│ │ │ │   │ └── assert-plus@1.0.0
│ │ │ │   ├── jsbn@0.1.1
│ │ │ │   └── tweetnacl@0.14.5
│ │ │ ├── is-typedarray@1.0.0
│ │ │ ├── isstream@0.1.2
│ │ │ ├── json-stringify-safe@5.0.1
│ │ │ ├─┬ mime-types@2.1.17
│ │ │ │ └── mime-db@1.30.0
│ │ │ ├── oauth-sign@0.8.2
│ │ │ ├── performance-now@0.2.0
│ │ │ ├── qs@6.4.0
│ │ │ ├── safe-buffer@5.1.1
│ │ │ ├── stringstream@0.0.5
│ │ │ ├─┬ tough-cookie@2.3.3
│ │ │ │ └── punycode@1.4.1
│ │ │ ├─┬ tunnel-agent@0.6.0
│ │ │ │ └── safe-buffer@5.1.1 deduped
│ │ │ └── uuid@3.1.0
│ │ ├── underscore@1.8.3 deduped
│ │ ├── uuid@3.1.0
│ │ ├── validator@3.35.0
│ │ ├─┬ xml2js@0.2.7
│ │ │ └── sax@0.5.2
│ │ └── xmlbuilder@0.4.3
│ ├─┬ debug@2.6.9
│ │ └── ms@2.0.0
│ ├── lodash@4.17.4
│ ├─┬ machina@2.0.0
│ │ └── lodash@3.10.1
│ └── traverse@0.6.6
├─┬ azure-iot-device-mqtt@1.2.0
│ ├── azure-iot-common@1.2.0 deduped
│ ├── azure-iot-device@1.1.19 deduped
│ ├─┬ azure-iot-mqtt-base@1.2.0
│ │ ├── azure-iot-common@1.2.0 deduped
│ │ ├── machina@2.0.0 deduped
│ │ └─┬ mqtt@2.13.0
│ │   ├─┬ commist@1.0.0
│ │   │ ├── leven@1.0.2
│ │   │ └── minimist@1.2.0 deduped
│ │   ├─┬ concat-stream@1.6.0
│ │   │ ├── inherits@2.0.3 deduped
│ │   │ ├─┬ readable-stream@2.3.3
│ │   │ │ ├── core-util-is@1.0.2 deduped
│ │   │ │ ├── inherits@2.0.3 deduped
│ │   │ │ ├── isarray@1.0.0 deduped
│ │   │ │ ├── process-nextick-args@1.0.7 deduped
│ │   │ │ ├── safe-buffer@5.1.1 deduped
│ │   │ │ ├─┬ string_decoder@1.0.3
│ │   │ │ │ └── safe-buffer@5.1.1 deduped
│ │   │ │ └── util-deprecate@1.0.2 deduped
│ │   │ └── typedarray@0.0.6
│ │   ├─┬ end-of-stream@1.4.0
│ │   │ └─┬ once@1.4.0
│ │   │   └── wrappy@1.0.2
│ │   ├─┬ help-me@1.1.0
│ │   │ ├─┬ callback-stream@1.1.0
│ │   │ │ ├── inherits@2.0.3 deduped
│ │   │ │ └── readable-stream@2.0.6 deduped
│ │   │ ├─┬ glob-stream@6.1.0
│ │   │ │ ├── extend@3.0.1
│ │   │ │ ├─┬ glob@7.1.2
│ │   │ │ │ ├── fs.realpath@1.0.0
│ │   │ │ │ ├─┬ inflight@1.0.6
│ │   │ │ │ │ ├── once@1.4.0 deduped
│ │   │ │ │ │ └── wrappy@1.0.2 deduped
│ │   │ │ │ ├── inherits@2.0.3 deduped
│ │   │ │ │ ├─┬ minimatch@3.0.4
│ │   │ │ │ │ └─┬ brace-expansion@1.1.8
│ │   │ │ │ │   ├── balanced-match@1.0.0
│ │   │ │ │ │   └── concat-map@0.0.1
│ │   │ │ │ ├── once@1.4.0 deduped
│ │   │ │ │ └── path-is-absolute@1.0.1
│ │   │ │ ├─┬ glob-parent@3.1.0
│ │   │ │ │ ├─┬ is-glob@3.1.0
│ │   │ │ │ │ └── is-extglob@2.1.1
│ │   │ │ │ └── path-dirname@1.0.2
│ │   │ │ ├── is-negated-glob@1.0.0
│ │   │ │ ├─┬ ordered-read-streams@1.0.1
│ │   │ │ │ └── readable-stream@2.0.6 deduped
│ │   │ │ ├─┬ pumpify@1.3.5
│ │   │ │ │ ├── duplexify@3.5.1 deduped
│ │   │ │ │ ├── inherits@2.0.3 deduped
│ │   │ │ │ └── pump@1.0.2 deduped
│ │   │ │ ├─┬ readable-stream@2.3.3
│ │   │ │ │ ├── core-util-is@1.0.2 deduped
│ │   │ │ │ ├── inherits@2.0.3 deduped
│ │   │ │ │ ├── isarray@1.0.0 deduped
│ │   │ │ │ ├── process-nextick-args@1.0.7 deduped
│ │   │ │ │ ├── safe-buffer@5.1.1 deduped
│ │   │ │ │ ├─┬ string_decoder@1.0.3
│ │   │ │ │ │ └── safe-buffer@5.1.1 deduped
│ │   │ │ │ └── util-deprecate@1.0.2 deduped
│ │   │ │ ├── remove-trailing-separator@1.1.0
│ │   │ │ ├─┬ to-absolute-glob@2.0.1
│ │   │ │ │ ├─┬ extend-shallow@2.0.1
│ │   │ │ │ │ └── is-extendable@0.1.1
│ │   │ │ │ ├─┬ is-absolute@0.2.6
│ │   │ │ │ │ ├─┬ is-relative@0.2.1
│ │   │ │ │ │ │ └─┬ is-unc-path@0.1.2
│ │   │ │ │ │ │   └── unc-path-regex@0.1.2
│ │   │ │ │ │ └── is-windows@0.2.0
│ │   │ │ │ └── is-negated-glob@1.0.0 deduped
│ │   │ │ └─┬ unique-stream@2.2.1
│ │   │ │   ├── json-stable-stringify@1.0.1 deduped
│ │   │ │   └─┬ through2-filter@2.0.0
│ │   │ │     ├── through2@2.0.3 deduped
│ │   │ │     └── xtend@4.0.1 deduped
│ │   │ ├─┬ through2@2.0.3
│ │   │ │ ├─┬ readable-stream@2.3.3
│ │   │ │ │ ├── core-util-is@1.0.2 deduped
│ │   │ │ │ ├── inherits@2.0.3 deduped
│ │   │ │ │ ├── isarray@1.0.0 deduped
│ │   │ │ │ ├── process-nextick-args@1.0.7 deduped
│ │   │ │ │ ├── safe-buffer@5.1.1 deduped
│ │   │ │ │ ├─┬ string_decoder@1.0.3
│ │   │ │ │ │ └── safe-buffer@5.1.1 deduped
│ │   │ │ │ └── util-deprecate@1.0.2 deduped
│ │   │ │ └── xtend@4.0.1 deduped
│ │   │ └── xtend@4.0.1 deduped
│ │   ├── inherits@2.0.3 deduped
│ │   ├── minimist@1.2.0
│ │   ├─┬ mqtt-packet@5.4.0
│ │   │ ├─┬ bl@1.2.1
│ │   │ │ └── readable-stream@2.0.6 deduped
│ │   │ ├── inherits@2.0.3 deduped
│ │   │ ├── process-nextick-args@1.0.7 deduped
│ │   │ └── safe-buffer@5.1.1 deduped
│ │   ├─┬ pump@1.0.2
│ │   │ ├── end-of-stream@1.4.0 deduped
│ │   │ └── once@1.4.0 deduped
│ │   ├─┬ readable-stream@2.3.3
│ │   │ ├── core-util-is@1.0.2 deduped
│ │   │ ├── inherits@2.0.3 deduped
│ │   │ ├── isarray@1.0.0 deduped
│ │   │ ├── process-nextick-args@1.0.7 deduped
│ │   │ ├── safe-buffer@5.1.1 deduped
│ │   │ ├─┬ string_decoder@1.0.3
│ │   │ │ └── safe-buffer@5.1.1 deduped
│ │   │ └── util-deprecate@1.0.2 deduped
│ │   ├── reinterval@1.1.0
│ │   ├─┬ split2@2.2.0
│ │   │ └── through2@2.0.3 deduped
│ │   ├─┬ websocket-stream@5.0.1
│ │   │ ├─┬ duplexify@3.5.1
│ │   │ │ ├── end-of-stream@1.4.0 deduped
│ │   │ │ ├── inherits@2.0.3 deduped
│ │   │ │ ├── readable-stream@2.0.6 deduped
│ │   │ │ └── stream-shift@1.0.0
│ │   │ ├── inherits@2.0.3 deduped
│ │   │ ├─┬ readable-stream@2.3.3
│ │   │ │ ├── core-util-is@1.0.2 deduped
│ │   │ │ ├── inherits@2.0.3 deduped
│ │   │ │ ├── isarray@1.0.0 deduped
│ │   │ │ ├── process-nextick-args@1.0.7 deduped
│ │   │ │ ├── safe-buffer@5.1.1 deduped
│ │   │ │ ├─┬ string_decoder@1.0.3
│ │   │ │ │ └── safe-buffer@5.1.1 deduped
│ │   │ │ └── util-deprecate@1.0.2 deduped
│ │   │ ├── safe-buffer@5.1.1 deduped
│ │   │ ├─┬ ws@3.2.0
│ │   │ │ ├── async-limiter@1.0.0
│ │   │ │ ├── safe-buffer@5.1.1 deduped
│ │   │ │ └── ultron@1.1.0
│ │   │ └── xtend@4.0.1 deduped
│ │   └── xtend@4.0.1
│ ├─┬ debug@3.1.0
│ │ └── ms@2.0.0 deduped
│ └── machina@2.0.0 deduped
├── ipp@1.1.0
├── n@2.1.8
├── net@1.0.2
├─┬ node-printer@1.0.2
│ └── underscore@1.8.3
└── polly-js@1.4.3
 
- **cloned repo:** 
"azure-iot-device": "^1.1.19",
"azure-iot-device-mqtt": "^1.2.0",
 

# Description of the issue:
Exception generated in azure-iot-mqtt-base/lib/mqtt_translate_error.js:43, mqttError or mqttError.message is undefined.  At the time the event was being sent a disconnect event was received in the client.  Two devices, in different countries connected to the same hub, received the disconnect event at the same time.

# Code sample exhibiting the issue:
			var messageData = JSON.stringify({deviceId: deviceId, heartbeat: heartbeatTime.toISOString()});
			var message = new Message(messageData);
			client.sendEvent(message, function(err) {
			if(!err) {
				logMessage("Heartbeat sent to hub", 0);
			}
			else {
				logMessage("Could not send heartbeat to hub: " + err.toString(), 2);
			}

# Console log of the issue:
/home/pi/Visible/node_modules/azure-iot-mqtt-base/lib/mqtt_translate_error.js:43
    if (mqttError.message.indexOf('client disconnecting') > -1) {
                         ^

TypeError: Cannot read property 'indexOf' of undefined
    at Object.translateError (/home/pi/Visible/node_modules/azure-iot-mqtt-base/lib/mqtt_translate_error.js:43:26)
    at /home/pi/Visible/node_modules/azure-iot-device-mqtt/lib/mqtt.js:233:73
    at constructor.publish (/home/pi/Visible/node_modules/azure-iot-mqtt-base/lib/mqtt_base.js:46:84)
    at constructor.handle (/home/pi/Visible/node_modules/machina/lib/machina.js:613:25)
    at constructor.Fsm.(anonymous function) [as handle] (/home/pi/Visible/node_modules/machina/lib/machina.js:466:63)
    at MqttBase.publish (/home/pi/Visible/node_modules/azure-iot-mqtt-base/lib/mqtt_base.js:154:19)
    at constructor.sendEvent (/home/pi/Visible/node_modules/azure-iot-device-mqtt/lib/mqtt.js:230:37)
    at constructor.handle (/home/pi/Visible/node_modules/machina/lib/machina.js:613:25)
    at constructor.Fsm.(anonymous function) [as handle] (/home/pi/Visible/node_modules/machina/lib/machina.js:466:63)
    at Mqtt.sendEvent (/home/pi/Visible/node_modules/azure-iot-device-mqtt/lib/mqtt.js:374:19)

**Comment by pierreca** [comment]
most definitely a bug. thanks for reporting it. we need to test that the `error.message` field exists before calling `indexOf` on it.

**Comment by ProgrammingPescador** [comment]
Pierre

Thank you for replying.  Only too happy to help.

Are you able to offer any further assistance with some other issues that we
are seeing?  The devices we have connected will lose connection from the
hub after a number of hours, even though I have implemented a heartbeat
event from the device every thirty minutes.  I am
client.fromConnectionString() to create the client instance.  Should I be
using the fromsharedAccessSignature() method instead and mange the
expiration myself?

Is there anywhere where these scenarios are described?

Regards
David Dwyer

**Comment by pierreca** [comment]
We will release the fix for this as part of our next release, in the next couple of days.

**Comment by pierreca** [comment]
The fix is part of the latest release
https://github.com/Azure/azure-iot-sdk-node/releases/tag/2017-10-24
