### ISSUE TITLE
Issue with 1.1.19 of device sdk and 1.2 of mqtt sdk?

### ISSUE THREAD

**Issue by ProgrammingPescador** [Azure/azure-iot-sdk-node#108]
# Context
- **OS and version used:**
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
- **Node.js version:** 8.5.0 
- **npm version:** 5.4.2 
- **list of installed packages:**
 ─┬ azure-iot-device@1.1.19
│ ├── azure-iot-common@1.2.0
│ ├─┬ azure-iot-http-base@1.2.0
│ │ ├── azure-iot-common@1.2.0 deduped
│ │ ├── debug@2.6.9 deduped
│ │ └── uuid@2.0.3
│ ├─┬ azure-storage@2.6.0
│ │ ├── browserify-mime@1.2.9
│ │ ├── extend@1.2.1
│ │ ├─┬ json-edm-parser@0.1.2
│ │ │ └── jsonparse@1.2.0
│ │ ├─┬ md5.js@1.3.4
│ │ │ ├─┬ hash-base@3.0.4
│ │ │ │ ├── inherits@2.0.3 deduped
│ │ │ │ └── safe-buffer@5.1.1 deduped
│ │ │ └── inherits@2.0.3
│ │ ├─┬ readable-stream@2.0.6
│ │ │ ├── core-util-is@1.0.2
│ │ │ ├── inherits@2.0.3 deduped
│ │ │ ├── isarray@1.0.0
│ │ │ ├── process-nextick-args@1.0.7
│ │ │ ├── string_decoder@0.10.31
│ │ │ └── util-deprecate@1.0.2
│ │ ├─┬ request@2.81.0
│ │ │ ├── aws-sign2@0.6.0
│ │ │ ├── aws4@1.6.0
│ │ │ ├── caseless@0.12.0
│ │ │ ├─┬ combined-stream@1.0.5
│ │ │ │ └── delayed-stream@1.0.0
│ │ │ ├── extend@3.0.1
│ │ │ ├── forever-agent@0.6.1
│ │ │ ├─┬ form-data@2.1.4
│ │ │ │ ├── asynckit@0.4.0
│ │ │ │ ├── combined-stream@1.0.5 deduped
│ │ │ │ └── mime-types@2.1.17 deduped
│ │ │ ├─┬ har-validator@4.2.1
│ │ │ │ ├─┬ ajv@4.11.8
│ │ │ │ │ ├── co@4.6.0
│ │ │ │ │ └─┬ json-stable-stringify@1.0.1
│ │ │ │ │   └── jsonify@0.0.0
│ │ │ │ └── har-schema@1.0.5
│ │ │ ├─┬ hawk@3.1.3
│ │ │ │ ├─┬ boom@2.10.1
│ │ │ │ │ └── hoek@2.16.3 deduped
│ │ │ │ ├─┬ cryptiles@2.0.5
│ │ │ │ │ └── boom@2.10.1 deduped
│ │ │ │ ├── hoek@2.16.3
│ │ │ │ └─┬ sntp@1.0.9
│ │ │ │   └── hoek@2.16.3 deduped
│ │ │ ├─┬ http-signature@1.1.1
│ │ │ │ ├── assert-plus@0.2.0
│ │ │ │ ├─┬ jsprim@1.4.1
│ │ │ │ │ ├── assert-plus@1.0.0
│ │ │ │ │ ├── extsprintf@1.3.0
│ │ │ │ │ ├── json-schema@0.2.3
│ │ │ │ │ └─┬ verror@1.10.0
│ │ │ │ │   ├── assert-plus@1.0.0
│ │ │ │ │   ├── core-util-is@1.0.2 deduped
│ │ │ │ │   └── extsprintf@1.3.0 deduped
│ │ │ │ └─┬ sshpk@1.13.1
│ │ │ │   ├── asn1@0.2.3
│ │ │ │   ├── assert-plus@1.0.0
│ │ │ │   ├─┬ bcrypt-pbkdf@1.0.1
│ │ │ │   │ └── tweetnacl@0.14.5 deduped
│ │ │ │   ├─┬ dashdash@1.14.1
│ │ │ │   │ └── assert-plus@1.0.0
│ │ │ │   ├─┬ ecc-jsbn@0.1.1
│ │ │ │   │ └── jsbn@0.1.1 deduped
│ │ │ │   ├─┬ getpass@0.1.7
│ │ │ │   │ └── assert-plus@1.0.0
│ │ │ │   ├── jsbn@0.1.1
│ │ │ │   └── tweetnacl@0.14.5
│ │ │ ├── is-typedarray@1.0.0
│ │ │ ├── isstream@0.1.2
│ │ │ ├── json-stringify-safe@5.0.1
│ │ │ ├─┬ mime-types@2.1.17
│ │ │ │ └── mime-db@1.30.0
│ │ │ ├── oauth-sign@0.8.2
│ │ │ ├── performance-now@0.2.0
│ │ │ ├── qs@6.4.0
│ │ │ ├── safe-buffer@5.1.1
│ │ │ ├── stringstream@0.0.5
│ │ │ ├─┬ tough-cookie@2.3.3
│ │ │ │ └── punycode@1.4.1
│ │ │ ├─┬ tunnel-agent@0.6.0
│ │ │ │ └── safe-buffer@5.1.1 deduped
│ │ │ └── uuid@3.1.0
│ │ ├── underscore@1.8.3 deduped
│ │ ├── uuid@3.1.0
│ │ ├── validator@3.35.0
│ │ ├─┬ xml2js@0.2.7
│ │ │ └── sax@0.5.2
│ │ └── xmlbuilder@0.4.3
│ ├─┬ debug@2.6.9
│ │ └── ms@2.0.0
│ ├── lodash@4.17.4
│ ├─┬ machina@2.0.0
│ │ └── lodash@3.10.1
│ └── traverse@0.6.6
├─┬ azure-iot-device-mqtt@1.2.0
│ ├── azure-iot-common@1.2.0 deduped
│ ├── azure-iot-device@1.1.19 deduped
│ ├─┬ azure-iot-mqtt-base@1.2.0
│ │ ├── azure-iot-common@1.2.0 deduped
│ │ ├── machina@2.0.0 deduped
│ │ └─┬ mqtt@2.13.0
│ │   ├─┬ commist@1.0.0
│ │   │ ├── leven@1.0.2
│ │   │ └── minimist@1.2.0 deduped
│ │   ├─┬ concat-stream@1.6.0
│ │   │ ├── inherits@2.0.3 deduped
│ │   │ ├─┬ readable-stream@2.3.3
│ │   │ │ ├── core-util-is@1.0.2 deduped
│ │   │ │ ├── inherits@2.0.3 deduped
│ │   │ │ ├── isarray@1.0.0 deduped
│ │   │ │ ├── process-nextick-args@1.0.7 deduped
│ │   │ │ ├── safe-buffer@5.1.1 deduped
│ │   │ │ ├─┬ string_decoder@1.0.3
│ │   │ │ │ └── safe-buffer@5.1.1 deduped
│ │   │ │ └── util-deprecate@1.0.2 deduped
│ │   │ └── typedarray@0.0.6
│ │   ├─┬ end-of-stream@1.4.0
│ │   │ └─┬ once@1.4.0
│ │   │   └── wrappy@1.0.2
│ │   ├─┬ help-me@1.1.0
│ │   │ ├─┬ callback-stream@1.1.0
│ │   │ │ ├── inherits@2.0.3 deduped
│ │   │ │ └── readable-stream@2.0.6 deduped
│ │   │ ├─┬ glob-stream@6.1.0
│ │   │ │ ├── extend@3.0.1
│ │   │ │ ├─┬ glob@7.1.2
│ │   │ │ │ ├── fs.realpath@1.0.0
│ │   │ │ │ ├─┬ inflight@1.0.6
│ │   │ │ │ │ ├── once@1.4.0 deduped
│ │   │ │ │ │ └── wrappy@1.0.2 deduped
│ │   │ │ │ ├── inherits@2.0.3 deduped
│ │   │ │ │ ├─┬ minimatch@3.0.4
│ │   │ │ │ │ └─┬ brace-expansion@1.1.8
│ │   │ │ │ │   ├── balanced-match@1.0.0
│ │   │ │ │ │   └── concat-map@0.0.1
│ │   │ │ │ ├── once@1.4.0 deduped
│ │   │ │ │ └── path-is-absolute@1.0.1
│ │   │ │ ├─┬ glob-parent@3.1.0
│ │   │ │ │ ├─┬ is-glob@3.1.0
│ │   │ │ │ │ └── is-extglob@2.1.1
│ │   │ │ │ └── path-dirname@1.0.2
│ │   │ │ ├── is-negated-glob@1.0.0
│ │   │ │ ├─┬ ordered-read-streams@1.0.1
│ │   │ │ │ └── readable-stream@2.0.6 deduped
│ │   │ │ ├─┬ pumpify@1.3.5
│ │   │ │ │ ├── duplexify@3.5.1 deduped
│ │   │ │ │ ├── inherits@2.0.3 deduped
│ │   │ │ │ └── pump@1.0.2 deduped
│ │   │ │ ├─┬ readable-stream@2.3.3
│ │   │ │ │ ├── core-util-is@1.0.2 deduped
│ │   │ │ │ ├── inherits@2.0.3 deduped
│ │   │ │ │ ├── isarray@1.0.0 deduped
│ │   │ │ │ ├── process-nextick-args@1.0.7 deduped
│ │   │ │ │ ├── safe-buffer@5.1.1 deduped
│ │   │ │ │ ├─┬ string_decoder@1.0.3
│ │   │ │ │ │ └── safe-buffer@5.1.1 deduped
│ │   │ │ │ └── util-deprecate@1.0.2 deduped
│ │   │ │ ├── remove-trailing-separator@1.1.0
│ │   │ │ ├─┬ to-absolute-glob@2.0.1
│ │   │ │ │ ├─┬ extend-shallow@2.0.1
│ │   │ │ │ │ └── is-extendable@0.1.1
│ │   │ │ │ ├─┬ is-absolute@0.2.6
│ │   │ │ │ │ ├─┬ is-relative@0.2.1
│ │   │ │ │ │ │ └─┬ is-unc-path@0.1.2
│ │   │ │ │ │ │   └── unc-path-regex@0.1.2
│ │   │ │ │ │ └── is-windows@0.2.0
│ │   │ │ │ └── is-negated-glob@1.0.0 deduped
│ │   │ │ └─┬ unique-stream@2.2.1
│ │   │ │   ├── json-stable-stringify@1.0.1 deduped
│ │   │ │   └─┬ through2-filter@2.0.0
│ │   │ │     ├── through2@2.0.3 deduped
│ │   │ │     └── xtend@4.0.1 deduped
│ │   │ ├─┬ through2@2.0.3
│ │   │ │ ├─┬ readable-stream@2.3.3
│ │   │ │ │ ├── core-util-is@1.0.2 deduped
│ │   │ │ │ ├── inherits@2.0.3 deduped
│ │   │ │ │ ├── isarray@1.0.0 deduped
│ │   │ │ │ ├── process-nextick-args@1.0.7 deduped
│ │   │ │ │ ├── safe-buffer@5.1.1 deduped
│ │   │ │ │ ├─┬ string_decoder@1.0.3
│ │   │ │ │ │ └── safe-buffer@5.1.1 deduped
│ │   │ │ │ └── util-deprecate@1.0.2 deduped
│ │   │ │ └── xtend@4.0.1 deduped
│ │   │ └── xtend@4.0.1 deduped
│ │   ├── inherits@2.0.3 deduped
│ │   ├── minimist@1.2.0
│ │   ├─┬ mqtt-packet@5.4.0
│ │   │ ├─┬ bl@1.2.1
│ │   │ │ └── readable-stream@2.0.6 deduped
│ │   │ ├── inherits@2.0.3 deduped
│ │   │ ├── process-nextick-args@1.0.7 deduped
│ │   │ └── safe-buffer@5.1.1 deduped
│ │   ├─┬ pump@1.0.2
│ │   │ ├── end-of-stream@1.4.0 deduped
│ │   │ └── once@1.4.0 deduped
│ │   ├─┬ readable-stream@2.3.3
│ │   │ ├── core-util-is@1.0.2 deduped
│ │   │ ├── inherits@2.0.3 deduped
│ │   │ ├── isarray@1.0.0 deduped
│ │   │ ├── process-nextick-args@1.0.7 deduped
│ │   │ ├── safe-buffer@5.1.1 deduped
│ │   │ ├─┬ string_decoder@1.0.3
│ │   │ │ └── safe-buffer@5.1.1 deduped
│ │   │ └── util-deprecate@1.0.2 deduped
│ │   ├── reinterval@1.1.0
│ │   ├─┬ split2@2.2.0
│ │   │ └── through2@2.0.3 deduped
│ │   ├─┬ websocket-stream@5.0.1
│ │   │ ├─┬ duplexify@3.5.1
│ │   │ │ ├── end-of-stream@1.4.0 deduped
│ │   │ │ ├── inherits@2.0.3 deduped
│ │   │ │ ├── readable-stream@2.0.6 deduped
│ │   │ │ └── stream-shift@1.0.0
│ │   │ ├── inherits@2.0.3 deduped
│ │   │ ├─┬ readable-stream@2.3.3
│ │   │ │ ├── core-util-is@1.0.2 deduped
│ │   │ │ ├── inherits@2.0.3 deduped
│ │   │ │ ├── isarray@1.0.0 deduped
│ │   │ │ ├── process-nextick-args@1.0.7 deduped
│ │   │ │ ├── safe-buffer@5.1.1 deduped
│ │   │ │ ├─┬ string_decoder@1.0.3
│ │   │ │ │ └── safe-buffer@5.1.1 deduped
│ │   │ │ └── util-deprecate@1.0.2 deduped
│ │   │ ├── safe-buffer@5.1.1 deduped
│ │   │ ├─┬ ws@3.2.0
│ │   │ │ ├── async-limiter@1.0.0
│ │   │ │ ├── safe-buffer@5.1.1 deduped
│ │   │ │ └── ultron@1.1.0
│ │   │ └── xtend@4.0.1 deduped
│ │   └── xtend@4.0.1
│ ├─┬ debug@3.1.0
│ │ └── ms@2.0.0 deduped
│ └── machina@2.0.0 deduped
├── ipp@1.1.0
├── n@2.1.8
├── net@1.0.2
├─┬ node-printer@1.0.2
│ └── underscore@1.8.3
└── polly-js@1.4.3
 
- **cloned repo:** 
"azure-iot-device": "^1.1.19",
"azure-iot-device-mqtt": "^1.2.0",
 

# Description of the issue:
After upgrading to library versions 1.1.19 of device SDK and 1.2 of the mqtt library communication between the device and the hub stops after some time, but the time is not consistent.  No errors or events are generated so there is no code that captures the fault.  We have a call to sendevent every thirty minutes as a heartbeat (which may not be necessary) and we see this stop.  Attempting to call an on device method returns a timeout.

Version 1.1.16 of the two libraries did not display the problem.  My device ran for 12 hours last night sending  heartbeats and I was able to call device methods this morning

Where can I look to determine what may be going wrong?

# Console log of the issue:

**Comment by pierreca** [comment]
Hi - sorry to hear that.
you can set the DEBUG env variable to either `*` (or if it is too verbose at least `device:mqtt,azure-iot-device.Client`) will produce much more details logs.

**Comment by pierreca** [comment]
Also, additional question because methods and d2c events are slightly different:
- are you saying that the MQTT connection seems broken and even the heartbeat messages don't leave the device or do you always see those?
- and what you are seeing is device method callbacks not being called on the device side (as if the subscription had ended?)

**Comment by jtjk** [comment]
This might have something to do with the [73](https://github.com/Azure/azure-iot-sdk-node/issues/73 )

**Comment by ProgrammingPescador** [comment]
I had previously looked at issue 73 mentioned above.  As I am using `fromConnectionString` I investigated `fromSharedAccessKey` but was unable to get that to work.  Are there any examples of how to generate a shared access key and how to use it_  I did Google but was unable to find any that worked!

I have upgraded to Node 8.7 and npm 5.5.1 and am rerunning the tests...

**Comment by jtjk** [comment]
Hi, I did not mean that 73 solves your issue, but SDK team should check if the root cause is same for both issues. 

Btw, node 8.7 is not helping here. I have been testing all major node-versions and only 4.8.4 seems to be reliable.

**Comment by ProgrammingPescador** [comment]
I thought I set the DEBUG environment variable but don't seem to be getting any joy.  I have googled and used DEBUG='*' but don't appear to be getting anything in the debug log file in /var/log, am I doing something wrong?

With regards to the application, I currently am in a situation where Device Explorer sees the device is on line, I can send a message to the device but cannot call a device method Attempting to call a method from device explorer results in a timeout message-

I am going to revert to Node 4..8.4 and see if that helps

**Comment by pierreca** [comment]
Thanks for all the feedback folks, it's really helpful.

when setting the `DEBUG` env variable, logs will be sent to stderr (that's the standard behavior for the `debug` package we're using).

The device status in DeviceExplorer might be slightly out of date, by the way, it's not a reliable way of checking whether a device is online or not. Plus, a device being online doesn't guarantee methods will work (the device has to be subscribed to specific method topics). 

What kind of timeouts are you seeing? after how much time? Is it a `TimeoutError`, a `GatewayTimeoutError` or a `BadDeviceResponseError`?

**Comment by ProgrammingPescador** [comment]
In the scenario I had yesterday the device is connected to the hub and
sending events, I was able to send a message to the device from Device
Explorer that was processed correctly.  when I asked to invoke a method,
that is registered the timeout error was returned.

My testing involves having the device start up and register all direct
methods.  the device then sends a heartbeat event every thirty minutes.  I
will manually call all of the device methods every ten minutes to verify
they are still working and also send a message to the device to verify that
the message is still processed.

Thanks

**Comment by ProgrammingPescador** [comment]
When I am unable to invoke a device method I get error code 504101 returned

**Comment by pierreca** [comment]
OK - I think what happens in that case is that after renewing the shared access signature, the method handlers were not getting reattached - because the device was not responding in time to the method calls, you'd get a timeout.

I can think of 2 things that would help with this issue:
- upgrade to the packages we have just released (`azure-iot-device@1.2.0`) - we have rewritten large parts of this code to be more stable and automatically reattach handlers and resubscribe topics if necessary
- adjust your [method request parameters](https://docs.microsoft.com/en-us/javascript/api/azure-iothub/devicemethodparams?view=azure-iot-typescript-latest), more specifically try adjusting `connectTimeoutInSeconds` (determines the timeout value for IoT Hub to connect to your device) and `responseTimeoutInSeconds` (determines the timeout value for IoT Hub to get the response from the device once connected).

Can you please try this and let us know if that helps? if not we have also improved our logging so I'd suggest to set the `DEBUG` environment variable to: `azure-iot-*` and post them here for us to look at.

**Comment by ProgrammingPescador** [comment]
Hi Pierre

Thanks for the update, for the moment we have implemented a 30 minute client shutdown and reconnect procedure.  This has been run over night and works perfectly.  We have out big product demo today (using the software) and other projects have come up in the last week so I will not be working on this for a while.

Once I am back on the project I will do the updates and let you know what the outcome is

Thanks

**Comment by pierreca** [comment]
@ProgrammingPescador Thanks for the update and good luck with the demo. In that case I'll close the issue for now and we can reopen it or open a new one with new information when you get back on it.
