### ISSUE TITLE
IoT Central. Module component telemetry displays as _unmodeleddata when using AMQP.

### ISSUE THREAD

**Issue by pavel-orlov** [Azure/azure-iot-sdk-node#1135]
### Context

- **iotedge version:** 1.2.9
- **azureiotedge-hub version:** 1.2
- **azure-iot-device version:** 1.18.0
- **azure-iot-device-mqtt version:** 1.16.0
- **azure-iot-device-amqp version:** 1.14.0

### Description
As described [here](https://docs.microsoft.com/en-us/azure/iot-central/core/concepts-telemetry-properties-commands#telemetry) message property `$.sub` is set with a component name. 
When using MQTT as transport, IoT Central app properly displays telemetry and maps it to defined component capabilities. But when using AMQP transport, the app displays telemetry as _unmodeleddata.
[Here](https://docs.microsoft.com/en-us/azure/iot-develop/concepts-convention#telemetry) it says to add `dt-subject` property with a component name, but it doesn't work.
Is it possible to use module component telemetry over AMQP for IoT Central?

**Comment by ymoreiratiti** [comment]
Same problem here, but with HTTP transport

**Comment by rido-min** [comment]
Hi @pavel-orlov,

>Is it possible to use module component telemetry over AMQP for IoT Central?

Do you mean an Edge module using a PnP component? also we'd like to know if is there any reason to prefer AMQP over MQTT to connect devices to Central?

**Comment by anthonyvercolano** [comment]
Released
