### ISSUE TITLE
No support for dt-subject on HTTP Transport

### ISSUE THREAD

**Issue by ymoreiratiti** [Azure/azure-iot-sdk-node#1141]
# Context

- **OS and version used:** <VERSION> Windows 11 with WSL2
- **Node.js version:** <VERSION> 16.15.1
- **npm version:** <VERSION> 8.12.2
- **list of installed packages:** {"azure-iot-device-http": "^1.14.0",}

## Description of the issue

When using the HTTP transport layer, the message property "dt-subject" is transformed to "iothub-app-dt-subject". This makes the Azure Hub API ignore the subject and show the message as unmodeled data.

## Code sample exhibiting the issue

```typescript
const message = new Message(
          JSON.stringify({
            datetimeSignal,
            line,
            version: iotDataCollectorProperties.lastCollectFlightReports,
          }),
        );

        message.properties.add('dt-subject', 'logHistory');
        message.contentType = 'application/json';
        message.contentEncoding = 'utf-8';

        await azureIoTClientMqtt.sendEvent(message);
```

![image](https://user-images.githubusercontent.com/5731429/180674654-dd1ffe5e-597b-4f38-8314-5b76509597ca.png)

-----

Analysing the code I found the code block where all message properties is added to the header with the prefix iothub-app
https://github.com/Azure/azure-iot-sdk-node/blob/26695213809ff87e3e052c8f82de3be3a8afc066/device/transport/http/src/http.ts#L177

-----

The same appear to be happening with `sendEventBatch`. Check this file:
https://github.com/Azure/azure-iot-sdk-node/blob/26695213809ff87e3e052c8f82de3be3a8afc066/device/transport/http/src/http.ts#L278

-----

I believe he should detect when the message property is dt-subject and ignore prefix, so the header should be only "dt-subject".

**Comment by anthonyvercolano** [comment]
Well, um, maybe.  Since PnP is still in preview, it's questionable whether we should be special casing dt-subject.

If you look in some other later preview material, usually in helper samples, you would see this as $.sub

You would find that in 'c'.  Note that 'c' ONLY supports MQTT.  C sharp, much to my surprise, does seem to support what you want for HTTP.

So, why not utilize MQTT.  You can use MQTT over websockets if you face firewall issues.

**Comment by ymoreiratiti** [comment]
In my scenario, I have a cronjob who downloads the log and sends it line by line. Currently, I'm using MQTT and doing an iteration for each file line, but I believe using the batch will be more network optimized.

**Comment by anthonyvercolano** [comment]
@ymoreiratiti I'm not understanding here.

What are your referring to when you say "batch"?  How does "batch" interact with using HTTP?

**Comment by ymoreiratiti** [comment]
@anthonyvercolano for batch i'm refering to [sendEventBatch](https://github.com/Azure/azure-iot-sdk-node/blob/26695213809ff87e3e052c8f82de3be3a8afc066/device/transport/http/src/http.ts#L253). 

You can send multiple messages with one request.

**Comment by anthonyvercolano** [comment]
Released
