### ISSUE TITLE
DPS endpoint is no longer working

### ISSUE THREAD

**Issue by jezzdk** [Azure/azure-iot-sdk-node#1156]
## Context

- **OS and version used:** macOS Ventura 13.0
- **Node.js version:** 16.18.0
- **npm version:** 8.19.3
- **list of installed packages:** 
├── @azure/storage-blob@12.12.0
├── @types/async@3.2.15
├── @types/node@16.18.3
├── @types/ws@7.4.7
├── @types/yargs@17.0.13
├── azure-iot-device-amqp@1.13.8
├── azure-iot-device-http@1.13.8
├── azure-iot-device-mqtt@1.15.8
├── azure-iot-device@1.17.8
├── azure-iot-provisioning-device-mqtt@1.7.12
├── azure-iot-provisioning-device@1.8.12
├── azure-iot-security-symmetric-key@1.7.12
├── https-proxy-agent@5.0.0
├── source-map-support@0.5.21
├── ts-node@8.10.2
├── tslint@6.1.3
├── typescript@4.4.4
└── yargs@17.6.2

## Description of the issue

I've created a simple javascript client based on the examples. I have made sure that every configuration has been set properly. But when I run the client, it fails when trying to provision the device. I have also tried to run a sample from the repo, without changing the code, and it also fails when trying to provision. Both have been working a few weeks ago.

It seems the DPS endpoint is not working. The [Azure status page](https://status.azure.com/en-us/status) shows that it should be working though.

I have registered the device in IoT Central and set the needed env variables. I have double checked that they all are correct.

In the code below, the IOTHUB_DEVICE_DPS_ENDPOINT env variable is set to "global.azure-devices-provisioning.net", as per the documentation. However, I keep getting a "Server unavailable" error.

## Code sample exhibiting the issue

```typescript
public async provisionDeviceClient(): Promise<string> {
  const provisioningSecurityClient = new SymmetricKeySecurityClient(
    process.env.IOTHUB_DEVICE_DPS_DEVICE_ID,
    process.env.IOTHUB_DEVICE_DPS_DEVICE_KEY
  );

  const provisioningClient = ProvisioningDeviceClient.create(
    process.env.IOTHUB_DEVICE_DPS_ENDPOINT,
    process.env.IOTHUB_DEVICE_DPS_ID_SCOPE,
    new ProvisioningTransport(),
    provisioningSecurityClient
  );

  const provisioningPayload = {
    iotcModelId: "xxxxx",
  };

  provisioningClient.setProvisioningPayload(provisioningPayload);

  const connectionString = await new Promise<string>((resolve, reject) => {
    provisioningClient.register((dpsError, dpsResult) => {
      if (dpsError) {
        return reject(dpsError);
      }

      return resolve(
        `HostName=${dpsResult.assignedHub};DeviceId=${dpsResult.deviceId};SharedAccessKey=IOTHUB_DEVICE_DPS_DEVICE_KEY`
      );
    });
  });

  return connectionString;
}
```

The result of `provisioningClient.register()` is an error stating: "Connection refused: Server unavailable". I have tried from several different networks.

The hostname "global.azure-devices-provisioning.net" resolves to "idsu-prod-am-001-su-az.westeurope.cloudapp.azure.com".

**Comment by anthonyvercolano** [comment]
@jezzdk Any possibility you are using some limited time subscription?

**Comment by jezzdk** [comment]
@anthonyvercolano That might be the case, although I don't see any indication of it in IoT Central. Where can I check for this?

**Comment by jezzdk** [comment]
I figured it out now. Turns out I had switched the scope ID and device ID around... Not sure why it has worked earlier. Maybe because I'm an idiot.

**Comment by Selekena** [comment]
What is the DPS instance you are working with here?

**Comment by Selekena** [comment]
can you please share the DPS instance you were working with. Could you also share the full error code that you were getting?

**Comment by jezzdk** [comment]
> can you please share the DPS instance you were working with. Could you also share the full error code that you were getting?

Check the OP, its all there.
