### ISSUE TITLE
Error compiling azure-iothub in TypeScript

### ISSUE THREAD

**Issue by nebrius** [Azure/azure-iot-sdk-node#119]
# Context
- **OS and version used:** macOS High Sierra
- **Node.js version:** 8.8.0
- **npm version:** 5.5.1
- **list of installed packages:** 
├─┬ azure-iothub@1.1.18
│ ├─┬ azure-iot-amqp-base@1.2.1
│ │ ├─┬ amqp10@3.5.3
│ │ │ ├── bl@1.2.1 deduped
│ │ │ ├── bluebird@3.5.1 deduped
│ │ │ ├── buffer-builder@0.2.0
│ │ │ ├── debug@2.6.9 deduped
│ │ │ ├── lodash@4.17.4 deduped
│ │ │ ├── node-int64@0.4.0
│ │ │ └── stately.js@1.3.0
│ │ ├─┬ amqp10-transport-ws@0.0.5
│ │ │ └── nodejs-websocket@1.7.1
│ │ ├── async@2.5.0 deduped
│ │ ├── azure-iot-common@1.2.1 deduped
│ │ ├── bluebird@3.5.1
│ │ ├─┬ debug@3.1.0
│ │ │ └── ms@2.0.0 deduped
│ │ ├─┬ machina@2.0.0
│ │ │ └── lodash@3.10.1
│ │ └── uuid@3.1.0 deduped
│ ├── azure-iot-common@1.2.1
│ ├─┬ azure-iot-http-base@1.2.0
│ │ ├── azure-iot-common@1.2.0
│ │ ├── debug@2.6.9 deduped
│ │ └── uuid@2.0.3
│ ├─┬ debug@2.6.9
│ │ └── ms@2.0.0
│ └── lodash@4.17.4 deduped
└── typescript@2.5.3

(note: results trimmed because I have 300+ in my list)

# Description of the issue:
Compiling azure-iothub in a TypeScript app throws a compilation error in this library.

# Code sample exhibiting the issue:

tsconfig.json:

```JSON
{
  "compilerOptions": {
    "target": "es2015",
    "module": "commonjs",
    "sourceMap": true,
    "outDir": "./dist",
    "rootDir": "./src",
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "noUnusedLocals": true,
    "noImplicitReturns": true,
    "typeRoots": [ "./node_modules/@types", "./typings" ]
  }
}
```

test.ts:

```TypeScript
import { Registry } from 'azure-iothub';
Registry.fromConnectionString('<hidden>');
```

# Console log of the issue:

```sh
node_modules/azure-iothub/lib/amqp.d.ts(11,22): error TS2420: Class 'Amqp' incorrectly implements interface 'Transport'.
  Types of property 'disconnect' are incompatible.
    Type '(done: Callback<any>) => void' is not assignable to type '(done: Callback<Disconnected>) => void'.
      Types of parameters 'done' and 'done' are incompatible.
        Types of parameters 'err' and 'err' are incompatible.
          Type 'Error | undefined' is not assignable to type 'Error'.
            Type 'undefined' is not assignable to type 'Error'.
node_modules/azure-iothub/lib/amqp_ws.d.ts(7,22): error TS2420: Class 'AmqpWs' incorrectly implements interface 'Transport'.
  Types of property 'disconnect' are incompatible.
    Type '(done: Callback<any>) => void' is not assignable to type '(done: Callback<Disconnected>) => void'.
```

# Notes:

I can get around this by removing the `implements Client.Transport` part of the compiled type definition that comes from https://github.com/Azure/azure-iot-sdk-node/blob/master/service/src/amqp.ts#L54 in my node_modules folder, but this isn't a good practice to get into.

I'm more than happy to fix this myself, but I wanted to check with you all first before updating the call signature for https://github.com/Azure/azure-iot-sdk-node/blob/master/service/src/amqp.ts#L83 to match the signature at https://github.com/Azure/azure-iot-sdk-node/blob/master/service/src/client.ts#L303. Do you know if there's a reason the callback in the derived class sets the callback to `Callback<any>` instead of `Callback<Connected>`?

**Comment by pierreca** [comment]
Hi @nebrius 
thanks for sending this very good write up. no reason for Amqp and AmqpWs not to implement the Transport interface properly. I actually feel bad that our CI doesn't catch this. 

If you want to submit a PR I'll merge it quickly - if not that's OK, i can make the change myself and it'll be fixed with the next release. (we relesae on a 2 week cycle).

If you're blocked and need an out of band release I can look at that too.

**Comment by nebrius** [comment]
Thanks for the response @pierreca. No worries about not catching it either. I tend to configure TypeScript to be more strict than most, so this kind of thing happens to me occasionally.

I'll submit a PR, since I already have the code open :)

**Comment by nebrius** [comment]
PR is open. I should not that this is not a blocking issue for me since I was able to implement the workaround mentioned in the notes section above. Thanks again for your input!

**Comment by pierreca** [comment]
Packages including the fixes have been released. thanks a lot for your contribution!
https://github.com/Azure/azure-iot-sdk-node/releases/tag/2017-11-3

**Comment by JasonKleban** [comment]
Getting a similar error out-of-the-box with `export declare class X509AuthenticationProvider implements AuthenticationProvider`

```
(9,22): error TS2420: Class 'X509AuthenticationProvider' incorrectly implements interface 'AuthenticationProvider'.
  Types of property 'getDeviceCredentials' are incompatible.
    Type '(callback: (err: Error, credentials?: TransportConfig | undefined) => void) => void' is not assignable to type '(callback: (err: Error, credentials: TransportConfig) => void) => void'.
      Types of parameters 'callback' and 'callback' are incompatible.
        Types of parameters 'credentials' and 'credentials' are incompatible.
          Type 'TransportConfig | undefined' is not assignable to type 'TransportConfig'.
            Type 'undefined' is not assignable to type 'TransportConfig'.
```

Again, commenting out the import bypasses it.

**Comment by pierreca** [comment]
@JasonKleban this will be tracked with #193, please open new issues instead of commenting on old closed ones. Thanks!
