### ISSUE TITLE
Missing lodash.merge dependency in azure-iothub npm package version 1.16.3

### ISSUE THREAD

**Issue by joost-lambregts** [Azure/azure-iot-sdk-node#1195]
# Context

- **OS and version used:** Windows (app service plan on Azure)
- **Node.js version:** 16.20.1 
- **npm version:** 8.19.4

## Description of the issue
We are running an Azure Function on an app service plan that is running on an app service plan. The function runs into the following error:
```
Exception: Worker was unable to load function scheduleRequestHandler: 'Cannot find module 'lodash.merge'
Require stack:
- C:\home\site\wwwroot\node_modules\azure-iothub\dist\common-amqp\amqp.js
- C:\home\site\wwwroot\node_modules\azure-iothub\dist\amqp.js
- C:\home\site\wwwroot\node_modules\azure-iothub\dist\client.js
- C:\home\site\wwwroot\node_modules\azure-iothub\iothub.js
- C:\home\site\wwwroot\node_modules\@enecoiot\edge-command-handler\index.js
- C:\home\site\wwwroot\shared\steeringbox.js
- C:\home\site\wwwroot\scheduleRequestHandler\index.js
- C:\Program Files (x86)\SiteExtensions\Functions\4.21.3\workers\node\dist\src\worker-bundle.js
- C:\Program Files (x86)\SiteExtensions\Functions\4.21.3\workers\node\dist\src\nodejsWorker.js'
```
The problem seems pretty clear. Indeed, I can see that in version 1.16.3 an import of lodash.merge was added to dist\common-amqp\amqp.js, but this module is not added as a dependency in package.json. There is a depenency to lodash, but that is not to lodash.merge which is a seperate package.

**Comment by lev-i** [comment]
@joost-lambregts 

This is an issue for azure-iot-hub-node, which we no longer hold ownership of. If you file this issue [here](https://github.com/Azure/azure-iot-hub-node), it should be an easy fix for them. I'll close this out, but if you have other issues feel free to re-open or file a new ticket.
