### ISSUE TITLE
Does the nodejs sdk support x.509 certificate authentication for it's ModuleClient?

### ISSUE THREAD

**Issue by akboba01** [Azure/azure-iot-sdk-node#1216]
When attempting to use the `ModuleClient` with x.509 authentication I get an error `NotImplementedError: ModuleClient only supports SAS Token authentication`. 

```
  const moduleClient = ModuleClient.fromConnectionString(
    `HostName=${hubName};DeviceId=${deviceId};ModuleId=${moduleId};x509=true`,
    Mqtt
  );
```

However, the IoT Hub [docs](https://learn.microsoft.com/en-us/azure/iot-hub/module-twins-node#module-authentication) imply this is possible. Is there a different way of using the node sdk to do this?

**Comment by olivakar** [comment]
It will throw this error if the connection string does not contain a `SharedAccessKey` field because x509 authentication is not supported for modules.

**Comment by vishnureddy17** [comment]
Seems resolved, closing issue. Feel free to re-open if needed.
