### ISSUE TITLE
React-Native support for azure-iot-sdk-node

### ISSUE THREAD

**Issue by Shahanshah-TA** [Azure/azure-iot-sdk-node#1221]
Any plan for React Native support. I want to use the https://github.com/Azure/azure-iot-sdk-node/blob/a85e280350a12954f46672761b0b516d08d374b5/provisioning/device/samples/register_symkey.js and https://github.com/Azure/azure-iot-sdk-node/blob/a85e280350a12954f46672761b0b516d08d374b5/provisioning/device/samples/register_x509.js @jeremymeng 
Thanks

**Comment by vishnureddy17** [comment]
Hi, there is no plan for React Native support.
