### ISSUE TITLE
[Technical Question] Running SDK in browser 

### ISSUE THREAD

**Issue by AlbyST** [Azure/azure-iot-sdk-node#1222]
Hello,

I would like to run the SDK, the modules for DPS and IOTHUB services in particular, in the browser. Would it be possible? 

Thank you.

**Comment by vishnureddy17** [comment]
Thanks for the question. Unfortunately, this SDK does not have browser support.

**Comment by Shahanshah-TA** [comment]
Hi @vishnureddy17 is there any plan in future to have browser support?

**Comment by vishnureddy17** [comment]
There is no plan for future browser support @Shahanshah-TA
