### ISSUE TITLE
Unable to update from 1.1.7 to 1.2.0

### ISSUE THREAD

**Issue by wmmihaa** [Azure/azure-iot-sdk-node#128]
# Context
- **OS and version used:** 16.4 Ubuntu Core
- **Node.js version:** 7.10
- **npm version:** 4.12
- **cloned repo:** axians/microservicebus-node

# Description of the issue:
We used to be running azure-iot-device@1.1.7 and azure-iot-mqtt@1.1.7, but decided to updated to make use of the reconnect functionality. After updating the devices we get an error saying:

```
TypeError: azure_iot_common_2.ExponentialBackOffWithJitter is not a constructor
```
Has anything changed in term of client settings for connections etc?

# Code sample exhibiting the issue:
```javascript
var Message = require('azure-iot-common').Message;
var ReceiveClient = require('azure-iot-device').Client;
var DeviceProtocol = require('azure-iot-device-mqtt').MqttWs; // Default transport for Receiver

if (!receiver)
    receiver = ReceiveClient.fromSharedAccessSignature(connectionSettings.receiverToken, DeviceProtocol);

receiver.open(function (err, transport) {
    if (err) {
        me.onQueueErrorReceiveCallback('AZURE IoT: Could not connect: ' + err);
        if (err.name === "UnauthorizedError") {
            me.onUnauthorizedErrorCallback();
        }
    }
    else {
        me.onQueueDebugCallback("AZURE IoT: Receiver is ready");
        isConnected = true;
        receiver.on('disconnect', function () {
            isConnected = false;
            me.onQueueErrorReceiveCallback('AZURE IoT: Disconnected');
        });

        receiver.on('error', function (err) {
            console.error(err.message);
            me.onQueueErrorReceiveCallback('AZURE IoT: Error: ' + err.message);
        });

        receiver.on('message', function (msg) {
            try {
                var service = msg.properties.propertyList.find(function (i) {
                    return i.key === "service";
                });
                var message = JSON.parse(msg.data.toString('utf8'));
                var responseData = {
                    body: message,
                    applicationProperties: { value: { service: service.value } }
                }
                me.onQueueMessageReceivedCallback(responseData);
                receiver.complete(msg, function () { });
            }
            catch (e) {
                me.onQueueErrorReceiveCallback('AZURE IoT: Could not connect: ' + e.message);
            }
        });

        // Start twin (only supported on MQTT)
        if (protocolType === "MQTT" || protocolType === "MQTT-WS") {
            receiver.getTwin(function (err, twin) {
                if (err) {
                    me.onQueueErrorReceiveCallback('AZURE IoT: Could not get twin: ' + err);
                }
                else {
                    me.twin = twin;
                    me.onQueueDebugCallback("AZURE IoT: Device twin is ready");
                    twin.on('properties.desired', function (desiredChange) {
                        // Incoming state
                        me.onQueueDebugCallback("AZURE IoT: Received new state");
                        me.currentState = {
                            desired: desiredChange,
                            reported: twin.properties.reported
                        }
                        me.onStateReceivedCallback(me.currentState);
                    });
                }
            });
        }

        // Only start sender if key is provided
        if (connectionSettings.senderToken && !sender) {
            startSender(function () {
                callback();
            });
        }
        else {
            if (callback != null)
                callback();
        }

    }
```

# Console log of the issue:

**Comment by pierreca** [comment]
the `ExponentialBackoffWithJitter` comes with the newer versions of the `azure-iot-common` library. can you post the full console log with the error, stacktrace etc?

**Comment by pierreca** [comment]
@wmmihaa any update on this? I see where this instantiation takes place but the generated code looks fine to me... and although I don't have all the bits and pieces to make your code run, after fixing a couple of errors I had (calls to me.stuff() etc) it was running fine

**Comment by wmmihaa** [comment]
Thanks for getting back to me @pierreca. My problem is that the code is running on a far away remote site. I can deploy the update remotely, but I have to be careful not to mess anything up or I'll be in for a ride ;)

I've been working on reproducing the issue locally but with limited success. I know you're like to clean up the issues. but I'd appreciate if you could give me a few more days.

Cheers
Mikael

**Comment by pierreca** [comment]
@wmmihaa no problem at all. I only want to close issues that are actually solved. I'll be looking forward to your feedback next week. Thanks!

**Comment by wmmihaa** [comment]
I think I can confirm that this works with latest release (1.2.2). I think it was related to the fact that the azure-iot-device-mqtt brought in an older version of azure-iot-device. BTW, it seams weird to have dependancies to azure-iot-device from azure-iot-device-mqtt

**Comment by pierreca** [comment]
There are 2 reasons for that: 
- some interfaces that are defined in azure-iot-device and used in azure-iot-device-mqtt
- we initially created an factory method `clientFromConnectionString()` on each of the transport that returned a `azure-iot-device.Client` - i'm not a fan of this method but we try to not do breaking changes...

Thanks for confirming, I'll close this issue.
