### ISSUE TITLE
Device created with x509 by default, should be symmetric

### ISSUE THREAD

**Issue by jonbgallant** [Azure/azure-iot-sdk-node#138]
# Context
any os, but tried on windows

# Description of the issue:

creating a device with this code, causes it to default to x509 cert, it should be symmetric by default

# Code sample exhibiting the issue:
```
var device = new iothub.Device(null);
device.deviceId = 'MyDevice';
```

# Console log of the issue:

**Comment by jtjk** [comment]
We are experiencing same problem by using node.js API. Device is created but symmetric key is null.

**Comment by pierreca** [comment]
looking into it. 

In the meantime I'd suggest the workaround to use an object with a single `deviceId` property, like so:
```js
var device = {
  deviceId: 'MyDevice'
};
```

I believe this would have the behavior that you are expecting.

**Comment by pierreca** [comment]
So yeah, still checking if the service changed it default behavior but there was definitely something wonky with the SDK so #140 is going to fix that.

**Comment by pierreca** [comment]
Still checking if the service changed it default behavior but there was definitely something wonky with the SDK so #140 is going to fix that.

**Comment by pierreca** [comment]
Still checking if the service changed it default behavior but there was definitely something wonky with the SDK so #140 is going to fix that.

**Comment by pierreca** [comment]
A new release including the fix has been published:
https://github.com/Azure/azure-iot-sdk-node/releases/tag/2017-11-15

Thanks again for your help!
