### ISSUE TITLE
Retry policy for MQTT C2D sample

### ISSUE THREAD

**Issue by snobu** [Azure/azure-iot-sdk-node#148]
I took this sample, removed the sending logic and left in the listening for C2D messages part -
https://github.com/Azure/azure-iot-sdk-node/blob/master/device/samples/simple_sample_device.js

All is well, except if the network reconnects (think WiFi drop and re-assoc), it will just sit there and no longer be connected to IoT Hub (subsequent C2D messages are no longer received). There is no error message or event being emitted, looks completely hanged.

Do i need to wrap everything in my own retry logic? Is this MQTT specific? What's the best practice here?

**Comment by pierreca** [comment]
No, that's definitely a scenario that should work. As asked in the PR template, can you let us know what OS and npm package versions you're using?

**Comment by pierreca** [comment]
might be related to https://github.com/Azure/azure-iot-sdk-node/issues/132

**Comment by snobu** [comment]
Node 8.9.1 on Debian Jessie (armhf). Latest Azure IoT packages since i npm installed yesterday. Indeed it seems to be the same issue you linked to, i will wait the 3 minures to confirm `disxonnect` is fired.

**Comment by snobu** [comment]
Waited >20 minutes with the Ethernet cable unplugged, no event was fired, no reconnect was attempted. Upon restarting the Node process i am getting the queued C2D messages, no complaints there.

**Comment by pierreca** [comment]
Is that with the latest from the master branch or with the currently released packages? (the master branch contains the fix, and we will release those in the next couple of days)

**Comment by snobu** [comment]
That may be it. I'm using the npm packages. I'll try cloning master and giving it another shot later today. Thanks for the tip.

**Comment by pierreca** [comment]
@snobu I just released a new set of packages, could you please try with those?
https://github.com/Azure/azure-iot-sdk-node/releases/tag/2017-11-15

Thanks again for your help! feel free to close the issue if it is solved with this release, or let us know what the new behavior. console logs, code, anything helps us reproduce issues (if they still occur)

**Comment by snobu** [comment]
Oh that's beautiful! I will report back with findings.

**Comment by snobu** [comment]
```bash
npm install azure-iot-device-mqtt@latest --save
```
aaaand it works like a dream! Thank you!

![image](https://media.giphy.com/media/l1J9O9elEvuRjMyXu/giphy.gif)

**Comment by pierreca** [comment]
great :) thanks for your feedback!
