### ISSUE TITLE
Typescript definition for DeviceMethodParams incorrectly defined

### ISSUE THREAD

**Issue by briancr-ms** [Azure/azure-iot-sdk-node#15]
# Context
- **OS and version used: Windows 10
- **Node.js version: v6.2.1
- **npm version: 3.5.0

# Description of the issue:
The Typescript definition for DeviceMethodParams in device_method_params.d.ts defines a required field called "name". This is a mismatch with the DeviceMethod constructor, which requires a field called "methodName".

**Comment by pierreca** [comment]
Fixed with https://github.com/Azure/azure-iot-sdk-node/commit/8e64d631a406d2c3bde53da338eca90005e85f83

Will close the issue when a new package is released!

**Comment by pierreca** [comment]
Fixed with azure-iot-device@1.1.6
