### ISSUE TITLE
TTL property on cloud-to-device message

### ISSUE THREAD

**Issue by snobu** [Azure/azure-iot-sdk-node#151]
Can i set a time to live property on a cloud-to-device message?
I know i can set a default in IoT Hub (that affects all C2D messages), but what i what to achieve is different messages having different TTLs.

IoT Hub resource:
```
"cloudToDevice": {
      ...
      "defaultTtlAsIso8601": "PT3M",    // 3 minutes
      ...
```

**Comment by snobu** [comment]
Just found out about `expiryTimeUtc` from [here](https://github.com/Azure/azure-iot-sdk-node/blob/amqp-disconnected-handler-leak/common/transport/amqp/devdoc/amqp_message.md).
```
message.expiryTimeUtc = Date.now() + 60000; // one minute
serviceClient.send(targetDevice, message, printResultFor('send', context));
```
There's also a mention of it [here](https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/iot-hub/iot-hub-devguide-messages-c2d.md#message-expiration-time-to-live), but that's probably the .NET one given the title case.

Am i using the right thing? Looks like it is working, i am getting the desired behavior.

**Comment by pierreca** [comment]
yup, that seems correct.
