### ISSUE TITLE
Need "status" and "lastActivityTime" from device twin

### ISSUE THREAD

**Issue by vspedr** [Azure/azure-iot-sdk-node#157]
# Context
- **OS and version used:** RHEL 7.4
- **Node.js version:** 8.9.0 
- **npm version:** 5.5.1
- **list of installed packages:** `azure-iothub@1.1.16`

# Description of the issue:
This is more of a question than a issue. I'm using a registry query to retrieve device twins. I know from the Twin class docs that these results do not include properties such as `status` and `lastActivityTime`, which are present in the deprecated Device class. However, I need these properties to fill a table where each row represents a device, along with other properties such as deviceId and tags that are already provided.
Is there a way to request these properties when using queries?

# Console log of the issue:
## Example from query

```
    {
        "deviceId": "1242",
        // how can I get "status" and "lastActivityTime" here?
        "etag": "AAAAAAAAAAM=",
        "tags": {
            "someTag": "someValue,
            "anotherTag": "anotherValue"
        },
        "properties": {
            "desired": {
                "$metadata": {
                    "$lastUpdated": "2017-11-08T22:07:19.4096708Z"
                },
                "$version": 1
            },
            "reported": {
                "$metadata": {
                    "$lastUpdated": "2017-11-08T22:07:19.4096708Z"
                },
                "$version": 1
            }
        }
    }
```

**Comment by anthonyvercolano** [comment]
I have included a link to the jobs system.  Perhaps this might be helpful?

[Manage your IoT Hub device identities in bulk](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-bulk-identity-mgmt)

**Comment by vspedr** [comment]
Thanks @anthonyvercolano, I did not know about export jobs. However, I would have to export the entire registry every time and then filter out the results within the client, is that right? I need to filter out some devices by their tags, so if there was a way to retrieve that information using twin queries, that would be ideal. Any thoughts?

**Comment by anthonyvercolano** [comment]
Before the end of this calendar year you will be able to get status and lastActivityTime as part of the query result.

**Comment by vspedr** [comment]
Great! If there's any way I can contribute to this feature, please let me know.

**Comment by pierreca** [comment]
@vspedr not much to do here, just waiting on the service team to deploy the change. We'll update the issue when it's done. still shooting for the end of December.

**Comment by pierreca** [comment]
Fix for this has been deployed and we need to update the SDK to take advantage of it (need to update the API version). Likely in February.

**Comment by vspedr** [comment]
Thanks for the follow up @pierreca!

**Comment by votson** [comment]
Thank you so much to fix this for me

**Comment by votson** [comment]
Hi what this is

**Comment by votson** [comment]
I'm so sorry  get to many thing going on my mind. Hey what  going on here
on games this not the same like before when i play like missing something .
Can fix for me should be my account come together the last account

**Comment by pierreca** [comment]
@vspedr azure-iothub@1.2.5 should have the fix for this!
