### ISSUE TITLE
azure-iothub nextAsTwin() "Expected 2 arguments" continuationToken - is not optional

### ISSUE THREAD

**Issue by Qba91** [Azure/azure-iot-sdk-node#162]
# Context
- **OS and version used:** Windows 10
- **Node.js version:** v8.9.1
- **npm version:** 5.5.1
- **list of installed packages:** 
+-- @types/node@8.0.53
+-- azure-iothub@1.2.1
| +-- async@2.6.0
| | `-- lodash@4.17.4 deduped
| +-- azure-iot-amqp-base@1.2.3
| | +-- amqp10@3.5.3
| | | +-- bl@1.2.1
| | | | `-- readable-stream@2.3.3
| | | |   +-- core-util-is@1.0.2
| | | |   +-- inherits@2.0.3
| | | |   +-- isarray@1.0.0
| | | |   +-- process-nextick-args@1.0.7
| | | |   +-- safe-buffer@5.1.1
| | | |   +-- string_decoder@1.0.3
| | | |   | `-- safe-buffer@5.1.1 deduped
| | | |   `-- util-deprecate@1.0.2
| | | +-- bluebird@3.5.1 deduped
| | | +-- buffer-builder@0.2.0
| | | +-- debug@2.6.9 deduped
| | | +-- lodash@4.17.4 deduped
| | | +-- node-int64@0.4.0
| | | `-- stately.js@1.3.0
| | +-- amqp10-transport-ws@0.0.5
| | | `-- nodejs-websocket@1.7.1
| | +-- async@2.6.0 deduped
| | +-- azure-iot-common@1.2.2 deduped
| | +-- bluebird@3.5.1
| | +-- debug@3.1.0
| | | `-- ms@2.0.0 deduped
| | +-- machina@2.0.0 deduped
| | `-- uuid@3.1.0
| +-- azure-iot-common@1.2.2
| +-- azure-iot-http-base@1.2.2
| | +-- azure-iot-common@1.2.2 deduped
| | +-- debug@2.6.9 deduped
| | `-- uuid@2.0.3
| +-- debug@2.6.9
| | `-- ms@2.0.0
| +-- lodash@4.17.4
| `-- machina@2.0.0
|   `-- lodash@3.10.1
+-- readline-sync@1.4.7
`-- typescript@2.6.1
- **cloned repo:** https://github.com/Azure/azure-iot-sdk-node.git

# Description of the issue:
done is not an optional parameter - not '?'. Function can not be called with one argument.

# Code sample exhibiting the issue:
    next(continuationTokenOrCallback: string | Callback<any>, done?: Callback<any>): void;
    /**
     * @method              module:azure-iothub.Query#nextAsTwin
     * @description         Gets the next page of results for this query and cast them as Twins.
     * @param {string}      continuationToken    Continuation Token used for paging through results (optional)
     * @param {Function}    done                 The callback that will be called with either an Error object or
     *                                           the results of the query.
     */
    nextAsTwin(continuationToken: string | Callback<Twin[]>, done: Callback<Twin[]>): void;

# Console log of the issue:
app/iot-hub/iot-hub.service.ts(106,29): error TS2554: Expected 2 arguments, but got 1.
app/iot-hub/iot-hub.service.ts(110,17): error TS2554: Expected 2 arguments, but got 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! piniothub@1.0.0 start: `tsc && node ./dist/index.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the piniothub@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jakub\AppData\Roaming\npm-cache\_logs\2017-11-24T11_48_26_021Z-debug.log

**Comment by anthonyvercolano** [comment]
Can you give me a bit more of an example of why you want to call the next function without a done function?

**Comment by Qba91** [comment]
I'm trying to run this example: 

`var query = registry.createQuery('SELECT * FROM devices', 100);
var onResults = function(err, results) {
    if (err) {
        console.error('Failed to fetch the results: ' + err.message);
    } else {
        // Do something with the results
        results.forEach(function(twin) {
            console.log(twin.deviceId);
        });

        if (query.hasMoreResults) {
            query.nextAsTwin(onResults);
        }
    }
};
query.nextAsTwin(onResults);`

from: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-query-language.
This example uses one arguments function nextAsTwin (done) which is callback done, for now I deliberately omit the use of continuationToken. 

`
...
nextAsTwin(continuationToken: string | Callback<Twin[]>, done: Callback<Twin[]>): void {
    /*Codes_SRS_NODE_SERVICE_QUERY_16_016: [If `continuationToken` is a function and `done` is undefined the `next` method shall assume that `continuationToken` is actually the callback and us it as such (see requirements associated with the `done` parameter)]*/
    if (typeof continuationToken === 'function' && !done) {
      done = continuationToken;
      continuationToken = null;
    } 
...`

**Comment by anthonyvercolano** [comment]
Ok, now I feel silly.  The regular next function has the question mark on it.  The nextAsTwin doesn't.  I have to investigate why the unit tests didn't catch this.  I don't think that adding the ? would make this a breaking change.  I'll talk with some folks on Monday.  Thank you for catching this.

**Comment by pierreca** [comment]
Fix released with azure-iothub@1.2.2
https://github.com/Azure/azure-iot-sdk-node/releases/tag/2017-12-1
