### ISSUE TITLE
Iot Hub Client usage with multiple devices

### ISSUE THREAD

**Issue by rsarili** [Azure/azure-iot-sdk-node#171]
What is efficient way to send messages to multiple devices?

In 'send_c3d_message' sample message send to only one device, so one iot hub client is opened,
If we want to send messages to multiple devices in different times, 

Should we create iot hub client for every device when we want to send a message and then close the client? or
Should we create only one iot hub client and keep open this connection every time and handle all messaging for different devices in that client?

**Comment by pierreca** [comment]
There's no easy answer for that - the measure of efficiency changes depending on what your scenario is. 

One client will send messages one by one. if you're looking for efficiency in resources (sockets, memory..), one client for multiple devices is the way to go. if you're looking for throughput, parallelizing clients might help. but in that case you may also want to scale up the number of node instances running. etc.

I'd recommend going to StackOverflow for this type of questions, the issues here are used more for bug tracking.
