### ISSUE TITLE
[device][amqp] Message won't be queried from IoT Hub or Event Hub if attached AMQP message annotations

### ISSUE THREAD

**Issue by michaeljqzq** [Azure/azure-iot-sdk-node#177]
# Context
- **OS and version used:** Windows 10 
- **Node.js version:** 7.6.0 
- **npm version:** 4.1.2 

# Description of the issue:
after added data in amqpMessage.messageAnnotations (previously it is undefined), the message sent from device can no longer be queried by IoT Hub. ( I tried Device Explorer/ Event hub sdk ). It seems in the IoT Hub portal, the message number will increase but I can't get the message in above ways.

I tried capturing the packet. And found that the message annotations are encoded in the outgoing message, and also received successful response from server side.

 
![packet](https://user-images.githubusercontent.com/9349786/33813890-b4f4abb8-de61-11e7-8115-788c4cb08aca.jpg)

The packet captured from Node & C# SDK here:
[packet.zip](https://github.com/Azure/azure-iot-sdk-node/files/1546408/packet.zip)

So I wonder is there anything else to do to use message annotations? Since adding message annotations on C# device SDK works and can be correctly received by server side.

# Code sample exhibiting the issue:
in fromMessage(), amqp_message.ts (Line 57)
`amqpMessage.messageAnnotations = {};`
Here i use an empty object of message annotations, also tried with
`amqpMessage.messageAnnotations = { key: 'value'};`
and didn't work either.

# Console log of the issue:

**Comment by pierreca** [comment]
That should work. since this is internal work, let's look at server logs together.
closing.
