### ISSUE TITLE
Get 400 response when creating device with id contains #

### ISSUE THREAD

**Issue by formulahendry** [Azure/azure-iot-sdk-node#187]
# Context
- **npm version:** azure-iothub@1.2.0

# Description of the issue:
Get 400 response from SDK, when creating device with id contains `#`
![image](https://user-images.githubusercontent.com/1050213/34284659-a658aa04-e70e-11e7-9c92-481a2cffcf9f.png)

# Code sample exhibiting the issue:
https://github.com/Microsoft/vscode-azure-iot-toolkit/blob/bf406fbc0d7903b4b38b32097d5034b685b8aaff/src/deviceExplorer.ts#L80

**Comment by pierreca** [comment]
Looks like it's just a matter of uri-encoding the device id in the registry class. that's a pretty easy fix. would you mind taking a stab at it and submitting a pull-request?

**Comment by pierreca** [comment]
@formulahendry 
fix was released on NPM today:
https://github.com/Azure/azure-iot-sdk-node/releases/tag/2018-2-7
