### ISSUE TITLE
Exception on disconnect

### ISSUE THREAD

**Issue by mastasky** [Azure/azure-iot-sdk-node#19]
Hi all,

I am running the azure-iot-device-mqtt library on Ubuntu 16.04. 

Periodically, the client connection to the IOT Hub will fail with this exception:

```
.../node_modules/azure-iot-device-mqtt/lib/mqtt_base.js:122
  this.client.removeAllListeners();
             ^

TypeError: Cannot read property 'removeAllListeners' of undefined
    at MqttBase.disconnect (/home/cognigy/Cognigy_CloudServices_NLP/CognigyBrain/CognigyBrain/node_modules/azure-iot-device-mqtt/lib/mqtt_base.js:122:14)
    at Mqtt.updateSharedAccessSignature (/home/cognigy/Cognigy_CloudServices_NLP/CognigyBrain/CognigyBrain/node_modules/azure-iot-device-mqtt/lib/mqtt.js:15$
    at constructor.updateSharedAccessSignature (/home/cognigy/Cognigy_CloudServices_NLP/CognigyBrain/CognigyBrain/node_modules/azure-iot-device/lib/client.j$
    at constructor.handle (/home/cognigy/Cognigy_CloudServices_NLP/CognigyBrain/CognigyBrain/node_modules/machina/lib/machina.js:613:25)
```

Before this exception, everything works great.

Any ideas?
Cheers,
Phil

**Comment by pierreca** [comment]
Thanks for reporting this, it looks like a bug. Can you please confirm the version of node.js and the version of the SDK that you're running? A simple dump of `npm ls` would help.

Also, is it always happening at after a specific time (45 minutes?) or is it random?

**Comment by mastasky** [comment]
Requested information below. What we can see in the logs is that our Tedious connection to Azure SQL also drops just before the exception above, so the reason for the exception above could be an intermittent disconnect of the server itself (which is strange, looking at that it's an Azure VM).

Node v7.4.0

Full stack trace
```
/home/cognigy/Cognigy_CloudServices_NLP/CognigyBrain/CognigyBrain/node_modules/azure-iot-device-mqtt/lib/mqtt_base.js:122
  this.client.removeAllListeners();
             ^

TypeError: Cannot read property 'removeAllListeners' of undefined
    at MqttBase.disconnect (/home/cognigy/Cognigy_CloudServices_NLP/CognigyBrain/CognigyBrain/node_modules/azure-iot-device-mqtt/lib/mqtt_base.js:122:14)
    at Mqtt.updateSharedAccessSignature (/home/cognigy/Cognigy_CloudServices_NLP/CognigyBrain/CognigyBrain/node_modules/azure-iot-device-mqtt/lib/mqtt.js:153:14)
    at constructor.updateSharedAccessSignature (/home/cognigy/Cognigy_CloudServices_NLP/CognigyBrain/CognigyBrain/node_modules/azure-iot-device/lib/client.js:127:33)
    at constructor.handle (/home/cognigy/Cognigy_CloudServices_NLP/CognigyBrain/CognigyBrain/node_modules/machina/lib/machina.js:613:25)
    at constructor.Fsm.(anonymous function) [as handle] (/home/cognigy/Cognigy_CloudServices_NLP/CognigyBrain/CognigyBrain/node_modules/machina/lib/machina.js:466:63)
    at Client.updateSharedAccessSignature (/home/cognigy/Cognigy_CloudServices_NLP/CognigyBrain/CognigyBrain/node_modules/azure-iot-device/lib/client.js:541:13)
    at Client._renewSharedAccessSignature (/home/cognigy/Cognigy_CloudServices_NLP/CognigyBrain/CognigyBrain/node_modules/azure-iot-device/lib/client.js:448:8)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

```

Azure NPMs: 

```
├─┬ azure-event-hubs@0.0.6
│ ├─┬ amqp10@3.4.1
│ │ ├── buffer-builder@0.2.0
│ │ ├─┬ debug@2.6.1
│ │ │ └── ms@0.7.2
│ │ ├── lodash@4.17.4
│ │ ├── node-amqp-encoder@0.0.2
│ │ ├── node-int64@0.4.0
│ │ └── stately.js@1.3.0
│ ├─┬ azure-iot-common@1.1.3
│ │ └── crypto@0.0.3
│ └── uuid@3.0.1
├─┬ azure-iot-device@1.1.7
│ ├── azure-iot-common@1.1.5
│ ├─┬ azure-iot-http-base@1.1.5
│ │ ├── azure-iot-common@1.1.5
│ │ └─┬ debug@2.6.1
│ │   └── ms@0.7.2
│ ├─┬ azure-storage@2.1.0
│ │ ├── browserify-mime@1.2.9
│ │ ├── extend@1.2.1
│ │ ├─┬ json-edm-parser@0.1.2
│ │ │ └── jsonparse@1.2.0
│ │ ├─┬ md5.js@1.3.4
│ │ │ └── hash-base@3.0.3
│ │ ├── node-uuid@1.4.7
│ │ ├── readable-stream@2.0.6
│ │ ├─┬ request@2.74.0
│ │ │ ├── bl@1.1.2
│ │ │ ├── extend@3.0.0
│ │ │ └─┬ form-data@1.0.1
│ │ │   └─┬ async@2.1.5
│ │ │     └── lodash@4.17.4
│ │ ├── underscore@1.4.4
│ │ ├── validator@3.22.2
│ │ ├─┬ xml2js@0.2.7
│ │ │ └── sax@0.5.2
│ │ └── xmlbuilder@0.4.3
│ ├─┬ debug@2.6.1
│ │ └── ms@0.7.2
│ ├── es5-shim@4.5.9
│ ├── lodash@4.17.4
│ ├─┬ machina@2.0.0
│ │ └── lodash@3.10.1
│ └── traverse@0.6.6
├─┬ azure-iot-device-amqp@1.1.7
│ ├─┬ azure-iot-amqp-base@1.1.6
│ │ ├─┬ amqp10-transport-ws@0.0.5
│ │ │ └── nodejs-websocket@1.7.1
│ │ ├── azure-iot-common@1.1.5
│ │ ├─┬ debug@2.6.1
│ │ │ └── ms@0.7.2
│ │ ├─┬ sinon@1.17.7
│ │ │ ├── formatio@1.1.1
│ │ │ ├── lolex@1.3.2
│ │ │ ├── samsam@1.1.2
│ │ │ └─┬ util@0.10.3
│ │ │   └── inherits@2.0.1
│ │ └─┬ sinon-as-promised@4.0.2
│ │   ├─┬ create-thenable@1.0.2
│ │   │ ├─┬ object.omit@2.0.1
│ │   │ │ ├─┬ for-own@0.1.4
│ │   │ │ │ └── for-in@0.1.6
│ │   │ │ └── is-extendable@0.1.1
│ │   │ └── unique-concat@0.2.2
│ │   └── native-promise-only@0.8.1
│ └── azure-iot-common@1.1.5
├─┬ azure-iot-device-mqtt@1.1.7
│ ├── azure-iot-common@1.1.5
│ ├─┬ debug@2.6.1
│ │ └── ms@0.7.2
│ └─┬ mqtt@1.14.1
│   ├─┬ commist@1.0.0
│   │ ├── leven@1.0.2
│   │ └── minimist@1.2.0
│   ├─┬ concat-stream@1.6.0
│   │ └── typedarray@0.0.6
│   ├─┬ end-of-stream@1.1.0
│   │ └── once@1.3.3
│   ├─┬ help-me@1.0.1
│   │ ├── callback-stream@1.1.0
│   │ ├─┬ glob-stream@5.3.5
│   │ │ ├── glob@5.0.15
│   │ │ ├─┬ glob-parent@3.1.0
│   │ │ │ ├─┬ is-glob@3.1.0
│   │ │ │ │ └── is-extglob@2.1.1
│   │ │ │ └── path-dirname@1.0.2
│   │ │ ├─┬ micromatch@2.3.11
│   │ │ │ ├─┬ arr-diff@2.0.0
│   │ │ │ │ └── arr-flatten@1.0.1
│   │ │ │ ├── array-unique@0.2.1
│   │ │ │ ├─┬ braces@1.8.5
│   │ │ │ │ ├─┬ expand-range@1.8.2
│   │ │ │ │ │ └─┬ fill-range@2.2.3
│   │ │ │ │ │   ├── is-number@2.1.0
│   │ │ │ │ │   ├── isobject@2.1.0
│   │ │ │ │ │   ├── randomatic@1.1.6
│   │ │ │ │ │   └── repeat-string@1.6.1
│   │ │ │ │ ├── preserve@0.2.0
│   │ │ │ │ └── repeat-element@1.1.2
│   │ │ │ ├─┬ expand-brackets@0.1.5
│   │ │ │ │ └── is-posix-bracket@0.1.1
│   │ │ │ ├── extglob@0.3.2
│   │ │ │ ├── filename-regex@2.0.0
│   │ │ │ ├── kind-of@3.1.0
│   │ │ │ ├── normalize-path@2.0.1
│   │ │ │ ├─┬ parse-glob@3.0.4
│   │ │ │ │ ├── glob-base@0.3.0
│   │ │ │ │ └── is-dotfile@1.0.2
│   │ │ │ └─┬ regex-cache@0.4.3
│   │ │ │   ├── is-equal-shallow@0.1.3
│   │ │ │   └── is-primitive@2.0.0
│   │ │ ├─┬ ordered-read-streams@0.3.0
│   │ │ │ └── is-stream@1.1.0
│   │ │ ├─┬ through2@0.6.5
│   │ │ │ └─┬ readable-stream@1.0.34
│   │ │ │   └── isarray@0.0.1
│   │ │ ├─┬ to-absolute-glob@0.1.1
│   │ │ │ └── extend-shallow@2.0.1
│   │ │ └─┬ unique-stream@2.2.1
│   │ │   ├── json-stable-stringify@1.0.1
│   │ │   └── through2-filter@2.0.0
│   │ └── through2@2.0.3
│   ├── inherits@2.0.3
│   ├── minimist@1.2.0
│   ├─┬ mqtt-connection@2.1.1
│   │ ├─┬ reduplexer@1.1.0
│   │ │ └─┬ readable-stream@1.0.34
│   │ │   └── isarray@0.0.1
│   │ └─┬ through2@0.6.5
│   │   └─┬ readable-stream@1.0.34
│   │     └── isarray@0.0.1
│   ├─┬ mqtt-packet@3.4.8
│   │ └─┬ bl@0.9.5
│   │   └─┬ readable-stream@1.0.34
│   │     └── isarray@0.0.1
│   ├─┬ pump@1.0.2
│   │ └─┬ end-of-stream@1.1.0
│   │   └── once@1.3.3
│   ├─┬ readable-stream@1.0.34
│   │ └── isarray@0.0.1
│   ├── reinterval@1.1.0
│   ├── split2@2.1.1
│   └─┬ websocket-stream@3.3.3
│     └─┬ duplexify@3.5.0
│       ├─┬ end-of-stream@1.0.0
│       │ └── once@1.3.3
│       └── stream-shift@1.0.0
├─┬ azure-iothub@1.1.7
│ ├── azure-iot-common@1.1.5
│ ├── lodash@4.17.4
│ └── uuid@2.0.3
```

**Comment by pierreca** [comment]
Looks like the error happens when we try to renew the shared access signature, which is a token with an expiry time using the `symmetricKey` contained in the connection string. This token expires every 60 minutes so we renew it every 45. Looks like for some reason the way we do that doesn't work in your setup, I'm suspecting we have a bug somewhere.

As a temporary workaround, another way to authenticate the device with IoT hub is to use an x509 certificate: instead of a symmetric key, the registry contains the certificate thumbprint, and the client uses the `setOptions` api to set the certificate and key files. This authentication method doesn't require disconnecting the client every 45 minutes. 

A simple sample showing x509 usage can be found here:
https://github.com/Azure/azure-iot-sdk-node/blob/master/device/samples/simple_sample_device_x509.js
and a way to generate the certificate and insert the thumbprint in the registry here:
https://github.com/Azure/azure-iot-sdk-node/blob/master/build/tools/create_device_certs.js

Obviously we're going to look at this issue more closely but in the meantime I hope this might help.

**Comment by anthonyvercolano** [comment]
A quick question when you create the device in your application, do you invoke

Client.fromConnectionString(connectionString, Protocol)

or do you invoke:

Client.fromSharedAccessSignature(sas, Protocol);

Thank you,
Tony

**Comment by tameraw** [comment]
@mastasky - Please let us know if still having issues.

**Comment by SebastianPilarski** [comment]
Hello,
I am experiencing the exact same issue. Do you recommend authenticating with the x509 certificate to avoid it? 

I invoke Client.fromConnectionString(connectionString, Protocol) by the way.

**Comment by pierreca** [comment]
@SebastianPilarski yes, using x509 certificates will work around this issue. 

@anthonyvercolano @tameraw I think that issue isn't resolved so i'm reopening it.

**Comment by sharathbaddam** [comment]
Hello,
I am experiencing the exact same issue. 

I invoke client from .fromConnectionString();

Thanks

**Comment by pierreca** [comment]
@sharathbaddam @SebastianPilarski @mastasky we've made big changes to the MQTT layer of the SDK in the latest iterations of the SDK, you should update and let us know if you still experience errors. should be more stable now.

Also, if x509 is not an option, you can consider using `Client.fromSharedAccessSignature()` to create the client and create the shared access signature yourself (see https://github.com/Azure/azure-iot-sdk-node/blob/master/device/core/src/client.ts#L717 for an example of how to create a SAS). This will prevent the disconnection/reconnection dance that has to happen in MQTT every 45 minutes to renew the SAS token.

**Comment by sharathbaddam** [comment]
@pierreca Thank you, I will update my libraries and let you know.!

**Comment by pierreca** [comment]
@sharathbaddam @SebastianPilarski @mastasky
we've finally released a version that include our fully-fledged retry logic. with the past improvements to the MQTT state machine, I'm positive this bug in itself is fixed. doesn't mean all connectivity issues are fixed, but this should be a great improvement.

If you still have connectivity issues, please open a new issue with updated information (logs etc).
