### ISSUE TITLE
TypeError: transportCtor is not a constructor

### ISSUE THREAD

**Issue by desuryan** [Azure/azure-iot-sdk-node#202]
# Context
- **OS and version used:** <VERSION> 
- **Node.js version:** <VERSION> 
- **npm version:** <VERSION> 
- **list of installed packages:** <VERSION> 
- **cloned repo:** <VERSION> 

# Description of the issue:
Showing the message as "TypeError: transportCtor is not a constructor" while trying to send data in Azure IOT HUb.

# Code sample exhibiting the issue:

# Console log of the issue:
TypeError: transportCtor is not a constructor

**Comment by pierreca** [comment]
Without seeing how you create the client I can’t help. I’ll close and let you reopen if you add more details. I’m guessing the problem is that you’re either not passing a transport argument or you’re instantiating it instead of passing the constructor. Please look at the samples for a working solution.

**Comment by cell2749** [comment]
Was the issue re-opened and resolved?

Here is what I have:
`
const { Message, Client } = require("azure-iot-device");
...
const client = Client.fromConnectionString(connectionString);
`

**Comment by YoDaMa** [comment]
@cell2749 it would be better for you to open a new issue with your code snippet and problem. The original issue filer did not provide any further details so there's no reason to open this issue. 
 
 However, for your case, you should start by following the simple device sample provided in the samples folder: https://github.com/Azure/azure-iot-sdk-node/blob/master/device/samples/simple_sample_device.js

**Comment by Harsheet196** [comment]
> Was the issue re-opened and resolved?
> 
> Here is what I have:
> 
> ```js
> const { Message, Client } = require("azure-iot-device");
> 
> ...
> 
> const client = Client.fromConnectionString(connectionString);
> ```

Getting same issue Using Latest version

**Comment by cell2749** [comment]
> > Was the issue re-opened and resolved?
> > Here is what I have:
> > ```js
> > const { Message, Client } = require("azure-iot-device");
> > 
> > ...
> > 
> > const client = Client.fromConnectionString(connectionString);
> > ```
> 
> Getting same issue Using Latest version... Any solutions you got?

It was 3 years ago when I was doing this, so I don't remember much. However, it seems that I had to provide also a protocol to the connection. Again, not sure if this was what solved it since it was a long time ago.

```js
const { Message, Client } = require("azure-iot-device");
const { Amqp: Protocol } = require("azure-iot-device-amqp");
....
const client = Client.fromConnectionString(connectionString, Protocol);
```

**Comment by Harsheet196** [comment]
> > > Was the issue re-opened and resolved?
> > > Here is what I have:
> > > ```js
> > > const { Message, Client } = require("azure-iot-device");
> > > 
> > > ...
> > > 
> > > const client = Client.fromConnectionString(connectionString);
> > > ```
> > 
> > 
> > Getting same issue Using Latest version... Any solutions you got?
> 
> It was 3 years ago when I was doing this, so I don't remember much. However, it seems that I had to provide also a protocol to the connection. Again, not sure if this was what solved it since it was a long time ago.
> 
> ```js
> const { Message, Client } = require("azure-iot-device");
> const { Amqp: Protocol } = require("azure-iot-device-amqp");
> ....
> const client = Client.fromConnectionString(connectionString, Protocol);
> ```

Ohh thanks but when I am trying to insert the protocol parameter its giving the error other if i Leave it blank its working, checking the Lib i found its taking by default AMQP protocol. I need to use MQTT though..
