### ISSUE TITLE
Is there an event triggered if twin state is lost

### ISSUE THREAD

**Issue by wmmihaa** [Azure/azure-iot-sdk-node#206]
# Context
- **OS and version used:** Ubuntu Core 16.04
- **Node.js version:** 7.10
- **npm version:** 5.5.1
- **We are connected using celluar network, and currently using AMQP**

# Description of the issue:
It seems twin state is less resilient to network interrupts, and from time to time we loose the ability to receive state. Is there an event, indicating we've lost state "connection"? This is somewhat related to the #136 issue

**Comment by pierreca** [comment]
That is a correct assessment of the current situation and we have an item high in our backlog to fix this, likely during February.

**Comment by wmmihaa** [comment]
Thanks @pierreca.  
Let me know if there is ANYTHING we can do to help. I can send you syslogs or other metrix/logs. Just let me know.

**Comment by pierreca** [comment]
@wmmihaa I've just checked in a fix for this - twins can now retry just like any other operation. 
I've discovered a couple other minor things in the twin code that I will strive to fix into another pull request or 2 before I release new packages. stay tuned!

**Comment by wmmihaa** [comment]
Great news.
Will you be available at the mvp summit this week? If so it’d be great to meet up and have a beer.

________________________________

**Comment by pierreca** [comment]
@wmmihaa sure, with pleasure. I’m around on campus. Would thursday work? Kinda busy tomorrow and Wednesday night.

**Comment by pierreca** [comment]
Fix has been published!
https://github.com/Azure/azure-iot-sdk-node/releases/tag/2018-3-9

**Comment by yzhong94** [comment]
@wmmihaa , thank you for your contribution to our open-sourced project!  Please help us improve by filling out this 2-minute customer satisfaction survey.
