### ISSUE TITLE
Device SDK - Node Light?

### ISSUE THREAD

**Issue by bluebrolly** [Azure/azure-iot-sdk-node#211]
Good evening everyone, I am trying to use the Device SDK in openWRT (NodeJS) but the SDK is too large for the storage space. I noticed that there are extra dependencies like lodash. Is there a light version of the Device SDK for AMQP or MQTT that provides the same functionality?

Thanks

**Comment by pierreca** [comment]
Hi
there is no "light" version. if you're using only C2D and D2C features you could switch to HTTP which has less dependencies. The other option would be to go directly with one of the AMQP or MQTT libraries and not the full SDK but if these libraries are those creating the issue because of their dependencies, there's not much we can do.

I assume you're installing only one transport package right?  you only need one anwyay (azure-iot-device-amqp, azure-iot-device-mqtt or azure-iot-device-http)

Also, out of curiosity, how big is the gap between the space you have and the space the SDK is taking?

**Comment by bluebrolly** [comment]
OpenWRT is 32MB. I have after all my other code, servers, oauth2 clients ect, about 16mb left or so. The space it takes up is around 45mb.

The problem with HTTP I thought was there is no open connection like MQTT / AMQP so pushing messages down would be difficult unless I check often, and at that point you are using a lot of bandwidth compared to MQTT which keeps the connection open. (GSM data usage concern)

I have been able to install mqtt-base and amqp-base but I am not sure it has everything to send message up. I could always get rid of Azure IoT SDK and go with a lightweight MQTT / AMQP client... and use the iot-hub service SDK for authentication control?

**Comment by pierreca** [comment]
Interesting - I would need to do a more thorough analysis of our dependency tree to understand who's bringing so much weight in. if you have suggestions or want to send a pull-request our way we'll happily look at it.

The other solution you're suggesting is also very valid - just go directly with one of the MQTT or AMQP libraries. you can absolutely do everything the SDK does since basically our code is just plumbing over these protocols to make it easy to use advanced features such as CBS authentication, Twin or Device Methods.

For MQTT I'd recommend looking at [mqtt.js](https://github.com/mqttjs/MQTT.js/), for AMQP you have the choice between [node-amqp10](https://github.com/noodlefrenzy/node-amqp10) and [rhea](https://github.com/grs/rhea). This SDK depends on node-amqp10 right now but are also keeping an eye on rhea and it's a good library too).

**Comment by bluebrolly** [comment]
So from what I am seeing it takes 45mb to download the main files, then it "builds" on the machine, after the build, the folder takes up 20.448mb. Attached is a snapshot of what is downloaded for azure-iot-device-http.

mqw azure-iot-device-http@1.3.0
  tqq azure-iot-common@1.3.0
  tqw azure-iot-device@1.3.0
  x tqw azure-storage@2.7.0
  x x tqq browserify-mime@1.2.9
  x x tqq extend@1.2.1
  x x tqw json-edm-parser@0.1.2
  x x x mqq jsonparse@1.2.0
  x x tqw md5.js@1.3.4
  x x x tqq hash-base@3.0.4
  x x x mqq inherits@2.0.3
  x x tqw readable-stream@2.0.6
  x x x tqq core-util-is@1.0.2
  x x x tqq isarray@1.0.0
  x x x tqq process-nextick-args@1.0.7
  x x x tqq string_decoder@0.10.31
  x x x mqq util-deprecate@1.0.2
  x x tqw request@2.81.0
  x x x tqq aws-sign2@0.6.0
  x x x tqq aws4@1.6.0
  x x x tqq caseless@0.12.0
  x x x tqw combined-stream@1.0.5
  x x x x mqq delayed-stream@1.0.0
  x x x tqq extend@3.0.1
  x x x tqq forever-agent@0.6.1
  x x x tqw form-data@2.1.4
  x x x x mqq asynckit@0.4.0
  x x x tqw har-validator@4.2.1
  x x x x tqw ajv@4.11.8
  x x x x x tqq co@4.6.0
  x x x x x mqw json-stable-stringify@1.0.1
  x x x x x   mqq jsonify@0.0.0
  x x x x mqq har-schema@1.0.5
  x x x tqw hawk@3.1.3
  x x x x tqq boom@2.10.1
  x x x x tqq cryptiles@2.0.5
  x x x x tqq hoek@2.16.3
  x x x x mqq sntp@1.0.9
  x x x tqw http-signature@1.1.1
  x x x x tqq assert-plus@0.2.0
  x x x x tqw jsprim@1.4.1
  x x x x x tqq assert-plus@1.0.0
  x x x x x tqq extsprintf@1.3.0
  x x x x x tqq json-schema@0.2.3
  x x x x x mqw verror@1.10.0
  x x x x x   mqq assert-plus@1.0.0
  x x x x mqw sshpk@1.13.1
  x x x x   tqq asn1@0.2.3
  x x x x   tqq assert-plus@1.0.0
  x x x x   tqq bcrypt-pbkdf@1.0.1
  x x x x   tqw dashdash@1.14.1
  x x x x   x mqq assert-plus@1.0.0
  x x x x   tqq ecc-jsbn@0.1.1
  x x x x   tqw getpass@0.1.7
  x x x x   x mqq assert-plus@1.0.0
  x x x x   tqq jsbn@0.1.1
  x x x x   mqq tweetnacl@0.14.5
  x x x tqq is-typedarray@1.0.0
  x x x tqq isstream@0.1.2
  x x x tqq json-stringify-safe@5.0.1
  x x x tqw mime-types@2.1.17
  x x x x mqq mime-db@1.30.0
  x x x tqq oauth-sign@0.8.2
  x x x tqq performance-now@0.2.0
  x x x tqq qs@6.4.0
  x x x tqq safe-buffer@5.1.1
  x x x tqq stringstream@0.0.5
  x x x tqw tough-cookie@2.3.3
  x x x x mqq punycode@1.4.1
  x x x tqq tunnel-agent@0.6.0
  x x x mqq uuid@3.2.1
  x x tqq underscore@1.8.3
  x x tqq uuid@3.2.1
  x x tqq validator@3.35.0
  x x tqw xml2js@0.2.7
  x x x mqq sax@0.5.2
  x x mqq xmlbuilder@0.4.3
  x tqq lodash@4.17.4
  x tqw machina@2.0.0
  x x mqq lodash@3.10.1
  x mqq traverse@0.6.6
  tqw azure-iot-http-base@1.3.0
  x tqq debug@2.6.9
  x mqq uuid@2.0.3
  tqw debug@3.1.0
  x mqq ms@2.0.0
  mqw node-crontab@0.0.8
    mqq cron-parser@0.3.6



Here is all the files size for that folder and each file (in kb):

28      node_modules/string_decoder
28      node_modules/util-deprecate
32      node_modules/getpass/node_modules/assert-plus
36      node_modules/getpass/node_modules
8       node_modules/getpass/lib
68      node_modules/getpass
220     node_modules/tough-cookie/lib
260     node_modules/tough-cookie
116     node_modules/underscore
16      node_modules/xml2js/lib
128     node_modules/xml2js
72      node_modules/jsbn
28      node_modules/json-edm-parser/test
56      node_modules/json-edm-parser
32      node_modules/caseless
40      node_modules/request/node_modules/uuid/lib
8       node_modules/request/node_modules/uuid/bin
112     node_modules/request/node_modules/uuid
52      node_modules/request/node_modules/extend
4       node_modules/request/node_modules/.bin
172     node_modules/request/node_modules
60      node_modules/request/lib
412     node_modules/request
20      node_modules/sntp/test
16      node_modules/sntp/lib
12      node_modules/sntp/examples
80      node_modules/sntp
68      node_modules/azure-iot-device-http/lib
96      node_modules/azure-iot-device-http
144     node_modules/azure-iot-common/lib
176     node_modules/azure-iot-common
24      node_modules/asn1/tst/ber
28      node_modules/asn1/tst
32      node_modules/asn1/lib/ber
40      node_modules/asn1/lib
92      node_modules/asn1
36      node_modules/boom/images
24      node_modules/boom/test
12      node_modules/boom/lib
116     node_modules/boom
24      node_modules/form-data/lib
44      node_modules/form-data
28      node_modules/process-nextick-args
20      node_modules/hash-base
8       node_modules/cron-parser/.idea/scopes
8       node_modules/cron-parser/.idea/libraries
76      node_modules/cron-parser/.idea
24      node_modules/cron-parser/test
24      node_modules/cron-parser/lib
148     node_modules/cron-parser
8       node_modules/node-crontab/test
8       node_modules/node-crontab/lib
36      node_modules/node-crontab
680     node_modules/machina/node_modules/lodash/internal
120     node_modules/machina/node_modules/lodash/object
104     node_modules/machina/node_modules/lodash/string
172     node_modules/machina/node_modules/lodash/array
32      node_modules/machina/node_modules/lodash/math
8       node_modules/machina/node_modules/lodash/date
112     node_modules/machina/node_modules/lodash/function
88      node_modules/machina/node_modules/lodash/chain
124     node_modules/machina/node_modules/lodash/lang
172     node_modules/machina/node_modules/lodash/collection
12      node_modules/machina/node_modules/lodash/number
68      node_modules/machina/node_modules/lodash/utility
2168    node_modules/machina/node_modules/lodash
2172    node_modules/machina/node_modules
196     node_modules/machina/lib
2420    node_modules/machina
84      node_modules/hawk/images
8       node_modules/hawk/example
16      node_modules/hawk/dist
200     node_modules/hawk/test
80      node_modules/hawk/lib
448     node_modules/hawk
48      node_modules/asynckit/lib
92      node_modules/asynckit
12      node_modules/jsonify/test
20      node_modules/jsonify/lib
48      node_modules/jsonify
44      node_modules/safe-buffer
204     node_modules/tweetnacl
8       node_modules/performance-now/src
12      node_modules/performance-now/test
8       node_modules/performance-now/lib
60      node_modules/performance-now
8       node_modules/readable-stream/doc/wg-meetings
72      node_modules/readable-stream/doc
64      node_modules/readable-stream/lib
184     node_modules/readable-stream
64      node_modules/azure-iot-device/lib/blob_upload
32      node_modules/azure-iot-device/lib/device_method
252     node_modules/azure-iot-device/lib
288     node_modules/azure-iot-device
20      node_modules/json-stable-stringify/example
28      node_modules/json-stable-stringify/test
76      node_modules/json-stable-stringify
12      node_modules/combined-stream/lib
32      node_modules/combined-stream
36      node_modules/punycode
36      node_modules/bcrypt-pbkdf
32      node_modules/verror/node_modules/assert-plus
36      node_modules/verror/node_modules
16      node_modules/verror/lib
100     node_modules/verror
8       node_modules/delayed-stream/lib
32      node_modules/delayed-stream
40      node_modules/isstream
44      node_modules/http-signature/lib
88      node_modules/http-signature
152     node_modules/sax/test
40      node_modules/sax/lib
400     node_modules/sax/examples
628     node_modules/sax
8       node_modules/azure-storage/jsdoc
40      node_modules/azure-storage/node_modules/uuid/lib
8       node_modules/azure-storage/node_modules/uuid/bin
112     node_modules/azure-storage/node_modules/uuid
4       node_modules/azure-storage/node_modules/.bin
120     node_modules/azure-storage/node_modules
72      node_modules/azure-storage/typings/globals/node
76      node_modules/azure-storage/typings/globals
792     node_modules/azure-storage/typings/azure-storage
876     node_modules/azure-storage/typings
16      node_modules/azure-storage/lib/common/md5-wrapper
40      node_modules/azure-storage/lib/common/signing
24      node_modules/azure-storage/lib/common/models
8       node_modules/azure-storage/lib/common/errors
128     node_modules/azure-storage/lib/common/util
8       node_modules/azure-storage/lib/common/diagnostics
80      node_modules/azure-storage/lib/common/streams
28      node_modules/azure-storage/lib/common/filters
88      node_modules/azure-storage/lib/common/services
20      node_modules/azure-storage/lib/common/request-wrapper
16      node_modules/azure-storage/lib/common/http
472     node_modules/azure-storage/lib/common
16      node_modules/azure-storage/lib/services/blob/internal
36      node_modules/azure-storage/lib/services/blob/models
532     node_modules/azure-storage/lib/services/blob
32      node_modules/azure-storage/lib/services/table/internal
20      node_modules/azure-storage/lib/services/table/models
184     node_modules/azure-storage/lib/services/table
16      node_modules/azure-storage/lib/services/queue/models
128     node_modules/azure-storage/lib/services/queue
8       node_modules/azure-storage/lib/services/file/internal
24      node_modules/azure-storage/lib/services/file/models
320     node_modules/azure-storage/lib/services/file
1168    node_modules/azure-storage/lib/services
1668    node_modules/azure-storage/lib
56      node_modules/azure-storage/examples/samples
60      node_modules/azure-storage/examples
136     node_modules/azure-storage/browser/samples
172     node_modules/azure-storage/browser
3036    node_modules/azure-storage
32      node_modules/ecc-jsbn/lib
60      node_modules/ecc-jsbn
32      node_modules/forever-agent
24      node_modules/jsonparse/test
8       node_modules/jsonparse/examples
20      node_modules/jsonparse/samplejson
92      node_modules/jsonparse
12      node_modules/extsprintf/lib
56      node_modules/extsprintf
8       node_modules/core-util-is/lib
44      node_modules/core-util-is
12      node_modules/uuid/misc
32      node_modules/uuid/benchmark
12      node_modules/uuid/test
100     node_modules/uuid
24      node_modules/md5.js
36      node_modules/isarray
32      node_modules/jsprim/node_modules/assert-plus
36      node_modules/jsprim/node_modules
24      node_modules/jsprim/lib
92      node_modules/jsprim
100     node_modules/browserify-mime
32      node_modules/dashdash/node_modules/assert-plus
36      node_modules/dashdash/node_modules
20      node_modules/dashdash/etc
40      node_modules/dashdash/lib
140     node_modules/dashdash
24      node_modules/extend
24      node_modules/qs/dist
60      node_modules/qs/test
36      node_modules/qs/lib
176     node_modules/qs
1704    node_modules/ajv/dist
20      node_modules/ajv/lib/dot/v5
144     node_modules/ajv/lib/dot
68      node_modules/ajv/lib/compile
24      node_modules/ajv/lib/refs
176     node_modules/ajv/lib/dotjs
464     node_modules/ajv/lib
28      node_modules/ajv/scripts
2284    node_modules/ajv
32      node_modules/stringstream
32      node_modules/debug/src
108     node_modules/debug
20      node_modules/json-schema/draft-00
24      node_modules/json-schema/draft-03/examples
44      node_modules/json-schema/draft-03
8       node_modules/json-schema/test
16      node_modules/json-schema/draft-04
20      node_modules/json-schema/draft-02
20      node_modules/json-schema/lib
20      node_modules/json-schema/draft-01
260     node_modules/json-schema
24      node_modules/inherits
28      node_modules/oauth-sign
16      node_modules/har-validator/src
16      node_modules/har-validator/lib/node4
16      node_modules/har-validator/lib/node6
16      node_modules/har-validator/lib/node7
16      node_modules/har-validator/lib/browser
68      node_modules/har-validator/lib
100     node_modules/har-validator
32      node_modules/tunnel-agent
60      node_modules/aws4
180     node_modules/mime-db
4       node_modules/.bin
28      node_modules/mime-types
36      node_modules/azure-iot-http-base/node_modules/debug/src
112     node_modules/azure-iot-http-base/node_modules/debug
116     node_modules/azure-iot-http-base/node_modules
44      node_modules/azure-iot-http-base/lib
192     node_modules/azure-iot-http-base
20      node_modules/ms
24      node_modules/is-typedarray
72      node_modules/validator/test
156     node_modules/validator
44      node_modules/hoek/images
16      node_modules/hoek/test/modules
92      node_modules/hoek/test
36      node_modules/hoek/lib
216     node_modules/hoek
32      node_modules/assert-plus
16      node_modules/json-stringify-safe/test
48      node_modules/json-stringify-safe
1700    node_modules/lodash/fp
5004    node_modules/lodash
32      node_modules/co
32      node_modules/aws-sign2
8       node_modules/traverse/test/lib
92      node_modules/traverse/test
24      node_modules/traverse/examples
8       node_modules/traverse/testling
164     node_modules/traverse
32      node_modules/sshpk/node_modules/assert-plus
36      node_modules/sshpk/node_modules
16      node_modules/sshpk/man/man1
20      node_modules/sshpk/man
84      node_modules/sshpk/lib/formats
180     node_modules/sshpk/lib
20      node_modules/sshpk/bin
300     node_modules/sshpk
80      node_modules/har-schema/lib
96      node_modules/har-schema
8       node_modules/cryptiles/test
8       node_modules/cryptiles/lib
40      node_modules/cryptiles
24      node_modules/xmlbuilder/lib
44      node_modules/xmlbuilder
20448   node_modules/

**Comment by pierreca** [comment]
lodash definitely looks like one of the worst offenders and we have 2 copies of it because of the dependency on machina.js. Good to know. In any case, fitting is 16MB is going to be difficult especially if your code itself depends on other packages that are going to bring other dependencies.

For such a constrained environment I would strongly suggest to look at the C SDK or at using just a protocol library, we have big stuff coming down the pipeline and it's unlikely we can get to size-reduction work in a timely manner here.

**Comment by bluebrolly** [comment]
If I go C, I may as well go embedded. I'll look at the C library at just using it as the transport method and have everything else in NodeJS

**Comment by pierreca** [comment]
Sounds reasonable. closing issue as it seems the question is answered, feel free to reopen or create new issues if you have other questions.
