### ISSUE TITLE
Is it possible to set contentType and encoding?

### ISSUE THREAD

**Issue by wmmihaa** [Azure/azure-iot-sdk-node#219]
When using IoT Hub Routes we need to set **contentType** and **encoding** of the message or we will otherwise not be able to route the message to the appropriate end-point.

[The C# sample](https://azure.microsoft.com/en-us/blog/iot-hub-message-routing-now-with-routing-on-message-body/]) is pretty straight forward, but we can't get it to work for node-js: 

```
// C# - Working
using (var message = new Message(messageBytes)) 
{ 
    // Set message body type and content encoding. 
    message.ContentEncoding = "utf-8"; 
    message.ContentType = "application/json"; 
 
    // Add other custom application properties.  
    message.Properties["Status"] = "Active";  // Routing property
 
    await deviceClient.SendEventAsync(message); 
}
```

```
// JavaScript - Not working
message.contentEncoding = "utf-8"; 
message.contentType = "application/json"; 
message.properties.add("Status", "Active");  // Routing property
client.sendEvent(message);
```

We are currently using AMQP, but can switch to MQTT should it be required...

**Comment by wmmihaa** [comment]
Should I understand, - tagging the issue "enhancement" means: -"No it's not supported at the moment"?

**Comment by pierreca** [comment]
@wmmihaa it means it's not implemented yet and is on our backlog (as opposed to a bug that happens on a feature already implemented)

**Comment by jimoneil** [comment]
FWIW, I posted at the [blog announcement from May](https://azure.microsoft.com/en-us/blog/iot-hub-message-routing-now-with-routing-on-message-body/) that this is not working.  It's not completely clear if this is AMQP only or MQTT.  I would recommend an update to the blog post since it is one of the more definitive resources for this feature.

**Comment by pierreca** [comment]
This has been implemented and released now:
https://github.com/Azure/azure-iot-sdk-node/releases/tag/2018-3-9

**Comment by yzhong94** [comment]
@jimoneil @wmmihaa , thank you for your contribution to our open-sourced project!  Please help us improve by filling out this 2-minute customer satisfaction survey.

**Comment by virtualamjath** [comment]
can you provide sample to setup content Type and Encoding Type on message 

// JavaScript - Not working
message.contentEncoding = "utf-8"; 
message.contentType = "application/json"; 
message.properties.add("Status", "Active");  // Routing property
client.sendEvent(message);

this wont work
