### ISSUE TITLE
AMQP Transport: Could not send

### ISSUE THREAD

**Issue by jtjk** [Azure/azure-iot-sdk-node#229]
Hi,

When I am sending Azure IoT AMQP message from device to cloud, I get: AMQP Transport: Could not send

# Context
- **OS and version used:** Beaglebone Black Debian 8.7 and Linux 4.4.91-ti-r133
- **Node.js version:** 9.4.0
- **npm version:** 5.6.0
- **list of installed packages:** 

├─┬ azure-iot-device@1.3.0
│ ├── azure-iot-common@1.3.0
│ ├─┬ azure-iot-http-base@1.3.0
│ │ ├── azure-iot-common@1.3.0 deduped
│ │ ├─┬ debug@2.6.9
│ │ │ └── ms@2.0.0 deduped
│ │ └── uuid@2.0.3
│ ├─┬ azure-storage@2.7.0
│ │ ├── browserify-mime@1.2.9
│ │ ├── extend@1.2.1
│ │ ├─┬ json-edm-parser@0.1.2
│ │ │ └── jsonparse@1.2.0
│ │ ├─┬ md5.js@1.3.4
│ │ │ ├─┬ hash-base@3.0.4
│ │ │ │ ├── inherits@2.0.3 deduped
│ │ │ │ └── safe-buffer@5.1.1 deduped
│ │ │ └── inherits@2.0.3 deduped
│ │ ├─┬ readable-stream@2.0.6
│ │ │ ├── core-util-is@1.0.2
│ │ │ ├── inherits@2.0.3 deduped
│ │ │ ├── isarray@1.0.0
│ │ │ ├── process-nextick-args@1.0.7
│ │ │ ├── string_decoder@0.10.31
│ │ │ └── util-deprecate@1.0.2
│ │ ├─┬ request@2.81.0
│ │ │ ├── aws-sign2@0.6.0
│ │ │ ├── aws4@1.6.0
│ │ │ ├── caseless@0.12.0
│ │ │ ├─┬ combined-stream@1.0.5
│ │ │ │ └── delayed-stream@1.0.0
│ │ │ ├── extend@3.0.1
│ │ │ ├── forever-agent@0.6.1
│ │ │ ├─┬ form-data@2.1.4
│ │ │ │ ├── asynckit@0.4.0
│ │ │ │ ├── combined-stream@1.0.5 deduped
│ │ │ │ └── mime-types@2.1.17 deduped
│ │ │ ├─┬ har-validator@4.2.1
│ │ │ │ ├─┬ ajv@4.11.8
│ │ │ │ │ ├── co@4.6.0
│ │ │ │ │ └─┬ json-stable-stringify@1.0.1
│ │ │ │ │   └── jsonify@0.0.0
│ │ │ │ └── har-schema@1.0.5
│ │ │ ├─┬ hawk@3.1.3
│ │ │ │ ├─┬ boom@2.10.1
│ │ │ │ │ └── hoek@2.16.3 deduped
│ │ │ │ ├─┬ cryptiles@2.0.5
│ │ │ │ │ └── boom@2.10.1 deduped
│ │ │ │ ├── hoek@2.16.3
│ │ │ │ └─┬ sntp@1.0.9
│ │ │ │   └── hoek@2.16.3 deduped
│ │ │ ├─┬ http-signature@1.1.1
│ │ │ │ ├── assert-plus@0.2.0
│ │ │ │ ├─┬ jsprim@1.4.1
│ │ │ │ │ ├── assert-plus@1.0.0
│ │ │ │ │ ├── extsprintf@1.3.0
│ │ │ │ │ ├── json-schema@0.2.3
│ │ │ │ │ └─┬ verror@1.10.0
│ │ │ │ │   ├── assert-plus@1.0.0
│ │ │ │ │   ├── core-util-is@1.0.2 deduped
│ │ │ │ │   └── extsprintf@1.3.0 deduped
│ │ │ │ └─┬ sshpk@1.13.1
│ │ │ │   ├── asn1@0.2.3
│ │ │ │   ├── assert-plus@1.0.0
│ │ │ │   ├─┬ bcrypt-pbkdf@1.0.1
│ │ │ │   │ └── tweetnacl@0.14.5 deduped
│ │ │ │   ├─┬ dashdash@1.14.1
│ │ │ │   │ └── assert-plus@1.0.0
│ │ │ │   ├─┬ ecc-jsbn@0.1.1
│ │ │ │   │ └── jsbn@0.1.1 deduped
│ │ │ │   ├─┬ getpass@0.1.7
│ │ │ │   │ └── assert-plus@1.0.0
│ │ │ │   ├── jsbn@0.1.1
│ │ │ │   └── tweetnacl@0.14.5
│ │ │ ├── is-typedarray@1.0.0
│ │ │ ├── isstream@0.1.2 deduped
│ │ │ ├── json-stringify-safe@5.0.1
│ │ │ ├── mime-types@2.1.17 deduped
│ │ │ ├── oauth-sign@0.8.2
│ │ │ ├── performance-now@0.2.0
│ │ │ ├── qs@6.4.0
│ │ │ ├── safe-buffer@5.1.1 deduped
│ │ │ ├── stringstream@0.0.5
│ │ │ ├─┬ tough-cookie@2.3.3
│ │ │ │ └── punycode@1.4.1
│ │ │ ├─┬ tunnel-agent@0.6.0
│ │ │ │ └── safe-buffer@5.1.1 deduped
│ │ │ └── uuid@3.2.1
│ │ ├── underscore@1.8.3
│ │ ├── uuid@3.2.1
│ │ ├── validator@3.35.0
│ │ ├─┬ xml2js@0.2.7
│ │ │ └── sax@0.5.2
│ │ └── xmlbuilder@0.4.3
│ ├─┬ debug@3.1.0
│ │ └── ms@2.0.0 deduped
│ ├── lodash@4.17.4
│ ├─┬ machina@2.0.0
│ │ └── lodash@3.10.1
│ └── traverse@0.6.6
├─┬ azure-iot-device-amqp@1.3.0
│ ├─┬ async@2.6.0
│ │ └── lodash@4.17.4 deduped
│ ├─┬ azure-iot-amqp-base@1.3.0
│ │ ├─┬ amqp10@3.5.3
│ │ │ ├─┬ bl@1.2.1
│ │ │ │ └── readable-stream@2.0.6 deduped
│ │ │ ├── bluebird@3.5.1 deduped
│ │ │ ├── buffer-builder@0.2.0
│ │ │ ├─┬ debug@2.6.9
│ │ │ │ └── ms@2.0.0 deduped
│ │ │ ├── lodash@4.17.4 deduped
│ │ │ ├── node-int64@0.4.0
│ │ │ └── stately.js@1.3.0
│ │ ├─┬ amqp10-transport-ws@0.0.5
│ │ │ └── nodejs-websocket@1.7.1
│ │ ├── async@2.6.0 deduped
│ │ ├── azure-iot-common@1.3.0 deduped
│ │ ├── bluebird@3.5.1
│ │ ├── debug@3.1.0 deduped
│ │ ├── machina@2.0.0 deduped
│ │ └── uuid@3.2.1
│ ├── azure-iot-common@1.3.0 deduped
│ ├── azure-iot-device@1.3.0 deduped
│ ├── debug@3.1.0 deduped
│ ├── machina@2.0.0 deduped
│ └── uuid@3.2.1
├─┬ azure-iot-device-mqtt@1.3.0
│ ├── azure-iot-common@1.3.0 deduped
│ ├── azure-iot-device@1.3.0 deduped
│ ├─┬ azure-iot-mqtt-base@1.3.0
│ │ ├── azure-iot-common@1.3.0 deduped
│ │ ├── machina@2.0.0 deduped
│ │ └─┬ mqtt@2.15.1
│ │   ├─┬ commist@1.0.0
│ │   │ ├── leven@1.0.2
│ │   │ └── minimist@1.2.0 deduped
│ │   ├─┬ concat-stream@1.6.0
│ │   │ ├── inherits@2.0.3 deduped
│ │   │ ├─┬ readable-stream@2.3.3
│ │   │ │ ├── core-util-is@1.0.2 deduped
│ │   │ │ ├── inherits@2.0.3 deduped
│ │   │ │ ├── isarray@1.0.0 deduped
│ │   │ │ ├── process-nextick-args@1.0.7 deduped
│ │   │ │ ├── safe-buffer@5.1.1 deduped
│ │   │ │ ├─┬ string_decoder@1.0.3
│ │   │ │ │ └── safe-buffer@5.1.1 deduped
│ │   │ │ └── util-deprecate@1.0.2 deduped
│ │   │ └── typedarray@0.0.6
│ │   ├─┬ end-of-stream@1.4.1
│ │   │ └─┬ once@1.4.0
│ │   │   └── wrappy@1.0.2
│ │   ├─┬ help-me@1.1.0
│ │   │ ├─┬ callback-stream@1.1.0
│ │   │ │ ├── inherits@2.0.3 deduped
│ │   │ │ └── readable-stream@2.0.6 deduped
│ │   │ ├─┬ glob-stream@6.1.0
│ │   │ │ ├── extend@3.0.1
│ │   │ │ ├─┬ glob@7.1.2
│ │   │ │ │ ├── fs.realpath@1.0.0
│ │   │ │ │ ├─┬ inflight@1.0.6
│ │   │ │ │ │ ├── once@1.4.0 deduped
│ │   │ │ │ │ └── wrappy@1.0.2 deduped
│ │   │ │ │ ├── inherits@2.0.3 deduped
│ │   │ │ │ ├─┬ minimatch@3.0.4
│ │   │ │ │ │ └─┬ brace-expansion@1.1.8
│ │   │ │ │ │   ├── balanced-match@1.0.0
│ │   │ │ │ │   └── concat-map@0.0.1
│ │   │ │ │ ├── once@1.4.0 deduped
│ │   │ │ │ └── path-is-absolute@1.0.1
│ │   │ │ ├─┬ glob-parent@3.1.0
│ │   │ │ │ ├─┬ is-glob@3.1.0
│ │   │ │ │ │ └── is-extglob@2.1.1
│ │   │ │ │ └── path-dirname@1.0.2
│ │   │ │ ├── is-negated-glob@1.0.0
│ │   │ │ ├─┬ ordered-read-streams@1.0.1
│ │   │ │ │ └── readable-stream@2.0.6 deduped
│ │   │ │ ├─┬ pumpify@1.4.0
│ │   │ │ │ ├── duplexify@3.5.3 deduped
│ │   │ │ │ ├── inherits@2.0.3 deduped
│ │   │ │ │ └── pump@2.0.1 deduped
│ │   │ │ ├─┬ readable-stream@2.3.3
│ │   │ │ │ ├── core-util-is@1.0.2 deduped
│ │   │ │ │ ├── inherits@2.0.3 deduped
│ │   │ │ │ ├── isarray@1.0.0 deduped
│ │   │ │ │ ├── process-nextick-args@1.0.7 deduped
│ │   │ │ │ ├── safe-buffer@5.1.1 deduped
│ │   │ │ │ ├─┬ string_decoder@1.0.3
│ │   │ │ │ │ └── safe-buffer@5.1.1 deduped
│ │   │ │ │ └── util-deprecate@1.0.2 deduped
│ │   │ │ ├── remove-trailing-separator@1.1.0
│ │   │ │ ├─┬ to-absolute-glob@2.0.2
│ │   │ │ │ ├─┬ is-absolute@1.0.0
│ │   │ │ │ │ ├─┬ is-relative@1.0.0
│ │   │ │ │ │ │ └─┬ is-unc-path@1.0.0
│ │   │ │ │ │ │   └── unc-path-regex@0.1.2
│ │   │ │ │ │ └── is-windows@1.0.1
│ │   │ │ │ └── is-negated-glob@1.0.0 deduped
│ │   │ │ └─┬ unique-stream@2.2.1
│ │   │ │   ├── json-stable-stringify@1.0.1 deduped
│ │   │ │   └─┬ through2-filter@2.0.0
│ │   │ │     ├── through2@2.0.3 deduped
│ │   │ │     └── xtend@4.0.1 deduped
│ │   │ ├─┬ through2@2.0.3
│ │   │ │ ├─┬ readable-stream@2.3.3
│ │   │ │ │ ├── core-util-is@1.0.2 deduped
│ │   │ │ │ ├── inherits@2.0.3 deduped
│ │   │ │ │ ├── isarray@1.0.0 deduped
│ │   │ │ │ ├── process-nextick-args@1.0.7 deduped
│ │   │ │ │ ├── safe-buffer@5.1.1 deduped
│ │   │ │ │ ├─┬ string_decoder@1.0.3
│ │   │ │ │ │ └── safe-buffer@5.1.1 deduped
│ │   │ │ │ └── util-deprecate@1.0.2 deduped
│ │   │ │ └── xtend@4.0.1 deduped
│ │   │ └── xtend@4.0.1 deduped
│ │   ├── inherits@2.0.3 deduped
│ │   ├── minimist@1.2.0
│ │   ├─┬ mqtt-packet@5.4.0
│ │   │ ├── bl@1.2.1 deduped
│ │   │ ├── inherits@2.0.3 deduped
│ │   │ ├── process-nextick-args@1.0.7 deduped
│ │   │ └── safe-buffer@5.1.1 deduped
│ │   ├─┬ pump@2.0.1
│ │   │ ├── end-of-stream@1.4.1 deduped
│ │   │ └── once@1.4.0 deduped
│ │   ├─┬ readable-stream@2.3.3
│ │   │ ├── core-util-is@1.0.2 deduped
│ │   │ ├── inherits@2.0.3 deduped
│ │   │ ├── isarray@1.0.0 deduped
│ │   │ ├── process-nextick-args@1.0.7 deduped
│ │   │ ├── safe-buffer@5.1.1 deduped
│ │   │ ├─┬ string_decoder@1.0.3
│ │   │ │ └── safe-buffer@5.1.1 deduped
│ │   │ └── util-deprecate@1.0.2 deduped
│ │   ├── reinterval@1.1.0
│ │   ├─┬ split2@2.2.0
│ │   │ └── through2@2.0.3 deduped
│ │   ├─┬ websocket-stream@5.1.1
│ │   │ ├─┬ duplexify@3.5.3
│ │   │ │ ├── end-of-stream@1.4.1 deduped
│ │   │ │ ├── inherits@2.0.3 deduped
│ │   │ │ ├── readable-stream@2.0.6 deduped
│ │   │ │ └── stream-shift@1.0.0
│ │   │ ├── inherits@2.0.3 deduped
│ │   │ ├─┬ readable-stream@2.3.3
│ │   │ │ ├── core-util-is@1.0.2 deduped
│ │   │ │ ├── inherits@2.0.3 deduped
│ │   │ │ ├── isarray@1.0.0 deduped
│ │   │ │ ├── process-nextick-args@1.0.7 deduped
│ │   │ │ ├── safe-buffer@5.1.1 deduped
│ │   │ │ ├─┬ string_decoder@1.0.3
│ │   │ │ │ └── safe-buffer@5.1.1 deduped
│ │   │ │ └── util-deprecate@1.0.2 deduped
│ │   │ ├── safe-buffer@5.1.1 deduped
│ │   │ ├─┬ ws@3.3.3
│ │   │ │ ├── async-limiter@1.0.0
│ │   │ │ ├── safe-buffer@5.1.1 deduped
│ │   │ │ └── ultron@1.1.1
│ │   │ └── xtend@4.0.1 deduped
│ │   └── xtend@4.0.1
│ ├── debug@3.1.0 deduped
│ └── machina@2.0.0 deduped
├─┬ body-parser@1.18.2
│ ├── bytes@3.0.0
│ ├── content-type@1.0.4
│ ├─┬ debug@2.6.9
│ │ └── ms@2.0.0 deduped
│ ├── depd@1.1.2
│ ├─┬ http-errors@1.6.2
│ │ ├── depd@1.1.1
│ │ ├── inherits@2.0.3
│ │ ├── setprototypeof@1.0.3
│ │ └── statuses@1.4.0
│ ├── iconv-lite@0.4.19
│ ├─┬ on-finished@2.3.0
│ │ └── ee-first@1.1.1
│ ├── qs@6.5.1
│ ├─┬ raw-body@2.3.2
│ │ ├── bytes@3.0.0 deduped
│ │ ├── http-errors@1.6.2 deduped
│ │ ├── iconv-lite@0.4.19 deduped
│ │ └── unpipe@1.0.0
│ └─┬ type-is@1.6.15
│   ├── media-typer@0.3.0
│   └─┬ mime-types@2.1.17
│     └── mime-db@1.30.0
├── csv-parse@0.1.0
├─┬ express@4.16.2
│ ├─┬ accepts@1.3.4
│ │ ├── mime-types@2.1.17 deduped
│ │ └── negotiator@0.6.1
│ ├── array-flatten@1.1.1
│ ├── body-parser@1.18.2 deduped
│ ├── content-disposition@0.5.2
│ ├── content-type@1.0.4 deduped
│ ├── cookie@0.3.1
│ ├── cookie-signature@1.0.6
│ ├─┬ debug@2.6.9
│ │ └── ms@2.0.0 deduped
│ ├── depd@1.1.2 deduped
│ ├── encodeurl@1.0.2
│ ├── escape-html@1.0.3
│ ├── etag@1.8.1
│ ├─┬ finalhandler@1.1.0
│ │ ├─┬ debug@2.6.9
│ │ │ └── ms@2.0.0 deduped
│ │ ├── encodeurl@1.0.2 deduped
│ │ ├── escape-html@1.0.3 deduped
│ │ ├── on-finished@2.3.0 deduped
│ │ ├── parseurl@1.3.2 deduped
│ │ ├── statuses@1.3.1
│ │ └── unpipe@1.0.0 deduped
│ ├── fresh@0.5.2
│ ├── merge-descriptors@1.0.1
│ ├── methods@1.1.2
│ ├── on-finished@2.3.0 deduped
│ ├── parseurl@1.3.2
│ ├── path-to-regexp@0.1.7
│ ├─┬ proxy-addr@2.0.2
│ │ ├── forwarded@0.1.2
│ │ └── ipaddr.js@1.5.2
│ ├── qs@6.5.1
│ ├── range-parser@1.2.0
│ ├── safe-buffer@5.1.1
│ ├─┬ send@0.16.1
│ │ ├─┬ debug@2.6.9
│ │ │ └── ms@2.0.0 deduped
│ │ ├── depd@1.1.2 deduped
│ │ ├── destroy@1.0.4
│ │ ├── encodeurl@1.0.2 deduped
│ │ ├── escape-html@1.0.3 deduped
│ │ ├── etag@1.8.1 deduped
│ │ ├── fresh@0.5.2 deduped
│ │ ├── http-errors@1.6.2 deduped
│ │ ├── mime@1.4.1
│ │ ├── ms@2.0.0 deduped
│ │ ├── on-finished@2.3.0 deduped
│ │ ├── range-parser@1.2.0 deduped
│ │ └── statuses@1.3.1
│ ├─┬ serve-static@1.13.1
│ │ ├── encodeurl@1.0.2 deduped
│ │ ├── escape-html@1.0.3 deduped
│ │ ├── parseurl@1.3.2 deduped
│ │ └── send@0.16.1 deduped
│ ├── setprototypeof@1.1.0
│ ├── statuses@1.3.1
│ ├── type-is@1.6.15 deduped
│ ├── utils-merge@1.0.1
│ └── vary@1.1.2
├─┬ getmac@1.4.0
│ ├── editions@1.3.3
│ └─┬ extract-opts@3.3.1
│   ├─┬ eachr@3.2.0
│   │ ├── editions@1.3.3 deduped
│   │ └── typechecker@4.4.1 deduped
│   ├── editions@1.3.3 deduped
│   └─┬ typechecker@4.4.1
│     └── editions@1.3.3 deduped
├─┬ mathjs@1.4.0
│ └── decimal.js@4.0.4
├─┬ mongoose@4.13.10
│ ├─┬ async@2.1.4
│ │ └── lodash@4.17.4 deduped
│ ├── bson@1.0.4
│ ├── hooks-fixed@2.0.2
│ ├── kareem@1.5.0
│ ├── lodash.get@4.4.2
│ ├─┬ mongodb@2.2.34
│ │ ├── es6-promise@3.2.1
│ │ ├─┬ mongodb-core@2.1.18
│ │ │ ├── bson@1.0.4 deduped
│ │ │ └─┬ require_optional@1.0.1
│ │ │   ├── resolve-from@2.0.0
│ │ │   └── semver@5.5.0
│ │ └─┬ readable-stream@2.2.7
│ │   ├── buffer-shims@1.0.0
│ │   ├── core-util-is@1.0.2 deduped
│ │   ├── inherits@2.0.3 deduped
│ │   ├── isarray@1.0.0 deduped
│ │   ├── process-nextick-args@1.0.7 deduped
│ │   ├─┬ string_decoder@1.0.3
│ │   │ └── safe-buffer@5.1.1 deduped
│ │   └── util-deprecate@1.0.2 deduped
│ ├── mpath@0.3.0
│ ├── mpromise@0.5.5
│ ├─┬ mquery@2.3.3
│ │ ├── bluebird@3.5.0
│ │ ├─┬ debug@2.6.9
│ │ │ └── ms@2.0.0 deduped
│ │ ├── regexp-clone@0.0.1 deduped
│ │ └── sliced@0.0.5
│ ├── ms@2.0.0
│ ├── muri@1.3.0
│ ├── regexp-clone@0.0.1
│ └── sliced@1.0.1
├─┬ node-nmap@4.0.0
│ ├── queued-up@2.0.2
│ └─┬ xml2js@0.4.19
│   ├── sax@1.2.4
│   └── xmlbuilder@9.0.4
├─┬ sqlite3@3.1.13
│ ├── nan@2.7.0
│ └─┬ node-pre-gyp@0.6.38
│   ├─┬ hawk@3.1.3
│   │ ├─┬ boom@2.10.1
│   │ │ └── hoek@2.16.3 deduped
│   │ ├─┬ cryptiles@2.0.5
│   │ │ └── boom@2.10.1 deduped
│   │ ├── hoek@2.16.3
│   │ └─┬ sntp@1.0.9
│   │   └── hoek@2.16.3 deduped
│   ├─┬ mkdirp@0.5.1
│   │ └── minimist@0.0.8
│   ├─┬ nopt@4.0.1
│   │ ├── abbrev@1.1.1
│   │ └─┬ osenv@0.1.4
│   │   ├── os-homedir@1.0.2
│   │   └── os-tmpdir@1.0.2
│   ├─┬ npmlog@4.1.2
│   │ ├─┬ are-we-there-yet@1.1.4
│   │ │ ├── delegates@1.0.0
│   │ │ └── readable-stream@2.3.3 deduped
│   │ ├── console-control-strings@1.1.0
│   │ ├─┬ gauge@2.7.4
│   │ │ ├── aproba@1.2.0
│   │ │ ├── console-control-strings@1.1.0 deduped
│   │ │ ├── has-unicode@2.0.1
│   │ │ ├── object-assign@4.1.1
│   │ │ ├── signal-exit@3.0.2
│   │ │ ├─┬ string-width@1.0.2
│   │ │ │ ├── code-point-at@1.1.0
│   │ │ │ ├─┬ is-fullwidth-code-point@1.0.0
│   │ │ │ │ └── number-is-nan@1.0.1
│   │ │ │ └── strip-ansi@3.0.1 deduped
│   │ │ ├─┬ strip-ansi@3.0.1
│   │ │ │ └── ansi-regex@2.1.1
│   │ │ └─┬ wide-align@1.1.2
│   │ │   └── string-width@1.0.2 deduped
│   │ └── set-blocking@2.0.0
│   ├─┬ rc@1.2.1
│   │ ├── deep-extend@0.4.2
│   │ ├── ini@1.3.4
│   │ ├── minimist@1.2.0
│   │ └── strip-json-comments@2.0.1
│   ├─┬ request@2.81.0
│   │ ├── aws-sign2@0.6.0
│   │ ├── aws4@1.6.0
│   │ ├── caseless@0.12.0
│   │ ├─┬ combined-stream@1.0.5
│   │ │ └── delayed-stream@1.0.0
│   │ ├── extend@3.0.1
│   │ ├── forever-agent@0.6.1
│   │ ├─┬ form-data@2.1.4
│   │ │ ├── asynckit@0.4.0
│   │ │ ├── combined-stream@1.0.5 deduped
│   │ │ └── mime-types@2.1.17 deduped
│   │ ├─┬ har-validator@4.2.1
│   │ │ ├─┬ ajv@4.11.8
│   │ │ │ ├── co@4.6.0
│   │ │ │ └─┬ json-stable-stringify@1.0.1
│   │ │ │   └── jsonify@0.0.0
│   │ │ └── har-schema@1.0.5
│   │ ├── hawk@3.1.3 deduped
│   │ ├─┬ http-signature@1.1.1
│   │ │ ├── assert-plus@0.2.0
│   │ │ ├─┬ jsprim@1.4.1
│   │ │ │ ├── assert-plus@1.0.0
│   │ │ │ ├── extsprintf@1.3.0
│   │ │ │ ├── json-schema@0.2.3
│   │ │ │ └─┬ verror@1.10.0
│   │ │ │   ├── assert-plus@1.0.0
│   │ │ │   ├── core-util-is@1.0.2 deduped
│   │ │ │   └── extsprintf@1.3.0 deduped
│   │ │ └─┬ sshpk@1.13.1
│   │ │   ├── asn1@0.2.3
│   │ │   ├── assert-plus@1.0.0
│   │ │   ├─┬ bcrypt-pbkdf@1.0.1
│   │ │   │ └── tweetnacl@0.14.5 deduped
│   │ │   ├─┬ dashdash@1.14.1
│   │ │   │ └── assert-plus@1.0.0
│   │ │   ├─┬ ecc-jsbn@0.1.1
│   │ │   │ └── jsbn@0.1.1 deduped
│   │ │   ├─┬ getpass@0.1.7
│   │ │   │ └── assert-plus@1.0.0
│   │ │   ├── jsbn@0.1.1
│   │ │   └── tweetnacl@0.14.5
│   │ ├── is-typedarray@1.0.0
│   │ ├── isstream@0.1.2
│   │ ├── json-stringify-safe@5.0.1
│   │ ├─┬ mime-types@2.1.17
│   │ │ └── mime-db@1.30.0
│   │ ├── oauth-sign@0.8.2
│   │ ├── performance-now@0.2.0
│   │ ├── qs@6.4.0
│   │ ├── safe-buffer@5.1.1
│   │ ├── stringstream@0.0.5
│   │ ├─┬ tough-cookie@2.3.3
│   │ │ └── punycode@1.4.1
│   │ ├─┬ tunnel-agent@0.6.0
│   │ │ └── safe-buffer@5.1.1 deduped
│   │ └── uuid@3.1.0
│   ├─┬ rimraf@2.6.2
│   │ └─┬ glob@7.1.2
│   │   ├── fs.realpath@1.0.0
│   │   ├─┬ inflight@1.0.6
│   │   │ ├── once@1.4.0 deduped
│   │   │ └── wrappy@1.0.2 deduped
│   │   ├── inherits@2.0.3 deduped
│   │   ├─┬ minimatch@3.0.4
│   │   │ └─┬ brace-expansion@1.1.8
│   │   │   ├── balanced-match@1.0.0
│   │   │   └── concat-map@0.0.1
│   │   ├── once@1.4.0 deduped
│   │   └── path-is-absolute@1.0.1
│   ├── semver@5.4.1
│   ├─┬ tar@2.2.1
│   │ ├─┬ block-stream@0.0.9
│   │ │ └── inherits@2.0.3 deduped
│   │ ├─┬ fstream@1.0.11
│   │ │ ├── graceful-fs@4.1.11
│   │ │ ├── inherits@2.0.3 deduped
│   │ │ ├── mkdirp@0.5.1 deduped
│   │ │ └── rimraf@2.6.2 deduped
│   │ └── inherits@2.0.3
│   └─┬ tar-pack@3.4.0
│     ├─┬ debug@2.6.9
│     │ └── ms@2.0.0
│     ├── fstream@1.0.11 deduped
│     ├─┬ fstream-ignore@1.0.5
│     │ ├── fstream@1.0.11 deduped
│     │ ├── inherits@2.0.3 deduped
│     │ └── minimatch@3.0.4 deduped
│     ├─┬ once@1.4.0
│     │ └── wrappy@1.0.2
│     ├─┬ readable-stream@2.3.3
│     │ ├── core-util-is@1.0.2
│     │ ├── inherits@2.0.3 deduped
│     │ ├── isarray@1.0.0
│     │ ├── process-nextick-args@1.0.7
│     │ ├── safe-buffer@5.1.1 deduped
│     │ ├─┬ string_decoder@1.0.3
│     │ │ └── safe-buffer@5.1.1 deduped
│     │ └── util-deprecate@1.0.2
│     ├── rimraf@2.6.2 deduped
│     ├── tar@2.2.1 deduped
│     └── uid-number@0.0.6
└─┬ winston@2.4.0
  ├── async@1.0.0
  ├── colors@1.0.3
  ├── cycle@1.0.3
  ├── eyes@0.1.8
  ├── isstream@0.1.2
  └── stack-trace@0.0.10

# Description of the issue:
I get above mentioned error maybe every 10th time when I am sending msg. Same code has been working before. This project has been using Azure IoT 1,5 years.

# Code sample exhibiting the issue:
  hub.sendEvent(new Message(JSON.stringify(deviceState)), function(
    err,
    msg
  ) {
    console.log("sendEvent", err, msg)
  })

# Console log of the issue:
sendEvent { Error: AMQP Transport: Could not send
    at Object.translateError (/root/device/node_modules/azure-iot-amqp-base/lib/amqp_common_errors.js:88:25)
    at /root/device/node_modules/azure-iot-device-amqp/lib/amqp.js:29:40
    at /root/device/node_modules/azure-iot-device-amqp/lib/amqp.js:303:97
    at SenderLink.operationErrorHandler (/root/device/node_modules/azure-iot-amqp-base/lib/amqp.js:280:29)
    at SenderLink.emit (events.js:165:20)
    at constructor._onEnter (/root/device/node_modules/azure-iot-amqp-base/lib/sender_link.js:87:35)
    at constructor.transition (/root/device/node_modules/machina/lib/machina.js:653:28)
    at constructor.Fsm.(anonymous function) [as transition] (/root/device/node_modules/machina/lib/machina.js:466:63)
    at constructor.forceDetach (/root/device/node_modules/azure-iot-amqp-base/lib/sender_link.js:163:36)
    at constructor.handle (/root/device/node_modules/machina/lib/machina.js:613:25)
    at constructor.Fsm.(anonymous function) [as handle] (/root/device/node_modules/machina/lib/machina.js:466:63)
    at SenderLink._this._detachHandler (/root/device/node_modules/azure-iot-amqp-base/lib/sender_link.js:38:24)
    at SenderLink.emit (events.js:165:20)
    at SenderLink.Link.forceDetach (/root/device/node_modules/amqp10/lib/link.js:168:8)
    at SenderLink.forceDetach (/root/device/node_modules/amqp10/lib/sender_link.js:298:30)
    at forceDetachLink (/root/device/node_modules/amqp10/lib/session.js:452:41)
    at Array.forEach (<anonymous>)
    at Session._resetLinkState (/root/device/node_modules/amqp10/lib/session.js:453:31)
    at AMQPClient._clearConnectionState (/root/device/node_modules/amqp10/lib/amqp_client.js:379:36)
    at /root/device/node_modules/amqp10/lib/amqp_client.js:120:12
    at Promise._execute (/root/device/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/root/device/node_modules/bluebird/js/release/promise.js:483:18)
  amqpError: 
   { AmqpProtocolError: amqp:link:detach-forced:detach-forced
    at SenderLink.Link.forceDetach (/root/device/node_modules/amqp10/lib/link.js:170:12)
    at SenderLink.forceDetach (/root/device/node_modules/amqp10/lib/sender_link.js:298:30)
    at forceDetachLink (/root/device/node_modules/amqp10/lib/session.js:452:41)
    at Array.forEach (<anonymous>)
    at Session._resetLinkState (/root/device/node_modules/amqp10/lib/session.js:453:31)
    at AMQPClient._clearConnectionState (/root/device/node_modules/amqp10/lib/amqp_client.js:379:36)
    at /root/device/node_modules/amqp10/lib/amqp_client.js:120:12
    at Promise._execute (/root/device/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/root/device/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/root/device/node_modules/bluebird/js/release/promise.js:79:10)
    at AMQPClient.connect (/root/device/node_modules/amqp10/lib/amqp_client.js:117:10)
    at constructor._onEnter (/root/device/node_modules/azure-iot-amqp-base/lib/amqp.js:167:37)
    at constructor.transition (/root/device/node_modules/machina/lib/machina.js:653:28)
    at constructor.Fsm.(anonymous function) [as transition] (/root/device/node_modules/machina/lib/machina.js:466:63)
    at constructor.connect (/root/device/node_modules/azure-iot-amqp-base/lib/amqp.js:113:36)
    at constructor.handle (/root/device/node_modules/machina/lib/machina.js:613:25)
    at constructor.Fsm.(anonymous function) [as handle] (/root/device/node_modules/machina/lib/machina.js:466:63)
    at Amqp.connect (/root/device/node_modules/azure-iot-amqp-base/lib/amqp.js:397:19)
    at /root/device/node_modules/azure-iot-device-amqp/lib/amqp.js:236:45
    at SharedAccessKeyAuthenticationProvider.getDeviceCredentials (/root/device/node_modules/azure-iot-device/lib/sak_authentication_provider.js:64:9)
    at constructor._onEnter (/root/device/node_modules/azure-iot-device-amqp/lib/amqp.js:227:55)
    at constructor.transition (/root/device/node_modules/machina/lib/machina.js:653:28)
     name: 'AmqpProtocolError',
     message: 'amqp:link:detach-forced:detach-forced',
     condition: 'amqp:link:detach-forced',
     description: 'detach-forced',
     errorInfo: undefined } } undefined

**Comment by pierreca** [comment]
@jtjk from the stack trace it looks like something's wrong with the connection or session and the amqp10 library is disconnecting the link (which would make it impossible to send an event).

we pushed a few fixes both in the amqp10 and in our sdk in the latest iteration - i would suggest you update to the latest version first, to see if that helps or not. also a few related questions:
- how would you rate your device connectivity? (stable, unstable, low/high bandwidth?)
- are you configuring the a retry policy at all or using defaults?
- Are you using a device connection string or a shared access policy connection string?

if you want to give us more details about what's happening you can also set the `DEBUG` environment variable to `azure*` if you want to see just the SDK logs or `*` if you want to see SDK logs + amqp10 logs. if you post them here don't forget to scrub for potential confidential information.

**Comment by pierreca** [comment]
In the absence of additional feedback i'm closing this, feel free to reopen to add more context and help us debug the issue.
