### ISSUE TITLE
Typo on github page

### ISSUE THREAD

**Issue by prosser** [Azure/azure-iot-sdk-node#255]
# Context
See https://azure.github.io/azure-iot-sdk-node/

# Description of the issue:
This text has the typo (emphasis added to the typo):

> Devices and data sources in an IoT solution can range from a simple network-connected sensor **to a powerful**, to a standalone computing device.

Bold text should be omitted or edited to make a bit more sense.

# Code sample exhibiting the issue:
n/a

# Console log of the issue:
n/a

**Comment by pierreca** [comment]
fixed with https://github.com/Azure/azure-iot-sdk-node/commit/17b2a8306e1d2a4d03d6144a743f9c577c2f8c6f, thanks for reporting that!
