### ISSUE TITLE
ArgumentError: The connection string is missing the property: SharedAccessKeyName

### ISSUE THREAD

**Issue by zaheer308** [Azure/azure-iot-sdk-node#261]
![capture1](https://user-images.githubusercontent.com/36606213/38162449-e2890c6e-34fa-11e8-97e2-6aff5a5dd061.PNG)

**Comment by pierreca** [comment]
I believe with bash you need quotes around the connection string, otherwise the `;` is interpreted as the end of the command.

**Comment by pierreca** [comment]
@zaheer308 please let us know if that answers the question. in the absence of feedback, we'll close the issue in a couple days.
