### ISSUE TITLE
Azure IoT Hub Cloud to Device

### ISSUE THREAD

**Issue by pk12382** [Azure/azure-iot-sdk-node#265]
Hi All,
I am newbie for IoT, I have implement the sample code given on Azure site to send receive data on Cloud.
I have user RPI and send data to Azure IoT hub and data save in Azure Storage. It working fine.
But I am not able to receive Data from Cloud to Device repeatedly.
I am able to get data from Cloud to Device only once.
How to receive data continue from Cloud to Device.
I have used same example provided on Azure IoT Hub.
I have use Node.js on Azure Iot Hub and python in RPI

**Comment by anthonyvercolano** [comment]
Not sure which example you are referring to.  Not sure how you are sending from the cloud to the device.

What OS are you running on?

There is a template at https://github.com/Azure/azure-iot-sdk-node/issues/new that you could fill out that would provide more information and permit us to give a more informed response.

I often use the DeviceExplorer (a rapidly being depreciated tool), to do simply testing, for monitoring the device to cloud messages or to send cloud to device messages.  You can find that in the c# sdk.

https://github.com/Azure/azure-iot-sdk-csharp/releases

**Comment by pierreca** [comment]
@pk12382 without clarification from your side, we're closing the issue. feel free to add information and reopen it if you haven't solved this on your side already.
