### ISSUE TITLE
Could not send D2C message if device name contains '#'

### ISSUE THREAD

**Issue by formulahendry** [Azure/azure-iot-sdk-node#288]
# Context
- **OS and version used:** Windows 10
- **Node.js version:** v10.1.0
- **npm version:** 6.0.1
- **SDK version:** azure-iot-device-mqtt@1.4.1

# Code sample exhibiting the issue:
Update `<connectionString>` with connectionString of a device name which contains '#'
```javascript
'use strict';

var clientFromConnectionString = require('azure-iot-device-mqtt').clientFromConnectionString;
var Message = require('azure-iot-device').Message;
var connectionString = '<connectionString>';
var client = clientFromConnectionString(connectionString);

function printResultFor(op, client) {
    return function printResult(err, res) {
        if (err) console.log(op + ' error: ' + err.toString());
        if (res) console.log(op + ' status: ' + res.constructor.name);
        client.close();
    };
}

var connectCallback = function (err) {
    if (err) {
        console.log('Could not connect: ' + err);
    } else {
        console.log('Client connected');
        var data = 'Hello IoT Hub!';
        var message = new Message(data);
        console.log('Sending message: ' + message.getData());
        client.sendEvent(message, printResultFor('send', client));
    }
};

client.open(connectCallback);
```

# Console log of the issue:
```
Client connected
Sending message: Hello IoT Hub!
```
No `printResultFor` callback. No D2C message is sent

**Comment by pierreca** [comment]
likely an issue with how the topic is encoded. thanks for filing this!

**Comment by pierreca** [comment]
Ran a little experiment and it seems like support for  the `#` sign needs to be reviewed with the service team. resolution might take a few more weeks.

**Comment by pierreca** [comment]
Given the inactivity around these issues I'm closing them. For all intent and purposes I'd say the `#` sign isn't supported in device ids.

**Comment by az-iot-builder-01** [comment]
@formulahendry, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
