### ISSUE TITLE
azure-iot-device-amqp: method receiver link has invalid rcvSettleMode

### ISSUE THREAD

**Issue by annabokhan** [Azure/azure-iot-sdk-node#293]
# Context
- **OS and version used:** Ubuntu 16.04
- **Node.js version:** 9.8.0
- **npm version:** 5.6.0
- **list of installed packages:** 
├─┬ async@2.6.0
│ └── lodash@4.17.10 deduped
├── azure-iot-common@1.5.0
├─┬ azure-iot-device@1.4.1
│ ├── azure-iot-common@1.5.0 deduped
│ ├─┬ azure-iot-http-base@1.4.0
│ │ ├── azure-iot-common@1.5.0 deduped
│ │ ├── debug@3.1.0 deduped
│ │ └── uuid@3.2.1 deduped
│ ├── azure-storage@2.8.2 deduped
│ ├─┬ debug@3.1.0
│ │ └── ms@2.0.0
│ ├── lodash@4.17.10 deduped
│ ├─┬ machina@2.0.2
│ │ └── lodash@3.10.1
│ └── traverse@0.6.6
├─┬ azure-iot-device-amqp@1.4.1
│ ├── async@2.6.0 deduped
│ ├─┬ azure-iot-amqp-base@1.5.1
│ │ ├─┬ amqp10@3.6.0
│ │ │ ├── bl@1.2.1 deduped
│ │ │ ├── bluebird@3.5.1 deduped
│ │ │ ├── buffer-builder@0.2.0 deduped
│ │ │ ├─┬ debug@2.6.9
│ │ │ │ └── ms@2.0.0 deduped
│ │ │ ├── lodash@4.17.10 deduped
│ │ │ ├── node-int64@0.4.0 deduped
│ │ │ └── stately.js@1.3.0 deduped
│ │ ├─┬ amqp10-transport-ws@0.0.5
│ │ │ └── nodejs-websocket@1.7.1
│ │ ├── async@2.6.0 deduped
│ │ ├── azure-iot-common@1.5.0 deduped
│ │ ├── bluebird@3.5.1 deduped
│ │ ├── debug@3.1.0 deduped
│ │ ├── machina@2.0.2 deduped
│ │ └── uuid@3.2.1 deduped
│ ├── azure-iot-common@1.5.0 deduped
│ ├── azure-iot-device@1.4.1 deduped
│ ├── debug@3.1.0 deduped
│ ├── machina@2.0.2 deduped
│ └── uuid@3.2.1 deduped
├─┬ azure-iothub@1.3.0
│ ├── async@2.6.0 deduped
│ ├─┬ azure-iot-amqp-base@1.5.0
│ │ ├── amqp10@3.6.0 deduped
│ │ ├── amqp10-transport-ws@0.0.5 deduped
│ │ ├── async@2.6.0 deduped
│ │ ├── azure-iot-common@1.5.0 deduped
│ │ ├── bluebird@3.5.1 deduped
│ │ ├── debug@3.1.0 deduped
│ │ ├── machina@2.0.2 deduped
│ │ └── uuid@3.2.1 deduped
│ ├── azure-iot-common@1.5.0 deduped
│ ├─┬ azure-iot-http-base@1.3.3
│ │ ├── azure-iot-common@1.5.0 deduped
│ │ ├── debug@3.1.0 deduped
│ │ └── uuid@3.2.1 deduped
│ ├── debug@3.1.0 deduped
│ ├── lodash@4.17.10 deduped
│ └── machina@2.0.2 deduped

# Description of the issue:
Using AMQP transport, device fails to receive more than 100 method requests - link credits are exhausted and the refill policy does not kick in, because received messages were not settled. 
Explicitly setting the rcvSettleMode to 0 (autoSettle) in the link options [here](https://github.com/Azure/azure-iot-sdk-node/blob/7ff8a643a95e5c5db49a52d4509b7d66c4328416/device/transport/amqp/src/amqp_device_method_client.ts#L86) solves the problem:
```
const linkOptions = {
  attach: {
   properties: {
     'com.microsoft:api-version': endpoint.apiVersion,
     'com.microsoft:channel-correlation-id': credentials.deviceId
    },
    rcvSettleMode: 0
  }
}
```
# Console log of the issue:
```
Fri, 18 May 2018 19:25:40 GMT amqp10:framing => @transfer(20) [handle=1 deliveryId=102 deliveryTag=<Buffer 31 30 32> messageFormat=0 settled=false more=false rcvSettleMode=0 state=null resume=false aborted=false batchable=false]
Fri, 18 May 2018 19:25:40 GMT amqp10:framing <= @transfer(20) [handle=2 deliveryId=101 deliveryTag=<Buffer a1 36 2d b2 49 c4 68 4b 8d 60 ab 00 c4 64 b2 d7> messageFormat=0 settled=true more=false rcvSettleMode=0 state=null resume=false aborted=false batchable=false]
Fri, 18 May 2018 19:25:40 GMT amqp10:link:receiver Rx message 101 on /devices/1526671524441/methods/devicebound_cb631a56-e7f3-4cbb-9c84-465c40615db8, 0 credit, 298 window left.
Fri, 18 May 2018 19:25:40 GMT amqp10:link:receiver received from (/devices/1526671524441/methods/devicebound_cb631a56-e7f3-4cbb-9c84-465c40615db8): {}
```

# Simple test that reproduces the problem:

    let client = require('azure-iothub').Client.fromConnectionString(connectionString);
     async.times(101, (n, next) => {
            client.invokeDeviceMethod(deviceId, {
                methodName: 'someMethod',
                payload: {},
                responseTimeoutInSeconds: 60,
                connectTimeoutInSeconds: 5
            }, (err, response) => {
                console.log(n, err);
                next(err)
            })
        }, done)

**Comment by pierreca** [comment]
@annabokhan thanks for filing this, definitely a bug - @anthonyvercolano I think there are 2 ways to fix this: either set the recvSettleMode as suggested or manually accept method requests as they come in. both ways are valid imho. Can you take a look ?

**Comment by anthonyvercolano** [comment]
Already on it.  Investigating.

**Comment by anthonyvercolano** [comment]
I believe the best fix would be to change the link options for the method link to first.

We'll try to have something for you early in the week.

**Comment by annabokhan** [comment]
Thank you for the prompt response

**Comment by anthonyvercolano** [comment]
#294

**Comment by anthonyvercolano** [comment]
Has been fixed in the latest release.

**Comment by pierreca** [comment]
@annabokhan 

thank you for your contribution to our open-sourced project! Please help us improve by filling out [this 2-minute customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V).
