### ISSUE TITLE
1.4.2 Libraries not published on npm correctly?

### ISSUE THREAD

**Issue by arkuhn** [Azure/azure-iot-sdk-node#297]
# Context
Updating the device and mqtt node libraries

# Description of the issue:
Release 1.4.2 as listed on the release pages of this repository is not published on npm as 1.4.2 / is out of sync with GitHub.

![image](https://user-images.githubusercontent.com/9009111/40373589-3aa4c806-5db5-11e8-97ef-012f37ca7355.png)
![image](https://user-images.githubusercontent.com/9009111/40373611-46722a2a-5db5-11e8-88d8-aee63571a029.png)

Resulting in the following npm error message:
`No matching version found for azure-iot-device@1.4.2`

**Comment by BertKleewein** [comment]
investigating

**Comment by BertKleewein** [comment]
There is an active issue at npmjs.org which would explain this.  I am continuing to monitor.
https://status.npmjs.org/incidents/3rjzvts6v98k

**Comment by arkuhn** [comment]
Thank you for looking into this. Its worth noting that not only does the website _display_ 1.4.1, but I am unable to **install** 1.4.2 using npm.
```
npm install azure-iot-device@1.4.2
npm ERR! code ETARGET
npm ERR! notarget No matching version found for azure-iot-device@1.4.2
```


 Thanks again!

**Comment by anthonyvercolano** [comment]
We simply rev’d the versions and pushed out new packages.  Newest version DO show up on npm now.

**Comment by arkuhn** [comment]
Thank you!

**Comment by pierreca** [comment]
@arkuhn 
thank you for your contribution to our open-sourced project! Please help us improve by filling out [this 2-minute customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V).
