### ISSUE TITLE
sendEventBatch crashes

### ISSUE THREAD

**Issue by murdockcrc** [Azure/azure-iot-sdk-node#3]
I am trying to send batched events using the NodeJS SDK, by calling method `client.sendEventBatch()`.

However, the app crashes with the following exception:

```
"thisClient._transport.sendEventBatch is not a function"
```

This happens on _client.js_, line 192:

```JS
sendEventBatch: function (msgBatch, sendEventBatchCallback) {
      thisClient._transport.sendEventBatch(msgBatch, function(err, result) { //App crashes here
            safeCallback(sendEventBatchCallback, err, result);
          });
        },
```

**Comment by anthonyvercolano** [comment]
Hi,

Which protocol are you using?  sendEventBatch is only available with http.

I would say that crashing seems inappropriate to me.   I will discuss with the team a more graceful way of failing.

Tony

**Comment by anthonyvercolano** [comment]
This will be addressed in a future release of the node sdk.  We will raise a different exception - "not implemented"

**Comment by pierreca** [comment]
I just added code to throw the correct exception: https://github.com/Azure/azure-iot-sdk-node/commit/6c95bbb0543f73d6cb7d850f327d5a6784933e74
