### ISSUE TITLE
Unhandled 'error' event - at MqttClient._handleConnack

### ISSUE THREAD

**Issue by periclesroalves** [Azure/azure-iot-sdk-node#307]
- **list of installed packages:** 
```
azure-iot-device@1.4.1
azure-iot-device-mqtt@1.4.1
azure-iot-mqtt-base@1.4.0
mqtt@2.17.0
```

Very often our application is terminated by an unhandled error event coming from the SDK, always with the following output:

```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Connection refused: Not authorized
    at MqttClient._handleConnack (/app/node_modules/mqtt/lib/client.js:893:15)
    at MqttClient._handlePacket (/app/node_modules/mqtt/lib/client.js:329:12)
    at work (/app/node_modules/mqtt/lib/client.js:271:12)
    at Writable.writable._write (/app/node_modules/mqtt/lib/client.js:281:5)
    at doWrite (/app/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/app/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at Writable.write (/app/node_modules/mqtt/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at TLSSocket.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at TLSSocket.Readable.push (_stream_readable.js:208:10)
    at TLSWrap.onread (net.js:607:20
```

Inspecting the SDK code, the error handler for the MQTT client is registered as soon as it's returned by `connect()`. Checking the lib MQTT code, there's not synchronous path from `connect()` to the point where the error is emitted (`handleConnack()`), so there's no possibility that it's being emitted before the client is returned.

The error handler is unregistered before the client is closed in the following part of `mqtt_base.ts`:

```
  private _disconnectClient(forceDisconnect: boolean, callback: () => void): void {
    this._mqttClient.removeAllListeners();
    /* Codes_SRS_NODE_COMMON_MQTT_BASE_16_001: [The disconnect method shall call the done callback when the connection to the server has been closed.] */
    this._mqttClient.end(forceDisconnect, callback);
  }
```

If `forceDisconnect` is false (which seems to be the case for most flows in the SDK), the client does close the underlying TCP stream when `end()` is called, thus a `connAck` packet can still be parsed and the observed error will emitted, even though we already unregistered the error handler.

MQTT lib does not provide a way to find out when the underlying stream has been effectively closed and it's safe to unregister the error handler, so we might have to request this functionality there.

AB#7366634

**Comment by pierreca** [comment]
@periclesroalves thanks for filing this issue - do you have a way to reproduce the issue that would allow us to hook up a debugger ?

**Comment by periclesroalves** [comment]
@pierreca, unfortunately I don't. I tried to repro it by explicitly disabling my device from IotHub's side, which answers with the same `Not authorized` error, but it seems like it's a timing issue, e.g., a `connAck` has to arrive from the server between the call to `end()` and the `disconnect` packet is sent by the client before closing the stream.

**Comment by pierreca** [comment]
@periclesroalves just out of curiosity have you tried commenting out the call to `removeAllListeners()` to validate your hypothesis?

IIRC we've had issues in the past with the call to `end()` hanging - which might be why we decided to remove all listeners before we call it instead of in a callback. we could switch those 2 lines and see if that solves the issue but it's still a shot in the dark at that point.

**Comment by periclesroalves** [comment]
@pierreca, I haven't commented it to test, since there are only two places in the code where this error listener is removed (the other one happens after the call to `end()`) and the probability of this happening depends on how often IotHub answers with a connection refused.

Moving `removeAllListeners()` to the `end()` callback might reduce the frequency, but won't eliminate this scenario, since MQTT calls the `end()` callback before closing the tcp pipe, which means a new packet can still show up and trigger the error.

**Comment by pierreca** [comment]
@periclesroalves so it sounds like we have a bigger problem that may need refactoring both in the SDK and in the mqtt.js library - likely not something we can tackle before july.

if you have a way to test whether commenting out the call to removeAllListeners() influences the problem, I'd greatly appreciate the info.

**Comment by periclesroalves** [comment]
Just an update on this: I was waiting for a spot on a test env. I commented the call to `removeAllListeners()` to see if it has any influence. I'll update here again in a week or so.

**Comment by pierreca** [comment]
@periclesroalves did you see any difference by any chance?

**Comment by periclesroalves** [comment]
@pierreca I commented the calls to `removeAllListers()` and left it running in our test env. I observed it for a week, but it didn't fail. Again, the number of devices in our test env is much smaller, so we can't be sure that the scenario actually happened. But considering that some failure would happen in our test env every 2-3 days, it's a positive sign.

I then changed the MQTT lib itself to print the `inspect()` output for the client right before emitting the `error` event that ends the process, to see if we can get any useful info about the context. The only interesting thing is that, as expected, there are no event handlers registered and the client is in a `disconnecting` state. Here's the output:

```
MqttClient {
  options: 
   { protocol: 'mqtts',
     slashes: true,
     auth: null,
     host: '<REDACTED>',
     port: 8883,
     hostname: '<REDACTED>',
     hash: null,
     search: '',
     query: {},
     pathname: null,
     href: '<REDACTED>',
     protocolId: 'MQTT',
     protocolVersion: 4,
     clean: false,
     clientId: '<REDACTED>',
     rejectUnauthorized: true,
     username: '<REDACTED>',
     reconnectPeriod: 0,
     keepalive: 180,
     reschedulePings: false,
     password: '<REDACTED>',
     connectTimeout: 30000,
     resubscribe: true },
  streamBuilder: [Function: wrapper],
  outgoingStore: 
   Store {
     options: 
      { clean: true },
     _inflights: {} },
  incomingStore: 
   Store {
     options: 
      { clean: true },
     _inflights: {} },
  queueQoSZero: true,
  _resubscribeTopics: {},
  messageIdToTopic: {},
  pingTimer: null,
  connected: false,
  disconnecting: true,
  queue: 
   [ { packet: 
        { cmd: 'disconnect' },
       cb: [Function: bound setImmediate] } ],
  connackTimer: 
   Timeout {
     '0': null,
     _called: false,
     _idleTimeout: -1,
     _idlePrev: null,
     _idleNext: null,
     _idleStart: 169693431,
     _onTimeout: null,
     _timerArgs: undefined,
     _repeat: null,
     _destroyed: false,
     [Symbol(asyncId)]: 4139309,
     [Symbol(triggerAsyncId)]: 4139281 },
  reconnectTimer: null,
  nextId: 10225,
  outgoing: {},
  _events: {},
  _eventsCount: 0,
  domain: null,
  _maxListeners: undefined,
  stream: 
   TLSSocket {
     _tlsOptions: 
      { pipe: false,
        secureContext: 
         SecureContext {
           context: SecureContext {},
           singleUse: true },
        isServer: false,
        requestCert: true,
        rejectUnauthorized: true,
        session: undefined,
        NPNProtocols: undefined,
        ALPNProtocols: undefined,
        requestOCSP: undefined },
     _secureEstablished: true,
     _securePending: false,
     _newSessionPending: false,
     _controlReleased: true,
     _SNICallback: null,
     servername: null,
     npnProtocol: undefined,
     alpnProtocol: false,
     authorized: true,
     authorizationError: null,
     encrypted: true,
     _events: 
      { close: 
         [ [Function],
           [Function: onclose],
           [Function: bound setImmediate] ],
        end: 
         [ { [Function: bound onceWrapper]
             listener: [Function: onend] },
           { [Function: bound onceWrapper]
             listener: [Function: onend] },
           [Function: onend] ],
        finish: 
         [ [Function: onSocketFinish],
           [Function: onfinish] ],
        _socketEnd: [Function: onSocketEnd],
        secure: [Function],
        secureConnect: [Function],
        error: 
         [ [Function: nop],
           [Function: onerror] ],
        data: [Function: ondata] },
     _eventsCount: 8,
     connecting: false,
     _hadError: false,
     _handle: 
      TLSWrap {
        _parent: 
         TCP {
           reading: [Getter/Setter],
           owner: [Circular],
           onread: null,
           onconnection: null,
           writeQueueSize: 0 },
        _parentWrap: undefined,
        _secureContext: 
         SecureContext {
           context: SecureContext {},
           singleUse: true },
        reading: true,
        owner: [Circular],
        onread: [Function: onread],
        writeQueueSize: 0,
        onhandshakestart: [Function],
        onhandshakedone: [Function],
        onocspresponse: [Function],
        onerror: [Function] },
     _parent: null,
     _host: '<REDACTED>',
     _readableState: 
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: 
         BufferList {
           head: null,
           tail: null,
           length: 0 },
        length: 0,
        pipes: 
         Writable {
           _writableState: 
            WritableState {
              objectMode: false,
              highWaterMark: 16384,
              finalCalled: false,
              needDrain: false,
              ending: false,
              ended: false,
              finished: false,
              destroyed: false,
              decodeStrings: true,
              defaultEncoding: 'utf8',
              length: 4,
              writing: true,
              corked: 0,
              sync: true,
              bufferProcessing: false,
              onwrite: [Function],
              writecb: [Function: nop],
              writelen: 4,
              bufferedRequest: null,
              lastBufferedRequest: null,
              pendingcb: 1,
              prefinished: false,
              errorEmitted: false,
              bufferedRequestCount: 0,
              corkedRequestsFree: 
               CorkedRequest {
                 next: null,
                 entry: null,
                 finish: [Function] } },
           writable: true,
           domain: null,
           _events: 
            { unpipe: [Function: onunpipe],
              drain: [Function],
              error: [Function: onerror],
              close: 
               { [Function: bound onceWrapper]
                 listener: [Function: onclose] },
              finish: 
               { [Function: bound onceWrapper]
                 listener: [Function: onfinish] } },
           _eventsCount: 5,
           _maxListeners: undefined,
           _write: [Function] },
        pipesCount: 1,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: false,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: true,
     domain: null,
     _maxListeners: 1000,
     _writableState: 
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: false,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        destroyed: false,
        decodeStrings: false,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: false,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: 
         { next: 
            { next: null,
              entry: null,
              finish: [Function: bound onCorkedFinish] },
           entry: null,
           finish: [Function: bound onCorkedFinish] } },
     writable: true,
     allowHalfOpen: false,
     _bytesDispatched: 505,
     _sockname: null,
     _pendingData: null,
     _pendingEncoding: '',
     server: undefined,
     _server: null,
     ssl: 
      TLSWrap {
        _parent: 
         TCP {
           reading: [Getter/Setter],
           owner: [Circular],
           onread: null,
           onconnection: null,
           writeQueueSize: 0 },
        _parentWrap: undefined,
        _secureContext: 
         SecureContext {
           context: SecureContext {},
           singleUse: true },
        reading: true,
        owner: [Circular],
        onread: [Function: onread],
        writeQueueSize: 0,
        onhandshakestart: [Function],
        onhandshakedone: [Function],
        onocspresponse: [Function],
        onerror: [Function] },
     _requestCert: true,
     _rejectUnauthorized: true,
     read: [Function],
     _consuming: true,
     [Symbol(asyncId)]: 4139304,
     [Symbol(bytesRead)]: 0 } }
```

**Comment by pierreca** [comment]
@periclesroalves thanks for the update!
do you think, using the same mechanism, that you could dump the state of the `azure-iot-device-mqtt.Mqtt` state machine?

**Comment by periclesroalves** [comment]
@pierreca just to make sure, you want the state of `Mqtt` and **not** `MqttBase`, right. I'll register a dummy error handler right after `removeAllListers()` that emits a different event, so `Mqtt` can dump it's state and end the process.

**Comment by pierreca** [comment]
@periclesroalves actually that's a good point - both MqttBase and Mqtt would be even better.

**Comment by peolivei2** [comment]
@pierreca here's the data:

MqttBase._fsm:
```
constructor {
  namespace: 'mqtt-base',
  initialState: 'disconnected',
  states: { ... },
  eventListeners: { ... },
  useSafeEmit: false,
  hierarchy: {},
  pendingDelegations: {},
  _stamped: true,
  inputQueue: [],
  targetReplayState: 'connecting',
  state: 'connecting',
  priorState: 'disconnected',
  priorAction: 'disconnected.connect',
  currentAction: '',
  currentActionArgs: undefined,
  inExitHandler: false }
```
Mqtt._fsm:
```
constructor {
  initialState: 'disconnected',
  states: { ... },
  eventListeners: { ... },
  namespace: 'fsm.1004',
  useSafeEmit: false,
  hierarchy: {},
  pendingDelegations: {},
  _stamped: true,
  inputQueue: [],
  targetReplayState: 'connecting',
  state: 'connecting',
  priorState: 'disconnected',
  priorAction: '',
  currentAction: '',
  currentActionArgs: undefined,
  inExitHandler: false }
```
These were printed by a dummy error listener that I added to the mqtt client right after the call to `removeAllListeners()` in [line 36 of mqtt_base.ts](https://github.com/Azure/azure-iot-sdk-node/blob/master/common/transport/mqtt/src/mqtt_base.ts#L36). Inspecting the transitions in the code, this means that either the error listener is being called after the call to `MQTT.end()` or after the mqtt client itself emits a `close` event (as `closeEvent` is the only place that transitions to `disconnected` without passing through `MQTT.end()` first).

In any case, this means that the mqtt client is emitting an error event after we remove the handler and there doesn't seem to be another place were we can remove the listeners at a later point than we do today. I still think the root of the problem is what I mentioned in the other comment: MQTT doesn't have a way to signal that the TCP pipe has been effectively closed, which would be the safest way to remove the handler.

**Comment by khendry** [comment]
I'm seeing this same call stack and error, while trying to use the DPS `client.register()` to provision a device. I'm using an intermediate cert on the DPS provisioning group and have verified the certs and chain locally.

**Comment by khendry** [comment]
> I'm seeing this same call stack and error, while trying to use the DPS `client.register()` to provision a device. I'm using an intermediate cert on the DPS provisioning group and have verified the certs and chain locally. 

I've found my issue and it appears to be a pure case of p.e.b.k.a.c.
