### ISSUE TITLE
receiveFeedback doesn't work

### ISSUE THREAD

**Issue by taroyutao** [Azure/azure-iot-sdk-node#312]
I refer to the [document](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-node-node-c2d)

Every thing works fine except the receiveFeedback.

code sample:

```js
'use strict';

var Client = require('azure-iothub').Client;
var Message = require('azure-iot-common').Message;

var connectionString = 'HostName=<REMOVED>;SharedAccessKeyName=iothubowner;SharedAccessKey=<REMOVED>';
var targetDevice = 'test';

var serviceClient = Client.fromConnectionString(connectionString);

function printResultFor(op) {
  return function printResult(err, res) {
    if (err) console.log(op + ' error: ' + err.toString());
    if (res) console.log(op + ' status: ' + res.constructor.name);
  };
}

function receiveFeedback(err, receiver){
  receiver.on('message', function (msg) {
    console.log('Feedback message:')
    console.log(msg.getData().toString('utf-8'));
  });
}

serviceClient.open(function (err) {
  if (err) {
    console.error('Could not connect: ' + err.message);
  } else {
    console.log('Service client connected');
    serviceClient.getFeedbackReceiver(receiveFeedback);
    var message = new Message('Cloud to device message.');
    message.ack = 'full';
    message.messageId = "My Message ID";
    console.log('Sending message: ' + message.getData());
    serviceClient.send(targetDevice, message, printResultFor('send'));
  }
});
```
The result is:

---

![image](https://user-images.githubusercontent.com/20704268/41355327-ccd27854-6f53-11e8-83f0-9072b3b8606b.png)

---

I use it in  device exployer, it works fine:
---
![image](https://user-images.githubusercontent.com/20704268/41355517-4c754636-6f54-11e8-9c10-b33a2c1c311a.png)
---

It's also working fine in java sdk, does it a bug in node sdk?

**Comment by pierreca** [comment]
Thanks for filing this issue, I'm going to look into it. I've removed the shared access key from your question, please rotate it and in the future be careful about posting secrets in public questions.

**Comment by pierreca** [comment]
@taroyutao just tested this feature manually (it's also tested automatically with each release), and it seems to work fine. when using device explorer, are you using exactly the same device code? 

one thing you can do to gather more data and help debug the issue is to set the `DEBUG` environment variable to `*`. 

Also, in the issue template, we ask for SDK version, OS and version of node, those are all useful information if you want us to try and reproduce the issue.

**Comment by taroyutao** [comment]
@pierreca thanks for your feedback.

Project download[ link](https://yunewstoragetest.blob.core.chinacloudapi.cn/aaaaa/dd.zip)

use code:
---
node test.js

---

node version: v8.11.3

send same:


![qq 20180614202629](https://user-images.githubusercontent.com/20704268/41412014-431c9e1e-7011-11e8-84d3-636f58952471.png)

**Comment by pierreca** [comment]
@taroyutao you just resent exactly the same information, it's not really going to help much.

Please:
1. set the `DEBUG` environment variable to `*`
2. add code to handle potential errors in the `getFeedbackReceiver` call
3. make sure you call `client.complete(message, callback)` on the device side. I still haven't seen the device code.

add the code and the logs in the issue rather than in zip files.

thanks

**Comment by taroyutao** [comment]
@pierreca thanks for your advice.

I am sure I have called client.complete(message, callback), my device code as follows:

**C# code:**

---
using System;
using Microsoft.Azure.Devices.Client;
using System.Text;

namespace SimulatedDevice
{
    class Program
    {
        static DeviceClient deviceClient;
        static string iotHubUri = "<iot url>";
        static string deviceKey = "<key>";

        static void Main(string[] args)
        {
            deviceClient = DeviceClient.Create(iotHubUri, new DeviceAuthenticationWithRegistrySymmetricKey("yudevicetest", deviceKey), TransportType.Mqtt);
            ReceiveC2dAsync();
            Console.ReadKey();
        }

        private static async void ReceiveC2dAsync()
        {
            Console.WriteLine("\nReceiving cloud to device messages from service");
            while (true)
            {
                Message receivedMessage = await deviceClient.ReceiveAsync();
                if (receivedMessage == null) continue;

                Console.ForegroundColor = ConsoleColor.Yellow;
                Console.WriteLine("Received message: {0}", Encoding.ASCII.GetString(receivedMessage.GetBytes()));
                Console.ResetColor();

                await deviceClient.CompleteAsync(receivedMessage);
            }
        }
    }
}
---

It works fine and can receive the message. I used [device deployer](https://github.com/Azure/azure-iot-sdk-csharp/tree/master/tools/DeviceExplorer) to send C2D, it has feedback. So I think the device code is ok.

I have try to set the debug environment variable to *, but we cannot get more information:

---

![11](https://user-images.githubusercontent.com/20704268/41468656-54329790-70dd-11e8-931c-44644d6f6f1e.png)

---

The device also can receive the message which i send from sever.

I also test the nodejs iot device exployer in Linux by the [link](https://github.com/azure/iothub-explorer), it also cannot get the feedback infomation, the device can receive the message.

![feedback](https://user-images.githubusercontent.com/20704268/41469206-f9c38c4a-70de-11e8-9bca-852a75274ae6.png)

I'm not too good at Nodejs language.  I will try my best on this issue.

I think it's easy to reproduce the issue. Look forward to your more help.

Thanks.

**Comment by pierreca** [comment]
@taroyutao if you set the `DEBUG` env variable to `express;*` you're not going to see anything related to the SDK. Please set it to just `*`. Without the logs, there's nothing I can do to help you as I cannot reproduce the issue (if i could, it'd have a fix already... all our end-to-end tests and samples work fine so I don't know what's going on here)

**Comment by taroyutao** [comment]
@pierreca I have tried to create a new Iot hub in new region, everything works fine. So I think there is someting wrong with the server, ignore it. A new one can satisfy the needs.

So this issue can been closed. Thank you very much for your help.

**Comment by pierreca** [comment]
@taroyutao OK, thanks for the feedback!

If you want to follow up with specifics on why it doesn't work with the other hub I would encourage you to file a support request on the Azure portal:  [here's how to do it](https://docs.microsoft.com/en-us/azure/azure-supportability/how-to-create-azure-support-request).

*thank you for your contribution to our open-sourced project! Please help us improve by filling out [this 2-minute customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V).*
