### ISSUE TITLE
Should call setOptions with CA cert file's content instead of path

### ISSUE THREAD

**Issue by LazarusX** [Azure/azure-iot-sdk-node#321]
In https://github.com/Azure/azure-iot-sdk-node/blob/21a130fb1d9194f29e57a51e14005246edfe6938/device/core/src/module_client.ts#L309, the `setOption` function is called with the CA cert file's path instead of the content string, which causes error “Could not connect: unable to get local issuer certificate”.

**Comment by pierreca** [comment]
@avranju is looking at that - thanks for helping us track this here!

**Comment by avranju** [comment]
PR #324 is out for fixing this issue.

**Comment by pierreca** [comment]
#324 has been merged!
