### ISSUE TITLE
Why doesn't this SDK use the shared C library?

### ISSUE THREAD

**Issue by vortec** [Azure/azure-iot-sdk-node#33]
Hello there!
I'm wondering why this repository, unlike the Python SDK, doesn't use the shared C library (https://github.com/Azure/azure-iot-sdk-c).
Is it for performance or security reasons? Was it simpler to rewrite from scratch than to integrate a C extension? What about maintenance work when the protocol changes?
Thanks :)

**Comment by olivierbloch** [comment]
Hi @vortec 

We looked at several solutions for having as much common code as possible across our SDKs and estimated that the amount of efforts, time and complexity of the various wrapper, transpilation, and other such solutions was not worth it: the developer experience and the feedback from Node.js community made it clear that Native JS was preferred.
Another big advantage of native JS is the ease for the community to contribute to the SDK.

For Python, we made a different choice, but are not excluding switching to native Python code as we are constantly monitoring feedback and usage.
Your input in very welcome.
Thanks

**Comment by pierreca** [comment]
to add to that: we evaluated mainly node-gyp, emscripten, edgejs and a couple other options I can't remember, and none were satisfactory experience-wise. Each asked significant sacrifices (developer experience, performance, portability, maintenance needed...). on top of that we asked people who work on packages we depend on and people who depend on our SDK, and all sides told us using C bindings would make their life worse. So we elected not to do that.
 
The feedback on the Python side was not nearly as clear-cut - but as @olivierbloch said we're always looking for feedback and will listen to any argumented opinion.

Closing this as I believe this answers your question, feel free to reopen if you need clarifications.
