### ISSUE TITLE
azure-iot-security-tpm broken with Node.js v10.x.x

### ISSUE THREAD

**Issue by pierreca** [Azure/azure-iot-sdk-node#332]
Because of this;
- https://github.com/node-ffi/node-ffi/issues/465

as soon as a new package is published we will pull the new version of ffi and close this.

**Comment by pierreca** [comment]
@w01fgang That's a possibility we may have to consider but it looks like the maintainers are still active and that the fixes have been checked in so I'm willing to wait a little more to see if they publish a new version.

**Comment by pierreca** [comment]
update: now looking at fastcall and node-ffi-napi as alternatives.

**Comment by pierreca** [comment]
The fix for this was released with https://github.com/Azure/azure-iot-sdk-node/tree/2019-03-05

**Comment by az-iot-builder-01** [comment]
@w01fgang, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
