### ISSUE TITLE
Failing to connector from React Node.js web app

### ISSUE THREAD

**Issue by walpoletim-bjss** [Azure/azure-iot-sdk-node#337]
I have successfully used your code in a node.js backend application.

console.log("CONNECTING: ", connectionString)
        client = clientFromConnectionString(connectionString);
        console.log('IOT SETUP');
        
        var connectCallback = function (err) {
            console.log('IOT CALLBACK');
            if (err) {
                console.log('Could not connect: ' + err);
                
            } else {
                console.log('Client connected');
                
            }
          };
          console.log("OPENING CONNECTION")
          client.open(connectCallback);

        }

However, when the same code is used inside a React application, the connection fails - The callback is never called, and the following error is thrown:

VM366 bundle.js:110162 Uncaught TypeError: Cannot read property 'then' of undefined
    at App.connect (VM366 bundle.js:110162)
    at onSubmit (VM366 bundle.js:110040)
    at HTMLUnknownElement.boundFunc (VM366 bundle.js:34458)
    at Object.ReactErrorUtils.invokeGuardedCallback (VM366 bundle.js:34464)
    at executeDispatch (VM366 bundle.js:33979)
    at Object.executeDispatchesInOrder (VM366 bundle.js:34002)
    at executeDispatchesAndRelease (VM366 bundle.js:22229)
    at executeDispatchesAndReleaseTopLevel (VM366 bundle.js:22240)
    at Array.forEach (<anonymous>)
    at forEachAccumulated (VM366 bundle.js:74034)
    at Object.processEventQueue (VM366 bundle.js:22440)
    at runEventQueueInBatch (VM366 bundle.js:166599)
    at Object.handleTopLevel [as _handleTopLevel] (VM366 bundle.js:166609)
    at handleTopLevelImpl (VM366 bundle.js:166694)
    at ReactDefaultBatchingStrategyTransaction.perform (VM366 bundle.js:27967)
    at Object.batchedUpdates (VM366 bundle.js:166446)
    at Object.batchedUpdates (VM366 bundle.js:16246)
    at dispatchEvent (VM366 bundle.js:166769)

**Comment by pierreca** [comment]
@walpoletim-bjss Sorry to hear your hitting this - My understanding is that React is a client-side framework meant to be run in a browser or browser-like environment (such as Electron). Our SDK is meant to run within a Node.js process: it's not a generic multi-modal, browser-compatible javascript SDK: it's just meant for Node.js. So I'm afraid we do not build nor test nor support this use case.

Or am I missing something? can you clarify how you integrate the SDK in your application? Without more detail, it's impossible for us to help or see what's going on. This stack trace unfortunately does not tell us anything we can use.

**Comment by walpoletim-bjss** [comment]
Hi

Thanks for the reply.  Here is the use case which is popular and well used.

Use mqtt ( over websockets) to run a chatbot connection over iot either unauthenticated or potentially authenticated.

I am more than happy to have detailed discussion with relevant people to provide you with business case justifications for this if required.

Tim

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by pierreca** [comment]
@walpoletim-bjss sure: @yzhong94 is probably the right person to lead this discussion on our side. either leave your email here (we can delete the comment later) or for more confidentiality open a support request on the azure portal (anyone with a subscription can do that for free) and mention this issue and both my username and @yzhong94 in the description ([support](https://docs.microsoft.com/en-us/azure/azure-supportability/how-to-create-azure-support-request)).

In addition as far as react support is concerned it's a big work item that hinges on many things (we're dependent on the node runtime and some of our dependencies are too) so it's an item we'd track in uservoice rather than on a github issue: [User Voice](https://feedback.azure.com/forums/321918-azure-iot)

**Comment by walpoletim-bjss** [comment]
Hi

Thanks for the reply – can you please touch base directly at Tim.Walpole@bjss.com<mailto:Tim.Walpole@bjss.com>, so we can discuss in more detail

Thanks

Tim

**Comment by pierreca** [comment]
deleted comment with email as promised - we'll reach out.

**Comment by az-iot-builder-01** [comment]
@walpoletim-bjss, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/DesignPage.aspx#FormId=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu&Token=af48ed4ed02842bea21e0d3933b78fac)
