### ISSUE TITLE
ExponentialBackOffWithJitter algorithm not implemented as documented

### ISSUE THREAD

**Issue by smanousos** [Azure/azure-iot-sdk-node#338]
azure-iot-common version 1.7.1, retry_policy.js line 93:
`return Math.min(constants.cMin + (Math.pow(retryCount - 1, 2) - 1) * randomJitter, constants.cMax);`

This uses (retryCount - 1)^2.  To match the documentation it should be 2^(retryCount - 1)

**Comment by pierreca** [comment]
@smanousos the PR is out - the fix will be part of our next release. That was an embarassing one... thanks for finding this!! I will update this issue when the fix is checked in and again when it is released.

**Comment by smanousos** [comment]
"embarrassing": been there, done that.
thanx for the quick response!

**Comment by pierreca** [comment]
packages were published (v1.7.2) with the fix included. Thanks a lot for reporting this!

**Comment by az-iot-builder-01** [comment]
@smanousos, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/DesignPage.aspx#FormId=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu&Token=af48ed4ed02842bea21e0d3933b78fac)
