### ISSUE TITLE
Possible memory leak using azure-iot-amqp-base (on client:errorReceived)

### ISSUE THREAD

**Issue by gagle** [Azure/azure-iot-sdk-node#35]
```
azure-iot-amqp-base@1.1.6
azure-iothub@1.1.7
```

I would like to explain an issue that we're having with a Nodejs module when we're using the AMQP WS library. We can successfully connect to Azure and send messages but after some time of inactivity (~3-4hrs aprox) Nodejs emits a warning:

```
Warning: Possible EventEmitter memory leak detected. 11 client:errorReceived listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:259:19)
    at AMQPClient.addListener (events.js:275:10)
    at Amqp.connect (C:\\Program Files\iconnect\iconnect-message-handler\node_modules\iconnect-message-handler\node_modules\azure-iot-amqp-base\lib\amqp.js:108:16)
    at AmqpWs.connect (C:\\Program Files\iconnect\iconnect-message-handler\node_modules\iconnect-message-handler\node_modules\azure-iothub\lib\amqp.js:84:14)
    at AmqpWs.<anonymous> (C:\\Program Files\iconnect\iconnect-message-handler\node_modules\iconnect-message-handler\node_modules\azure-iothub\lib\amqp.js:57:12)
    at C:\\Program Files\iconnect\iconnect-message-handler\node_modules\iconnect-message-handler\node_modules\azure-iothub\lib\amqp.js:48:9
    at C:\\Program Files\iconnect\iconnect-message-handler\node_modules\iconnect-message-handler\node_modules\azure-iothub\lib\amqp.js:48:9
    at C:\\Program Files\iconnect\iconnect-message-handler\node_modules\iconnect-message-handler\node_modules\azure-iot-amqp-base\lib\amqp.js:83:7
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

I've when digging in the code in the file azure-iot-amqp-base/lib/amqp.js and I see that at some points a handler is a attached to the event client:errorReceived and later presumably it is removed, but the reality is that when the 11th handler is added, Nodejs emits a warning because by default it has 10 max listener per event. It seems that some handlers are not removed.

```
this._amqp.on('client:errorReceived', connectErrorHander);
```

**Comment by pierreca** [comment]
@gagle Looks like this is tied to a section of code that changed significantly in the past 2 versions of the SDK, because we introduced CBS over AMQP which enables renewing the shared access signature without connecting/disconnecting (which we had to using SASL-PLAIN authentication).

So i'm guessing your bug might be gone already. Can you give the latest packages (azure-iothub@1.1.9 and azure-iot-amqp-base@1.1.7 a try and let us know if you still observe the problem?

**Comment by gagle** [comment]
@pierreca After all the night up and running this error has disapeared but now the client that reads from the hub using the client from azure-iot-device@1.1.9 and the Transport from azure-iot-device-mqtt@1.1.9 stopped from receiving new messages.

We have an scenario (that need to be changed but this is what we have currently) where the devices write to the hub using azure-iothub with AmqpWs and read using azure-iot-device with MqttWs.

This time I don't get any error, the client that reads from the hub simply doesn't emit incoming messages. I need to further investigate but this issue can be closed.
