### ISSUE TITLE
Twin is not implemented over HTTP when using 'azure-iot-device-http'@1.7.3 for transport 

### ISSUE THREAD

**Issue by toolboc** [Azure/azure-iot-sdk-node#351]
# Context
- **OS and version used:** 2018-04-18-raspbian-stretch-lite
- **Node.js version:**  8.9.4

# Description of the issue:
Twin is not implemented over HTTP when using 'azure-iot-device-http'@1.7.3 for transport 

# Code sample exhibiting the issue:

    const { Http: Transport } = require('azure-iot-device-http');
    const { ModuleClient, Message } = require('azure-iot-device');

    console.debug('Connecting to IoT Edge...');
    ModuleClient.fromEnvironment(Transport, (err, moduleClient) => {
    if (err) {
      console.error(`IoT Edge Connection error: ${err}`);
      cb(err);
    }
    client = moduleClient;
    console.debug('Fetching device twin...');
        client.getTwin((err, twin) => {
         console.debug('Fetched device twin');
         });
     });

# Console log of the issue:
 
/node_modules/azure-iot-device-http/lib/http.js:497
        throw new azure_iot_common_1.errors.NotImplementedError('Twin is not implemented over HTTP.');
        ^
NotImplementedError: Twin is not implemented over HTTP.
    at Http.getTwin (/node_modules/azure-iot-device-http/lib/http.js:497:15)
    at /node_modules/azure-iot-device/lib/twin.js:67:30
    at retryOperation (/node_modules/azure-iot-common/lib/retry_operation.js:31:13)
    at RetryOperation.retry (/node_modules/azure-iot-common/lib/retry_operation.js:57:9)
    at Twin.get (/node_modules/azure-iot-device/lib/twin.js:65:17)
    at ModuleClient.InternalClient.getTwin (/node_modules/azure-iot-device/lib/internal_client.js:231:20)

**Comment by pierreca** [comment]
That is actually a service limitation (which this error type may not express well) so there's not much the SDK can do here.

**Comment by anthonyvercolano** [comment]
Closing as this is architectural decision on the part of the service.

**Comment by az-iot-builder-01** [comment]
@toolboc, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by tameraw** [comment]
@toolboc - Was there any particular need why you were looking for this functionality over HTTP?
Twin support is available over both MQTT & AMQP and both protocols are supported over Websockets as well, in case the MQTT and AMQP ports are not accessible in your scenario.

**Comment by toolboc** [comment]
@tameraw , I initially looked into using a different transport method to see if it would fix an [issue I had invoking Direct Methods on an ARM device](https://github.com/Azure/iotedge/issues/98#issuecomment-415836594).  The [issue](https://github.com/Azure/iotedge/issues/972) appears to still be outstanding at this time.

Regardless, I am a bit confused why we would offer the option to use HTTP transport if it results in inability to use a core feature of IoT Edge (Device Twin)?
