### ISSUE TITLE
Intermittent Messages Not Sent (No Errors) to IoT Hub

### ISSUE THREAD

**Issue by KernelGamut32** [Azure/azure-iot-sdk-node#353]
# Context
- **OS and version used:** Linux
- **Node.js version:** 6.10.2
- **list of installed packages:**
    "async": "^2.6.0",
    "azure-iot-device": "^1.4.1",
    "azure-iot-device-mqtt": "^1.4.1",
    "azure-iothub": "^1.3.0",
    "body-parser": "^1.17.1",
    "es5-shim": "^4.5.9",
    "eslint": "^4.19.1",
    "express": "^4.15.3",
    "jslinq": "^1.0.21",
    "lodash": "^4.15.0",
    "properties-reader": "^0.0.15"

# Description of the issue:

We have a node connector running on the edge which coordinates communications between on-prem devices and IoT Hub. We are using the NoRetry policy with the connection. Intermittently, after several days of successful communication/interaction with the IoT Hub, messages from our connector will simply stop making it to the IoT Hub. There are no exceptions in the logs (that I can see) to indicate an issue. We have a console.log statement in our code that outputs a "Message Enqueued" result for each successfully transmitted message - seemingly without rhyme or reason (and after seeing those "Message Enqueued" results for several days), they simply stop. The log shows attempts to continue to put the messages on the wire to the Hub but we receive no confirmation back that they were received. Additionally, if you check the edge device in Device Explorer, it shows "Disconnected" but we never receive the "disconnect" event from the Hub.

Appears to resemble issues like https://github.com/Azure/azure-iot-sdk-node/issues/352

**Comment by pierreca** [comment]
Updates to #352 seem to be related to AMQP - this is MQTT.

What i'm not clear about is why the keepalive isn't detecting and triggering a disconnect event if the retry policy is set to `NoRetry()`

@KernelGamut32 I realize we're 6 months late answering this. apologies for that. if that's still an issue would you mind posting the code you're using to set the retry policy, send messages, and subscribe to the disconnect event?

**Comment by jebrando** [comment]
@KernelGamut32 If this is still an issue please reopen this issue with any detail you feel appropriate, or you can open a new one.

Thank you.

**Comment by az-iot-builder-01** [comment]
@KernelGamut32, @jebrando, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
