### ISSUE TITLE
Found a bug: All queries are failing with ArgumentError('\'device\' must have a deviceId property'

### ISSUE THREAD

**Issue by Praveena0989** [Azure/azure-iot-sdk-node#355]
If I do `select *` then it works but if I do `select some_field` then it will fail with ArgumentError('\'device\' must have a deviceId property'. 

Bug I noticed is when I select specific field, then deviceId in the response is coming as `DeviceId` not `deviceId` so this part of code is failing 
                 
     if (!device.deviceId) {
        /*Codes_SRS_NODE_IOTHUB_TWIN_16_007: [The `Twin(device, registryClient)` constructor shall throw an `ArgumentError` if `device` is an object and does not have a `deviceId` property.]*/
        throw new errors.ArgumentError('\'device\' must have a deviceId property');
    }

This is in the file `https://github.com/Azure/azure-iot-sdk-node/blob/master/service/src/twin.ts`

**Comment by anthonyvercolano** [comment]
Would you be able to provide a small sample program that demonstrates the issue?  Please do not include any connection strings.

Thank you.

**Comment by Praveena0989** [comment]
const queryString = "SELECT properties.reported.air_quality_data AS data FROM devices WHERE deviceId='10000001'";
    const query = registry.createQuery(queryString);
    var onResults = function (err, results) {
      if (err) {
        console.error('Failed to fetch the results: ' + err.message);
      } else {
        console.log("success");
      }
    };
    query.nextAsTwin(onResults);`

**Comment by anthonyvercolano** [comment]
Would I be correct in assuming that your twin does NOT actually have the air_quality_data in the reported properties?

**Comment by anthonyvercolano** [comment]
Since you are doing a projection (with the clause in the SELECT), you should utilize query.next().  nextAsTwin assumes that the results of the query are twins.

**Comment by Praveena0989** [comment]
@anthonyvercolano  I do have air_quality_data in reported properties
