### ISSUE TITLE
TLSSocket.onclose Exception

### ISSUE THREAD

**Issue by DanielSaager** [Azure/azure-iot-sdk-node#36]
# Context
Raspi3
- **Node.js version:** 6.10.1 
- **npm version:** 4.4.4 
simulateddevice@1.0.0 /home/pi/node_modules/simulateddevice
├─┬ azure-iot-device@1.1.8
│ ├─┬ azure-iot-common@1.1.6
│ │ └── crypto@0.0.3
│ ├─┬ azure-iot-http-base@1.1.6
│ │ ├── azure-iot-common@1.1.6 deduped
│ │ └── debug@2.6.3 deduped
│ ├─┬ azure-storage@2.1.0
│ │ ├── browserify-mime@1.2.9
│ │ ├── extend@1.2.1
│ │ ├─┬ json-edm-parser@0.1.2
│ │ │ └── jsonparse@1.2.0
│ │ ├─┬ md5.js@1.3.4
│ │ │ ├─┬ hash-base@3.0.3
│ │ │ │ └── inherits@2.0.3 deduped
│ │ │ └── inherits@2.0.3 deduped
│ │ ├── node-uuid@1.4.8
│ │ ├─┬ readable-stream@2.0.6
│ │ │ ├── core-util-is@1.0.2
│ │ │ ├── inherits@2.0.3 deduped
│ │ │ ├── isarray@1.0.0
│ │ │ ├── process-nextick-args@1.0.7
│ │ │ ├── string_decoder@0.10.31
│ │ │ └── util-deprecate@1.0.2
│ │ ├─┬ request@2.74.0
│ │ │ ├── aws-sign2@0.6.0
│ │ │ ├── aws4@1.6.0
│ │ │ ├─┬ bl@1.1.2
│ │ │ │ └── readable-stream@2.0.6 deduped
│ │ │ ├── caseless@0.11.0
│ │ │ ├─┬ combined-stream@1.0.5
│ │ │ │ └── delayed-stream@1.0.0
│ │ │ ├── extend@3.0.0
│ │ │ ├── forever-agent@0.6.1
│ │ │ ├─┬ form-data@1.0.1
│ │ │ │ ├─┬ async@2.2.0
│ │ │ │ │ └── lodash@4.17.4 deduped
│ │ │ │ ├── combined-stream@1.0.5 deduped
│ │ │ │ └── mime-types@2.1.15 deduped
│ │ │ ├─┬ har-validator@2.0.6
│ │ │ │ ├─┬ chalk@1.1.3
│ │ │ │ │ ├── ansi-styles@2.2.1
│ │ │ │ │ ├── escape-string-regexp@1.0.5
│ │ │ │ │ ├─┬ has-ansi@2.0.0
│ │ │ │ │ │ └── ansi-regex@2.1.1
│ │ │ │ │ ├─┬ strip-ansi@3.0.1
│ │ │ │ │ │ └── ansi-regex@2.1.1 deduped
│ │ │ │ │ └── supports-color@2.0.0
│ │ │ │ ├─┬ commander@2.9.0
│ │ │ │ │ └── graceful-readlink@1.0.1
│ │ │ │ ├─┬ is-my-json-valid@2.16.0
│ │ │ │ │ ├── generate-function@2.0.0
│ │ │ │ │ ├─┬ generate-object-property@1.2.0
│ │ │ │ │ │ └── is-property@1.0.2
│ │ │ │ │ ├── jsonpointer@4.0.1
│ │ │ │ │ └── xtend@4.0.1 deduped
│ │ │ │ └─┬ pinkie-promise@2.0.1
│ │ │ │   └── pinkie@2.0.4
│ │ │ ├─┬ hawk@3.1.3
│ │ │ │ ├─┬ boom@2.10.1
│ │ │ │ │ └── hoek@2.16.3 deduped
│ │ │ │ ├─┬ cryptiles@2.0.5
│ │ │ │ │ └── boom@2.10.1 deduped
│ │ │ │ ├── hoek@2.16.3
│ │ │ │ └─┬ sntp@1.0.9
│ │ │ │   └── hoek@2.16.3 deduped
│ │ │ ├─┬ http-signature@1.1.1
│ │ │ │ ├── assert-plus@0.2.0
│ │ │ │ ├─┬ jsprim@1.4.0
│ │ │ │ │ ├── assert-plus@1.0.0
│ │ │ │ │ ├── extsprintf@1.0.2
│ │ │ │ │ ├── json-schema@0.2.3
│ │ │ │ │ └─┬ verror@1.3.6
│ │ │ │ │   └── extsprintf@1.0.2 deduped
│ │ │ │ └─┬ sshpk@1.11.0
│ │ │ │   ├── asn1@0.2.3
│ │ │ │   ├── assert-plus@1.0.0
│ │ │ │   ├─┬ bcrypt-pbkdf@1.0.1
│ │ │ │   │ └── tweetnacl@0.14.5 deduped
│ │ │ │   ├─┬ dashdash@1.14.1
│ │ │ │   │ └── assert-plus@1.0.0
│ │ │ │   ├─┬ ecc-jsbn@0.1.1
│ │ │ │   │ └── jsbn@0.1.1 deduped
│ │ │ │   ├─┬ getpass@0.1.6
│ │ │ │   │ └── assert-plus@1.0.0
│ │ │ │   ├─┬ jodid25519@1.0.2
│ │ │ │   │ └── jsbn@0.1.1 deduped
│ │ │ │   ├── jsbn@0.1.1
│ │ │ │   └── tweetnacl@0.14.5
│ │ │ ├── is-typedarray@1.0.0
│ │ │ ├── isstream@0.1.2
│ │ │ ├── json-stringify-safe@5.0.1
│ │ │ ├─┬ mime-types@2.1.15
│ │ │ │ └── mime-db@1.27.0
│ │ │ ├── node-uuid@1.4.8 deduped
│ │ │ ├── oauth-sign@0.8.2
│ │ │ ├── qs@6.2.3
│ │ │ ├── stringstream@0.0.5
│ │ │ ├─┬ tough-cookie@2.3.2
│ │ │ │ └── punycode@1.4.1
│ │ │ └── tunnel-agent@0.4.3
│ │ ├── underscore@1.4.4
│ │ ├── validator@3.22.2
│ │ ├─┬ xml2js@0.2.7
│ │ │ └── sax@0.5.2
│ │ └── xmlbuilder@0.4.3
│ ├─┬ debug@2.6.3
│ │ └── ms@0.7.2
│ ├── es5-shim@4.5.9
│ ├── lodash@4.17.4
│ ├─┬ machina@2.0.0
│ │ └── lodash@3.10.1
│ └── traverse@0.6.6
└─┬ azure-iot-device-mqtt@1.1.8
  ├── azure-iot-common@1.1.6 deduped
  ├── azure-iot-device@1.1.8 deduped
  ├── debug@2.6.3 deduped
  ├── es5-shim@4.5.9 deduped
  └─┬ mqtt@1.14.1
    ├─┬ commist@1.0.0
    │ ├── leven@1.0.2
    │ └── minimist@1.2.0 deduped
    ├─┬ concat-stream@1.6.0
    │ ├── inherits@2.0.3 deduped
    │ ├─┬ readable-stream@2.2.6
    │ │ ├── buffer-shims@1.0.0
    │ │ ├── core-util-is@1.0.2 deduped
    │ │ ├── inherits@2.0.3 deduped
    │ │ ├── isarray@1.0.0 deduped
    │ │ ├── process-nextick-args@1.0.7 deduped
    │ │ ├── string_decoder@0.10.31 deduped
    │ │ └── util-deprecate@1.0.2 deduped
    │ └── typedarray@0.0.6
    ├─┬ end-of-stream@1.4.0
    │ └─┬ once@1.4.0
    │   └── wrappy@1.0.2
    ├─┬ help-me@1.0.1
    │ ├─┬ callback-stream@1.1.0
    │ │ ├── inherits@2.0.3 deduped
    │ │ └── readable-stream@2.0.6 deduped
    │ ├─┬ glob-stream@5.3.5
    │ │ ├── extend@3.0.0
    │ │ ├─┬ glob@5.0.15
    │ │ │ ├─┬ inflight@1.0.6
    │ │ │ │ ├── once@1.4.0 deduped
    │ │ │ │ └── wrappy@1.0.2 deduped
    │ │ │ ├── inherits@2.0.3 deduped
    │ │ │ ├─┬ minimatch@3.0.3
    │ │ │ │ └─┬ brace-expansion@1.1.6
    │ │ │ │   ├── balanced-match@0.4.2
    │ │ │ │   └── concat-map@0.0.1
    │ │ │ ├── once@1.4.0 deduped
    │ │ │ └── path-is-absolute@1.0.1
    │ │ ├─┬ glob-parent@3.1.0
    │ │ │ ├─┬ is-glob@3.1.0
    │ │ │ │ └── is-extglob@2.1.1
    │ │ │ └── path-dirname@1.0.2
    │ │ ├─┬ micromatch@2.3.11
    │ │ │ ├─┬ arr-diff@2.0.0
    │ │ │ │ └── arr-flatten@1.0.1
    │ │ │ ├── array-unique@0.2.1
    │ │ │ ├─┬ braces@1.8.5
    │ │ │ │ ├─┬ expand-range@1.8.2
    │ │ │ │ │ └─┬ fill-range@2.2.3
    │ │ │ │ │   ├─┬ is-number@2.1.0
    │ │ │ │ │   │ └── kind-of@3.1.0 deduped
    │ │ │ │ │   ├─┬ isobject@2.1.0
    │ │ │ │ │   │ └── isarray@1.0.0 deduped
    │ │ │ │ │   ├─┬ randomatic@1.1.6
    │ │ │ │ │   │ ├── is-number@2.1.0 deduped
    │ │ │ │ │   │ └── kind-of@3.1.0 deduped
    │ │ │ │ │   ├── repeat-element@1.1.2 deduped
    │ │ │ │ │   └── repeat-string@1.6.1
    │ │ │ │ ├── preserve@0.2.0
    │ │ │ │ └── repeat-element@1.1.2
    │ │ │ ├─┬ expand-brackets@0.1.5
    │ │ │ │ └── is-posix-bracket@0.1.1
    │ │ │ ├─┬ extglob@0.3.2
    │ │ │ │ └── is-extglob@1.0.0
    │ │ │ ├── filename-regex@2.0.0
    │ │ │ ├── is-extglob@1.0.0
    │ │ │ ├─┬ is-glob@2.0.1
    │ │ │ │ └── is-extglob@1.0.0 deduped
    │ │ │ ├─┬ kind-of@3.1.0
    │ │ │ │ └── is-buffer@1.1.5
    │ │ │ ├── normalize-path@2.0.1
    │ │ │ ├─┬ object.omit@2.0.1
    │ │ │ │ ├─┬ for-own@0.1.5
    │ │ │ │ │ └── for-in@1.0.2
    │ │ │ │ └── is-extendable@0.1.1
    │ │ │ ├─┬ parse-glob@3.0.4
    │ │ │ │ ├─┬ glob-base@0.3.0
    │ │ │ │ │ ├─┬ glob-parent@2.0.0
    │ │ │ │ │ │ └── is-glob@2.0.1 deduped
    │ │ │ │ │ └─┬ is-glob@2.0.1
    │ │ │ │ │   └── is-extglob@1.0.0
    │ │ │ │ ├── is-dotfile@1.0.2
    │ │ │ │ ├── is-extglob@1.0.0
    │ │ │ │ └─┬ is-glob@2.0.1
    │ │ │ │   └── is-extglob@1.0.0 deduped
    │ │ │ └─┬ regex-cache@0.4.3
    │ │ │   ├─┬ is-equal-shallow@0.1.3
    │ │ │   │ └── is-primitive@2.0.0 deduped
    │ │ │   └── is-primitive@2.0.0
    │ │ ├─┬ ordered-read-streams@0.3.0
    │ │ │ ├── is-stream@1.1.0
    │ │ │ └── readable-stream@2.0.6 deduped
    │ │ ├─┬ through2@0.6.5
    │ │ │ ├─┬ readable-stream@1.0.34
    │ │ │ │ ├── core-util-is@1.0.2 deduped
    │ │ │ │ ├── inherits@2.0.3 deduped
    │ │ │ │ ├── isarray@0.0.1
    │ │ │ │ └── string_decoder@0.10.31 deduped
    │ │ │ └── xtend@4.0.1 deduped
    │ │ ├─┬ to-absolute-glob@0.1.1
    │ │ │ └─┬ extend-shallow@2.0.1
    │ │ │   └── is-extendable@0.1.1 deduped
    │ │ └─┬ unique-stream@2.2.1
    │ │   ├─┬ json-stable-stringify@1.0.1
    │ │   │ └── jsonify@0.0.0
    │ │   └─┬ through2-filter@2.0.0
    │ │     ├── through2@2.0.3 deduped
    │ │     └── xtend@4.0.1 deduped
    │ ├─┬ through2@2.0.3
    │ │ ├─┬ readable-stream@2.2.6
    │ │ │ ├── buffer-shims@1.0.0 deduped
    │ │ │ ├── core-util-is@1.0.2 deduped
    │ │ │ ├── inherits@2.0.3 deduped
    │ │ │ ├── isarray@1.0.0 deduped
    │ │ │ ├── process-nextick-args@1.0.7 deduped
    │ │ │ ├── string_decoder@0.10.31 deduped
    │ │ │ └── util-deprecate@1.0.2 deduped
    │ │ └── xtend@4.0.1 deduped
    │ └── xtend@4.0.1 deduped
    ├── inherits@2.0.3
    ├── minimist@1.2.0
    ├─┬ mqtt-connection@2.1.1
    │ ├── inherits@2.0.3 deduped
    │ ├── mqtt-packet@3.4.8 deduped
    │ ├─┬ reduplexer@1.1.0
    │ │ ├── inherits@2.0.3 deduped
    │ │ └─┬ readable-stream@1.0.34
    │ │   ├── core-util-is@1.0.2 deduped
    │ │   ├── inherits@2.0.3 deduped
    │ │   ├── isarray@0.0.1
    │ │   └── string_decoder@0.10.31 deduped
    │ └─┬ through2@0.6.5
    │   ├─┬ readable-stream@1.0.34
    │   │ ├── core-util-is@1.0.2 deduped
    │   │ ├── inherits@2.0.3 deduped
    │   │ ├── isarray@0.0.1
    │   │ └── string_decoder@0.10.31 deduped
    │   └── xtend@4.0.1 deduped
    ├─┬ mqtt-packet@3.4.8
    │ ├─┬ bl@0.9.5
    │ │ └─┬ readable-stream@1.0.34
    │ │   ├── core-util-is@1.0.2 deduped
    │ │   ├── inherits@2.0.3 deduped
    │ │   ├── isarray@0.0.1
    │ │   └── string_decoder@0.10.31 deduped
    │ └── inherits@2.0.3 deduped
    ├─┬ pump@1.0.2
    │ ├── end-of-stream@1.4.0 deduped
    │ └── once@1.4.0 deduped
    ├─┬ readable-stream@1.0.34
    │ ├── core-util-is@1.0.2 deduped
    │ ├── inherits@2.0.3 deduped
    │ ├── isarray@0.0.1
    │ └── string_decoder@0.10.31 deduped
    ├── reinterval@1.1.0
    ├─┬ split2@2.1.1
    │ └── through2@2.0.3 deduped
    ├─┬ websocket-stream@3.3.3
    │ ├─┬ duplexify@3.5.0
    │ │ ├─┬ end-of-stream@1.0.0
    │ │ │ └─┬ once@1.3.3
    │ │ │   └── wrappy@1.0.2 deduped
    │ │ ├── inherits@2.0.3 deduped
    │ │ ├── readable-stream@2.0.6 deduped
    │ │ └── stream-shift@1.0.0
    │ ├── inherits@2.0.3 deduped
    │ ├── through2@2.0.3 deduped
    │ ├─┬ ws@1.1.4
    │ │ ├── options@0.0.6
    │ │ └── ultron@1.0.2
    │ └── xtend@4.0.1 deduped
    └── xtend@4.0.1

# Description of the issue:
After four days of test this error occur

# Console log of the issue:
events.js:160
throw er; // Unhandled 'error' events

Error: premature close

at TLSSocket.onclose (/home/pi/node_modules/simulateddevice/node_modules/end-of.stream/index.js:43:67)
at emit0ne (events.js:101:20)
at TLSSocket.emit (events.js:188:7)
at _handle.close (net.js:501:12)
at TCP.done [as _onclose] (_tls_wrap.js:332:7)

**Comment by pierreca** [comment]
I've made some changes to the keep-alive configuration of the client recently, it hasn't been released as a package yet but will be by the end of the week. I'd be curious to hear if this problem reproduces with the code currently in the `master` branch.

Also, it'd help us to know what is happening with the client: what you are sending, receiving, etc. it might pinpoint to a race condition or something.

**Comment by pierreca** [comment]
Also curious to how it might be related to #27. ping @anthonyvercolano.

**Comment by DanielSaager** [comment]
A DHT22 sensor is connected with the raspi. DeviceId, temperature, humidity and the timestamp of measurement is send. 

I'll update the code...

**Comment by pierreca** [comment]
How often do you send this data? is it more frequently than every 4 minutes?

**Comment by DanielSaager** [comment]
every 15 seconds

**Comment by DanielSaager** [comment]
Yesterday following error occured

Sending message: {"Timestamp":"2017-04-24T01:04:18.434Z","ComponentId":"at5","Measure":"F_ist","Value":"95.40"}
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND atiothub2.azure-devices.net atiothub2.azure-devices.net:8883
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

**Comment by DanielSaager** [comment]
I've updated the code via
npm install -g azure-iothub

is this what you mean or

npm install -g azure-iothub@latest?

**Comment by pierreca** [comment]
Thanks for providing more details, that helps! 
the `ENOTFOUND` error is a name-resolution error, meaning it's highly likely that the internet connection dropped. In that case it's not even a connection problem with IoT Hub, it's the whole thing. I'm guessing the TLS error might also be related to network issues since it comes from lower in the network stack (in other words, it's the node socket that is failing, we're merely bubbling up the error)

Resisting such failures and building a retry logic that works across the 3 protocols we support is our highest priority right now, but until the only thing I can suggest is to code defensively against network failures (meaning don't fail, just maintain a queue of messages until the connection comes back).

**Comment by DanielSaager** [comment]
Is there a timeline for implementing the retry logic?

**Comment by pierreca** [comment]
working on it right now - it requires refactoring significant parts of the transport layers. basic scenarios will be covered first and I hope to have that done by the end of next week, proving the architectural concepts we're using. porting this over to MQTT should be quicker and come in the following month.

**Comment by martinadolfi** [comment]
Hi, I think that we´re talking about 2 different things here:
One is this error:
```
events.js:160
throw er; // Unhandled 'error' events

Error: premature close

at TLSSocket.onclose (/home/pi/node_modules/simulateddevice/node_modules/end-of.stream/index.js:43:67)
at emit0ne (events.js:101:20)
at TLSSocket.emit (events.js:188:7)
at _handle.close (net.js:501:12)
at TCP.done [as _onclose] (_tls_wrap.js:332:7)
```
The other one is about name resolution. 
I think that although a retry logic would be a usefull workarround probably for both, we're not getting to know the root cause of the first issue. (the second one is very clear to me).
I'm getting that same error, and I'll try to hande it on the code, but still it'll be great to know the root cause.
Regards!

**Comment by DanielSaager** [comment]
Hi Martin,which kind of error handling do you use? Right now I use callbacks and the error handling from the sdk samples like this https://github.com/Azure/azure-iot-sdk-node/blob/master/device/samples/simple_sample_device.js

What do you think about promise instead of callbacks?

reg

Daniel

**Comment by martinadolfi** [comment]
Hi @DanielSaager , I'm using the same sample. 
About the error, I'm pretty confident that it arises in this function:
```javascript
client.sendEvent(message, printResultFor('send'));
```
But apparently we don't have any error handling that sends the error to the callback function, and I think that's why it crashed before.

I'm not sure about this, I'm just digging into the code right now, but I think its somewhere  inside that function.

About a promise instead of callbacks, I don't really have that much experience with promises, so I can't give you any useful opinion. Perhaps @pierreca can help us figure out that.

Regads!.

M.

**Comment by DanielSaager** [comment]
Hi,
Is the implementing of the retry logic finished? I saw only AMQP improvements in the release history?

thx

**Comment by pierreca** [comment]
@DanielSaager @martinadolfi 
Retry logic has shipped for the device SDK with azure-iot-device@1.2.0 and transport versions > 1.2.1. 

@martinadolfi we're now tracking the "premature close" error on #73. 
@DanielSaager Looks like you're using the service SDK (`azure-iothub` package). Retry logic hasn't shipped yet but the basics are already there in #127 if you want to check it out.

Because these 2 items are tracked in separate issues, I'm closing this one down now.
