### ISSUE TITLE
Amqp client has a different behaviour in docker for windows and in docker for ubuntu

### ISSUE THREAD

**Issue by sNAtttu** [Azure/azure-iot-sdk-node#361]
# Context
- **OS and version used:** 
Windows 10 and Ubuntu 16.04
- **Node.js version:**  9.11.1 
- **npm version:** 5.8.0
- **list of installed packages:**
+-- azure-iot-device@1.7.3
| +-- azure-iot-common@1.7.3
| | `-- getos@3.1.0
| |   `-- async@2.4.0
| |     `-- lodash@4.17.10 deduped
| +-- azure-iot-http-base@1.7.3
| | +-- azure-iot-common@1.7.3 deduped
| | +-- debug@3.1.0 deduped
| | `-- uuid@3.3.2 deduped
| +-- azure-storage@2.10.1
| | +-- browserify-mime@1.2.9
| | +-- extend@1.2.1
| | +-- json-edm-parser@0.1.2
| | | `-- jsonparse@1.2.0
| | +-- md5.js@1.3.4
| | | +-- hash-base@3.0.4
| | | | +-- inherits@2.0.3 deduped
| | | | `-- safe-buffer@5.1.2 deduped
| | | `-- inherits@2.0.3
| | +-- readable-stream@2.0.6
| | | +-- core-util-is@1.0.2
| | | +-- inherits@2.0.3 deduped
| | | +-- isarray@1.0.0
| | | +-- process-nextick-args@1.0.7
| | | +-- string_decoder@0.10.31
| | | `-- util-deprecate@1.0.2
| | +-- request@2.88.0
| | | +-- aws-sign2@0.7.0
| | | +-- aws4@1.8.0
| | | +-- caseless@0.12.0
| | | +-- combined-stream@1.0.6
| | | | `-- delayed-stream@1.0.0
| | | +-- extend@3.0.2
| | | +-- forever-agent@0.6.1
| | | +-- form-data@2.3.2
| | | | +-- asynckit@0.4.0
| | | | +-- combined-stream@1.0.6 deduped
| | | | `-- mime-types@2.1.20 deduped
| | | +-- har-validator@5.1.0
| | | | +-- ajv@5.5.2
| | | | | +-- co@4.6.0
| | | | | +-- fast-deep-equal@1.1.0
| | | | | +-- fast-json-stable-stringify@2.0.0
| | | | | `-- json-schema-traverse@0.3.1
| | | | `-- har-schema@2.0.0
| | | +-- http-signature@1.2.0
| | | | +-- assert-plus@1.0.0
| | | | +-- jsprim@1.4.1
| | | | | +-- assert-plus@1.0.0 deduped
| | | | | +-- extsprintf@1.3.0
| | | | | +-- json-schema@0.2.3
| | | | | `-- verror@1.10.0
| | | | |   +-- assert-plus@1.0.0 deduped
| | | | |   +-- core-util-is@1.0.2 deduped
| | | | |   `-- extsprintf@1.4.0
| | | | `-- sshpk@1.14.2
| | | |   +-- asn1@0.2.4
| | | |   | `-- safer-buffer@2.1.2 deduped
| | | |   +-- assert-plus@1.0.0 deduped
| | | |   +-- bcrypt-pbkdf@1.0.2
| | | |   | `-- tweetnacl@0.14.5 deduped
| | | |   +-- dashdash@1.14.1
| | | |   | `-- assert-plus@1.0.0 deduped
| | | |   +-- ecc-jsbn@0.1.2
| | | |   | +-- jsbn@0.1.1 deduped
| | | |   | `-- safer-buffer@2.1.2 deduped
| | | |   +-- getpass@0.1.7
| | | |   | `-- assert-plus@1.0.0 deduped
| | | |   +-- jsbn@0.1.1
| | | |   +-- safer-buffer@2.1.2
| | | |   `-- tweetnacl@0.14.5
| | | +-- is-typedarray@1.0.0
| | | +-- isstream@0.1.2
| | | +-- json-stringify-safe@5.0.1
| | | +-- mime-types@2.1.20
| | | | `-- mime-db@1.36.0
| | | +-- oauth-sign@0.9.0
| | | +-- performance-now@2.1.0
| | | +-- qs@6.5.2
| | | +-- safe-buffer@5.1.2
| | | +-- tough-cookie@2.4.3
| | | | +-- psl@1.1.29
| | | | `-- punycode@1.4.1
| | | +-- tunnel-agent@0.6.0
| | | | `-- safe-buffer@5.1.2 deduped
| | | `-- uuid@3.3.2 deduped
| | +-- underscore@1.8.3
| | +-- uuid@3.3.2 deduped
| | +-- validator@9.4.1
| | +-- xml2js@0.2.8
| | | `-- sax@0.5.8
| | `-- xmlbuilder@0.4.3
| +-- debug@3.1.0
| | `-- ms@2.0.0
| +-- lodash@4.17.10
| +-- machina@2.0.2
| | `-- lodash@3.10.1
| `-- traverse@0.6.6
`-- azure-iot-device-amqp@1.7.3
  +-- async@2.6.1
  | `-- lodash@4.17.10 deduped
  +-- azure-iot-amqp-base@1.7.3
  | +-- amqp10@3.6.0
  | | +-- bl@1.2.2
  | | | +-- readable-stream@2.3.6
  | | | | +-- core-util-is@1.0.2 deduped
  | | | | +-- inherits@2.0.3 deduped
  | | | | +-- isarray@1.0.0 deduped
  | | | | +-- process-nextick-args@2.0.0
  | | | | +-- safe-buffer@5.1.2 deduped
  | | | | +-- string_decoder@1.1.1
  | | | | | `-- safe-buffer@5.1.2 deduped
  | | | | `-- util-deprecate@1.0.2 deduped
  | | | `-- safe-buffer@5.1.2 deduped
  | | +-- bluebird@3.5.2 deduped
  | | +-- buffer-builder@0.2.0
  | | +-- debug@2.6.9
  | | | `-- ms@2.0.0 deduped
  | | +-- lodash@4.17.10 deduped
  | | +-- node-int64@0.4.0
  | | `-- stately.js@1.3.0
  | +-- amqp10-transport-ws@0.0.5
  | | `-- nodejs-websocket@1.7.1
  | +-- async@2.6.1 deduped
  | +-- azure-iot-common@1.7.3 deduped
  | +-- bluebird@3.5.2
  | +-- debug@3.1.0 deduped
  | +-- lodash.merge@4.6.1
  | +-- machina@2.0.2 deduped
  | `-- uuid@3.3.2 deduped
  +-- azure-iot-common@1.7.3 deduped
  +-- azure-iot-device@1.7.3 deduped
  +-- debug@3.1.0 deduped
  +-- machina@2.0.2 deduped
  `-- uuid@3.3.2
- **cloned repo:**
This is the simulated device file from the example repository with dockerfile.
https://github.com/sNAtttu/SimulatedAmqpDevice.git

# Description of the issue:
I'm testing the offline capabilities of the client and the ampq transport using the "SimulatedDevice" example from the https://github.com/Azure-Samples/azure-iot-samples-node

I have the simulated device running on a docker container which uses mhart/alpine-node:9 image and the issue is that on Docker for Windows when I unplug the network cable the simulated device crashes instantly and throws the following error
```
/app/node_modules/amqp10/lib/frames.js:64
  stream.write(buffer, callback);
         ^

TypeError: Cannot read property 'write' of null
    at Object.frames.writeFrame (/app/node_modules/amqp10/lib/frames.js:64:10)
    at Connection.sendFrame (/app/node_modules/amqp10/lib/connection.js:329:10)
    at ReceiverLink.Link._sendDetach (/app/node_modules/amqp10/lib/link.js:228:27)
    at Object.sendDetach (/app/node_modules/amqp10/lib/link.js:34:14)
    at Object.event [as sendDetach] (/app/node_modules/stately.js/Stately.js:203:67)
    at ReceiverLink.Link.detach (/app/node_modules/amqp10/lib/link.js:129:11)
    at constructor._onEnter (/app/node_modules/azure-iot-amqp-base/lib/receiver_link.js:155:47)
    at constructor.transition (/app/node_modules/machina/lib/machina.js:653:28)
    at constructor.Fsm.(anonymous function) [as transition] (/app/node_modules/machina/lib/machina.js:466:63)
    at constructor.detach (/app/node_modules/azure-iot-amqp-base/lib/receiver_link.js:124:69)
    at constructor.handle (/app/node_modules/machina/lib/machina.js:613:25)
    at constructor.Fsm.(anonymous function) [as handle] (/app/node_modules/machina/lib/machina.js:466:63)
    at ReceiverLink.detach (/app/node_modules/azure-iot-amqp-base/lib/receiver_link.js:185:19)
    at /app/node_modules/azure-iot-amqp-base/lib/amqp_cbs.js:241:38
    at /app/node_modules/async/dist/async.js:3110:16
    at eachOfArrayLike (/app/node_modules/async/dist/async.js:1069:9)
```
However when I'm running the docker on Ubuntu 16.04 and unplug the network cable the simulated device does not crash instantly. It keeps creating and sending the telemetry, but doesn't seem to get anything back since it doesn't log "message sent" nor "send error" to the console.

After a while (~5min to ~20min) the client crashes to the same error as above.

# Code sample exhibiting the issue:
// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

'use strict';

// The device connection string to authenticate the device with your IoT hub.
//
// NOTE:
// For simplicity, this sample sets the connection string in code.
// In a production environment, the recommended approach is to use
// an environment variable to make it available to your application
// or use an HSM or an x509 certificate.
// https://docs.microsoft.com/azure/iot-hub/iot-hub-devguide-security
//
// Using the Azure CLI:
// az iot hub device-identity show-connection-string --hub-name {YourIoTHubName} --device-id MyNodeDevice --output table
var connectionString = '';

// Using the Node.js Device SDK for IoT Hub:
//   https://github.com/Azure/azure-iot-sdk-node
// The sample connects to a device-specific MQTT endpoint on your IoT Hub.
const { Amqp } = require('azure-iot-device-amqp');
var DeviceClient = require('azure-iot-device').Client
var Message = require('azure-iot-device').Message;

var client = DeviceClient.fromConnectionString(connectionString, Amqp);

// Create a message and send it to the IoT hub every second
setInterval(function(){
  // Simulate telemetry.
  var temperature = 20 + (Math.random() * 15);
  var message = new Message(JSON.stringify({
    temperature: temperature,
    timeStamp: new Date().toISOString(),
    humidity: 60 + (Math.random() * 20)
  }));

  // Add a custom application property to the message.
  // An IoT hub can filter on these properties without access to the message body.
  message.properties.add('temperatureAlert', (temperature > 30) ? 'true' : 'false');

  console.log('Sending message: ' + message.getData());
  // Send the message.
  client.sendEvent(message, function (err) {
    if (err) {
      console.error('send error: ' + err.toString());
    } else {
      console.log('message sent');
    }
  });
}, 1000);

**Comment by anthonyvercolano** [comment]
Thank you for the excellent bug report.  We will be investigating this shortly.  With the sdk switching to a new underlying AMQP transport, this may or may not have already been fixed.  We'll try to let you know what we find later this week or the beginning of next.

Again, thank you for the report.

**Comment by anthonyvercolano** [comment]
A comment on the different behavior between the OS.

It is a basic problem out of the SDK's control as to how long it will take to notice a cable being pulled.  Our C SDK team has waged a long battle with this particular issue.  On Ubuntu, one simply will not get a quick notification.  I've been told that one can Bing (or Google if you must) this issue and find much gnashing of teeth, always ending up with bearded Linux sages saying, no, this will not be fixed.

As for the eventual throw, within a day or two we will be releasing a new SDK that might address this in a cleaner manner.  I will get back to you on this.

**Comment by sNAtttu** [comment]
Hi!

Thanks for the information, I'll be testing these scenarios with the new SDK and after that think of an implementation which handles the different operating systems. 

If it's needed, I promise to use **Bing** in my quest for finding these bearded Linux sages for more wisdom 👍

**Comment by anthonyvercolano** [comment]
Closing as inactive.  Feel free to re-open if circumstances warrant.

**Comment by az-iot-builder-01** [comment]
@sNAtttu, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
