### ISSUE TITLE
Add support for Promise and callback to all the iot node sdks

### ISSUE THREAD

**Issue by amarzavery** [Azure/azure-iot-sdk-node#362]
The 4 packages with public APIs that would need to be promisified are:
azure-iot-device
azure-iothub
azure-iot-provisioning-device
azure-iot-provisioning-service
 
Docs for these are here:
https://docs.microsoft.com/en-us/javascript/api/azure-iot-device/?view=azure-node-latest
https://docs.microsoft.com/en-us/javascript/api/azure-iothub/?view=azure-node-latest
https://docs.microsoft.com/en-us/javascript/api/azure-iot-provisioning-device/?view=azure-node-latest
https://docs.microsoft.com/en-us/javascript/api/azure-iot-provisioning-service/?view=azure-node-latest
 
and the repo is here:
https://github.com/azure/azure-iot-sdk-node
with contributor instructions here:
https://github.com/Azure/azure-iot-sdk-node/blob/master/doc/node-devbox-setup.md
CI is here:
http://azure-iot-gate.westus.cloudapp.azure.com:8080/job/integrate-into-repo-node/

@kpajdzik - Will be working on this.
/cc @salameer, @pierreca

**Comment by pierreca** [comment]
`azure-iot-device` and `azure-iot-provisioning-device` should be your first targets. 

If you want to tackle service SDKs later, why not, but since we have plan to start using autorest to create those, this might be short-lived work so I'm not sure you'd want to spend your time on this.
Thanks for your help!

**Comment by anthonyvercolano** [comment]
Merged.

**Comment by az-iot-builder-01** [comment]
@amarzavery, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
