### ISSUE TITLE
Security vulnerability in lodash 3.x dependency in machina 2.0.x

### ISSUE THREAD

**Issue by bompi88** [Azure/azure-iot-sdk-node#377]
# Context
- **OS and version used:** `OSX 10.13.6`
- **Node.js version:** `8.11.4`
- **npm version:** `6.4.1`
- **list of installed packages:**
```
├─ azure-event-hubs@0.2.3
│  ├─ ms-rest-azure@^2.5.5
├─ azure-iot-amqp-base@2.0.0
│  ├─ azure-iot-common@1.7.4
├─ azure-iot-common@1.7.4
├─ azure-iot-device-mqtt@1.7.4
│  ├─ azure-iot-common@1.7.4
│  ├─ azure-iot-device@1.7.4
│  ├─ azure-iot-mqtt-base@1.7.4
├─ azure-iot-device@1.7.4
│  ├─ azure-iot-common@1.7.4
│  ├─ azure-iot-http-base@1.7.4
│  ├─ azure-storage@^2.8.1
├─ azure-iot-http-base@1.7.4
│  ├─ azure-iot-common@1.7.4
├─ azure-iot-mqtt-base@1.7.4
│  ├─ azure-iot-common@1.7.4
├─ azure-iothub@1.7.4
│  ├─ azure-iot-amqp-base@2.0.0
│  ├─ azure-iot-common@1.7.4
│  ├─ azure-iot-http-base@1.7.4
├─ azure-storage@2.10.1
├─ ms-rest-azure@2.5.7
```

# Description of the issue:
Running `npm audit` reports security vulnerability `Prototype Pollution` (rated as low) for the following packages:
- `azure-iot-amqp-base@2.0.0`
- `azure-iot-device-mqtt@1.7.4`
- `azure-iot-device@1.7.4`
- `azure-iot-mqtt-base@1.7.4`
- `azure-iothub@1.7.4`

This is caused by `machina` still using `lodash@3.x`. PR for updating `lodash` in `machina` is located [here](https://github.com/ifandelse/machina.js/pull/159).

![vulnerabilities](https://user-images.githubusercontent.com/3270628/46002118-720b0480-c0ad-11e8-8ec4-3984fbc007cc.png)

**Comment by anthonyvercolano** [comment]
Love the package.  We gave +2 on the pull request.  Let's see if the pull request gets some love.

**Comment by az-iot-builder-01** [comment]
@bompi88, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by StefanSchoof** [comment]
The Pull Request is open nearly 3 months without any reaction from a maintainer. The first reported [issue](https://github.com/ifandelse/machina.js/issues/157) is a half year old. I think you have to consider this package without maintenance and consider what to do.

**Comment by anthonyvercolano** [comment]
We are in a bit of a difficult place here.  Would you have suggested making a fork and apply the fix to the fork?  We are quite hesitant to do that.

**Comment by StefanSchoof** [comment]
I don't know what can be done. This is something I fear about in projects, building on some projects that get problems the maintainer does not longer react. The owners profile page says he is working still on GitHub, but in private repros.

**Comment by pierreca** [comment]
@StefanSchoof we're reaching out as best we can to the maintainer (over github and twitter, trying to not be intrusive though) as well as offering to help with maintaining Machina for now.

Basically we are always mindful of how it would be interepreted if we started incorporating the code or shipping a forked version of the project itself (Microsoft has not always been the best OSS citizen to say the least, so we're extra careful/respectful of the current maintainers' choices there) and migrating the SDK to a whole different state machine framework might be time consuming and potential for new bugs. 

it's definitely on our mind though, it's not like we're sleeping on it - if you have suggestions, we'll gladly study them :)

**Comment by StefanSchoof** [comment]
Thanks to give this insight. The sound like a balanced way. I just wanted to point out, that after waiting this time, it is a surprise if the problem goes away with more waiting.

For this matter I just got the mail, that the PR has been merged. Thanks.
