### ISSUE TITLE
Invalid Link to to get started

### ISSUE THREAD

**Issue by nikolenkoanton92** [Azure/azure-iot-sdk-node#4]
Hello,

Invalid url in documentation to  [Get started with device management](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-device-management-get-started)

Link to file: https://github.com/Azure/azure-iot-sdk-node/blob/master/doc/dmpatterns.md

**Comment by olivierbloch** [comment]
Thanks for the heads up.
I just fixed the bad links
