### ISSUE TITLE
in onDeviceMethod Callback the response is optional in 1.8.0

### ISSUE THREAD

**Issue by StefanSchoof** [Azure/azure-iot-sdk-node#404]
# Context
- **OS and version used:** Windows 10
- **Node.js version:** v.8.12.0
- **npm version:** 6.4..1
- **list of installed packages:** N/A
- **cloned repo:** N/A

# Description of the issue:
With the commit https://github.com/Azure/azure-iot-sdk-node/commit/2f07d4310ecfef96b31d3afd03ee9af4dd5212a2#diff-bfccd398cff869e5ab197f4c0db693bdR115 the Callback in the typescript signature `onDeviceMethod` the response is possible `undefined`. (Come from this line https://github.com/Azure/azure-iot-sdk-node/commit/2f07d4310ecfef96b31d3afd03ee9af4dd5212a2#diff-263a3620471f111424b917841d4ffd61R13) In no example I have seen that a check for undefined is done. Is this an unintended change of signature?

# Code sample exhibiting the issue:

```
    deviceClient.onDeviceMethod('something', (request, response) => {
        response.send(200, 'ok');
    });
```

results in a `Object is possibly 'undefined'` error.

# Console log of the issue:

**Comment by anthonyvercolano** [comment]
Fixed by pull request 412.

**Comment by az-iot-builder-01** [comment]
@StefanSchoof, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
