### ISSUE TITLE
can't receive cloud to device message (client.on) when client.onDeviceMethod is defined

### ISSUE THREAD

**Issue by michaelheyd** [Azure/azure-iot-sdk-node#41]
# Context
- **OS and version used:** Win10
- **Node.js version:** v6.10.3
- **npm version:** 3.10.10
- **list of installed packages:** 
+-- azure-iot-device@1.1.11
| +-- azure-iot-common@1.1.7
| | `-- crypto@0.0.3
| +-- azure-iot-http-base@1.1.7
| +-- azure-storage@2.1.0
| | +-- browserify-mime@1.2.9
| | +-- extend@1.2.1
| | +-- json-edm-parser@0.1.2
| | | `-- jsonparse@1.2.0
| | +-- md5.js@1.3.4
| | | `-- hash-base@3.0.3
| | +-- node-uuid@1.4.8
| | +-- readable-stream@2.0.6
| | | +-- core-util-is@1.0.2
| | | +-- isarray@1.0.0
| | | +-- process-nextick-args@1.0.7
| | | +-- string_decoder@0.10.31
| | | `-- util-deprecate@1.0.2
| | +-- request@2.74.0
| | | +-- aws-sign2@0.6.0
| | | +-- aws4@1.6.0
| | | +-- bl@1.1.2
| | | +-- caseless@0.11.0
| | | +-- combined-stream@1.0.5
| | | | `-- delayed-stream@1.0.0
| | | +-- extend@3.0.1
| | | +-- forever-agent@0.6.1
| | | +-- form-data@1.0.1
| | | | `-- async@2.4.0
| | | +-- har-validator@2.0.6
| | | | +-- chalk@1.1.3
| | | | | +-- ansi-styles@2.2.1
| | | | | +-- escape-string-regexp@1.0.5
| | | | | +-- has-ansi@2.0.0
| | | | | | `-- ansi-regex@2.1.1
| | | | | +-- strip-ansi@3.0.1
| | | | | `-- supports-color@2.0.0
| | | | +-- commander@2.9.0
| | | | | `-- graceful-readlink@1.0.1
| | | | +-- is-my-json-valid@2.16.0
| | | | | +-- generate-function@2.0.0
| | | | | +-- generate-object-property@1.2.0
| | | | | | `-- is-property@1.0.2
| | | | | `-- jsonpointer@4.0.1
| | | | `-- pinkie-promise@2.0.1
| | | |   `-- pinkie@2.0.4
| | | +-- hawk@3.1.3
| | | | +-- boom@2.10.1
| | | | +-- cryptiles@2.0.5
| | | | +-- hoek@2.16.3
| | | | `-- sntp@1.0.9
| | | +-- http-signature@1.1.1
| | | | +-- assert-plus@0.2.0
| | | | +-- jsprim@1.4.0
| | | | | +-- assert-plus@1.0.0
| | | | | +-- extsprintf@1.0.2
| | | | | +-- json-schema@0.2.3
| | | | | `-- verror@1.3.6
| | | | `-- sshpk@1.13.0
| | | |   +-- asn1@0.2.3
| | | |   +-- assert-plus@1.0.0
| | | |   +-- bcrypt-pbkdf@1.0.1
| | | |   +-- dashdash@1.14.1
| | | |   | `-- assert-plus@1.0.0
| | | |   +-- ecc-jsbn@0.1.1
| | | |   +-- getpass@0.1.7
| | | |   | `-- assert-plus@1.0.0
| | | |   +-- jodid25519@1.0.2
| | | |   +-- jsbn@0.1.1
| | | |   `-- tweetnacl@0.14.5
| | | +-- is-typedarray@1.0.0
| | | +-- isstream@0.1.2
| | | +-- json-stringify-safe@5.0.1
| | | +-- mime-types@2.1.15
| | | | `-- mime-db@1.27.0
| | | +-- oauth-sign@0.8.2
| | | +-- qs@6.2.3
| | | +-- stringstream@0.0.5
| | | +-- tough-cookie@2.3.2
| | | | `-- punycode@1.4.1
| | | `-- tunnel-agent@0.4.3
| | +-- underscore@1.4.4
| | +-- validator@3.22.2
| | +-- xml2js@0.2.7
| | | `-- sax@0.5.2
| | `-- xmlbuilder@0.4.3
| +-- debug@2.6.6
| | `-- ms@0.7.3
| +-- machina@2.0.0
| | `-- lodash@3.10.1
| `-- traverse@0.6.6
+-- azure-iot-device-amqp@1.1.11
| `-- azure-iot-amqp-base@1.1.8
|   +-- amqp10@3.5.0
|   | +-- buffer-builder@0.2.0
|   | +-- node-int64@0.4.0
|   | `-- stately.js@1.3.0
|   +-- amqp10-transport-ws@0.0.5
|   | `-- nodejs-websocket@1.7.1
|   +-- bluebird@3.5.0
|   `-- uuid@3.0.1
+-- azure-iot-device-http@1.1.11
| `-- node-crontab@0.0.8
|   `-- cron-parser@0.3.6
+-- azure-iot-device-mqtt@1.1.11
| `-- mqtt@1.14.1
|   +-- commist@1.0.0
|   | `-- leven@1.0.2
|   +-- concat-stream@1.6.0
|   | +-- readable-stream@2.2.9
|   | | +-- buffer-shims@1.0.0
|   | | `-- string_decoder@1.0.0
|   | `-- typedarray@0.0.6
|   +-- end-of-stream@1.4.0
|   | `-- once@1.4.0
|   |   `-- wrappy@1.0.2
|   +-- help-me@1.1.0
|   | +-- callback-stream@1.1.0
|   | +-- glob-stream@6.1.0
|   | | +-- extend@3.0.1
|   | | +-- glob-parent@3.1.0
|   | | | +-- is-glob@3.1.0
|   | | | | `-- is-extglob@2.1.1
|   | | | `-- path-dirname@1.0.2
|   | | +-- is-negated-glob@1.0.0
|   | | +-- ordered-read-streams@1.0.0
|   | | | `-- is-stream@1.1.0
|   | | +-- pumpify@1.3.5
|   | | +-- readable-stream@2.2.9
|   | | | `-- string_decoder@1.0.0
|   | | +-- remove-trailing-separator@1.0.1
|   | | +-- to-absolute-glob@2.0.1
|   | | | +-- extend-shallow@2.0.1
|   | | | | `-- is-extendable@0.1.1
|   | | | `-- is-absolute@0.2.6
|   | | |   +-- is-relative@0.2.1
|   | | |   | `-- is-unc-path@0.1.2
|   | | |   |   `-- unc-path-regex@0.1.2
|   | | |   `-- is-windows@0.2.0
|   | | `-- unique-stream@2.2.1
|   | |   +-- json-stable-stringify@1.0.1
|   | |   | `-- jsonify@0.0.0
|   | |   `-- through2-filter@2.0.0
|   | `-- through2@2.0.3
|   |   `-- readable-stream@2.2.9
|   |     `-- string_decoder@1.0.0
|   +-- inherits@2.0.3
|   +-- minimist@1.2.0
|   +-- mqtt-connection@2.1.1
|   | +-- reduplexer@1.1.0
|   | | `-- readable-stream@1.0.34
|   | |   `-- isarray@0.0.1
|   | `-- through2@0.6.5
|   |   `-- readable-stream@1.0.34
|   |     `-- isarray@0.0.1
|   +-- mqtt-packet@3.4.8
|   | `-- bl@0.9.5
|   |   `-- readable-stream@1.0.34
|   |     `-- isarray@0.0.1
|   +-- pump@1.0.2
|   +-- readable-stream@1.0.34
|   | `-- isarray@0.0.1
|   +-- reinterval@1.1.0
|   +-- split2@2.1.1
|   +-- websocket-stream@3.3.3
|   | +-- duplexify@3.5.0
|   | | +-- end-of-stream@1.0.0
|   | | | `-- once@1.3.3
|   | | `-- stream-shift@1.0.0
|   | `-- ws@1.1.4
|   |   +-- options@0.0.6
|   |   `-- ultron@1.0.2
|   `-- xtend@4.0.1
+-- es5-shim@4.5.9
+-- jshint@2.9.4
| +-- cli@1.0.1
| | `-- glob@7.1.1
| |   +-- fs.realpath@1.0.0
| |   +-- inflight@1.0.6
| |   `-- path-is-absolute@1.0.1
| +-- console-browserify@1.1.0
| | `-- date-now@0.1.4
| +-- exit@0.1.2
| +-- htmlparser2@3.8.3
| | +-- domelementtype@1.3.0
| | +-- domhandler@2.3.0
| | +-- domutils@1.5.1
| | | `-- dom-serializer@0.1.0
| | |   +-- domelementtype@1.1.3
| | |   `-- entities@1.1.1
| | +-- entities@1.0.0
| | `-- readable-stream@1.1.14
| |   `-- isarray@0.0.1
| +-- lodash@3.7.0
| +-- minimatch@3.0.3
| | `-- brace-expansion@1.1.7
| |   +-- balanced-match@0.4.2
| |   `-- concat-map@0.0.1
| +-- shelljs@0.3.0
| `-- strip-json-comments@1.0.4
`-- lodash@4.17.4
- **cloned repo:** n/a 

# Description of the issue:
I am hoping that I'm using the SDK incorrectly, but I'm having trouble setting up my client to receive Messages when I'm also receiving Methods. I've attached the complete file, but here are the snippets...

When I have the following code, the 'onMessage' never fires. When i comment the .onDeviceMethod functions, then the 'onMessage' fires.

// register handler for the message queue
console.log('registering message handler');
client.on('message', onMessage);

// register handlers for all the method names we are interested in
console.log('registering custom methods');
client.onDeviceMethod('blinkLight', onBlinkLight);

# Code sample exhibiting the issue:
Here is the complete file...
[iotTest.txt](https://github.com/Azure/azure-iot-sdk-node/files/993542/iotTest.txt)

**Comment by pierreca** [comment]
Definitely something fishy here. investigating.

**Comment by yuwzho** [comment]
I notice in the last version of code, when the `client.js` execute onDeviceMethod, it will invoke `message` listener first. But currently the code seems remove such logic.

**Comment by pierreca** [comment]
Yes, there is definitely some flawed logic with how we start the message listeners vs the method listeners. i'll have a fix for this in the next couple of days.

**Comment by JensChrMikkelsen** [comment]
The Cloud to Device command works only when one of the two is declared.

**Comment by pierreca** [comment]
@JensChrMikkelsen @yuwzho @michaelheyd we have a fix in review right now in the `fix-39-41` branch. 
If you want you can clone the repo and pull this branch to verify that the fix works.

we have a new release coming at the end of the week and these fixes should be part of it.

**Comment by pierreca** [comment]
we've released a new package (azure-iot-device@1.1.12) with a fix.
Closing the issue but feel free to reopen if you still see the issue (meaning the fix doesn't work). 

Thanks again for reporting this!
