### ISSUE TITLE
Problem in sending commands using direct method

### ISSUE THREAD

**Issue by samisarfraz** [Azure/azure-iot-sdk-node#415]
This is a bit weird and confusing issue but i'll try to explain it.I am facing a problem in sending commands using direct method (invoke method). We developed our code with azure c sdk (Arduino) and was able to send commands with Direct method (Method name + payload) when using Portal.Azure.com or windows 7 machine using device explorer. Initially we were using this feature from cloud (Direct method) then we shifted to device explorer as its easy to use. Device explorer was working fine on windows 7. We can send commands with method name and payload. But when we installed device explorer on windows 10 things got very peculiar as we only invoke a command with only method name (no payload). When we send the command with method name and payload (json string) it cause our device to restart and shows an error but these very same commands { method name and payload (json string)} execute fully when we send them from windows 7 device explorer or portal.azure.com – direct method / invoke method (no restart or errors) . We are facing the same problem when we use the sdks (java , node , C#) for sending commands.

**Comment by pierreca** [comment]
no point in opening the issue in multiple places, that just hinders our triage process. I've responded here: https://github.com/Azure/iothub-explorer/issues/56. closing this one.

**Comment by az-iot-builder-01** [comment]
@samisarfraz, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
