### ISSUE TITLE
TypeError: Callback has to be a Function (azure-iothub@ > 1.7.4)

### ISSUE THREAD

**Issue by beneuto** [Azure/azure-iot-sdk-node#416]
Code working fine using azure-iothub v1.7.4 but breaks in v1.7.5 and above with the error: **TypeError: Callback has to be a Function.**

Similar problem with azure-iot-device.

Minimal code example:

```
var connectionString = 'HostName=myhub.azure-devices.net;SharedAccessKeyName=test;SharedAccessKey=xxxxxxxxxxxxxxxxxxxxxxxxx';

var device =  {   deviceId: "xyz"   };
 
var registry = iothub.Registry.fromConnectionString(connectionString);

registry.get(device.deviceId, function(err, deviceInfo, res) {    });
```

**Comment by anthonyvercolano** [comment]
I'm at a bit of a loss.  I've taken the above supplied code.  Used my own device id and hub connection string and ran it on a 1.7.5 installation.  It worked fine.

**Comment by beneuto** [comment]
It may be because I am running through node-red function node?   

Node-RED version: v0.19.4
Node.js  version: v8.11.1

**Comment by anthonyvercolano** [comment]
Likely.  Will be discussing this with others who might have ideas.

**Comment by anthonyvercolano** [comment]
Which node-red module are you using?

**Comment by beneuto** [comment]
The Function node.

**Comment by anthonyvercolano** [comment]
Thank you.  Repro'd and investigating further.

**Comment by anthonyvercolano** [comment]
Should be available in the next release.

**Comment by az-iot-builder-01** [comment]
@beneuto, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
