### ISSUE TITLE
change keepalive for sendEvent on MQTT

### ISSUE THREAD

**Issue by virtualamjath** [Azure/azure-iot-sdk-node#417]
# Context
- **OS and version used:** <VERSION> Embedded Windows 
- **Node.js version:** <VERSION> 8.0
- **npm version:** <VERSION>latest
- **list of installed packages:** <VERSION> 

# Description of the issue:

I am using MQTT protocol to send data . I have set NoRetry() as i wanted to go into callback if any network failures are there. but it is coming only after 4 min . can i change that timeout period to some milli seconds when i am in NoRetry() . Reason is that in case if figured out the error in sending the message i can save data locally and send when connectivity comes back.
# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by virtualamjath** [comment]
@anthonyvercolano can you share sample code for it.

**Comment by anthonyvercolano** [comment]
You could try doing a client.SetOptions({keepAlive: 10}). The number is the number of second between keep alive packets. Do the setOptions before the open/connect occurs.  Also set all of your options at the same time.

Note of course that this will generate more network traffic.  Normally the keepAlive pings are at 180 seconds.

**Comment by virtualamjath** [comment]
@anthonyvercolano i tried by doing client.setOptions({keepalive : 10} ) ; 
var client = clientFromConnectionString(connectionString);
client.setOptions({keepalive: 10});
client.setRetryPolicy(new NoRetry());
client.open(connectCallback);

But it did not worked out i am getting failure in sending the message only after 5 minutes 
Log Here with time 
 status: MessageEnqueued   Fri Nov 02 2018 11:18:17 GMT+0530 (IST)
 status: MessageEnqueued   Fri Nov 02 2018 11:18:18 GMT+0530 (IST)
i am disconnectedFri Nov 02 2018 11:24:15 GMT+0530 (IST)
this is error sendeventNotConnectedError: getaddrinfo EAI_AGAIN cyientiothub.azure-devices.net:8883    Fri Nov 02 2018 11:24:15 GMT+0530 (IST)
Could not connect: NotConnectedError: getaddrinfo EAI_AGAIN cyientiothub.azure-devices.net:8883
this is error sendeventNotConnectedError: getaddrinfo EAI_AGAIN cyientiothub.azure-devices.net:8883    Fri Nov 02 2018 11:24:16 GMT+0530 (IST)
this is error sendeventNotConnectedError: getaddrinfo EAI_AGAIN cyientiothub.azure-devices.net:8883    Fri Nov 02 2018 11:24:17 GMT+0530 (IST)
this is error sendeventNotConnectedError: getaddrinfo EAI_AGAIN cyientiothub.azure-devices.net:8883    Fri Nov 02 2018 11:24:18 GMT+0530 (IST)

**Comment by virtualamjath** [comment]
@anthonyvercolano 
This is the reason in my application i am using is-internet-available module to check whether internet is available by pinging to google and only when i am connected then only sending data to cloud. But for knowing internet available it is consuming 350ms and i need to send telemetry at every second level and there few processing on each message i need to do at edge level . 

**Is there a way that i can check my client is connected to IoT Hub ?** 
**or after 4 min of internet outage will it automatically reconnects to IoT hub or I need to do** 
**client.close() 
Then client.open( connectionString )**

**Comment by anthonyvercolano** [comment]
Will get back to you.  Will discuss this with others.

**Comment by virtualamjath** [comment]
Hi @anthonyvercolano . Did you got chance to discuss with team about it.

**Comment by StefanSchoof** [comment]
There is the (undocumented?) `disconnect` event. See https://github.com/Azure/azure-iot-sdk-node/blob/master/device/core/src/device_client.ts#L84

**Comment by anthonyvercolano** [comment]
Hmm, I still need to search the online docs but the samples certainly use the 'disconnect' event.

**Comment by anthonyvercolano** [comment]
However, not really sure this will help you much.  It would seem as though the issue is noticing the disconnect occurring.  Note that on linux type OS's this is typically a very difficult thing to do.  Hence my attempt to have you crank down the keep alive. 

I still need to talk this over with others.

**Comment by pierreca** [comment]
This needs the introduction of a new API to set the keepalive value which is not trivial given the meaning of what "keepalive" is depending on the protocol. We could start with MQTT at least to unblock this.

**Comment by YoDaMa** [comment]
This issue is related to #537. A keepalive option will be added to the backlog of enhancements.

**Comment by anthonyvercolano** [comment]
Released.

**Comment by az-iot-builder-01** [comment]
@virtualamjath, @StefanSchoof, @YoDaMa, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
