### ISSUE TITLE
 TypeError: azure_iot_common_1.endpoint.deviceEventPath is not a function - azure-iot-common@1.7.4

### ISSUE THREAD

**Issue by kmaheshbabu-ckpt** [Azure/azure-iot-sdk-node#419]
Getting this error consistently
 
TypeError: azure_iot_common_1.endpoint.deviceEventPath is not a function - azure-iot-common@1.7.4

error occurs while invocation of 

iothub_client = Client.fromConnectionString(this.configuration.connection_string, Protocol);
iothub_client.open(this.on_connect.bind(this));

where 
let Protocol = require('azure-iot-device-mqtt').Mqtt;
this.configuration.connection_string is "HostName=myiot.azure-devices.net;DeviceId=abc-123456;SharedAccessKey=test"

Environment details
node -v
v8.12.0

Ubuntu x86_64

**Comment by kmaheshbabu-ckpt** [comment]
It appears because of the node_modules having a older version of dependency. 

Able to resolve the issue,  by deleting the node_modules and npm i.

**Comment by az-iot-builder-01** [comment]
@kmaheshbabu-ckpt, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
