### ISSUE TITLE
Node-red IoT Hub MQTT blocked by IP filtering

### ISSUE THREAD

**Issue by beneuto** [Azure/azure-iot-sdk-node#42]
Not exactly sure where this issue lies but raising it here because this node works fine with AMQP but if set to MQTT it fails when IP filtering is in place at the IoT Hub.

I am running node-red on Windows Server 2016 on an Azure VM.   I am attempting to establish whitelisted IP filtering.   In IoT Hub IP Filtering I have whitelisted the VM's external IP address (like 1.2.3.4/32).

The node is working fine using MQTT until the IP filter is established and then the following error is returned.

"Error while trying to send message:ServiceUnavailableError: mqtt.js returned Connection refused: Server unavailable error"

The node will work with the filter on if set to AMQP.

MQTT through the IP Filter is supported according to the IoT Hub documentation.

I am using the node on multiple tabs and all fail when the filter is applied.

**Comment by pierreca** [comment]
Rephrasing just to make sure I get the gist of the problem: you're saying that when IP filtering is active, on the same IP, without changing the configuration of the VM, you successfully connect using AMQP, but not MQTT. and without IP filtering, both AMQP and MQTT work. 
in other words, MQTT doesn't seem to work with IP filtering.
is that correct?

**Comment by beneuto** [comment]
That is correct.

**Comment by pierreca** [comment]
OK, I think we have the necessary repro steps, we're investigating and will keep you posted. Thanks for reporting this!

**Comment by mastermanu** [comment]
Beneuto - Can you please provide the name of the IoT Hub and a time frame as well to aid with debugging?

**Comment by mtuchkov** [comment]
Hello @beneuto,
We identified the issue on the server side and already acted on in, the fix will be deployed within the next month. We will update this github issue when it is deployed. No further action from you required.

**Comment by pierreca** [comment]
Closing as the fix has been deployed for a while now - let us know if you still observe issues.
