### ISSUE TITLE
Question: Are messages compressed before transmitted?

### ISSUE THREAD

**Issue by wmmihaa** [Azure/azure-iot-sdk-node#423]
Our devices are running on 3G/LTE networks and dataplan usage are of concern. Would there be any benefits compressing messages before submitting them? Such actions would of course require decompressing the messages on the reeiving end, but I was just wondering if they already are compressed or if threre is a setting to enable it.

We're using AMQP as device protocol.
Cheers
Mikael

**Comment by anthonyvercolano** [comment]
No compression is done.  You might suggest something about this in the user voice site.

**Comment by anthonyvercolano** [comment]
Not saying it's a bad idea.  Your opinions matter.  Try bringing this up in [User Voice](https://feedback.azure.com/forums/321918-azure-iot)
