### ISSUE TITLE
can we send Batch messages using node SDK  Using AMQP protocol 

### ISSUE THREAD

**Issue by virtualamjath** [Azure/azure-iot-sdk-node#424]
# Context
- **OS and version used:** <VERSION> 
- **Node.js version:** <VERSION> 
- **npm version:** <VERSION> 
- **list of installed packages:** <VERSION> 
- **cloned repo:** <VERSION> 

# Description of the issue:

# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by virtualamjath** [comment]
Sample provided in examples is broken

**Comment by anthonyvercolano** [comment]
Will take the sample issue as a bug.

**Comment by virtualamjath** [comment]
@Anthony. Can you reconfirm we don't have sending event batch.  In sample codes it wasn't there but somewhere I have seen seen Amqp protocol sending batch events using node

**Comment by virtualamjath** [comment]
Can you kindly send small sample to send to send batch events in using HTTP protocol...

**Comment by pierreca** [comment]
The sample is over there, in the samples repository:

https://github.com/Azure-Samples/azure-iot-samples-node/blob/master/iot-hub/Samples/device/send_telemetry_batch.js

**Comment by az-iot-builder-01** [comment]
@virtualamjath, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
