### ISSUE TITLE
Sample Code for Setting up the contentType and Encoding

### ISSUE THREAD

**Issue by virtualamjath** [Azure/azure-iot-sdk-node#433]
# Context
- **OS and version used:** <VERSION> 
- **Node.js version:** <VERSION> 
- **npm version:** <VERSION> 
- **list of installed packages:** <VERSION> 
- **cloned repo:** <VERSION> 

# Description of the issue:
In the github sample Codes i am not able to see how to set the contentType and Encoding Can yopu provide sample for this using MQTT adn Http protocols

**Comment by virtualamjath** [comment]
@anthonyvercolano It is been resolved issue  ... But there is no samples presented , can just specify where do i need to change for contentType and encoding 
https://github.com/Azure/azure-iot-sdk-node/issues/219

but no sample code available ...

**Comment by anthonyvercolano** [comment]
Are you saying that you've done a
```
message.contentType = "application/json";
message.contentEncodng = "utf-8";
message.properties.add(key,value);
```
And set up some routing via the portal and that doesn't work?

**Comment by az-iot-builder-01** [comment]
@virtualamjath, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by pjgpetecodes** [comment]
> Are you saying that you've done a
> 
> ```
> message.contentType = "application/json";
> message.contentEncodng = "utf-8";
> message.properties.add(key,value);
> ```
> 
> And set up some routing via the portal and that doesn't work?

In case anyone needs this... There's a typo in the example contentEncoding above..

The correct snippet is just;

message.contentType = "application/json";
message.contentEncoding = "utf-8";
