### ISSUE TITLE
Could not schedule twin update job: Error: BadRequest {"Message":"ErrorCode:ArgumentInvalid

### ISSUE THREAD

**Issue by saurabh-newera** [Azure/azure-iot-sdk-node#44]
While using the sdk 'azure-iothub', I have been facing this issue with scheduling twin update.

**Comment by pierreca** [comment]
@saurabh-newera can you paste a piece of code showing what you're trying to achieve, maybe with the job parameters? A basic console log would help too.

**Comment by saurabh-newera** [comment]
var startTime = new Date();
var maxExecutionTimeInSeconds =  60;
var patch = {
		etag: '*',
		desired: {
			building: '43',
			floor: 3
		}
	};
	function monitorJob (jobId, callback) {
		var jobMonitorInterval = setInterval(function() {
			jobClient.getJob(jobId, function(err, result) {
				if (err) {
					log.error('Could not get job status: ' + err.message);
				} else {
					log.debug('Job: ' + jobId + ' - status: ' + result.status);
					if (result.status === 'completed' || result.status === 'failed' || result.status === 'cancelled') {
						clearInterval(jobMonitorInterval);
						callback(null, result);
					}
				}
			});
		}, 5000);
	}
		
		var queryCondition = "deviceId IN ['my device id']";
		var jobId = uuid.v4();
		var jobStartTime = startTime;
		log.debug('scheduling Twin Update job with id: ' + jobId);
		jobClient.scheduleTwinUpdate(jobId,
                            queryCondition,
                            patch,
                            jobStartTime,
                            maxExecutionTimeInSeconds,
                            function(err) {
								
						
			if (err) {
				log.error('Could not schedule twin update job: ' + err.message);
			} else {
				monitorJob(twinJobId, function(err, result) {
					if (err) {
						log.error('Could not monitor twin update job: ' + err.message);
					} else {
						log.debug(JSON.stringify(result, null, 2));
					}
				});
			}
		});

@pierreca: thank you for responding.

**Comment by pierreca** [comment]
@saurabh-newera 
*edited your comment to show clearer code*

The problem here is the format of your patch: the `desired` object needs to be contained into the `properties` object, so to be clear:
```js
var twinPatch = {
  etag: '*',
  properties: {
    desired: {
      building: '43',
      floor: 3
    }
  }
};
```

Please let us know if that solves your issue.

**Comment by saurabh-newera** [comment]
@pierreca: That  resolved my issue! Thanks a lot!
