### ISSUE TITLE
Provide example for sending Module Twin reported property

### ISSUE THREAD

**Issue by sandervandevelde** [Azure/azure-iot-sdk-node#444]
In the IoT Edge documentation, there is a [node.js](https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-node-module) tutorial.
It shows how to handle module twin desired properties. 
Please provide an example on how to send reported properties back to the IoTHub.

**Comment by anthonyvercolano** [comment]
azure-iot-sdk-node/device/samples/simple_sample_module_twin.js ?

**Comment by anthonyvercolano** [comment]
If you're thinking that Edge documentation should have such a tutorial, suggest filing this as an issue against Edge.

**Comment by darobs** [comment]
Hello @sandervandevelde 

Yes, please file this against [Azure IoT Edge repo](https://github.com/Azure/iotedge).

Until then @anthonyvercolano's referenced an example from this repo that should get you started.

Thank you.

**Comment by sandervandevelde** [comment]
I was unable to find an example in this library.

But thanks to @AntonioMaioProtiviti, I found the code in the [simple sample device twin example](https://github.com/Azure/azure-iot-sdk-node/blob/master/device/samples/simple_sample_device_twin.js)

>     // create a patch to send to the hub
>     var patch = {firmwareVersion:'1.2.1', weather:{temperature: 72, humidity: 17}};
>
>     // send the patch
>     twin.properties.reported.update(patch, function(err) {
>        if (err) throw err;
>        console.log('twin state reported');
>     });

This is a good starting point.

If it has value, I will make a pull request in the IoT Edge node.js tutorial.

Thanks,

Sander

**Comment by az-iot-builder-01** [comment]
@darobs, @sandervandevelde, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
