### ISSUE TITLE
TypeError: _this._transport.sendEvent is not a function

### ISSUE THREAD

**Issue by uma075** [Azure/azure-iot-sdk-node#453]
# Context
- **OS and version us:** Windows 10 
- **Node.js version:** 8.11.1 
- **npm version:** 5.6.0 
- **list of installed packages:** 
"azure-iot-security-x509": "1.3.2",
    "azure-iot-device": "1.3.2",
    "azure-iot-provisioning-device": "1.4.2",
    "azure-iot-provisioning-device-amqp": "1.4.2",
    "azure-iot-provisioning-device-http": "1.4.2",
    "azure-iot-provisioning-device-mqtt": "1.4.2"

# Description of the issue:
I have sucessfully provisioned Device, I am using X509 certs for provisioning and its working fine. Now I want to send device messages to IoT hub, so I have created a seperate class DeviceHelper, but I am geeting this error. Can somebody please help?
TypeError: _this._transport.sendEvent is not a function

# Code sample exhibiting the issue:
Code for Device Provisioning

```
var fs = require('fs');
var DeviceHelper = require('./device-helper');
var Transport = require('azure-iot-provisioning-device-http').Http;
var X509Security = require('azure-iot-security-x509').X509Security;
var ProvisioningDeviceClient = require('azure-iot-provisioning-device').ProvisioningDeviceClient;
// Register the device.  Do not force a re-registration.
        deviceClient.register(function (err, result) {
            if (err) {
                that.setProvisionStatus(PROVISION_STATUS.ERROR);
                console.log(err);
            } else {
                console.log('registration succeeded');
                that.assignedHub = result.assignedHub;
                console.log('assigned hub=' + result.assignedHub);
                console.log('deviceId=' + result.deviceId);
                var deviceHelper = new DeviceHelper(that.deviceId, that.assignedHub, deviceCert, Transport);
                deviceHelper.sendEvent();
            }
        });
```
DeviceHelper code:

```
var Device = require('azure-iot-device');
var Client = Device.Client;
var X509AuthenticationProvider = Device.X509AuthenticationProvider;
var Message = Device.Message;
var Http = Device.Http;

var client = {};
class DeviceHelper {

  constructor(deviceId, hubName, security, transport) {
    client = Client.fromAuthenticationProvider(X509AuthenticationProvider.fromX509Options(
      deviceId, hubName, security
    ),transport);
  }

  print(err, res) {
    if (err) console.log(err.toString());
    if (res) console.log(res.statusCode + ' ' + res.statusMessage);
  }

  sendEvent() {
// Error on this line
    client.sendEvent(new Message('hello world'), this.print);
  }
}

module.exports = DeviceHelper;
```

# Console log of the issue:
TypeError: _this._transport.sendEvent is not a function
index.js:23
message:"_this._transport.sendEvent is not a function"
stack:"TypeError: _this._transport.sendEvent is not a function\n    at D:\Working\Brahma\web-communicator\server\iot-agent\node_modules\azure-iot-device\lib\client.js:216:30\n    at retryOperation (D:\Working\Brahma\web-communicator\server\iot-agent\node_modules\azure-iot-device\node_modules\azure-iot-common\lib\retry_operation.js:31:13)\n    at RetryOperation.retry (D:\Working\Brahma\web-communicator\server\iot-agent\node_modules\azure-iot-device\node_modules\azure-iot-common\lib\retry_operation.js:57:9)\n    at Client.sendEvent (D:\Working\Brahma\web-communicator\server\iot-agent\node_modules\azure-iot-device\lib\client.js:214:17)\n    at DeviceHelper.sendEvent (D:\Working\Brahma\web-communicator\server\iot-agent\device-helper.js:22:12)\n    at D:\Working\Brahma\web-communicator\server\iot-agent\iot-device.js:99:30\n    at D:\Working\Brahma\web-communicator\server\iot-agent\node_modules\azure-iot-provisioning-device\lib\x509_registration.js:50:33\n    at constructor._onEnter (D:\Working\Brahma\web-communicator\server\iot...
__proto__:Error {constructor: , name: "TypeError", message: "", …}

**Comment by uma075** [comment]
Also posted the question on stackoverflow.com.
[https://stackoverflow.com/questions/53909704/typeerror-this-transport-sendevent-is-not-a-function](https://stackoverflow.com/questions/53909704/typeerror-this-transport-sendevent-is-not-a-function)

**Comment by anthonyvercolano** [comment]
The transport that you are sending to your deviceHelper constructor appears to be a provisioning transport. I think you want to send a device client transport. Your code snippet for the deviceHelper module does a require on a device transport. That is the kind of transport that has a send.

**Comment by uma075** [comment]
> The transport that you are sending to your deviceHelper constructor appears to be a provisioning transport. I think you want to send a device client transport. Your code snippet for the deviceHelper module does a require on a device transport. That is the kind of transport that has a send.

It worsk, Thanks

**Comment by az-iot-builder-01** [comment]
@uma075, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
