### ISSUE TITLE
twin.update() is missing when the device twin is returned as part of a promise

### ISSUE THREAD

**Issue by brendan-myers** [Azure/azure-iot-sdk-node#457]
# Context
- **OS and version used:** Mac OS X 10.14
- **Node.js version:** v9.20
- **npm version:** 5.6.0
- **list of installed packages:**
```
├─┬ azure-iothub@1.8.3
```

# Description of the issue:
Device Twin does not contain the `update` function when returned from a promise. It does, however, when it is returned using the callback method.

# Code sample exhibiting the issue:
```
var iothub = require('azure-iothub');
var connectionString = '<<connection string>>';
var registry = iothub.Registry.fromConnectionString(connectionString);
var deviceId = "<<device id>>";

registry.getTwin(deviceId, function (err, twin) {
    console.log("Callback -> " + !!twin.update);
});

registry.getTwin(deviceId).then(twin => {
    console.log("Promise -> " + !!twin.update);
});
```

# Console log of the issue:
```
Promise -> false
Callback -> true
```

**Comment by anthonyvercolano** [comment]
This is somewhat regrettable.  For the promise api, one needs to say something like twin.responseBody.update

**Comment by pierreca** [comment]
This seems like the same API issue as 2nd problem in #459. ping @kpajdzik

**Comment by pierreca** [comment]
To close on this:
- @anthonyvercolano is correct in his suggestion.
- This API shape is ugly but changing it is a breaking change. We'll have to live with it for now and we'll fix this for v2.x.x

Because of this (admittedly unfortunate) situation I'm closing this as "wontfix" (given there are no v2.x.x plans for now).

**Comment by az-iot-builder-01** [comment]
@brendan-myers, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
