### ISSUE TITLE
EdgedAuthConfig & IotEdgeAuthenticationProvider not being exported on device.js file 

### ISSUE THREAD

**Issue by axel-saredo** [Azure/azure-iot-sdk-node#467]
Hi there,  
I noticed that EdgedAuthConfig & IotEdgeAuthenticationProvider are being exported on the device.d.ts file **but not on the device.js file.** 
[Here is the device.d.ts file ](https://github.com/Azure/azure-iot-sdk-node/blob/master/device/core/device.d.ts#L13) and [here is the device.js file ](https://github.com/Azure/azure-iot-sdk-node/blob/master/device/core/device.js). As you can see this is true and it generates a complicated error that is hard to see. 

Thank you.

**Comment by anthonyvercolano** [comment]
Ddevice.js will be fixed in next release.  (Tuesday or so next week.)

**Comment by anthonyvercolano** [comment]
Published.

**Comment by az-iot-builder-01** [comment]
@axel-saredo, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by axel-saredo** [comment]
Thank you very much for the answer and the fixes!
