### ISSUE TITLE
azure-iothub: may need to review dependencies (azure-iot-common)

### ISSUE THREAD

**Issue by beneuto** [Azure/azure-iot-sdk-node#477]
# Context
- Node-red v0.19.5 on Azure App Service
- Node.js v10.14.1
- Npm v6.4.1
- azure-iothub v1.8.2

# Description of the issue:
Application suddenly failed Monday evening (28 Jan 2019).   Error: _**azure_iot_common_2.httpCallbackToPromise is not a function**_

Tried upgrade of azure-iothub to latest v1.9.2 but still error.

Resolved by explicitly installing azure-iot-common v1.9.2.

# Code sample exhibiting the issue:
```
var registry = iothub.Registry.fromConnectionString(connectionString);
registry.get(device.deviceId);
```

NOTE: registry.get(device.deviceId, function(err, deviceInfo, res) { ...  }) variant also failed with same error.

**Comment by anthonyvercolano** [comment]
The package.json for azure-iothub does reference the azure-IoT-common 1.92

**Comment by anthonyvercolano** [comment]
@beneuto I'm hoping you can give a better description of what how we have an incorrect dependency.  As far as I can tell, we have this correct.

**Comment by anthonyvercolano** [comment]
Perhaps a fairly short code section with its package.json as it was before the problem occurred.  Then what happened that provoked the failure on the the 28th.

What you mean by upgrading then doing the install?

**Comment by beneuto** [comment]
Nevermind.  Looks like npm was corrupted.   Rebuilt npm_modules and lock file with the original config and is working ok.

**Comment by az-iot-builder-01** [comment]
@beneuto, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
