### ISSUE TITLE
Connecting to IoT Hub using MQTT issue

### ISSUE THREAD

**Issue by melzoghbi** [Azure/azure-iot-sdk-node#48]
Hi,

I am using Azure NodeJS SDK to connect to IoT hub through MQTT protocol. When i try to run my app i get the following error:

![image](https://user-images.githubusercontent.com/11993393/27056139-f32e3af4-4f94-11e7-8341-0ae7c0bd696f.png)

The error shows that there is no method isString in azure-iot-device-mqtt version that i am using in line #221. 

This app runs on Raspbian Jessie OS on Pi Zero W that has nodejs version: 0.10.29.

**Comment by pierreca** [comment]
util.isString() was introduced in node 0.11 and you're using node 0.10.
https://nodejs.org/api/util.html#util_util_isstring_object

We cannot support node 0.10 anymore - the node maintainers themselves have declared this version "end of life" (https://github.com/nodejs/LTS#lts-schedule1) and our dependencies are dropping support for it. 

Please upgrade to a more recent version of node to resolve your issue.

**Comment by melzoghbi** [comment]
Thanks a lot @pierreca for clarifying this issue. I will update my node installation and will give it a shot.

**Comment by melzoghbi** [comment]
After I upgraded my node to 6.11.0 it works like a champ!
