### ISSUE TITLE
azure-iot-security-tpm doesn't allow for more than one TpmSecurityClient when using TPM simulator

### ISSUE THREAD

**Issue by casabon** [Azure/azure-iot-sdk-node#480]
# Context
- **OS and version used:** Windows 10
- **Node.js version:** v10.15.0
- **npm version:** 6.4.1

# Description of the issue:
When two `TpmSecurityClient`s are instantiated in the same application, the TPM simulator will no longer function - instead, only a single instance of TpmSecurityClient used in this case with the simulator seems to be required.

If this is the case, it's rather confusing. When trying to build an application with multiple files, it's common to `require` the package and instantiate the security client on a per-class/per-module basis - this is where I originally ran into this issue, where two classes both created their own instances of TpmSecurityClient to do work, which fails. 

If you can only have one simulated TpmSecurityClient, then it might make more sense to handle this with a Singleton under the hood - at least for me, seeing the `var foo = new bar();` pattern used in the quickstarts shows that I can create quite a few of these things and they shouldn't conflict with one another and I can have locally scoped `TpmSecurityClient`s instead. 

# Code sample exhibiting the issue:
A failing testcase, note the locally scoped `new ... TpmSecurityClient` at L20, L46:
https://gist.github.com/casabon/8ebcf905a07a53f28b3320d8275d24af

A passing testcase, note `const ... new TpmSecurityClient` at L9:
https://gist.github.com/casabon/73d6f25fdb4168f27f42d031eceb4c29

**Comment by anthonyvercolano** [comment]
I'm going to have to page all the stuff in having to do with tpm.  I have a fairly in-efficient memory manager.

Let me get back to you tomorrow.

**Comment by anthonyvercolano** [comment]
Looking at the link you sent.  The first parameter of the TpmSecurityClient is always undefined.  Where am I missing the invocation with it set otherwise?

In addition, great care should be taken.  If you are trying to call both of  your functions, you could easily end up both trying to invoke commands on the tpm at the same time.  This could be bad.

**Comment by casabon** [comment]
Ah, I seem to have mixed up two of the methods when implementing this. The core issue might be slightly different but I believe there is still an issue; I'm going to try to make a reduced testcase and get back to you.

**Comment by casabon** [comment]
Edited the primary bug with better test cases and a description. Sorry for the lack of clarity.

**Comment by anthonyvercolano** [comment]
It is not a permitted use of the tssJs.tpm(bool) to call it twice.  The first is opening a socket and the second will just wait until the first one goes away.

**Comment by casabon** [comment]
Closing as by design.

**Comment by az-iot-builder-01** [comment]
@casabon, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by pierreca** [comment]
paging @amarochk for issues with tss.js and the TPM simulator.
