### ISSUE TITLE
Promise from client.invokeDeviceMethod does not get resolved

### ISSUE THREAD

**Issue by StefanSchoof** [Azure/azure-iot-sdk-node#481]
# Context
- **OS and version used:** Windows 10
- **Node.js version:** v10.15.0
- **npm version:** 6.4.1
- **list of installed packages:**
```
`-- azure-iothub@1.9.2
  +-- async@2.6.1
  | `-- lodash@4.17.11 deduped
  +-- azure-iot-amqp-base@2.2.2
  | +-- async@2.6.1 deduped
  | +-- azure-iot-common@1.9.2 deduped
  | +-- debug@3.2.6 deduped
  | +-- lodash.merge@4.6.1
  | +-- machina@4.0.2 deduped
  | +-- rhea@0.3.9 deduped
  | +-- uuid@3.3.2
  | `-- ws@6.1.3
  |   `-- async-limiter@1.0.0
  +-- azure-iot-common@1.9.2
  | `-- getos@3.1.1
  |   `-- async@2.6.1 deduped
  +-- azure-iot-http-base@1.9.2
  | +-- azure-iot-common@1.9.2 deduped
  | +-- debug@3.2.6 deduped
  | `-- uuid@3.3.2 deduped
  +-- debug@3.2.6
  | `-- ms@2.1.1
  +-- lodash@4.17.11
  +-- machina@4.0.2
  | `-- lodash@4.17.11 deduped
  `-- rhea@0.3.9
    `-- debug@3.2.6 deduped
```
(a simple `npm install azure-iothub` in a empty dir)
- **cloned repo:** n/a

# Description of the issue:
Promise from  `client.invokeDeviceMethod` does not get resolved. Using the callback version I got result in time below 200ms. Using the same parameter the promise version, the resulting promise is after 5 min still in pending state.

# Code sample exhibiting the issue:
```javascript
const { Client } = require("azure-iothub");

const connectionString = "<insert your connection string here>";

const client = Client.fromConnectionString(connectionString);

console.time("timeout")
console.time("promise")
const promise = client.invokeDeviceMethod("something", {methodName: "test"}).then(
    () => console.timeEnd("promise"),
    () => console.timeEnd("promise"));

console.time("cb");
client.invokeDeviceMethod("something", {methodName: "test"}, () => {
    console.timeEnd("cb");
});


setTimeout(() => {
    console.log(promise);
    console.timeEnd("timeout");
}, 5 * 60 * 1000);
```

# Console log of the issue:
```
cb: 111.362ms
Promise { <pending> }
timeout: 300054.684ms
```

**Comment by anthonyvercolano** [comment]
Thank you.  We'll take a look.

**Comment by anthonyvercolano** [comment]
Just checking.  There are two  () => console.timeEnd("promise") in the .then.  You only need one, correct?

**Comment by anthonyvercolano** [comment]
Sorry about the delay. I hope to get this in within 10 days.

**Comment by anthonyvercolano** [comment]
Released.

**Comment by az-iot-builder-01** [comment]
@StefanSchoof, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
