### ISSUE TITLE
azure-iot-device-amqp client not throwing error when device is disabled

### ISSUE THREAD

**Issue by chrisahardie** [Azure/azure-iot-sdk-node#483]
# Context
- **OS and version used:** Windows 10
- **Node.js version:** 9.7.1
- **npm version:** 5.6.0
- **list of installed packages:** "azure-iot-device": "^1.8.2",
    "azure-iot-device-amqp": "^1.8.2",
    "uuid": "^3.2.1",
    "winston": "^2.4.2",
    "winston-azuretable": "^1.1.0"

# Description of the issue:
If I disable my IoT device, I would expect an error to be passed to the callback when I invoke `open`. Instead, I appear to connect, have a disconnect event raised, and when I retry my connection my device appears to be connected.

# Code sample exhibiting the issue:
```
const createIoTHubCommunicator = (onMessage) => {
  let client;

  const send = (data) => {
    ...  
  };

  return new Promise((resolve, reject) => {
    client = clientFromConnectionString(config.iotHubConnectionString);

    const connectionCallback = (err) => {
      if (err) {
        logger.error('Could not connect, will attempt to reconnect in 5 seconds: ' + err.toString());
        setTimeout(() => client.open(connectionCallback), 5000);
      } else {
        logger.info('client connected to iot hub')
    
        client.on('error', function (err) {
          logger.error(err.message);
        });
    
        client.on('disconnect', function () {
          logger.warn("Disconnected from IOT hub, attempting to reconnect.")
          client.removeAllListeners();
          client.open(connectionCallback);
        });

        resolve({ send })
      }
    }

    try {
      client.open(connectionCallback);
    }
    catch(err) {
      reject(err);
    }
  });
};
```

# Console log of the issue:

The logs produce the following:

>2019-02-02T20:36:42.999Z - info: client connected to iot hub
>2019-02-02T20:36:43.345Z - warn: Disconnected from IOT hub, attempting to reconnect.
>2019-02-02T20:36:44.165Z - info: client connected to iot hub

The `err` argument to the `connectionCallback` is always null, so I'm getting this behaviour that looks unusual to me. If the device has been disabled, shouldn't an `err` be produced to indicate that the device is not presently allowed to connect? If my assumption is not correct, how should the device be made aware that it isn't really connected?

**Comment by anthonyvercolano** [comment]
We will take a closer look at this issue.  However, to set expectations properly I would say that a change for this behavior, for AMQP, would probably be a couple of months away, if acted upon.

**Comment by pierreca** [comment]
Update on this issue:
- the service team has identified this as a bug and a fix is being reviewed this week.
- the fix should be deployed within the next few weeks to all regions
- given this fix is considered a breaking change (in the service behavior) it will not be enabled by default and will require to open a support ticket to have this enabled on a hub or subscription.

**Comment by anthonyvercolano** [comment]
Should be available world wide in two weeks.

**Comment by anthonyvercolano** [comment]
@chrisahardie The fix for this has been propagated world wide (although perhaps not yet for national clouds).

As it would be a breaking change it must be enabled via a feature flag (“FailAuthorizationForDisabledDevice”) at the subscription or hub level.  One would ask for this via a support request.

I think we can consider this one closed?

**Comment by az-iot-builder-01** [comment]
@chrisahardie, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by chrisahardie** [comment]
Certainly, thanks
