### ISSUE TITLE
Bad Request Error when querying next results for Enrollment Group

### ISSUE THREAD

**Issue by imalao** [Azure/azure-iot-sdk-node#502]
# Context
- **OS and version used:** MacOS High Sierra v10.13.6
- **Node.js version:** v8.11.2
- **npm version:** 6.4.1
- **list of installed packages:** azure-iot-common: 1.9.3, azure-iot-http-base: 1.9.3, azure-iot-provisioning-service: 1.5.3

# Description of the issue:

Following this sample code: https://github.com/Azure/azure-iot-sdk-node/blob/master/provisioning/service/samples/query.js

I get an error when calling for the next page of results for `Enrollment Group` Queries only:
```
  azure-iot-http-base.RestApiClient POST call to /enrollmentGroups/query?api-version=2018-11-01 returned Error: Bad Request +92ms
  azure-iot-http-base.Http Could not parse error body: Unknown body format +0ms
{"message":"Failed to fetch the results: Error: {\"errorCode\":400000,\"trackingId\":\"b2b515eb-4e93-4f59-aa5b-f2b3de1428d8\",\"message\":\"Bad Request\",\"timestampUtc\":\"2019-03-05T20:16:24.4536417Z\"}","level":"error","timestamp":"2019-03-05T20:16:24.462Z"}
 at Function.RestApiClient.translateError (node_modules/azure-iot-http-base/lib/rest_api_client.js:215:25)
    at requestCallback (node_modules/azure-iot-http-base/lib/rest_api_client.js:115:40)
    at IncomingMessage.<anonymous> (node_modules/azure-iot-http-base/lib/http.js:118:17)

```
Calling `next` on Individual Enrollments queries and Device Registration State queries work as expected.

The enrollment group query has returned the same encoded `x-ms-continuation` header (`K1JJRDpWeGt6QU9rNkZRQWFrUllBQUFBQUFBPT0jUlQ6MSNUUkM6MSNGUEM6QWdGYVpGb0NBQnFSWkFJQXZaYz0=`) every time. This doesn't decode to anything readable.

However, the Individual Enrollment queries and Device Registration State queries return different `x-ms-continuation` headers that decode to something of the format `{"token":null,"range":{"min":"xxx","max":"xxx"}}`.

**Comment by pierreca** [comment]
thanks for reporting this! we'll look this up and come back here if we have more questions.

**Comment by pierreca** [comment]
quick update: reproduced the problem. will talk with the service team.

**Comment by anushprabhu** [comment]
This seems to a bug in DPS with a particular Api version.

**Comment by pierreca** [comment]
@imalao a fix has been submitted for deployment by the service team. will keep you posted when it's fully deployed.

**Comment by imalao** [comment]
fantastic! thank you!

**Comment by pierreca** [comment]
@imalao The fix has been deployed (thanks @anushprabhu!) so I'm closing this issue. thanks again for reporting it!

**Comment by az-iot-builder-01** [comment]
@anushprabhu, @imalao, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
