### ISSUE TITLE
onDeviceMethod error: did not match any of the expected formats

### ISSUE THREAD

**Issue by sondreb** [Azure/azure-iot-sdk-node#52]
# Context
- **OS and version used:** Windows 10 Insider (Fast)
- **Node.js version:** 7.10.0
- **npm version:** 4.2.0
- **list of installed packages:** 

azure-iot-device-amqp@1.1.14
azure-iot-device@1.1.14
azure-iothub@1.1.11

# Description of the issue:
Not able to configure device method handler without app crashing.

# Exception details:

``
AmqpError: amqp:not-found:{"errorCode":404006,"trackingId":"c15b5673836d4dea942157b300059562-G:4-TimeStamp:06/26/2017 20:39:22","message":"The link address 'amqps://INSTANCE.azure-devices.net/devices/DEVICE/methods/devicebound' did not match any of the expected formats.","timestampUtc":"2017-06-26T20:39:22.0724349Z"}
``

# Code sample exhibiting the issue:

```
var Protocol = require('azure-iot-device-amqp').Amqp;
var Client = require('azure-iot-device').Client;
var ConnectionString = require('azure-iot-device').ConnectionString;
var Message = require('azure-iot-device').Message;
var config = require('./device-config');

var connectionString = config.connectionString;
var client = Client.fromConnectionString(connectionString, Protocol);

var connectCallback = function (err) {
    if (err) {
        console.error('Could not connect: ' + err);
    } else {
        console.log('Client connected');

        client.onDeviceMethod('REBOOT', (request, response) => {  });
    }
};

client.open(connectCallback);
```

Doing a simply .on('message') handler works with no issues:

```
client.on('message', (msg) => { });
```

And I think my code is very similar to this sample here, but not MQTT:

https://github.com/Azure/azure-iot-sdk-node/blob/9649e1f37128ac2a4debaf08271ff273674322df/device/samples/dmpatterns_reboot_device.js

**Comment by sondreb** [comment]
Works if I change the protocol to MQTT, is the method calls not supported by AMQP?

So changing to this, works just fine:

```
var Protocol = require('azure-iot-device-mqtt').Mqtt;
```

**Comment by pierreca** [comment]
@sondreb Methods will be supported over AMQP in the coming weeks. We have it working in a limited private preview and are ironing the last wrinkles before we ship it publicly.

Are you unblocked with MQTT or do you require AMQP?

**Comment by sondreb** [comment]
That's a fairly undocumented thing? I was not able to see any information that methods was not supported  for AMQP and the SDK fails to give any proper warning ;-)

I just figured AMQP was better for my needs, but I can use MQTT for now without any problems. Thanks!
