### ISSUE TITLE
Doc: provisioning tools command args

### ISSUE THREAD

**Issue by lordbah** [Azure/azure-iot-sdk-node#525]
# Context
- **OS and version used:** <VERSION>Windows 10 
- **Node.js version:** <VERSION>8.11.4 
- **npm version:** <VERSION>6.8.0 
- **list of installed packages:** <VERSION>N/A, doc bug 
- **cloned repo:** <VERSION>2019-2-6-21-ge2a5bb43 

# Description of the issue:

provisioning/tools/readme.md says
`pass the "intermediate" command`
and
`pass the "device" command`
but the example below each shows the "root" command being passed
`F:\repos\node\provisioning\tools>node create_test_cert.js root "Intermediate CA 1" "My Test Root Certificate"` 
# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by anthonyvercolano** [comment]
#527

**Comment by anthonyvercolano** [comment]
Fixed.  Thank you.  In next release.

**Comment by az-iot-builder-01** [comment]
@lordbah, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
