### ISSUE TITLE
RegistrationClient doesn't expose setProvisioningPayload function (Typescript)

### ISSUE THREAD

**Issue by paolerm** [Azure/azure-iot-sdk-node#530]
```
import { Http as Transport } from 'azure-iot-provisioning-device-http';
import { SymmetricKeySecurityClient } from 'azure-iot-security-symmetric-key';
import { ProvisioningDeviceClient } from 'azure-iot-provisioning-device';
const transport = new Transport();

const securityClient = new SymmetricKeySecurityClient('<REGISTRATION_ID>', '<SYMMETRIC_KEY>');
const deviceClient = ProvisioningDeviceClient.create('global.azure-devices-provisioning.net', '<SCOPE_ID>', transport, securityClient);
(deviceClient as any).setProvisioningPayload({ ... });
```

I cannot call `deviceClient.setProvisioningPayload` because `ProvisioningDeviceClient.create` returns a `RegistrationClient `object but this interface doesn't expose `setProvisioningPayload `function.

I'm currently using these library versions:
```
"azure-iot-provisioning-device": "^1.5.5",
"azure-iot-provisioning-device-http": "^1.5.5",
"azure-iot-security-symmetric-key": "^1.5.5",
```

**Comment by anthonyvercolano** [comment]
#532

**Comment by anthonyvercolano** [comment]
Fix checked in.  Release on Monday.

**Comment by anthonyvercolano** [comment]
Released

**Comment by az-iot-builder-01** [comment]
@paolerm, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
