### ISSUE TITLE
Signing certificate info did not match chain elements

### ISSUE THREAD

**Issue by raamanihilent** [Azure/azure-iot-sdk-node#532]
# Context

# Description of the issue:

I am trying auto provisioning using Group enrollments

I have used openssl to create root certificate with common name as group id , uploaded it in DPS, have it verified. Using the same certificate from the registration_x509.js, running in to errors.

# Code sample exhibiting the issue:
register_x509.js

# Console log of the issue:
error registering device: UnauthorizedError: Error: {"errorCode":401002,"trackingId":"74b63f1b-3322-494c-813f-7a7bdb70a434","message":"Signing certificate info did not match chain elements","timestampUtc":"2019-04-11T15:04:33.3514759Z"}

**Comment by anthonyvercolano** [comment]
The statement: "Using the same certificate from the registration_x509.js, running in to errors."

Are you saying that the same certificate that you placed in the group enrollment is the one you are using  here in register_x509.js?
```
var deviceCert = {
  cert: fs.readFileSync('[cert filename]').toString(),
  key: fs.readFileSync('[key filename]').toString()
};
```

**Comment by anthonyvercolano** [comment]
Also, would you please supply the openssl command that you used to create the root cert? (Please no identifying info.)

**Comment by raamanihilent** [comment]
I am currently trying it via the nodejs tool - here are my commands
node create_test_cert.js root group1
node create_test_cert.js intermediate group1int group1
node create_test_cert.js device group1intdevices group1int group1

I am able to verify the certificate in DPS.

var deviceCert = {
  cert: fs.readFileSync('group1intdevices_fullchain.pem').toString(),
  key: fs.readFileSync('group1intdevices_key.pem').toString()
};

error is 

error registering device: UnauthorizedError: Error: {"errorCode":401002,"trackingId":"ae3bb3c5-e32e-4bd6-bf53-4d6b10a557df","message":"Unauthorized","timestampUtc":"2019-04-11T17:40:01.1928971Z"}

**Comment by anthonyvercolano** [comment]
Which certificate did you verify?  I verified the cert group1 in your example above.
When I created the enrollment group in the portal.  group1  is the certificate I referred to in the enrollment.
I then successfully registered the device group1intdevices.

**Comment by raamanihilent** [comment]
Thanks anthony. 
root certificate

**Comment by anthonyvercolano** [comment]
I believe you used the common name for the group as the registrationId.

**Comment by anthonyvercolano** [comment]
In this case it *should* have been the name group1intdevices as opposed to group1.

**Comment by anthonyvercolano** [comment]
Wrong link above.

But, since I'm here, I'm inclined to say this should be closed as a programming error.
Your thoughts?

**Comment by raamanihilent** [comment]
Thank you and that worked. 
For others here is the reference code 

var registrationId = 'group1intdevices';
var deviceCert = {
  cert: fs.readFileSync('group1intdevices_fullchain.pem').toString(),
  key: fs.readFileSync('group1intdevices_key.pem').toString()
};

Thank you again.

**Comment by raamanihilent** [comment]
Thanks @ anthonyvercolano
Very timely and appreciate the help

**Comment by az-iot-builder-01** [comment]
@raamanihilent, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
