### ISSUE TITLE
Mobile ISP kill idle connections - keepalive

### ISSUE THREAD

**Issue by bragma** [Azure/azure-iot-sdk-node#537]
# Description of the issue:
Currently mqtt transport has a default keepalive of 3 minutes. While this can be ok for detecting dropped connections, it may not be enough to keep a connection alive since mobile operators kill idle connections with aggressive timeouts. Currently I tried both Vodafone and TIM and verified the problem, while Wind seems to have no issues.
The result is that connection is continuously dropped, detected as disconnected and reconnected.
As it is, cloud-2-device do not work.

I've tried to lower the keepalive value but it seems to me is not possible. setOptions does not allow it. Am I correct?

**Comment by YoDaMa** [comment]
This is an update to our progress on this enhancement: 

We currently don't have any way to adjust the keepalive value. This seems to be a reasonable request for an enhancement, so we will be adding this to the backlog.

**Comment by anthonyvercolano** [comment]
Released

**Comment by az-iot-builder-01** [comment]
@bragma, @YoDaMa, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
