### ISSUE TITLE
ErrorCode:IotHubUnauthorizedAccess;Unauthorized seen on embedded target board

### ISSUE THREAD

**Issue by barak19622** [Azure/azure-iot-sdk-node#54]
# Context
- **OS and version used:** Embedded board having a ARM7 processor, running Linux 3.14.52.

- **Node.js version:** v6.11.0

- **npm version:** 3.10.10

- **list of installed packages:** npm list
createdeviceidentity@1.0.0 /opt//createdeviceidentity
`-- azure-iothub@1.1.11
  +-- azure-iot-amqp-base@1.1.9
  | +-- amqp10@3.5.0
  | | +-- bl@1.2.1
  | | | `-- readable-stream@2.3.2
  | | |   +-- core-util-is@1.0.2
  | | |   +-- inherits@2.0.3
  | | |   +-- isarray@1.0.0
  | | |   +-- process-nextick-args@1.0.7
  | | |   +-- safe-buffer@5.1.1
  | | |   +-- string_decoder@1.0.3
  | | |   `-- util-deprecate@1.0.2
  | | +-- buffer-builder@0.2.0
  | | +-- node-int64@0.4.0
  | | `-- stately.js@1.3.0
  | +-- amqp10-transport-ws@0.0.5
  | | `-- nodejs-websocket@1.7.1
  | +-- bluebird@3.5.0
  | `-- uuid@3.1.0
  +-- azure-iot-common@1.1.8
  | `-- crypto@0.0.3
  +-- azure-iot-http-base@1.1.8
  +-- debug@2.6.8
  | `-- ms@2.0.0
  +-- lodash@4.17.4
  `-- uuid@2.0.3

- **cloned repo:** No, not a cloned repo.

# Description of the issue:
Ref: https://docs.microsoft.com/en-gb/azure/iot-hub/iot-hub-node-node-getstarted

I followed the steps detailed above in the URL (for node.js) and successfully ran it on my Ubuntu PC. The usage counter on my Azure portal also incremented. However, when I tried to follow the same steps on my embedded ARM target board running Linux (kernel 3.14.52), Step 1 is failing. 

When I run 'node CreateDeviceIdentity.js', I'm getting the following error: "ErrorCode:IotHubUnauthorizedAccess;Unauthorized". 

My Connection string is like this: 'HostName=<name>.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=<key>'
The ShareAccessKey value is the same used on my Ubuntu Host PC (and works there). Additionally, when I tried using 'iothub-explorer get <device_id> --connectionString' on my host PC, it spurts out many field values (device Id, generationId etc) but on my target board, I get the response as 'Error: UnauthorizedError: Unauthorized'. This is a secondary confirmation of the issue at hand. How to fix this issue? 

# Code sample exhibiting the issue:

# Console log of the issue:
iothub-explorer get <device_id> --connectionString

Error: UnauthorizedError: Unauthorized <-----THIS IS THE ERROR

**Comment by tameraw** [comment]
@barak19622 - Can you make sure the device clock is set correctly? The SDK will generate the SASToken with an expiry time based on your clock.

**Comment by barak19622** [comment]
I tried your suggestion tameraw. Thanks, it worked !!!
The system clock was the root cause. I'm able to simulate the situation correctly now, appreciate your support.

**Comment by barak19622** [comment]
Closing issue now.
