### ISSUE TITLE
Invalid Certificate Error

### ISSUE THREAD

**Issue by raamanihilent** [Azure/azure-iot-sdk-node#547]
# Description of the issue:
Not sure if it is an issue. Reaching out for help.

Trying out the samples.
Testing Individual enrollment with x509
Here is a scenario i am testing in the manufacturing process.
{ Company - Manufacturer - Device} 

node create_test_cert.js root <device_name>
node create_test_cert.js intermediate manufacturer <device_name>
node create_test_cert.js device device1 manufacturer <device_name>

I have uploaded the root certificate in DPS Individual Enrollment and could confirm that the device is registered.

in the register_x509.js I am calling using

var deviceCert = {
  cert: fs.readFileSync('device1_fullchain.pem').toString(),
  key: fs.readFileSync('device1_key.pem').toString()
};

# Console log of the issue:
errorCode":401002, "message":"Invalid certificate

**Comment by raamanihilent** [comment]
Please let me know if need to share any additional information?

**Comment by anthonyvercolano** [comment]
Sorry, kind of heads down on a particular (provisioning) feature.  I haven't had the chance to repro your issue.  My suspicion:

You should probably only use the leaf cert.  If doing an individual enrollment, the only thing needed would be the leaf.  Didn't even need to go through the verification for a root.

**Comment by raamanihilent** [comment]
node create_test_cert.js root <device_name> ---> ROOT
node create_test_cert.js intermediate manufacturer <device_name> --> INTERMEDIATE
node create_test_cert.js device intermediate manufacturer <device_name> --> LEAF Device certificate

I used the above steps to create leaf certificate. Should i follow a different procedure?

**Comment by anthonyvercolano** [comment]
node create_test_cert.js root "contoso.com"
node create_test_cert.js intermediate "redmondSite" "contoso.com"
node create_test_cert.js device "bestdeviceever" "redmondSite"

Then just use bestdeviceever_cert.pem and bestdeviceever_key.pem in the readFileSync.

**Comment by anthonyvercolano** [comment]
[Readme for provisioning tools](https://github.com/Azure/azure-iot-sdk-node/blob/master/provisioning/tools/readme.md)

and to repeat, these tools should NOT be used for production.  They are only there for helping understand certs.

**Comment by raamanihilent** [comment]
Thanks Anthony. Very helpful.

I followed the above recommendation and it worked. 

node create_test_cert.js root "xxxroot"
node create_test_cert.js intermediate "xxxxinter" "xxxroot"
node create_test_cert.js device "xxxdevice" "xxxinter"

Upload the Device certificate in to Azure DPS. (Common name of the device(leaf) certificate is used as the device id). Use the leaf cert/leaf key in the register_x509.js to call the Azure Global Device Provisioning end point.

Thanks again.
I am closing the issue now.

**Comment by az-iot-builder-01** [comment]
@raamanihilent, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
