### ISSUE TITLE
bad server cert test is timing out.

### ISSUE THREAD

**Issue by anthonyvercolano** [Azure/azure-iot-sdk-node#558]
running the bad server test gets a timeout on amqp.

**Comment by YoDaMa** [comment]
There are no plans in the backlog to address the flakiness of this test any time soon. Therefore we will close this issue.

**Comment by az-iot-builder-01** [comment]
@YoDaMa, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
