### ISSUE TITLE
Will Device SDK for Node be compatible for iOS devices

### ISSUE THREAD

**Issue by jkriba** [Azure/azure-iot-sdk-node#56]
# Description of the issue:
Kindly consider this as a technical question. Please let us know if the Device SDK for Node is compatible with iOS 10 devices by cross compiling, since we need to wrap the Object C client application to establish communication with the Azure IoT Hub.

Is there any workaround possible or any alternate provision given by Microsoft to develop an Device client application from iOS environment other than the PCL. thanks

**Comment by olivierbloch** [comment]
Hi @jkriba 
We are NOT considering cross compiling from node to C. however we are planning to have our C SDK support iOS. This discussion should be tracked in the C SDK repo's issue [#173](https://github.com/Azure/azure-iot-sdk-c/issues/173). Closing this one
