### ISSUE TITLE
Bug using Device.Client#close() as a Promise

### ISSUE THREAD

**Issue by kartben** [Azure/azure-iot-sdk-node#560]
in azure-iot-device 1.9.9, there is a bug/typo in `Device.Client#close()`'s call to `azure-iot-common#callbackToPromise` (wrong callback being passed), making it impossible to "await" a device client's `close()`

**Comment by YoDaMa** [comment]
Release 2019-07-17 includes this bugfix.

**Comment by az-iot-builder-01** [comment]
@YoDaMa, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
