### ISSUE TITLE
After edge device is created, it is sometimes not listed in IoT Hub Query 

### ISSUE THREAD

**Issue by formulahendry** [Azure/azure-iot-sdk-node#571]
# Context
- **OS and version used:** Windows 10
- **Node.js version:** 10.1
- **npm version:** 6.5
- **list of installed packages:** azure-iothub@1.9.9

# Description of the issue:

1. create an edge device
2. IoT Hub Query to query edge device list immediately
3. sometimes, it is not listed.

# Code sample exhibiting the issue:

```javascript
const iothub = require('azure-iothub');
const registry = iothub.Registry.fromConnectionString("...");
const deviceInfo = {
    deviceId: "_00" + Math.random(),
    capabilities: {
        iotEdge: true,
    }
};

async function main() {
    const device = await registry.create(deviceInfo);
    const deviceId = device.responseBody.deviceId;
    console.log(deviceId);
    const query = registry.createQuery("SELECT * FROM DEVICES where capabilities.iotEdge=true");
    const twins= ((await query.nextAsTwin())).result;
    const isEdgeDevice = twins.some(twin => twin.deviceId === deviceId)
    console.log(isEdgeDevice);
}

main();
```

# Console log of the issue:

Run above code for 10 times, about half of the times, the `isEdgeDevice` is `false`
```
> node "e:\Try\Test\createEdgeDevice.js"
_000.46408906734541433
false
```

**Comment by pierreca** [comment]
@formulahendry 
A few quick questions:
- if you wait a few seconds, does the device end up listed?
- do you get any error on device creation? or do you get a 201 Created response with the correct device description every time?

**Comment by formulahendry** [comment]
Hi @pierreca 

- if you wait a few seconds, does the device end up listed?  **Yes**
- do you get any error on device creation? or do you get a 201 Created response with the correct device description every time? **No, there is no error.**

**Comment by pierreca** [comment]
@formulahendry in that case, it sounds like the eventual consistency behavior of the service. it sometimes take a small amount of time for the query store to be populated with newly created identities. There's nothing the SDK can do about this unfortunately, and the correct behavior is to retry the query after a few seconds.

**Comment by az-iot-builder-01** [comment]
@formulahendry, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
