### ISSUE TITLE
Unable to use AMQP over web socket with HTTPS proxy due to AmqpTransportOptions missing webSocketAgent property

### ISSUE THREAD

**Issue by dimiboi** [Azure/azure-iot-sdk-node#574]
I am unable to use Azure IoT Hub Device SDK with an explicit corporate HTTPS proxy when using AMQP over web socket to connect to IoT Hub.

[`AmqpTransportOptions`](https://github.com/Azure/azure-iot-sdk-node/blob/734bd35f0a48b519ee4de233d1762e7ef2d4521c/device/core/src/interfaces.ts#L18) interface is missing `webSocketAgent` property, which is present in e.g. [`MqttTransportOptions`](https://github.com/Azure/azure-iot-sdk-node/blob/734bd35f0a48b519ee4de233d1762e7ef2d4521c/device/core/src/interfaces.ts#L79) interface. As a result, it is not possible to specify an HTTPS proxy agent for the web socket required to establish IoT Hub connection via HTTPS proxy.

Here is the [user voice idea](https://feedback.azure.com/forums/321918-azure-iot/suggestions/38023516-use-amqp-over-web-socket-connection-to-iot-hub-wit).

**Comment by YoDaMa** [comment]
@dimiboi thanks for filing this request for an enhancement to the SDK. We'll take a look to assess where we have the resources to take action on this enhancement. Of course, we also accept outside PRs.

**Comment by pierreca** [comment]
I believe this was adressed with https://github.com/Azure/azure-iot-sdk-node/releases/tag/2019-07-17
Closing. as resolved. Thanks for your contribution!

**Comment by az-iot-builder-01** [comment]
@YoDaMa, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
