### ISSUE TITLE
azure-iot-common/lib/results.d.ts compilation error with TypeScript 2.4

### ISSUE THREAD

**Issue by kurtb** [Azure/azure-iot-sdk-node#58]
# Context
- **OS and version used:** OS X Sierra
- **Node.js version:** 7.7.3
- **npm version:** 4.1.2
- **list of installed packages:** azure-iot-common
- **cloned repo:** private repo

# Description of the issue:
azure-iot-common/lib/results.d.ts(15,22): error TS2559: Type 'MessageEnqueued' has no properties in common with type 'Result'.
...
Same error for all derived classes in results.d.ts

**Comment by tameraw** [comment]
Fix checked in.
https://github.com/Azure/azure-iot-sdk-node/pull/57
