### ISSUE TITLE
Release note title is wrong...

### ISSUE THREAD

**Issue by wmmihaa** [Azure/azure-iot-sdk-node#588]
[Azure IoT SDKs for Node.js v1.9.10](https://github.com/Azure/azure-iot-sdk-node/releases/tag/2019-07-17) should be **Azure IoT SDKs for Node.js v1.10.0**

**Comment by YoDaMa** [comment]
@wmmihaa good catch. Updated.

**Comment by az-iot-builder-01** [comment]
@YoDaMa, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
