### ISSUE TITLE
messages lost when disconnected with mqtt or amqp

### ISSUE THREAD

**Issue by ksaye** [Azure/azure-iot-sdk-node#59]
OS:  Ubuntu 16.04.1
Node: v4.2.6
relevant packages:

├─┬ azure-iot-device-amqp@1.1.15
│ ├─┬ azure-iot-amqp-base@1.1.10
│ ├─┬ azure-iot-common@1.1.9
│ ├─┬ azure-iot-device@1.1.15
│ │ ├── azure-iot-http-base@1.1.9
│ │ ├─┬ azure-storage@2.2.1
└─┬ azure-iot-device-mqtt@1.1.15

I need to support a device being disconnected for hours or days at a time.  Reading the delay in the "ondisconnect" callback , how can I accurately detect if we have lost connection and "queue" messages?

I am testing with the sample client: https://github.com/Azure/azure-iot-sdk-node/blob/master/device/samples/simple_sample_device.js

I do see the disconnect is detected in ~6 minutes after I disconnect the ethernet.

In that sample code, removeAllListners and open is called on disconnect.  In my case, this loses all the queued messages and because the connection is still down, I get a failed to connect to IoT Hub and error out.

How can I set an indefinite retry and not lose messages?

**Comment by anthonyvercolano** [comment]
It is fairly OS dependent as to how long it takes to notice that the network is disconnected.  Typically this take longer on linux.

In a future release (sometime before Oct 31) we will be aligning the node sdk to have the same sort of reconnection/retry capabilities that you can now find in the C SDK.

**Comment by pierreca** [comment]
@ksaye we've introduced a retry logic that should solve your issue in the latest release: 
- https://github.com/Azure/azure-iot-sdk-node/releases/tag/2017-10-24
- https://www.npmjs.com/package/azure-iot-device (`azure-iot-device@1.2.0`)

Please update to the latest version of the SDK and let us know if you're still seeing the issue!
