### ISSUE TITLE
create_test_cert.js tool error

### ISSUE THREAD

**Issue by stevebus** [Azure/azure-iot-sdk-node#593]
trying to run the create_test_cert.js script from the provisioning/tools folder (after doing npm install) gives the error below.   does it require a specific (undocumented) version of Node?

# Context
windows subsystem for linux

# Description of the issue:
trying to run the create_test_cert js script results in the following error..

node create_test_cert.js
/home/stevebus/dpstest/certtools/node_modules/pem/lib/pem.js:9
const { promisify } = require('es6-promisify')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/stevebus/dpstest/certtools/create_test_cert.js:7:11)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by pierreca** [comment]
it looks like the error is not with our code but within one of the dependencies, the pem module. is it possible that you're running a very old version of node that doesn't support this syntax?

LTS version is 10, current is 12, anything older than 8 should be updated. (https://nodejs.org/en/about/releases/)

**Comment by stevebus** [comment]
Frak...  I thought I had checked that and was running 12.7.0.  Turns out I entered the 'node --version' command in the wrong terminal  (I can, however, report that my totally unrelated Azure Ubuntu VM is running 12.7.0  :-) ).

I upgraded my WSL box to 12.7.0 and it's all good.  Thanks for the quick response and sorry about the spam.

closing....

**Comment by az-iot-builder-01** [comment]
@stevebus, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
