### ISSUE TITLE
Azure IoT SDKs for Node.js v1.11.0 packages are not available in npm

### ISSUE THREAD

**Issue by dimiboi** [Azure/azure-iot-sdk-node#599]
```
> npm find azure-iot-device
NAME                      | DESCRIPTION          | AUTHOR          | DATE       | VERSION  | KEYWORDS
azure-iot-device          | Azure IoT device SDK | =anthonyvercol… | 2019-07-17 | 1.10.0   |
azure-iot-common          | Common components…   | =anthonyvercol… | 2019-07-17 | 1.10.0   |
azure-iot-device-mqtt     | MQTT transport for…  | =anthonyvercol… | 2019-07-17 | 1.10.0   |
azure-iot-device-amqp     | AMQP transport for…  | =anthonyvercol… | 2019-07-17 | 1.10.0   |
azure-iot-device-http     | HTTP transport for…  | =anthonyvercol… | 2019-07-17 | 1.10.0   |
```

**Comment by YoDaMa** [comment]
Thanks for pointing this out. It looks like there is an issue in the partner release script. I'm investigating.

**Comment by YoDaMa** [comment]
Looks like the packages are now officially published now.

**Comment by YoDaMa** [comment]
I'm going to close this now since it's been validated. `npm find azure-iot-device` will still only show the 1.10.0 for a while but that's an issue with npm's find. On npmjs you can see the package has now been published:  https://www.npmjs.com/package/azure-iot-device

**Comment by az-iot-builder-01** [comment]
@YoDaMa, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by dimiboi** [comment]
@YoDaMa, thank you for a prompt resolution.
