### ISSUE TITLE
IOT connection will be interrupt after 45 min

### ISSUE THREAD

**Issue by kuomingwu** [Azure/azure-iot-sdk-node#60]
[Issue describe]
IOT connection which create from nodejs will be interrupt after 45 min 

[NPM]
c:\Users\danilai\Desktop\NodejsConsoleApp1\NodejsConsoleApp1>npm ls
nodejs-console-app1@0.0.0 c:\Users\danilai\Desktop\NodejsConsoleApp1\NodejsConsoleApp1
+-- azure-iot-device@1.1.15
| +-- azure-iot-common@1.1.9
| | `-- crypto@0.0.3
| +-- azure-iot-http-base@1.1.9
| +-- azure-storage@2.2.1
| | +-- browserify-mime@1.2.9
| | +-- extend@1.2.1
| | +-- json-edm-parser@0.1.2
| | | `-- jsonparse@1.2.0
| | +-- md5.js@1.3.4
| | | `-- hash-base@3.0.4
| | |   `-- safe-buffer@5.1.1
| | +-- readable-stream@2.0.6
| | | +-- core-util-is@1.0.2
| | | +-- isarray@1.0.0
| | | +-- process-nextick-args@1.0.7
| | | +-- string_decoder@0.10.31
| | | `-- util-deprecate@1.0.2
| | +-- request@2.74.0
| | | +-- aws-sign2@0.6.0
| | | +-- aws4@1.6.0
| | | +-- bl@1.1.2
| | | +-- caseless@0.11.0
| | | +-- combined-stream@1.0.5
| | | | `-- delayed-stream@1.0.0
| | | +-- extend@3.0.1
| | | +-- forever-agent@0.6.1
| | | +-- form-data@1.0.1
| | | | `-- async@2.5.0
| | | +-- har-validator@2.0.6
| | | | +-- chalk@1.1.3
| | | | | +-- ansi-styles@2.2.1
| | | | | +-- escape-string-regexp@1.0.5
| | | | | +-- has-ansi@2.0.0
| | | | | | `-- ansi-regex@2.1.1
| | | | | +-- strip-ansi@3.0.1
| | | | | `-- supports-color@2.0.0
| | | | +-- commander@2.11.0
| | | | +-- is-my-json-valid@2.16.0
| | | | | +-- generate-function@2.0.0
| | | | | +-- generate-object-property@1.2.0
| | | | | | `-- is-property@1.0.2
| | | | | `-- jsonpointer@4.0.1
| | | | `-- pinkie-promise@2.0.1
| | | |   `-- pinkie@2.0.4
| | | +-- hawk@3.1.3
| | | | +-- boom@2.10.1
| | | | +-- cryptiles@2.0.5
| | | | +-- hoek@2.16.3
| | | | `-- sntp@1.0.9
| | | +-- http-signature@1.1.1
| | | | +-- assert-plus@0.2.0
| | | | +-- jsprim@1.4.0
| | | | | +-- assert-plus@1.0.0
| | | | | +-- extsprintf@1.0.2
| | | | | +-- json-schema@0.2.3
| | | | | `-- verror@1.3.6
| | | | `-- sshpk@1.13.1
| | | |   +-- asn1@0.2.3
| | | |   +-- assert-plus@1.0.0
| | | |   +-- bcrypt-pbkdf@1.0.1
| | | |   +-- dashdash@1.14.1
| | | |   | `-- assert-plus@1.0.0
| | | |   +-- ecc-jsbn@0.1.1
| | | |   +-- getpass@0.1.7
| | | |   | `-- assert-plus@1.0.0
| | | |   +-- jsbn@0.1.1
| | | |   `-- tweetnacl@0.14.5
| | | +-- is-typedarray@1.0.0
| | | +-- isstream@0.1.2
| | | +-- json-stringify-safe@5.0.1
| | | +-- mime-types@2.1.15
| | | | `-- mime-db@1.27.0
| | | +-- node-uuid@1.4.8
| | | +-- oauth-sign@0.8.2
| | | +-- qs@6.2.3
| | | +-- stringstream@0.0.5
| | | +-- tough-cookie@2.3.2
| | | | `-- punycode@1.4.1
| | | `-- tunnel-agent@0.4.3
| | +-- underscore@1.8.3
| | +-- validator@3.35.0
| | +-- xml2js@0.2.7
| | | `-- sax@0.5.2
| | `-- xmlbuilder@0.4.3
| +-- debug@2.6.8
| | `-- ms@2.0.0
| +-- lodash@4.17.4
| +-- machina@2.0.0
| | `-- lodash@3.10.1
| `-- traverse@0.6.6
+-- azure-iot-device-amqp@1.1.15
| +-- azure-iot-amqp-base@1.1.10
| | +-- amqp10@3.5.0
| | | +-- buffer-builder@0.2.0
| | | +-- node-int64@0.4.0
| | | `-- stately.js@1.3.0
| | +-- amqp10-transport-ws@0.0.5
| | | `-- nodejs-websocket@1.7.1
| | `-- bluebird@3.5.0
| `-- uuid@3.1.0
+-- azure-iot-device-http@1.1.15
| `-- node-crontab@0.0.8
|   `-- cron-parser@0.3.6
`-- azure-iot-device-mqtt@1.1.15
  `-- mqtt@1.14.1
    +-- commist@1.0.0
    | `-- leven@1.0.2
    +-- concat-stream@1.6.0
    | +-- readable-stream@2.3.3
    | | `-- string_decoder@1.0.3
    | `-- typedarray@0.0.6
    +-- end-of-stream@1.4.0
    | `-- once@1.4.0
    |   `-- wrappy@1.0.2
    +-- help-me@1.1.0
    | +-- callback-stream@1.1.0
    | +-- glob-stream@6.1.0
    | | +-- extend@3.0.1
    | | +-- glob@7.1.2
    | | | +-- fs.realpath@1.0.0
    | | | +-- inflight@1.0.6
    | | | +-- minimatch@3.0.4
    | | | | `-- brace-expansion@1.1.8
    | | | |   +-- balanced-match@1.0.0
    | | | |   `-- concat-map@0.0.1
    | | | `-- path-is-absolute@1.0.1
    | | +-- glob-parent@3.1.0
    | | | +-- is-glob@3.1.0
    | | | | `-- is-extglob@2.1.1
    | | | `-- path-dirname@1.0.2
    | | +-- is-negated-glob@1.0.0
    | | +-- ordered-read-streams@1.0.1
    | | +-- pumpify@1.3.5
    | | +-- readable-stream@2.3.3
    | | | `-- string_decoder@1.0.3
    | | +-- remove-trailing-separator@1.0.2
    | | +-- to-absolute-glob@2.0.1
    | | | +-- extend-shallow@2.0.1
    | | | | `-- is-extendable@0.1.1
    | | | `-- is-absolute@0.2.6
    | | |   +-- is-relative@0.2.1
    | | |   | `-- is-unc-path@0.1.2
    | | |   |   `-- unc-path-regex@0.1.2
    | | |   `-- is-windows@0.2.0
    | | `-- unique-stream@2.2.1
    | |   +-- json-stable-stringify@1.0.1
    | |   | `-- jsonify@0.0.0
    | |   `-- through2-filter@2.0.0
    | `-- through2@2.0.3
    |   `-- readable-stream@2.3.3
    |     `-- string_decoder@1.0.3
    +-- inherits@2.0.3
    +-- minimist@1.2.0
    +-- mqtt-connection@2.1.1
    | +-- reduplexer@1.1.0
    | | `-- readable-stream@1.0.34
    | |   `-- isarray@0.0.1
    | `-- through2@0.6.5
    |   `-- readable-stream@1.0.34
    |     `-- isarray@0.0.1
    +-- mqtt-packet@3.4.8
    | `-- bl@0.9.5
    |   `-- readable-stream@1.0.34
    |     `-- isarray@0.0.1
    +-- pump@1.0.2
    +-- readable-stream@1.0.34
    | `-- isarray@0.0.1
    +-- reinterval@1.1.0
    +-- split2@2.1.1
    +-- websocket-stream@3.3.3
    | +-- duplexify@3.5.0
    | | +-- end-of-stream@1.0.0
    | | | `-- once@1.3.3
    | | `-- stream-shift@1.0.0
    | `-- ws@1.1.4
    |   +-- options@0.0.6
    |   `-- ultron@1.0.2
    `-- xtend@4.0.1

[Description of the issue]
1. We create IOT connection via nodejs and disable network then recovery connection, the connection will  be will be interrupted after 45 min and have exception as below : 

[IoT Hub Device] Client (45-sas) connected

{"type":"Alert","message":"IoT Hub device connected","device_id":"45-sas"}
{"sensor_id":234,"time":"2017-07-10T10:20:51.285Z"}
[IoT Hub Device] IoT Hub disconnected
[IoT Hub Device] Connection closed
[IoT Hub Device] Message error: Error: AMQP Transport: Could not send
[IoT Hub Device] Connection closed
Connect IoT Hub
[IoT Hub Device] Could not connect: Error: AMQP Transport: Could not connect
Connect IoT Hub
[IoT Hub Device] Could not connect: Error: AMQP Transport: Could not connect
Connect IoT Hub
[IoT Hub Device] Could not connect: Error: AMQP Transport: Could not connect
Connect IoT Hub
[IoT Hub Device] Could not connect: Error: AMQP Transport: Could not connect
Connect IoT Hub
[IoT Hub Device] Client (45-sas) connected

{"type":"Alert","message":"IoT Hub device connected","device_id":"45-sas"}
{"sensor_id":234,"time":"2017-07-10T10:22:51.300Z"}
{"sensor_id":234,"time":"2017-07-10T10:23:51.319Z"}
{"sensor_id":234,"time":"2017-07-10T10:24:51.336Z"}
{"sensor_id":234,"time":"2017-07-10T10:25:51.340Z"}
{"sensor_id":234,"time":"2017-07-10T10:26:51.358Z"}
{"sensor_id":234,"time":"2017-07-10T10:27:51.374Z"}
{"sensor_id":234,"time":"2017-07-10T10:28:51.392Z"}
{"sensor_id":234,"time":"2017-07-10T10:29:51.410Z"}
{"sensor_id":234,"time":"2017-07-10T10:30:51.428Z"}
{"sensor_id":234,"time":"2017-07-10T10:31:51.446Z"}
{"sensor_id":234,"time":"2017-07-10T10:32:51.463Z"}
{"sensor_id":234,"time":"2017-07-10T10:33:51.483Z"}
{"sensor_id":234,"time":"2017-07-10T10:34:51.505Z"}
{"sensor_id":234,"time":"2017-07-10T10:35:51.525Z"}
{"sensor_id":234,"time":"2017-07-10T10:36:51.530Z"}
{"sensor_id":234,"time":"2017-07-10T10:37:51.548Z"}
{"sensor_id":234,"time":"2017-07-10T10:38:51.555Z"}
{"sensor_id":234,"time":"2017-07-10T10:39:51.564Z"}
{"sensor_id":234,"time":"2017-07-10T10:40:51.572Z"}
{"sensor_id":234,"time":"2017-07-10T10:41:51.575Z"}
{"sensor_id":234,"time":"2017-07-10T10:42:51.581Z"}
{"sensor_id":234,"time":"2017-07-10T10:43:51.587Z"}
{"sensor_id":234,"time":"2017-07-10T10:44:51.593Z"}
{"sensor_id":234,"time":"2017-07-10T10:45:51.599Z"}
{"sensor_id":234,"time":"2017-07-10T10:46:51.611Z"}
{"sensor_id":234,"time":"2017-07-10T10:47:51.624Z"}
{"sensor_id":234,"time":"2017-07-10T10:48:51.630Z"}
{"sensor_id":234,"time":"2017-07-10T10:49:51.637Z"}
{"sensor_id":234,"time":"2017-07-10T10:50:51.644Z"}
{"sensor_id":234,"time":"2017-07-10T10:51:51.648Z"}
{"sensor_id":234,"time":"2017-07-10T10:52:51.655Z"}
{"sensor_id":234,"time":"2017-07-10T10:53:51.662Z"}
{"sensor_id":234,"time":"2017-07-10T10:54:51.671Z"}
{"sensor_id":234,"time":"2017-07-10T10:55:51.677Z"}
{"sensor_id":234,"time":"2017-07-10T10:56:51.683Z"}
{"sensor_id":234,"time":"2017-07-10T10:57:51.690Z"}
{"sensor_id":234,"time":"2017-07-10T10:58:51.713Z"}
{"sensor_id":234,"time":"2017-07-10T10:59:51.721Z"}
{"sensor_id":234,"time":"2017-07-10T11:00:51.728Z"}
{"sensor_id":234,"time":"2017-07-10T11:01:51.735Z"}
{"sensor_id":234,"time":"2017-07-10T11:02:51.749Z"}
{"sensor_id":234,"time":"2017-07-10T11:03:51.752Z"}

**events.js:160
      throw er; // Unhandled 'error' event
      ^
NotConnectedError: Cannot putToken while disconnected.
    at Amqp.putToken (c:\Users\danilai\Desktop\NodejsConsoleApp1\NodejsConsoleApp1\node_modules\azure-iot-amqp-base\lib\amqp.js:485:50)
    at Amqp.updateSharedAccessSignature (c:\Users\danilai\Desktop\NodejsConsoleApp1\NodejsConsoleApp1\node_modules\azure-iot-device-amqp\lib\amqp.js:198:20)
    at constructor.updateSharedAccessSignature (c:\Users\danilai\Desktop\NodejsConsoleApp1\NodejsConsoleApp1\node_modules\azure-iot-device\lib\client.js:131:42)
    at constructor.handle (c:\Users\danilai\Desktop\NodejsConsoleApp1\NodejsConsoleApp1\node_modules\machina\lib\machina.js:613:25)
    at constructor.Fsm.(anonymous function) [as handle] (c:\Users\danilai\Desktop\NodejsConsoleApp1\NodejsConsoleApp1\node_modules\machina\lib\machina.js:466:63)
    at Client._renewSharedAccessSignature (c:\Users\danilai\Desktop\NodejsConsoleApp1\NodejsConsoleApp1\node_modules\azure-iot-device\lib\client.js:671:19)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)**
 
2. We create connection and the IOT server not received message after 45 min but no any exception on it

[Code sample exhibiting the issue]

'use strict';

var fs = require('fs');

global.g_State = { "iot_hub_device_connected": false };

var Client = require('azure-iot-device').Client;
var ConnectionString = require('azure-iot-device').ConnectionString;
var Message = require('azure-iot-device').Message;

var connectionStringParam = "*********************";
var connectionString = ConnectionString.parse(connectionStringParam);
var deviceId = connectionString.DeviceId;

//var Protocol = require('azure-iot-device-mqtt').Mqtt;
//var client = Client.fromConnectionString(connectionStringParam, Protocol);

var clientFromConnectionString = require('azure-iot-device-amqp').clientFromConnectionString;
// AMQP-specific factory function returns Client object from core package 
//var client = clientFromConnectionString(connectionStringParam);
var client;

// Configure the client to use X509 authentication if required by the connection string.
if (connectionString.x509) {
    // Read X.509 certificate and private key.
    // These files should be in the current folder and use the following naming convention:
    // [device name]-cert.pem and [device name]-key.pem, example: myraspberrypi-cert.pem
    var options = {
        cert: fs.readFileSync(path.join(__dirname, deviceId + '-cert.pem')).toString(),
        key: fs.readFileSync(path.join(__dirname, deviceId + '-key.pem')).toString()
    };

    client.setOptions(options);

    console.log('[Device] Using X.509 client certificate authentication');
}

global.logMsg = function (msg) {
    var obj = {};

    var date = new Date();
    obj['Time'] = date;
    obj['Source'] = "app.js";

    if (typeof msg == "string") {
        obj['Event'] = msg;
    }
    else if (typeof msg == "object") {
        obj = Object.assign(obj, msg);
    }

    //console.log(JSON.stringify(obj));

    // generate file name to log based on current time
    var year = date.getFullYear();

    var month = date.getMonth() + 1;
    month = (month < 10 ? "0" : "") + month;

    var day = date.getDate();
    day = (day < 10 ? "0" : "") + day;

    var strFile = year + "-" + month + "-" + day + ".log";

    //console.log(strFile);

    fs.appendFile(strFile, JSON.stringify(obj) + "\n", (err) => {
        if (err) console.log('Error: fail to write log');
    });

    //var hour = date.getHours();
    //hour = (hour < 10 ? "0" : "") + hour;

    //var min  = date.getMinutes();
    //min = (min < 10 ? "0" : "") + min;

    //var sec  = date.getSeconds();
    //sec = (sec < 10 ? "0" : "") + sec;

    //var strFile=g_Config.config_folder + year + "-" + month + "-" + day + " " + hour + ":" + min + ":" +sec+ ".log";
    //console.log(strFile);
}

global.logErr = function (msg) {
    var obj = {};
    obj['Error'] = msg;
    logMsg(obj);
}

global.logWarn = function (msg) {
    var obj = {};
    obj['Warning'] = msg;
    logMsg(obj);
}

// Start sending messages after getting connected to IoT Hub
function connectCallback(err) {
    if (err) {
        console.log('[IoT Hub Device] Could not connect: ' + err);
        logErr("Fail to connect IoT Hub Device: " + err);
    } else {
        console.log('[IoT Hub Device] Client (' + deviceId + ') connected\n');
        logMsg("IoT Hub Device (" + deviceId + ") connected");
        client.on('message', receiveMessageCallback);

        // Remind me: add IoT Hub disconnect event handler
        client.on('error', function (err) {
            console.log('[IoT Hub Device] IoT Hub unprocessed error' + err);
            logErr('[IoT Hub Device] IoT Hub unprocessed error' + err);
            //console.error(err.message);
        });

        client.on('disconnect', function () {
            console.log('[IoT Hub Device] IoT Hub disconnected');
            logErr('[IoT Hub Device] IoT Hub disconnected');
            client.removeAllListeners();
            client.close(closeConnectionCallback);
            g_State.iot_hub_device_connected = false;
            //client.open(connectCallback);
        });

        var msg = {};
        msg['type'] = "Alert";
        msg['message'] = "IoT Hub device connected";
        msg['device_id'] = deviceId;

        sendMessage(msg);

        g_State.iot_hub_device_connected = true;
    }
}

// send message to IoT Hub
// Note: should check g_State.iot_hub_device_connected before calling sendMessage()
global.sendMessage = function (sensor_data) {
    var message = new Message(JSON.stringify(sensor_data));

    console.log(message.getData());
    logMsg(message.getData());

    //if(g_State.iot_hub_device_connected)
    //{ // send message to IoT Hub
    client.sendEvent(message, sendMessageCallback);
    //}

}

function sendMessageCallback(err) {
    if (err) {
        logErr('[IoT Hub Device] Message error: ' + err.toString());
        console.log('[IoT Hub Device] Message error: ' + err.toString());

        client.close(closeConnectionCallback);
        g_State.iot_hub_device_connected = false;

    } else {
        // Blink once after successfully sending one message.
        //blinkLED();
    }

}

// called when receiving a message from IoT Hub
function receiveMessageCallback(msg) {

    g_State.last_iot_hub_heart_bit_RX_time = new Date();

    try {
        var msgBodyString = msg.getData().toString('utf-8');
        var msgBody = JSON.parse(msgBodyString);
    } catch (err) {
        logErr('[IoT Hub Device] Fail to parse message: ' + msgBodyString);
        console.log('[IoT Hub Device] Fail to parse message: ' + msgBodyString);
        return;
    }

    logMsg('[IoT Hub Device] Received message: ' + msgBodyString);
    console.log('[IoT Hub Device] Received message: ' + msgBodyString);

    // send message to sensor
    //processMessage(msgBody);

    client.complete(msg, completeMessageCallback);
}

// called when complete receiving a message
function completeMessageCallback(err) {
    if (err) {
        console.log('[Device] Complete message error: ' + err.toString());
        logErr('[Device] Complete message error: ' + err.toString());
    }

    // remind me: think if we have to process it
}

// called when IoT Hub connection is closed
function closeConnectionCallback(err) {
    if (err) {
        console.error('[Device] Close connection error: ' + err.message + '\n');
        logErr('[Device] Close connection error: ' + err.message + '\n');
    } else {
        console.log('[IoT Hub Device] Connection closed');
        logMsg('[IoT Hub Device] Connection closed');
    }
}

// Connect to IoT Hub and send messages via the callback.
//client.open(connectCallback);

// periodically check IoT Hub connection (check g_State.iot_hub_device_connected)
function checkAndConnectIotHub() {
    //console.log("Check IoT Hub connection");
    //logMsg("Check IoT Hub connection");
    if (!g_State.iot_hub_device_connected) {
        console.log("Connect IoT Hub");
        logMsg("Connect IoT Hub");
        client = clientFromConnectionString(connectionStringParam);
        client.open(connectCallback);
    }

    // check and connect periodically
    setTimeout(function () {
        checkAndConnectIotHub();
    }, 10 * 1000);
    //}, 600 * 1000);
}

// periodically send message
function sendMessagetoIotHub() {
    if (g_State.iot_hub_device_connected) {
        var msg = {};
        var now = new Date();
        msg['sensor_id'] = 234;
        msg['time'] = now;

        sendMessage(msg);
    }

    // check and connect periodically
    setTimeout(function () {
        sendMessagetoIotHub();
    }, 60 * 1000);
}

checkAndConnectIotHub();

sendMessagetoIotHub();

[Repro]
We use clientFromConnectionString or  Client.fromSharedAccessSignature(sas, Protocol) have same issue on it.

**Comment by anthonyvercolano** [comment]
Thank you.  The unhandled error will be fixed in a very up coming release.

**Comment by anthonyvercolano** [comment]
Just to clarify a bit.  Your application starts,  It sends.  You cause a disconnect.  Then do NOT try to reconnect.  After 45 minutes (and still not trying to reconnect), you get the unhandled error? This is your scenario?

**Comment by kuomingwu** [comment]
@anthonyvercolano Thanks for your attention for this issue, we have two scenario : 
1. When the connection seems normal, we try to disable the NIC for testing and the network was interrupted, we get the information from connection :   
[IoT Hub Device] Could not connect: Error: AMQP Transport: Could not connect
Connect IoT Hub
then we try to enable the NIC and the IOT connection had been recovery, but after more then 45 min, we get the exception and have error such as 

throw er; // Unhandled 'error' event
^
NotConnectedError: Cannot putToken while disconnected.
at Amqp.putToken (c:\Users\danilai\Desktop\NodejsConsoleApp1\NodejsConsoleApp1\node_modules\azure-iot-amqp-base\lib\amqp.js:485:50)
at Amqp.updateSharedAccessSignature (c:\Users\danilai\Desktop\NodejsConsoleApp1\NodejsConsoleApp1\node_modules\azure-iot-device-amqp\lib\amqp.js:198:20)
at constructor.updateSharedAccessSignature (c:\Users\danilai\Desktop\NodejsConsoleApp1\NodejsConsoleApp1\node_modules\azure-iot-device\lib\client.js:131:42)
at constructor.handle (c:\Users\danilai\Desktop\NodejsConsoleApp1\NodejsConsoleApp1\node_modules\machina\lib\machina.js:613:25)
at constructor.Fsm.(anonymous function) [as handle] (c:\Users\danilai\Desktop\NodejsConsoleApp1\NodejsConsoleApp1\node_modules\machina\lib\machina.js:466:63)
at Client._renewSharedAccessSignature (c:\Users\danilai\Desktop\NodejsConsoleApp1\NodejsConsoleApp1\node_modules\azure-iot-device\lib\client.js:671:19)
at ontimeout (timers.js:386:14)
at tryOnTimeout (timers.js:250:5)
at Timer.listOnTimeout (timers.js:214:5)
===============================
2. we continue the IOT connection and no any operation on it, our IOT hub not receive any message after 45 min.

[ASK]
we would like to know : 
1. Do you have any workaround for prevent this bug ?
2. Do you have any ETA for release 

thanks a lot.

**Comment by anthonyvercolano** [comment]
I can answer "2" most easily.  I am comfortable that you can see a fix for this by July 28.

Your could close and re-open the connection.

**Comment by laishyy** [comment]
hi @anthonyvercolano  
have a good day.
Does the fix is released? 
thanks a lot.

**Comment by anthonyvercolano** [comment]
We are actively working on this.  Should have something by the end of the day Monday Seattle time.

**Comment by kuomingwu** [comment]
Hi Anthonyvercolano,

Thanks for your reply, is it fixed now ?

Regards,
Mo

**Comment by TonyErcolano** [comment]
You should see a release by EOD Thursday Seattle time.

**Comment by mikevax** [comment]
Anthonyvercolano,
    We ( Avigilon ) may have a a similar issues. We are using amqp-ws. In A streaming job in Azure we are monitoring the Operations monitoring endpoint. What we see are disconnects about every 45 min. however we do not see disconnect event in our nodeJS application running on our IoT device. Are there any update comming for the amqp-ws nodejs library. Last updated September 2016.

**Comment by pierreca** [comment]
Fixed with https://github.com/Azure/azure-iot-sdk-node/releases/tag/2017-8-4

**Comment by DanielStenis** [comment]
I'm not convinced this issue is fixed. I'm getting the same (or very similar) issue as the issue reporter, even after updating to to v1.1.17 Device package with npm.

```
NotConnectedError: Cannot putToken while disconnected.
    at Amqp.putToken (<REMOVED>/node_modules/azure-iot-amqp-base/lib/amqp.js:485:50)
    at Amqp.updateSharedAccessSignature (<REMOVED>/node_modules/azure-iot-device-amqp/lib/amqp.js:198:20)
    at constructor.updateSharedAccessSignature (<REMOVED>/node_modules/azure-iot-device/lib/client.js:125:42)
    at constructor.handle (<REMOVED>/node_modules/machina/lib/machina.js:613:25)
    at constructor.Fsm.(anonymous function) [as handle] (<REMOVED>/node_modules/machina/lib/machina.js:466:63)
    at Client._renewSharedAccessSignature (<REMOVED>/node_modules/azure-iot-device/lib/client.js:671:19)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
2017-08-10T22:07:28.282Z - error: Uncaught Exception: Cannot putToken while disconnected.
```

This occurred about 20 minutes after a disconnect resulting in that a couple of messages couldn't be sent (with error message `"AMQP Transport: Could not send"`). My application then reconnects and starts sending messages successfully again for the 20 minutes before the `NotConnectedError` exception is thrown.
