### ISSUE TITLE
registry.updateTwin wrong etag as no effect

### ISSUE THREAD

**Issue by SimonX200** [Azure/azure-iot-sdk-node#606]
When using updateTwin from your example azure-iot-sdk-node/service/samples/twin.js with a wrong etag then the updateTwin is still successful and the response is not indicating any problem.

nodejs example code:

package.json:
"azure-iothub": "^1.10.1",

-----------------------------------
const iothub = require('azure-iothub');
const registry = iothub.Registry.fromConnectionString(connectionString);

(async () => {
  var rsp;
  rsp = await registry.getTwin(deviceId);
  console.log('----------------------');
  console.log(rsp.responseBody.etag, rsp.responseBody.properties.desired);

  rsp = await registry.updateTwin(deviceId, { properties: { desired: { telemetryInterval: 100 } } }, 'abc');
  console.log('----------------------');
  console.log(rsp.responseBody.etag, rsp.responseBody.properties.desired);
  rsp = await registry.updateTwin(deviceId, { properties: { desired: { telemetryInterval: null } } }, 'xyz');
  console.log('----------------------');
  console.log(rsp.responseBody.etag, rsp.responseBody.properties.desired);
})();

**Comment by anthonyvercolano** [comment]
Fix has been released.  Thank you @SimonX200

**Comment by az-iot-builder-01** [comment]
@SimonX200, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
