### ISSUE TITLE
Potential Bug In Twin 

### ISSUE THREAD

**Issue by YoDaMa** [Azure/azure-iot-sdk-node#629]
According to APerrine:

https://github.com/Avsphere/azure-iot-node-sdk-samples/blob/master/questions/issue_twinInconsistencies.js

**Comment by anthonyvercolano** [comment]
I guess I would have preferred an actual issue report.  We have a template for that.

Why do you think you can get change notifications on a reported property?

**Comment by YoDaMa** [comment]
So the reported property should not receive change notifications. During the samples change we should call this out.

**Comment by az-iot-builder-01** [comment]
@YoDaMa, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
