### ISSUE TITLE
Potential Registry Promise Handling Bug in Promises

### ISSUE THREAD

**Issue by YoDaMa** [Azure/azure-iot-sdk-node#630]
Per APerrine: 

https://github.com/Avsphere/azure-iot-node-sdk-samples/blob/master/questions/issue_registryPromiseHandling.js

AB#7366637

**Comment by jebrando** [comment]
This shall be fixed when we move to the track 2

**Comment by az-iot-builder-01** [comment]
@YoDaMa, @jebrando, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
