### ISSUE TITLE
WebSocket connection to 'wss:<XXX...azure-devices.net/'> failed: Error during WebSocket handshake: Unexpected response code: 400

### ISSUE THREAD

**Issue by anupamhore** [Azure/azure-iot-sdk-node#634]
I am trying to use the azure-iot-device-mqtt in the application. I am trying to connect to the azure iot hub. Following is the code I am using. But whenver I am trying to connect I get the error
'WebSocket connection to 'wss:<XXX...azure-devices.net/'> failed: Error during WebSocket handshake: Unexpected response code: 400'. Can anyone guide me to fix this?

`
var Mqtt = require('azure-iot-device-mqtt').Mqtt;
var DeviceClient = require('azure-iot-device').Client
var connectionString = config.hubConnectionString;
var client = DeviceClient.fromConnectionString(connectionString, Mqtt);
// Connect to the IoT hub.
 client.open(function (err) {
    if (err) {
       console.log('Could not connect: ' + err);
    } else {
       console.log('Client connected');
    }
    client.close(function() {
       process.exit(0);
    });
});
`

**Comment by az-iot-builder-01** [comment]
@anupamhore, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
