### ISSUE TITLE
[Digitaltwins] client should set utf-8 encoding in messages

### ISSUE THREAD

**Issue by peolivei2** [Azure/azure-iot-sdk-node#638]
Digital twins client sends messages as JSON, so it should be setting `contentEncoding` to utf-8 (doc: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-routing-query-syntax#system-properties)

**Comment by anthonyvercolano** [comment]
There was discussion a few months back whether this was needed.  Consensus was defaulting was sufficient. We can add this on the next roll out.

**Comment by anthonyvercolano** [comment]
Fixed in the current .3 preview package

**Comment by az-iot-builder-01** [comment]
@peolivei2, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
