### ISSUE TITLE
lack of browser support in sdk

### ISSUE THREAD

**Issue by rlimberger** [Azure/azure-iot-sdk-node#640]
# Context
```
MacOS 10.14
Node.js 10.16.1
npm 6.11.3
azure-iot-device 1.12.0
azure-iot-device-mqtt 1.11.0
```

# Description of the issue:
Using the azure-iot-device sdk for node works in a standalone node program. When trying to use the same node code in a React web app, the connection to the IoT Hub fails with and error:

`stream.js:61 WebSocket connection to 'wss://my-iothub.azure-devices.net/' failed: Error during WebSocket handshake: Unexpected response code: 400`

# Code sample exhibiting the issue:
_App.js_
```
var Protocol = require('azure-iot-device-mqtt').Mqtt;
var Client = require('azure-iot-device').Client;

var connectionString = "HostName=my-iothub.azure-devices.net;DeviceId=<redacted>;SharedAccessKey=<redacted>=";
var client = Client.fromConnectionString(connectionString, Protocol);

var connectCallback = function (err) {
  if (err) {
    console.error('Could not connect: ' + err.message);
  }
  ...
};

client.open(connectCallback);
```

# Console log of the issue:
```
err
Event {isTrusted: true, transportError: Event, type: "error", target: WebSocket, currentTarget: WebSocket, …}
bubbles:false
cancelable:false
cancelBubble:false
composed:false
currentTarget:WebSocket {url: "wss://my-iothub.azure-devices.net/", readyState: 3, bufferedAmount: 0, …}
defaultPrevented:false
eventPhase:0
isTrusted:true
path:Array(0) []
returnValue:true
srcElement:WebSocket {url: "wss://my-iothub.azure-devices.net/", readyState: 3, bufferedAmount: 0, …}
target:WebSocket {url: "wss://my-iothub.azure-devices.net/", readyState: 3, bufferedAmount: 0, …}
timeStamp:1090.1149999990594
transportError:Event {isTrusted: true, transportError: Event, type: "error", …}
bubbles:false
cancelable:false
cancelBubble:false
composed:false
currentTarget:WebSocket {url: "wss://my-iothub.azure-devices.net/", readyState: 3, bufferedAmount: 0, …}
defaultPrevented:false
eventPhase:0
isTrusted:true
path:Array(0) []
returnValue:true
srcElement:WebSocket {url: "wss://my-iothub.azure-devices.net/", readyState: 3, bufferedAmount: 0, …}
target:WebSocket {url: "wss://my-iothub.azure-devices.net/", readyState: 3, bufferedAmount: 0, …}
```

AB#7366636

**Comment by rlimberger** [comment]
These are the failed network request's headers from Chrome debugger
```
Request URL: wss://my-iothub.azure-devices.net/
Request Method: GET
Status Code: 400 Bad Request
Content-Length: 158
Content-Type: application/json; charset=utf-8
Date: Wed, 02 Oct 2019 21:18:10 GMT
iothub-errorcode: InvalidProtocolVersion
Server: Microsoft-HTTPAPI/2.0
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cache-Control: no-cache
Connection: Upgrade
Host: my-iothub.azure-devices.net
Origin: http://localhost:3000
Pragma: no-cache
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
Sec-WebSocket-Key: <redacted>
Sec-WebSocket-Protocol: mqtt
Sec-WebSocket-Version: 13
Upgrade: websocket
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
```

**Comment by anthonyvercolano** [comment]
This is a quote from an older issue.  I'm using it because it's better explanation than what I could provide:

"My understanding is that React is a client-side framework meant to be run in a browser or browser-like environment (such as Electron). Our SDK is meant to run within a Node.js process: it's not a generic multi-modal, browser-compatible javascript SDK: it's just meant for Node.js. So I'm afraid we do not build nor test nor support this use case."

I do know that we have a newer explorer at: https://github.com/Azure/azure-iot-explorer/releases

It's an electron based app. It is only doing *server* side.  Perhaps how it is set up might provide some guidance.  Supporting the device client SDK is a goal but not for this current calendar year. It couldn't happen before the middle of next year either.

**Comment by rlimberger** [comment]
Thanks for the response, @anthonyvercolano. I was afraid you would say that. I had a look at the JS version of your SDK but it doesn't provide the functionality I'm looking for. 

Could you provide some guidance how a web app can directly connect to an IoT device and receive messages (i.e. Telemetry)?

**Comment by jebrando** [comment]
@rlimberger Sorry you hit this issue.  I've added browser-compatibility to our backlog as a feature we would like to invest in.  We will evaluate this and decide where it fits in our schedule.

**Comment by rlimberger** [comment]
@jebrando thank you! Meanwhile, what is the suggested way to interact with an IoT Edge device from a web app? Our use case needs both, get realtime telemetry and send messages to the device. Since the `azure-iot-device` sdk for node doesn't work in the browser, I was able to get the telemetry with `@azure/event-hubs` sdk in the browser. But I don't have a solution for sending a message to the device. Any advise?

**Comment by rlimberger** [comment]
Thank you @YoDaMa , I was able to use the Service SDK to make a module method call from a web app in browser. Regarding IoT Explorer, I already asked them and they are using a service worker that is launched from the Electron app in the background and relays the Node device SDK telemetry via a local WebSocket. This approach does not work for my use case. I need to use the sdk native in browser.

**Comment by YoDaMa** [comment]
Here's a summary for posterity as we work on this.
This enhancement encapsulates:

- Support for the Device and Service SDK in the browser. We currently don't support the SDK in the browser, and thus don't support electron apps. 
-The Azure IoT Explorer team has used the Service SDK in a separate process as part of their application and it is minimal.

**Comment by ridomin** [comment]
@rlimberger take a look to https://mqtt.rido.dev 
This sample shows how to connect to iothub from a browser using Paho JS library.

**Comment by anthonyvercolano** [comment]
We are not going to be updating the current implementation to supporting the browser.

**Comment by Gargamil** [comment]
> @rlimberger take a look to https://mqtt.rido.dev
> This sample shows how to connect to iothub from a browser using Paho JS library.

Big thanks for this!

BUT: Sad that Microsoft doesn't come up with a browser-supporting library, like @anthonyvercolano said.

**Comment by anthonyvercolano** [comment]
Ignore this please

**Comment by anthonyvercolano** [comment]
And this too.
