### ISSUE TITLE
Will Message

### ISSUE THREAD

**Issue by willin** [Azure/azure-iot-sdk-node#65]
# Context
- **OS and version used:**  OS X 10.12
- **Node.js version:**  8.2
- **npm version:**  5.3
- **list of installed packages:**  azure-iot-device-mqtt, azure-iot-device

# Description of the issue:

how to send mqtt Last Will / Testament message to specific route?

ref: Azure/azure-event-hubs-node#31

# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by mastermanu** [comment]
Hi @willin,

We currently do not support a Last Will / Testament for the MQTT Protocol.

May I ask what the scenario / customer requirement here is?

**Comment by pierreca** [comment]
@willin if you want to detect devices going online/offline you can use the operations monitoring endpoint:
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-operations-monitoring

You have to activate it on your hub first 
![image](https://user-images.githubusercontent.com/4979572/28738992-f0d05e14-73ab-11e7-9547-81879960e45a.png)

Then you can test this on your hub with `iothub-explorer monitor-ops --login <HUB CONNECTION STRING>`

**Comment by willin** [comment]
```js
const EventHubClient = require('azure-event-hubs').Client;

const connectionString = 'Endpoint=sb://iothub-ns-[xxxxxx].servicebus.chinacloudapi.cn/;SharedAccessKeyName=iothubowner;SharedAccessKey=[xxxxxx];EntityPath=[xxxxx]-operationmonitoring';

const printError = function (err) {
  console.log(err.message);
};

const printMessage = function (name, partitionId) {
  return function (message) {
    console.log('Message received: ');
    console.log(new Date());
    console.log(JSON.stringify(message.body.toString()));
    console.log(message);
    console.log(message.annotations['iothub-connection-device-id']);
    console.log(name, partitionId);
    console.log('');
  };
};
const client = EventHubClient.fromConnectionString(connectionString);
client.open()
  .then(client.getPartitionIds.bind(client))
  .then(partitionIds => partitionIds.map(partitionId => client.createReceiver('$Default', partitionId, { startAfterTime: Date.now() }).then((receiver) => {
    console.log(`Created partition receiver: ${partitionId}`);
    receiver.on('errorReceived', printError);
    receiver.on('message', printMessage('test', partitionId));
  })))
  .catch(printError);
```

could not get any msg.. @pierreca

**Comment by willin** [comment]
done thx
