### ISSUE TITLE
[module client] ModuleClient.fromSharedAccessSignature() doesn't work

### ISSUE THREAD

**Issue by peolivei2** [Azure/azure-iot-sdk-node#657]
For module client, the transport relies on the auth provider to get the moduleId and send messages to the correct module.
When using a connection string this works fine, as the connection string auth provider has support for moduleId.
However, it doesn't work when building the module client from a shared access signature, as the SAS auth provider does not support moduleId.

References:
[ModuleClient.fromSharedAccessSignature](https://github.com/Azure/azure-iot-sdk-node/blob/master/device/core/src/module_client.ts#L318)
[Code in SAS auth provider with no support for moduleId](https://github.com/Azure/azure-iot-sdk-node/blob/master/device/core/src/sas_authentication_provider.ts#L82)
[Code in MQTT transport that relies on moduleId from the auth provider](https://github.com/Azure/azure-iot-sdk-node/blob/master/device/transport/mqtt/src/mqtt.ts#L668)

**Comment by anthonyvercolano** [comment]
Released.

**Comment by az-iot-builder-01** [comment]
@peolivei2, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
