### ISSUE TITLE
Set ProductInfo in service SDK

### ISSUE THREAD

**Issue by blackchoey** [Azure/azure-iot-sdk-node#662]
# Context
- **OS and version used:** <VERSION> Windows 10
- **Node.js version:** <VERSION> 8.12.0
- **npm version:** <VERSION> 6.11.3
- **list of installed packages:** <VERSION> azure-iothub 1.11.0
- **cloned repo:** <VERSION> N/A

# Description of the issue:
Is there a way to set ProductInfo in service SDK?
In Azure IoT device SDK, there's a function `client.setOptions(...)` which allows me to set ProductInfo. But in service SDK, no such function exists.

# Code sample exhibiting the issue:
No need to provide sample for this issue

# Console log of the issue:
No need to provide log for this issue

**Comment by YoDaMa** [comment]
productInfo is used primarily for identification and is only supported on the Device Client Library. The Service Client Library (Service SDK) does not have any Product Info setting.

**Comment by blackchoey** [comment]
Thanks @YoDaMa Is there any plan to support setting ProductInfo in service client?

**Comment by YoDaMa** [comment]
No. After speaking with the team there is no plans or specs for the ProductInfo in Service Client

**Comment by az-iot-builder-01** [comment]
@YoDaMa, @blackchoey, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
