### ISSUE TITLE
Registry.getTwin signature returns any instead of Twin

### ISSUE THREAD

**Issue by chrisahardie** [Azure/azure-iot-sdk-node#673]
[getTwin has the following signature](https://github.com/Azure/azure-iot-sdk-node/blob/master/service/src/registry.ts#L530):

`getTwin(deviceId: string, done: HttpResponseCallback<any>): void;`

Any reason this couldn't be:

`getTwin(deviceId: string, done: HttpResponseCallback<Twin>): void;`

If there's no issue and you'd like, I'd be happy to submit a PR.

**Comment by anthonyvercolano** [comment]
I agree it seems better to make this change.

Sadly, since this is a published API, and if this change were made it conceivably could be a breaking change by making the API more restrictive.

I'll ask some others, but, I'm hesitant.

**Comment by anthonyvercolano** [comment]
I've talked with some folk.  We will be changing the type to Twin.  If you could wait, a few weeks, we'll put it (and a couple of others) in the *next* release.

**Comment by chrisahardie** [comment]
Cool, it's just a convenience for me, definitely not critical.

**Comment by az-iot-builder-01** [comment]
@chrisahardie, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
