### ISSUE TITLE
[Digitaltwins] register() callback never called if no telemetry or properties have been added

### ISSUE THREAD

**Issue by peolivei2** [Azure/azure-iot-sdk-node#677]
When using the DigitalTwin client, if we call `register()` on a client to which we have not added any telemetry or properties, the function callback is never called. For instance, in the sample code below, the promise returned by `register()` is never resolved or rejected.

```javascript
const client = Client.fromConnectionString('<connection-str>', Mqtt);
const dtClient = new DigitalTwinClient('<id>', client);
console.log('Calling registration');
dtClient.register().then(() => console.log('Client registered')).catch((err: any) => console.error('Could not register:', err));
setInterval(() => console.log('Still alive', new Date()), 30000);
```

**Comment by elhorton** [comment]
marking closed based on fixing commit mentioned above. Please reopen if the issue persists.

**Comment by az-iot-builder-01** [comment]
@peolivei2, @elhorton, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
