### ISSUE TITLE
Group enrollment fails due to Unauthorized 401002 intermittently

### ISSUE THREAD

**Issue by nikosandronikos** [Azure/azure-iot-sdk-node#679]
Provisioning via nodejs is failing for me more times than it is succeeding.

The error returned is:
```
  responseBody: '{"errorCode":401002,"trackingId":"4f3245f9-d969-4d47-bb81-5629ba466617","message":"Unauthorized","timestampUtc":"2020-01-17T05:11:45.7515964Z"}'
```

For any particular certificate, provisioning sometimes succeeds and sometimes fails. The returned error is an authentication error and appears to be related to verifying the CA chain. The pattern of failure is odd - re-using the same certificate gives more success. Slowing things down (e.g. sleep in code) gives more success. Generating a device certificate and provisioning devices without any artificial throttling gives primarily failure.

The certificates were generated with the `create_test_cert.js` script from the azure-iot-sdk-node tools directory.

The function used to provision is:
```
async function provisionDevice(provisioningHost, idScope, deviceId, deviceCert) {
    const transport = new Transport();

    const securityClient = new X509Security(deviceId, deviceCert);

    const deviceClient
        = ProvisioningDeviceClient.create(
            provisioningHost,
            idScope,
            transport,
            securityClient
        );

    return new Promise( (resolve, reject) => {
        deviceClient.register( (err, result) => {
            if (err) {
                reject(err);
            }

            resolve(result);
        });
    });
}
```

# Context
- **OS and version used:** Windows 10 Desktop x64 with Debian GNU/Linux 9 (stretch) under WSL
- **Node.js version:** v12.1.0
- **npm version:** 6.10.3
- **list of installed packages:** iothub@1.0.0 /c/Users/NikosAndronikos/Cognian/Azure/IoTHub
├─┬ azure-iot-device-mqtt@1.11.1
│ ├─┬ azure-iot-common@1.11.1
│ │ ├── debug@4.1.1 deduped
│ │ └─┬ getos@3.1.1
│ │   └─┬ async@2.6.1
│ │     └── lodash@4.17.15 deduped
│ ├─┬ azure-iot-device@1.12.1
│ │ ├─┬ @azure/storage-blob@10.5.0
│ │ │ ├─┬ @azure/ms-rest-js@2.0.4
│ │ │ │ ├─┬ @types/node-fetch@2.5.4
│ │ │ │ │ └── @types/node@13.1.4
│ │ │ │ ├─┬ @types/tunnel@0.0.1
│ │ │ │ │ └── @types/node@13.1.4 deduped
│ │ │ │ ├─┬ abort-controller@3.0.0
│ │ │ │ │ └── event-target-shim@5.0.1
│ │ │ │ ├─┬ form-data@2.5.1
│ │ │ │ │ ├── asynckit@0.4.0
│ │ │ │ │ ├─┬ combined-stream@1.0.8
│ │ │ │ │ │ └── delayed-stream@1.0.0
│ │ │ │ │ └─┬ mime-types@2.1.26
│ │ │ │ │   └── mime-db@1.43.0
│ │ │ │ ├── node-fetch@2.6.0
│ │ │ │ ├─┬ tough-cookie@3.0.1
│ │ │ │ │ ├── ip-regex@2.1.0
│ │ │ │ │ ├── psl@1.7.0
│ │ │ │ │ └── punycode@2.1.1
│ │ │ │ ├── tslib@1.10.0 deduped
│ │ │ │ ├── tunnel@0.0.6
│ │ │ │ ├── uuid@3.3.3 deduped
│ │ │ │ └─┬ xml2js@0.4.23
│ │ │ │   ├── sax@1.2.4
│ │ │ │   └── xmlbuilder@11.0.1
│ │ │ ├── events@3.0.0
│ │ │ └── tslib@1.10.0
│ │ ├── azure-iot-common@1.11.1 deduped
│ │ ├── azure-iot-http-base@1.10.1 deduped
│ │ ├── debug@4.1.1 deduped
│ │ ├── lodash@4.17.15 deduped
│ │ ├── machina@4.0.2 deduped
│ │ └── traverse@0.6.6
│ ├─┬ azure-iot-mqtt-base@1.10.1
│ │ ├── azure-iot-common@1.11.1 deduped
│ │ ├── debug@4.1.1 deduped
│ │ ├── machina@4.0.2 deduped
│ │ └─┬ mqtt@3.0.0
│ │   ├── base64-js@1.3.1
│ │   ├─┬ commist@1.1.0
│ │   │ ├── leven@2.1.0
│ │   │ └── minimist@1.2.0 deduped
│ │   ├─┬ concat-stream@1.6.2
│ │   │ ├── buffer-from@1.1.1
│ │   │ ├── inherits@2.0.4 deduped
│ │   │ ├── readable-stream@2.3.7 deduped
│ │   │ └── typedarray@0.0.6
│ │   ├─┬ end-of-stream@1.4.4
│ │   │ └─┬ once@1.4.0
│ │   │   └── wrappy@1.0.2
│ │   ├─┬ es6-map@0.1.5
│ │   │ ├─┬ d@1.0.1
│ │   │ │ ├── es5-ext@0.10.53 deduped
│ │   │ │ └── type@1.2.0
│ │   │ ├─┬ es5-ext@0.10.53
│ │   │ │ ├── es6-iterator@2.0.3 deduped
│ │   │ │ ├── es6-symbol@3.1.3 deduped
│ │   │ │ └── next-tick@1.0.0
│ │   │ ├─┬ es6-iterator@2.0.3
│ │   │ │ ├── d@1.0.1 deduped
│ │   │ │ ├── es5-ext@0.10.53 deduped
│ │   │ │ └── es6-symbol@3.1.3 deduped
│ │   │ ├─┬ es6-set@0.1.5
│ │   │ │ ├── d@1.0.1 deduped
│ │   │ │ ├── es5-ext@0.10.53 deduped
│ │   │ │ ├── es6-iterator@2.0.3 deduped
│ │   │ │ ├─┬ es6-symbol@3.1.1
│ │   │ │ │ ├── d@1.0.1 deduped
│ │   │ │ │ └── es5-ext@0.10.53 deduped
│ │   │ │ └── event-emitter@0.3.5 deduped
│ │   │ ├─┬ es6-symbol@3.1.3
│ │   │ │ ├── d@1.0.1 deduped
│ │   │ │ └─┬ ext@1.4.0
│ │   │ │   └── type@2.0.0
│ │   │ └─┬ event-emitter@0.3.5
│ │   │   ├── d@1.0.1 deduped
│ │   │   └── es5-ext@0.10.53 deduped
│ │   ├─┬ help-me@1.1.0
│ │   │ ├─┬ callback-stream@1.1.0
│ │   │ │ ├── inherits@2.0.4 deduped
│ │   │ │ └── readable-stream@2.3.7 deduped
│ │   │ ├─┬ glob-stream@6.1.0
│ │   │ │ ├── extend@3.0.2
│ │   │ │ ├─┬ glob@7.1.6
│ │   │ │ │ ├── fs.realpath@1.0.0
│ │   │ │ │ ├─┬ inflight@1.0.6
│ │   │ │ │ │ ├── once@1.4.0 deduped
│ │   │ │ │ │ └── wrappy@1.0.2 deduped
│ │   │ │ │ ├── inherits@2.0.4 deduped
│ │   │ │ │ ├─┬ minimatch@3.0.4
│ │   │ │ │ │ └─┬ brace-expansion@1.1.11
│ │   │ │ │ │   ├── balanced-match@1.0.0
│ │   │ │ │ │   └── concat-map@0.0.1
│ │   │ │ │ ├── once@1.4.0 deduped
│ │   │ │ │ └── path-is-absolute@1.0.1
│ │   │ │ ├─┬ glob-parent@3.1.0
│ │   │ │ │ ├─┬ is-glob@3.1.0
│ │   │ │ │ │ └── is-extglob@2.1.1
│ │   │ │ │ └── path-dirname@1.0.2
│ │   │ │ ├── is-negated-glob@1.0.0
│ │   │ │ ├─┬ ordered-read-streams@1.0.1
│ │   │ │ │ └── readable-stream@2.3.7 deduped
│ │   │ │ ├─┬ pumpify@1.5.1
│ │   │ │ │ ├── duplexify@3.7.1 deduped
│ │   │ │ │ ├── inherits@2.0.4 deduped
│ │   │ │ │ └─┬ pump@2.0.1
│ │   │ │ │   ├── end-of-stream@1.4.4 deduped
│ │   │ │ │   └── once@1.4.0 deduped
│ │   │ │ ├── readable-stream@2.3.7 deduped
│ │   │ │ ├── remove-trailing-separator@1.1.0
│ │   │ │ ├─┬ to-absolute-glob@2.0.2
│ │   │ │ │ ├─┬ is-absolute@1.0.0
│ │   │ │ │ │ ├─┬ is-relative@1.0.0
│ │   │ │ │ │ │ └─┬ is-unc-path@1.0.0
│ │   │ │ │ │ │   └── unc-path-regex@0.1.2
│ │   │ │ │ │ └── is-windows@1.0.2
│ │   │ │ │ └── is-negated-glob@1.0.0 deduped
│ │   │ │ └─┬ unique-stream@2.3.1
│ │   │ │   ├── json-stable-stringify-without-jsonify@1.0.1
│ │   │ │   └─┬ through2-filter@3.0.0
│ │   │ │     ├── through2@2.0.5 deduped
│ │   │ │     └── xtend@4.0.2 deduped
│ │   │ ├─┬ through2@2.0.5
│ │   │ │ ├── readable-stream@2.3.7 deduped
│ │   │ │ └── xtend@4.0.2 deduped
│ │   │ └── xtend@4.0.2 deduped
│ │   ├── inherits@2.0.4
│ │   ├── minimist@1.2.0
│ │   ├─┬ mqtt-packet@6.3.0
│ │   │ ├─┬ bl@1.2.2
│ │   │ │ ├── readable-stream@2.3.7 deduped
│ │   │ │ └── safe-buffer@5.1.2 deduped
│ │   │ ├── inherits@2.0.4 deduped
│ │   │ ├── process-nextick-args@2.0.1
│ │   │ └── safe-buffer@5.1.2
│ │   ├─┬ pump@3.0.0
│ │   │ ├── end-of-stream@1.4.4 deduped
│ │   │ └── once@1.4.0 deduped
│ │   ├─┬ readable-stream@2.3.7
│ │   │ ├── core-util-is@1.0.2
│ │   │ ├── inherits@2.0.4 deduped
│ │   │ ├── isarray@1.0.0
│ │   │ ├── process-nextick-args@2.0.1 deduped
│ │   │ ├── safe-buffer@5.1.2 deduped
│ │   │ ├─┬ string_decoder@1.1.1
│ │   │ │ └── safe-buffer@5.1.2 deduped
│ │   │ └── util-deprecate@1.0.2
│ │   ├── reinterval@1.1.0
│ │   ├─┬ split2@3.1.1
│ │   │ └─┬ readable-stream@3.4.0
│ │   │   ├── inherits@2.0.4 deduped
│ │   │   ├── string_decoder@1.1.1 deduped
│ │   │   └── util-deprecate@1.0.2 deduped
│ │   ├─┬ websocket-stream@5.5.0
│ │   │ ├─┬ duplexify@3.7.1
│ │   │ │ ├── end-of-stream@1.4.4 deduped
│ │   │ │ ├── inherits@2.0.4 deduped
│ │   │ │ ├── readable-stream@2.3.7 deduped
│ │   │ │ └── stream-shift@1.0.1
│ │   │ ├── inherits@2.0.4 deduped
│ │   │ ├── readable-stream@2.3.7 deduped
│ │   │ ├── safe-buffer@5.1.2 deduped
│ │   │ ├─┬ ws@3.3.3
│ │   │ │ ├── async-limiter@1.0.1 deduped
│ │   │ │ ├── safe-buffer@5.1.2 deduped
│ │   │ │ └── ultron@1.1.1
│ │   │ └── xtend@4.0.2 deduped
│ │   └── xtend@4.0.2
│ ├─┬ debug@4.1.1
│ │ └── ms@2.1.2
│ ├─┬ machina@4.0.2
│ │ └── lodash@4.17.15 deduped
│ └── uuid@3.3.3
├─┬ azure-iot-provisioning-device@1.7.1
│ ├── azure-iot-common@1.11.1 deduped
│ ├── debug@4.1.1 deduped
│ └── machina@4.0.2 deduped
├─┬ azure-iot-provisioning-device-http@1.7.1
│ ├── azure-iot-common@1.11.1 deduped
│ ├─┬ azure-iot-http-base@1.10.1
│ │ ├── azure-iot-common@1.11.1 deduped
│ │ ├── debug@4.1.1 deduped
│ │ └── uuid@3.3.3 deduped
│ ├── azure-iot-provisioning-device@1.7.1 deduped
│ ├── debug@4.1.1 deduped
│ └── machina@4.0.2 deduped
├─┬ azure-iot-security-x509@1.6.1
│ ├── azure-iot-common@1.11.1 deduped
│ └── debug@4.1.1 deduped
├─┬ azure-iothub@1.11.1
│ ├─┬ async@2.6.3
│ │ └── lodash@4.17.15 deduped
│ ├─┬ azure-iot-amqp-base@2.3.1
│ │ ├─┬ async@2.6.3
│ │ │ └── lodash@4.17.15 deduped
│ │ ├── azure-iot-common@1.11.1 deduped
│ │ ├── debug@4.1.1 deduped
│ │ ├── lodash.merge@4.6.2
│ │ ├── machina@4.0.2 deduped
│ │ ├── rhea@1.0.15 deduped
│ │ ├── uuid@3.3.3 deduped
│ │ └─┬ ws@6.2.1
│ │   └── async-limiter@1.0.1
│ ├── azure-iot-common@1.11.1 deduped
│ ├── azure-iot-http-base@1.10.1 deduped
│ ├── debug@4.1.1 deduped
│ ├── lodash@4.17.15
│ ├── machina@4.0.2 deduped
│ └─┬ rhea@1.0.15
│   └─┬ debug@3.2.6
│     └── ms@2.1.2 deduped
├─┬ chalk@3.0.0
│ ├─┬ ansi-styles@4.2.1
│ │ ├── @types/color-name@1.1.1
│ │ └─┬ color-convert@2.0.1
│ │   └── color-name@1.1.4
│ └─┬ supports-color@7.1.0
│   └── has-flag@4.0.0
├── dotenv@8.2.0
└─┬ pem@1.14.2
  ├── es6-promisify@6.0.2
  ├─┬ md5@2.2.1
  │ ├── charenc@0.0.2
  │ ├── crypt@0.0.2
  │ └── is-buffer@1.1.6
  ├── os-tmpdir@1.0.2
  └─┬ which@1.3.1
    └── isexe@2.0.0

**Comment by anthonyvercolano** [comment]
An application certainly can be throttled by the DPS service.  The example showed code that was provisioning the device but did not show code that was calling it.  If called in a tight loop I can certainly imagine it getting throttled.  On a bus now, in a couple of hours I will try to look up references to how many requests/miniute will invoke throttling.  Will also see if I can get a hint from your log entry and the service logs themselves.

**Comment by anthonyvercolano** [comment]
A few things:

 - create_test_cert lives in the build tools directory.  We mostly use it to create self-signed certs to use in our end-2-end test environment.   One should NOT use it in production.

 - Using it with CA chains seems odd.  This tools is basically just for creating self-signed certs.

 - The particular error message you sent in the OP got an UNAUTH error because *a* cert was expired.   It's not clear to me whether it was the particular client cert you were trying to authenticate the device with or perhaps a cert in the chain.  You can take the public cert pem files and find various web sites that will decode them and show you the expiration date.

**Comment by nikosandronikos** [comment]
Thanks for the response.

1) Throttling was something I considered but I couldn't get the failures to occur on any predictable schedule so I couldn't convince myself throttling was causing the issue. If throttling is the root cause, it seems the unauthorized error message may be incorrect and a 429 response may be more appropriate?

2) Understood, this is test code

3) I may be getting terms wrong here, but it's essentially a group enrollment scenario with root, intermediate, and device certificates created with create_test_cert. The intermediate is uploaded to the device provisioning service and verified.

4) Is that analysis based on the logs? All certificates are definitely not expired, and in this case why would I see some successes?

**Comment by anthonyvercolano** [comment]
The create_test_cert that you are using is from the c repo, correct?

**Comment by anthonyvercolano** [comment]
My apologies, I completely forgot about the create_test_cert.js in the provisioning directory.  That can certainly be used to create chains.  (And yes, that one should also only be used for testing.)

Below is what is found in the DPS logs for the error that you opened the issue with:

ErrorCode: IotHubUnauthorizedAccess
Message: Client certificate validation failed - A required certificate is not within its validity period when verifying against the current system clock or the timestamp in the signed file.

```
Timestamp: 01/17/2020 05:11:45
Tracking ID: 
Public Message: 
Public Info: null
Exception: Microsoft.Azure.Devices.Common.Core.Exceptions.IotHubException: Client certificate validation failed - A required certificate is not within its validity period when verifying against the current system clock or the timestamp in the signed file.
```

**Comment by anthonyvercolano** [comment]
Could you describe the scenario a bit more?

Are you trying to register like 10 devices in a row in one invocation of an app and most of them fail?   Or is it one device 10 times and that one fails?

Also, the app that you are running, just from a command line?

**Comment by anthonyvercolano** [comment]
I think your problem might be that your certs are *NOT YET* valid.  The cert that was being using was NOT valid UNTIL 5:11:46.  The UNAUTH happened at 5:11:45.  It was 1 second too soon.

**Comment by nikosandronikos** [comment]
Ahhhh! That sounds entirely plausible. I was going to put together a short demo but I think you've solved it. I'll test and report back.

**Comment by nikosandronikos** [comment]
Testing verifies your solution. Feel free to close this and thanks for your help.

**Comment by az-iot-builder-01** [comment]
@nikosandronikos, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
