### ISSUE TITLE
API Reference Link Broken

### ISSUE THREAD

**Issue by lusentis** [Azure/azure-iot-sdk-node#68]
# Context
n/a

# Description of the issue:
The [service/readme.md](https://github.com/Azure/azure-iot-sdk-node/blob/master/service/readme.md) file in this repository has a dead link under the section **Read More**: [API Reference](https://azure.github.io/azure-iot-sdks/) points to https://azure.github.io/azure-iot-sdks/ which returns a 404 page.

# Code sample exhibiting the issue:
n/a

# Console log of the issue:
n/a

**Comment by yzhong94** [comment]
@lusentis Thank you for letting us know.  We fixed the link on [service/readme.md](https://github.com/Azure/azure-iot-sdk-node/blob/master/service/readme.md), it points to this link now: https://azure.github.io/azure-iot-sdk-node/
