### ISSUE TITLE
[DigitalTwins][blocking issue] client doesn't work if interface schema id is "urn:azureiot:ModelDiscovery:ModelInformation:1"

### ISSUE THREAD

**Issue by peolivei2** [Azure/azure-iot-sdk-node#680]
If an interface with Id `urn:azureiot:ModelDiscovery:ModelInformation:1` is added to the client, the callback of the `register()` is never called. Looks like this conflicts with an Id that's used by the SDK. Example:

```javascript
const iface = new BaseInterface('myInterface', 'urn:azureiot:ModelDiscovery:ModelInformation:1');
iface['myTelemetry'] = new Telemetry();
client.addInterfaceInstance(iface);
await client.register();
```

**Comment by elhorton** [comment]
marking closed based on a fix in the above mentioned commit. Please reopen if the issue persists.

**Comment by az-iot-builder-01** [comment]
@peolivei2, @elhorton, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
