### ISSUE TITLE
wrong twin properties are getting removed when patching twin with a non existing key set as null

### ISSUE THREAD

**Issue by pguptax** [Azure/azure-iot-sdk-node#683]
# Context
- **OS and version used:** Windows 10, Debian 9
- **Node.js version:** 12.14.1
- **npm version:** 6.13.4
- **list of installed packages:**     azure-iothub@1.11.2

# Description of the issue:
If we set a non existent property to null, then all the siblings at the same level are removed from the parent.

**initial twin**
```
  "properties": {
    "desired": {
      "key1": {
        "key2": "val2"
      },
      "$metadata": {
        "$lastUpdated": "2020-01-30T17:35:15.4242828Z",
        "$lastUpdatedVersion": 22,
        "key1": {
          "$lastUpdated": "2020-01-30T17:35:15.4242828Z",
          "$lastUpdatedVersion": 22,
          "key2": {
            "$lastUpdated": "2020-01-30T17:35:15.4242828Z",
            "$lastUpdatedVersion": 22
          }
        }
      },
      "$version": 22
    }

```
Patch using twin.update
**patch**
```
      properties: {
        desired: {
          "key1":{
            "key3": null
          }
        }
      }
```
**result**
key2 got removed, but metadata still has key2 information
```
  "properties": {
    "desired": {
      "key1": {},
      "$metadata": {
        "$lastUpdated": "2020-01-30T17:35:15.4242828Z",
        "$lastUpdatedVersion": 22,
        "key1": {
          "$lastUpdated": "2020-01-30T17:35:15.4242828Z",
          "$lastUpdatedVersion": 22,
          "key2": {
            "$lastUpdated": "2020-01-30T17:35:15.4242828Z",
            "$lastUpdatedVersion": 22
          }
        }
      },
      "$version": 23
    }
```

**expected** No change in twin as property "key3" doesn't exist
```
  "properties": {
    "desired": {
      "key1": {
          "key2" : "val2"},
      "$metadata": {
        "$lastUpdated": "2020-01-30T17:35:15.4242828Z",
        "$lastUpdatedVersion": 22,
        "key1": {
          "$lastUpdated": "2020-01-30T17:35:15.4242828Z",
          "$lastUpdatedVersion": 22,
          "key2": {
            "$lastUpdated": "2020-01-30T17:35:15.4242828Z",
            "$lastUpdatedVersion": 22
          }
        }
      },
      "$version": 23
    }
```

# Code sample exhibiting the issue:
can be tested with the sample code easily
https://github.com/Azure/azure-iot-sdk-node/blob/master/service/samples/twin.js

AB#7366640

**Comment by anthonyvercolano** [comment]
Thank you very much for the bug report.

This behavior is incorrect.

This is back end issue so a response will take a bit more time.

We will update the issue when we get more information

**Comment by anthonyvercolano** [comment]
This fix has deployed world wide.

**Comment by az-iot-builder-01** [comment]
@pguptax, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
