### ISSUE TITLE
400027 Error whenever I try to invoke a direct method

### ISSUE THREAD

**Issue by weisssean** [Azure/azure-iot-sdk-node#689]
Tested it with the code snippet coming from the vscode extention:

In my edge module:
```
    var client = DeviceClient.fromConnectionString(deviceConnectionString,Transport);

    function onWriteLine(request, response) {
        console.log(request.payload);
  
        response.send(200, 'Input was written to log.', function (err) {
            if (err) {
                console.error('An error ocurred when sending a method response:\n' + err.toString());
            } else {
                console.log('Response to method \'' + request.methodName + '\' sent successfully.');
            }
    });
```
    

on my node server running on localhost:

```
   var methodName = 'writeLine';
   var deviceId = 'seansPi';
   var client = Client.fromConnectionString(connectionString);
   
   var methodParams = {
     methodName: methodName,
     payload: 'a line to be written',
     timeoutInSeconds: 30
   };
   
   client.invokeDeviceMethod(deviceId, methodParams, function (err, result) {
     if (err) {
       console.error('Failed to invoke method \'' + methodName + '\': ' + err.message);
     } else {
       console.log(methodName + ' on ' + deviceId + ':');
       console.log(JSON.stringify(result, null, 2));
     }
   });
```

What I am seeing returned from running this code or from calling direct method from the vscode extention is: 

Failed to invoke method 'writeLine': Error: {"Message":"{\"errorCode\":400027,\"trackingId\":\"978078206f1a4c2693b11b77780cbd86-G:82-TimeStamp:02/05/2020 17:57:53\",\"message\":\"BadRequest\",\"info\":{},\"timestampUtc\":\"2020-02-05T17:57:53.7778405Z\"}","ExceptionMessage":""}

Any idea as to what is going on?

**Comment by anthonyvercolano** [comment]
@weisssean I don't see any invocations of client.onDeviceMethod on you client.

**Comment by weisssean** [comment]
Sorry, I think the issue was that more than one module was listening to changes and they interfered with each-other.
It would be easier to debug if the messages had better information, but seems to all be working now.

**Comment by az-iot-builder-01** [comment]
@weisssean, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
