### ISSUE TITLE
Error creating a new module on edge device

### ISSUE THREAD

**Issue by davide-sergi** [Azure/azure-iot-sdk-node#702]
Hi,

i'm trying to create a new module on an existing edge device (from an Azure Function and using iot hub node sdk) and I get the follow error:
**Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.IoTDeviceManager ---> Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException: Result: Failure
Exception: TypeError: Converting circular structure to JSON**

Part of Azure function code is the follow:
`registry = ...
module.exports = async function (context, req) {
    let error = null
    let statusCode = null
    let body = null
    try{
        let deviceId = req.body.deviceId
        let moduleId = req.body.moduleId
        let result = await addEdgeModule(deviceId,moduleId)

        statusCode = 200
        body = result
    }catch(e){
        context.log(e)
        statusCode = 500
        error = e
        body = e
    }

    context.res = {
        statusCode: statusCode,
        body: body
    }
}

function addEdgeModule(deviceId,moduleId){
    return new Promise(
        async (resolve,reject)=>{
            try{
                let newModule = await registry.addModule({deviceId: deviceId, moduleId: moduleId})
                resolve(newModule)
            }catch(e){
                reject(e)
            }
        }
    )
}`

Trying to debug my code I understood that the problem is the line:
let newModule = await registry.addModule({deviceId: deviceId, moduleId: moduleId})

Any ideas on that?

Regards,
Davide

**Comment by anthonyvercolano** [comment]
I would suggest you log the values of deviceId and moduleId.  Perhaps what you are getting from the req.body isn't what you think it is?

**Comment by az-iot-builder-01** [comment]
@davide-sergi, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
