### ISSUE TITLE
Please add @types of this library for Typescript

### ISSUE THREAD

**Issue by kentonbmax** [Azure/azure-iot-sdk-node#71]
Typescript = MS, azure-iot-device should have @types

**Comment by pierreca** [comment]
Hi @kentonbmax the type files are shipped directly within the packages - so neither the code editor nor the compiler should have an issue finding them. I'm not sure why I should ship the types separately from the package itself.

Given this, what's the observed problem, if any?

**Comment by kentonbmax** [comment]
Environment: VSC, Typescript (Latest)

Without an api document, If I hover client which is a client from connect string for Azure device, I do not see the function signature for open.

**Comment by pierreca** [comment]
Might be a configuration issue. Are you working of the clone repo or using npm packages? Javascript or Typescript? 

both of them work fine for me. I have installed the modules using npm install and here's what I see, respectively in JS and TS. Is that the result you're looking for? 

![js](https://user-images.githubusercontent.com/4979572/29143882-a6f23790-7d0b-11e7-8f25-3767eabb4a24.png)
![ts](https://user-images.githubusercontent.com/4979572/29143885-a971baea-7d0b-11e7-8210-d4b63ec5f91d.png)

**Comment by kentonbmax** [comment]
sorry for the delay. I am running latest typescript as dev dependency in the latest VSC and using the lts version of nodejs. 

![image](https://user-images.githubusercontent.com/15804484/29324058-db48422e-81b0-11e7-8228-cceffb1287e6.png)

**Comment by pierreca** [comment]
I'm not sure what's going on - might be a question more suited for stackoverflow or VS Code forums. how are you importing the Client class? do you see suggestions working with any other package?

**Comment by kentonbmax** [comment]
This is what I'm doing from the example. 
import {Message} from 'azure-iot-device'
import {clientFromConnectionString} from 'azure-iot-device-mqtt'

var client = clientFromConnectionString(CONFIG.connection.azure)

**Comment by pierreca** [comment]
ok let's try something else:
```javascript
import { Message, Client } from 'azure-iot-device'
import { Mqtt } from 'azure-iot-device-mqtt'

let client = Client.fromConnectionString(CONFIG.connection.azure, Mqtt);
```

**Comment by kentonbmax** [comment]
Worked! Thank you. This would be a good example for api doc/wiki or
quickstart guide.

**Comment by pierreca** [comment]
Perfect! glad to hear that.
I'll look into it more because I wonder if somehow our type definition file is messed up in `azure-iot-device-mqtt` but at least you're unblocked.

**Comment by pierreca** [comment]
Seems like this was solved and autocomplete is working - just double-checked the scenario and it works fine. closing the issue.
