### ISSUE TITLE
TLS Cert Change for iothub (China)

### ISSUE THREAD

**Issue by willin** [Azure/azure-iot-sdk-node#72]
http://www.21vbluecloud.vankr.cn/t/jn0anrcnndn-5upd6h-a8vf-wb-zh-eipnwgch.html

after chinese contents there is an english translation.

which means:

- ssl cert fron Wosign to DigiCert
- change effect date: 2017.09.25

is there a need for node.js sdk update?

**Comment by pierreca** [comment]
certs are managed by the host OS - no change required on the SDK side.
