### ISSUE TITLE
Please add overload to update function to return Promise for Twin reported properties

### ISSUE THREAD

**Issue by a8775** [Azure/azure-iot-sdk-node#723]
# Context
- **cloned repo:** https://github.com/Azure/azure-iot-sdk-node/blob/a59ff919317907b5e448ba80ab42a89bd91630ed/device/core/src/twin.ts#L170

# Description of the issue:
Please add overload to update function to return Promise

# Code sample exhibiting the issue:

```TypeScript
let twin = await this.client.getTwin();
return twin.properties.reported.update( patch );
```

```TypeScript
let twin = await this.client.getTwin();
return new Promise( (resolve,reject) => {
    twin.properties.reported.update( patch, function(err: any) {
        if (err) {
            reject(err);
        } 
        else {
            resolve();
        }
    });
});

```

AB#7366639

**Comment by anthonyvercolano** [comment]
Thank you for the suggestion.

**Comment by danhellem** [comment]
We have added this item to our backlog and will prioritize accordingly against other work. No current ETA.

I am closing this issue for now. If you feel this issue is urgent and we should re-open please add a comment.
