### ISSUE TITLE
Estimated availability of Digital Twins / PnP

### ISSUE THREAD

**Issue by mattias-kindborg-axis-communications** [Azure/azure-iot-sdk-node#728]
Hi!

I would love to get my hand on the PnP functionality coming to Digital Twins. Is there an estimate when that functionality is released, and is there a beta package source one could take a dependency on until it officially is released?

Keep up the good work!

**Comment by anthonyvercolano** [comment]
Thank you for your questions.

You can find the preview for the code on npm under the tag pnp-preview.  It is important to get ALL the packages under that tag.  Don't just get the packages that have digitaltwins in their name.  Get all of the Azure IoT Node SDK that were released under that tag.  It won't go well if you try to pick and choose.

The code itself lives in this repo under the digitaltwins-preview branch.  Note that we are planning *significant* revisions to the API shape that will appear in the next version of the preview.  However, the general concepts will remain the same.  (Commands, Properties, Telemetry)

There are quite a documents that can be found.  One example is at: https://docs.microsoft.com/en-us/azure/iot-pnp/quickstart-connect-pnp-device-solution-node


When will it be released?  Can't really say.

**Comment by mattias-kindborg-axis-communications** [comment]
Thanks for a great response, can't wait for this to be official. Keep up the good work!

**Comment by az-iot-builder-01** [comment]
@mattias-kindborg-axis-communications, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
