### ISSUE TITLE
Warning message when install latest (1.13.0) sdk

### ISSUE THREAD

**Issue by SLdragon** [Azure/azure-iot-sdk-node#731]
Hi, team, when I try to install latest version of node sdk (1.13.0) through npm install, it would show warning messages as below:

```
npm WARN deprecated @opentelemetry/types@0.2.0: Package renamed to @opentelemetry/api, see https://github.com/open-telemetry/opentelemetry-js
```

Any plans to fix this warning?

**Comment by anthonyvercolano** [comment]
Well this is because of a dependency on another package.  Luckily that package belongs to another Azure team.  We will update shortly after they release.

**Comment by SLdragon** [comment]
Thank you very much!

**Comment by az-iot-builder-01** [comment]
@SLdragon, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by anthonyvercolano** [comment]
@SLdragon Did you want to leave this open?

**Comment by SLdragon** [comment]
Yeah, just keep it open before the it has been updated, so that we can know the progress, thank you!

**Comment by anthonyvercolano** [comment]
@SLdragon With the latest release of @azure/storage-blob sdk this should be fixed.

**Comment by SLdragon** [comment]
Thanks, got it!
