### ISSUE TITLE
Direct method: JSON parsing error in azure-iot-http-base

### ISSUE THREAD

**Issue by ramandeep-singh-1983** [Azure/azure-iot-sdk-node#736]
# Description of the issue:
I have a device running Azure IoT Device SDK for C. It's returning the following response for a direct method:

`{"filename":"logs.zip"}`

We are using the Node SDK's invokeDeviceMethod() of azure-iothub to invoke the direct method. I get an exception on this method with the following error string:

'Unexpected token ' in JSON at position 25'

On debugging the issue, i found out this line is causing the exception:
https://github.com/Azure/azure-iot-sdk-node/blob/master/common/transport/http/src/rest_api_client.ts#L160

The responseBody for the above direct method response is coming as:
`"{"status":200,"payload":{'filename': 'logs.zip'}}"`

I don't know why the payload JSON object has key and value in single quotes instead of double quotes. 

If i use the Microsoft's sample Node.js device simulator (instead of actual device running the IoT C SDK) and pass the same JSON, then it works fine. responseBody in this case is:
`"{"status":200,"payload":{"filename":"logs.zip"}}"`

Any ideas?

**Comment by anthonyvercolano** [comment]
It would seem that this is a problem on the device client application.  I would closely look and try to debug what is happening on your device application.

If nothing seems odd there, I would then report this issue to the C SDK repo issues.

**Comment by anthonyvercolano** [comment]
I would suggest turning on logging for your device client application:

https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/Iothub_sdk_options.md

Look for OPTION_LOG_TRACE

**Comment by ramandeep-singh-1983** [comment]
@anthonyvercolano yes it seems like a problem with device client indeed. I am trying to find that piece of code now, thanks for the device client logging link. I will post soon with my findings.

**Comment by amit12cool** [comment]
> @anthonyvercolano yes it seems like a problem with device client indeed. I am trying to find that piece of code now, thanks for the device client logging link. I will post soon with my findings.

@ramandeep-singh-1983  Im curious to know did this work with Azure portal sending the direct method to device using C sdk. If it doesn't then it looks like a device side issue but if it does then might be some handling of response is done on the Azure portal side and same not done on the azure iot nodejs sdk side. @anthonyvercolano thoughts?

**Comment by ramandeep-singh-1983** [comment]
ok, just managed to find the device client code and it is indeed sending response with single quotes:

`jsonResponse = "{'filename': '" + message + "'}";`

Azure portal seems to be able to handle this correctly and doesn't show error whereas Node.js SDK gives parsing error. 

@anthonyvercolano is this an feature of Azure portal that it is able to handle single quotes as well? Shouldn't Azure portal also give JSON parsing error in this case?

**Comment by anthonyvercolano** [comment]
As you point out in the OP, we use a standard JSON.parse.  Always have.  I've sent a note over to the portal folks asking if they are using different parsing code.  (Reasonable chance it's not even written in javascript.)

If you're curious you could try this using Azure IoT Explorer and see if you get different results.

That said, I do not see us changing how the Node SDK parses the return value.

**Comment by ramandeep-singh-1983** [comment]
I agree with parsing of JSON in the Node.js SDK so that shouldn't be changed. Just wondering why Azure portal is ok with. I'll try with Azure IoT explorer and post the results soon.

**Comment by ramandeep-singh-1983** [comment]
Results with Azure IoT Explorer:
I see error while calling the direct method so looks like it also fails to parse the response. It also works when i try to pass the single quote response from Node.js device simulator so looks like Node.js SDK stringifies the response properly before sending it so we don't see any issue there.

**Comment by anthonyvercolano** [comment]
Portal says:
"we don’t parse the response before we shove it into the Monaco editor we take it as a string and tell the editor, “look, we know this is, kinda, JSON-ish, make it look like that"

"So if it has “, fine. If it’s a ‘, cool. Heck we don’t even care if there are a bunch of \ in front of things. It’s Just a String"

**Comment by ramandeep-singh-1983** [comment]
@anthonyvercolano thanks for the update and really fast replies :)
I think we can close this ticket now.

**Comment by az-iot-builder-01** [comment]
@ramandeep-singh-1983, @amit12cool, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by harikeshydv** [comment]
@ramandeep-singh-1983 , @anthonyvercolano : I am also facing the same issue. 
invokeDeviceMethod is giving "Unexpected token  in JSON at position **"
Did you find the fix for the same?

**Comment by anthonyvercolano** [comment]
@harikeshydv 

I believe that we felt that this was a bug in the device application.  It should not be responding with a reply body that was NOT parsable with JSON.parse.

**Comment by harikeshydv** [comment]
@anthonyvercolano Thank you.

@ramandeep-singh-1983 : Did you raised a bug for this earlier in C device SDK or should I do it now?
