### ISSUE TITLE
how to send messages to specific partition

### ISSUE THREAD

**Issue by willin** [Azure/azure-iot-sdk-node#74]
# Context
- **OS and version used:** <VERSION> OS X 10.12.6
- **Node.js version:** <VERSION> 8.4.0
- **npm version:** <VERSION> 5.3.0

# Description of the issue:

how to send messages to specific partition

# Code sample exhibiting the issue:

C#: <https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.eventhubclient.createpartitionedsender?view=azureservicebus-4.1.1>

https://github.com/Azure/azure-iot-sdk-node/blob/master/device/samples/simple_sample_device.js#L45

```js
      var windSpeed = 10 + (Math.random() * 4); // range: [10, 14]
      var temperature = 20 + (Math.random() * 10); // range: [20, 30]
      var humidity = 60 + (Math.random() * 20); // range: [60, 80]
      var data = JSON.stringify({ deviceId: 'myFirstDevice', windSpeed: windSpeed, temperature: temperature, humidity: humidity });
      var message = new Message(data);
      message.properties.add('temperatureAlert', (temperature > 28) ? 'true' : 'false');
      // to partition no.1, will this work?
      message.properties.add('x-opt-partition-key', 'pk:1');
      console.log('Sending message: ' + message.getData());
      client.sendEvent(message, printResultFor('send'));
```

**Comment by pierreca** [comment]
This is not a feature we have implemented yet and it's unlikely we will get to it soon.

Right now all messages from a specific device always end up on the same partition so there is some predictability though, so I don't know about your scenario but that might help?

Here's the hash function to know which partition is going to be used based on the device id:

https://github.com/Azure/azure-iot-sdk-csharp/blob/a5108f60f343dee867a2243e5a59c4483f0c5a8b/service/Microsoft.Azure.Devices/Common/EventHubPartitionKeyResolver.cs

Feel free to add more context or let us know if that'll work for you.

**Comment by willin** [comment]
how about event-hubs createSender? @pierreca

**Comment by willin** [comment]
```js
// to partition no.1, will this work?
message.properties.add('x-opt-partition-key', 'pk:1');
```

means this won't work?

**Comment by pierreca** [comment]
Adding `x-opt-partition-key` to a message sent to IoT Hub will not work.

**Comment by v1shva** [comment]
Is there any other way to route messages to a specific partition?

**Comment by neha-s-deshpande** [comment]
In python, can we check to which partition device to cloud message is going?

**Comment by AiHaibara** [comment]
it seems make the perf test become more complex.
and if send batch to iothub, does this can control random for different partition or same partition to process?
