### ISSUE TITLE
MQTT: Message are lost and callback is not invoked for lost messages 

### ISSUE THREAD

**Issue by anhashia** [Azure/azure-iot-sdk-node#744]
# Context
- **OS and version used:** <VERSION> 
Windows 10
- **Node.js version:** <VERSION> 
- **npm version:** <VERSION> 
- **list of installed packages:** <VERSION> 
- **cloned repo:** <VERSION> 
https://github.com/Azure/azure-iot-sdk-node/

# Description of the issue:

Message are lost and callback is not involved for lost messages.
**Scenario** : Temporary connection loss scenario.

Sample used :  https://github.com/Azure/azure-iot-sdk-node/blob/master/device/samples/simple_sample_device.js . Cloned the latest available master.
Protocol used : **MQTT**

**Test case** : Send messages. Simulate temporary **connection loss**
**Expected Result** : Messages should queue up. And when the connection is available, pending messages should go through.
**Actual result** : Message are lost. There is  **no** callback for lost messages

# Code sample exhibiting the issue:

Sample used :  https://github.com/Azure/azure-iot-sdk-node/blob/master/device/samples/simple_sample_device.js . Took the latest available master.
# Console log of the issue:

Send log from device side
```
Client connected
Sending message: {"count":0,"windSpeed":11.199580697922379,"temperature":24.954225139836012,"humidity":66.99959235383004}
send status: MessageEnqueued
Sending message: {"count":1,"windSpeed":11.781031822327863,"temperature":22.896244156482847,"humidity":70.43171128234461}
send status: MessageEnqueued
Sending message: {"count":2,"windSpeed":10.419977725485257,"temperature":29.203472631348752,"humidity":73.78448520575469}
send status: MessageEnqueued
Sending message: {"count":3,"windSpeed":11.414247946320796,"temperature":27.55769755993414,"humidity":69.32154522003792}
Sending message: {"count":4,"windSpeed":13.950602909820507,"temperature":26.538154963471158,"humidity":72.56203888937654}
Sending message: {"count":5,"windSpeed":10.350289406040512,"temperature":22.472063630277436,"humidity":62.434268086270954}
Sending message: {"count":6,"windSpeed":13.00287288985784,"temperature":22.62395487857757,"humidity":75.52551323025435}
Sending message: {"count":7,"windSpeed":12.572040024968292,"temperature":26.279830038149925,"humidity":62.784326261815295}
Sending message: {"count":8,"windSpeed":11.539716897789907,"temperature":27.88646633753791,"humidity":66.36131204793674}
Sending message: {"count":9,"windSpeed":11.008454706873778,"temperature":24.801176180934657,"humidity":66.98248362352275}
Sending message: {"count":10,"windSpeed":11.698855260602965,"temperature":20.389844413402255,"humidity":72.06487656944175}
Sending message: {"count":11,"windSpeed":10.563058541599272,"temperature":24.93355133833517,"humidity":78.15460073629679}
Sending message: {"count":12,"windSpeed":10.311652989278421,"temperature":29.945043550107727,"humidity":75.47987492509257}
Sending message: {"count":13,"windSpeed":11.902164189322484,"temperature":24.693938734505192,"humidity":65.73262608380888}
send status: MessageEnqueued
Sending message: {"count":14,"windSpeed":11.575974241759864,"temperature":21.0206866112992,"humidity":69.33334173769042}
send status: MessageEnqueued
Sending message: {"count":15,"windSpeed":10.940354991379252,"temperature":26.54908764055881,"humidity":63.435515761867606}
send status: MessageEnqueued
 ```

Receive log from backend  application 
```
4/6/2020 12:44:52 PM> Device: [device3], Data:[{"count":0,"windSpeed":11.199580697922379,"temperature":24.954225139836012,"humidity":66.99959235383004}]Properties:
'temperatureAlert': 'false'
4/6/2020 12:44:54 PM> Device: [device3], Data:[{"count":1,"windSpeed":11.781031822327863,"temperature":22.896244156482847,"humidity":70.43171128234461}]Properties:
'temperatureAlert': 'false'
4/6/2020 12:44:56 PM> Device: [device3], Data:[{"count":2,"windSpeed":10.419977725485257,"temperature":29.203472631348752,"humidity":73.78448520575469}]Properties:
'temperatureAlert': 'true'
// no messages
4/6/2020 12:45:18 PM> Device: [device3], Data:[{"count":13,"windSpeed":11.902164189322484,"temperature":24.693938734505192,"humidity":65.73262608380888}]Properties:
'temperatureAlert': 'false'
4/6/2020 12:45:20 PM> Device: [device3], Data:[{"count":14,"windSpeed":11.575974241759864,"temperature":21.0206866112992,"humidity":69.33334173769042}]Properties:
'temperatureAlert': 'false'
```

AB#7366641

**Comment by jebrando** [comment]
@anhashia We are actively working on fixing this issue in our SDK and down the stack with the MQTT.js library.  I will let you know of our findings when we have something checked in.

**Comment by a8775** [comment]
This is possibly the same kind of problem #754 that I just encountered.
Do you have any workaround at this moment?

**Comment by YoDaMa** [comment]
There is a patch released related to this problem in https://github.com/Azure/azure-iot-sdk-node/pull/770. Please let us know if that patch (released in 1.14.0) fixes any issues related to this bug.

**Comment by anthonyvercolano** [comment]
Fixed and Released.

**Comment by az-iot-builder-01** [comment]
@jebrando, @a8775, @YoDaMa, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
