### ISSUE TITLE
AMQP : Pending messages are not sent on temporary connection loss scenario

### ISSUE THREAD

**Issue by anhashia** [Azure/azure-iot-sdk-node#745]
# Context
- **OS and version used:** <VERSION> 
Windows 10
- **Node.js version:** <VERSION> 
- **npm version:** <VERSION> 
- **list of installed packages:** <VERSION> 
- **cloned repo:** <VERSION> 
https://github.com/Azure/azure-iot-sdk-node (cloned latest master)

# Description of the issue:

For AMQP,  pending messages are not sent on connection loss scenario

# Code sample exhibiting the issue:

OS : Windows 10
Sample used :  https://github.com/Azure/azure-iot-sdk-node/blob/master/device/samples/simple_sample_device.js . Took the latest available master.
Protocol used : **AMQP**
 
**Test scenario**: Send messages. Simulate **temporary** connection loss
**Expected result** : Messages should queue up. And when the connection is available, pending messages should go through.
**Actual result** :  Pending message are **not sent**. Error thrown  is **send error: Error: AMQP Transport: Could not send**

# Console log of the issue:
```
Sending message: {"count":0,"windSpeed":10.877876397513603,"temperature":27.338289497627102,"humidity":66.85649437251939}
send status: MessageEnqueued
Sending message: {"count":1,"windSpeed":11.5576049149254,"temperature":25.039692568907665,"humidity":63.53666056865049}
send status: MessageEnqueued
Sending message: {"count":2,"windSpeed":12.915819198444611,"temperature":26.475537896780573,"humidity":78.68134029858635}
Sending message: {"count":3,"windSpeed":11.991620676443016,"temperature":29.187461935072974,"humidity":68.93263350660342}
Sending message: {"count":4,"windSpeed":13.884336677111785,"temperature":28.005098720824076,"humidity":60.43958469828135}
Sending message: {"count":5,"windSpeed":11.998645204624259,"temperature":28.81575773529537,"humidity":65.41295612344078}
Sending message: {"count":6,"windSpeed":10.71228967468545,"temperature":26.312269252461945,"humidity":78.60700079701826}
Sending message: {"count":7,"windSpeed":10.043591826378893,"temperature":22.47173052306222,"humidity":67.0201489144331}
Sending message: {"count":8,"windSpeed":13.537609924485686,"temperature":24.08833844067658,"humidity":61.872753310313364}
Sending message: {"count":9,"windSpeed":13.01966335708391,"temperature":20.394426705669233,"humidity":79.98449136486968}
Sending message: {"count":10,"windSpeed":13.256224355353233,"temperature":20.47345646145726,"humidity":78.46492573396951}
Sending message: {"count":11,"windSpeed":12.68234398009854,"temperature":22.001655624703606,"humidity":68.38243512850387}
send error: Error: AMQP Transport: Could not send
send error: Error: AMQP Transport: Could not send
send error: Error: AMQP Transport: Could not send
send error: Error: AMQP Transport: Could not send
send error: Error: AMQP Transport: Could not send
send error: Error: AMQP Transport: Could not send
send error: Error: AMQP Transport: Could not send
send error: Error: AMQP Transport: Could not send
send error: Error: AMQP Transport: Could not send
send error: Error: AMQP Transport: Could not send
Sending message: {"count":12,"windSpeed":11.104377362305154,"temperature":24.474546872320744,"humidity":64.94134918572443}
send status: MessageEnqueued
```

AB#7366650

**Comment by tonygleck** [comment]
We are working on this issue and will keep you updated on any information that comes up.

**Comment by az-iot-builder-01** [comment]
@tonygleck, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by Grimm2017** [comment]
What was the resolution for this?

**Comment by vishnureddy17** [comment]
@RA-David-A This was a Microsoft internal issue that was resolved outside of GitHub.

Feel free to file a separate issue if necessary for your case.
