### ISSUE TITLE
Device-streams features not suport device module

### ISSUE THREAD

**Issue by v-jiacz** [Azure/azure-iot-sdk-node#759]
**service->samples->c2d_tcp_streaming.js sample**

`client.initiateStream` 
The parameter only support **deviceId**, can you commit a  **moduleId** support version.

AB#7366644

**Comment by YoDaMa** [comment]
@v-jiacz this looks like an expansion on the samples for service client. If you would like it to be done as soon as possible we would recommend offering a PR with your requested changes.

**Comment by anthonyvercolano** [comment]
Closing this for now because device-streams is still not released.  Feel free to refile late in 2021
