### ISSUE TITLE
Uncaught Exception: NotConnectedError: "Cannot putToken while disconnected"

### ISSUE THREAD

**Issue by DanielStenis** [Azure/azure-iot-sdk-node#77]
# Context
- **OS and version used:** Raspbian
- **Node.js version:** v8.1.0
- **npm version:** 5.3.0
- **list of installed packages:** 
├─┬ azure-iot-device@1.1.17
│ ├─┬ azure-iot-common@1.1.11
│ │ └── crypto@0.0.3
│ ├─┬ azure-iot-http-base@1.1.11
│ │ ├── azure-iot-common@1.1.11 deduped
│ │ └── debug@2.6.8 deduped
│ ├─┬ azure-storage@2.2.2
│ │ ├── browserify-mime@1.2.9
│ │ ├── extend@1.2.1
│ │ ├─┬ json-edm-parser@0.1.2
│ │ │ └── jsonparse@1.2.0
│ │ ├─┬ md5.js@1.3.4
│ │ │ ├─┬ hash-base@3.0.4
│ │ │ │ ├── inherits@2.0.3 deduped
│ │ │ │ └── safe-buffer@5.1.1 deduped
│ │ │ └── inherits@2.0.3 deduped
│ │ ├─┬ readable-stream@2.0.6
│ │ │ ├── core-util-is@1.0.2
│ │ │ ├── inherits@2.0.3 deduped
│ │ │ ├── isarray@1.0.0 deduped
│ │ │ ├── process-nextick-args@1.0.7
│ │ │ ├── string_decoder@0.10.31
│ │ │ └── util-deprecate@1.0.2
│ │ ├─┬ request@2.74.0
│ │ │ ├── aws-sign2@0.6.0
│ │ │ ├── aws4@1.6.0
│ │ │ ├─┬ bl@1.1.2
│ │ │ │ └── readable-stream@2.0.6 deduped
│ │ │ ├── caseless@0.11.0
│ │ │ ├─┬ combined-stream@1.0.5
│ │ │ │ └── delayed-stream@1.0.0
│ │ │ ├── extend@3.0.1
│ │ │ ├── forever-agent@0.6.1
│ │ │ ├─┬ form-data@1.0.1
│ │ │ │ ├─┬ async@2.5.0
│ │ │ │ │ └── lodash@4.17.4 deduped
│ │ │ │ ├── combined-stream@1.0.5 deduped
│ │ │ │ └── mime-types@2.1.16 deduped
│ │ │ ├─┬ har-validator@2.0.6
│ │ │ │ ├── chalk@1.1.3 deduped
│ │ │ │ ├── commander@2.11.0
│ │ │ │ ├─┬ is-my-json-valid@2.16.0
│ │ │ │ │ ├── generate-function@2.0.0
│ │ │ │ │ ├─┬ generate-object-property@1.2.0
│ │ │ │ │ │ └── is-property@1.0.2
│ │ │ │ │ ├── jsonpointer@4.0.1
│ │ │ │ │ └── xtend@4.0.1
│ │ │ │ └─┬ pinkie-promise@2.0.1
│ │ │ │   └── pinkie@2.0.4
│ │ │ ├─┬ hawk@3.1.3
│ │ │ │ ├─┬ boom@2.10.1
│ │ │ │ │ └── hoek@2.16.3 deduped
│ │ │ │ ├─┬ cryptiles@2.0.5
│ │ │ │ │ └── boom@2.10.1 deduped
│ │ │ │ ├── hoek@2.16.3
│ │ │ │ └─┬ sntp@1.0.9
│ │ │ │   └── hoek@2.16.3 deduped
│ │ │ ├─┬ http-signature@1.1.1
│ │ │ │ ├── assert-plus@0.2.0
│ │ │ │ ├─┬ jsprim@1.4.1
│ │ │ │ │ ├── assert-plus@1.0.0
│ │ │ │ │ ├── extsprintf@1.3.0
│ │ │ │ │ ├── json-schema@0.2.3
│ │ │ │ │ └─┬ verror@1.10.0
│ │ │ │ │   ├── assert-plus@1.0.0
│ │ │ │ │   ├── core-util-is@1.0.2 deduped
│ │ │ │ │   └── extsprintf@1.3.0 deduped
│ │ │ │ └─┬ sshpk@1.13.1
│ │ │ │   ├── asn1@0.2.3
│ │ │ │   ├── assert-plus@1.0.0
│ │ │ │   ├─┬ bcrypt-pbkdf@1.0.1
│ │ │ │   │ └── tweetnacl@0.14.5 deduped
│ │ │ │   ├─┬ dashdash@1.14.1
│ │ │ │   │ └── assert-plus@1.0.0
│ │ │ │   ├─┬ ecc-jsbn@0.1.1
│ │ │ │   │ └── jsbn@0.1.1 deduped
│ │ │ │   ├─┬ getpass@0.1.7
│ │ │ │   │ └── assert-plus@1.0.0
│ │ │ │   ├── jsbn@0.1.1
│ │ │ │   └── tweetnacl@0.14.5
│ │ │ ├── is-typedarray@1.0.0
│ │ │ ├── isstream@0.1.2 deduped
│ │ │ ├── json-stringify-safe@5.0.1
│ │ │ ├─┬ mime-types@2.1.16
│ │ │ │ └── mime-db@1.29.0
│ │ │ ├── node-uuid@1.4.8
│ │ │ ├── oauth-sign@0.8.2
│ │ │ ├── qs@6.2.3
│ │ │ ├── stringstream@0.0.5
│ │ │ ├─┬ tough-cookie@2.3.2
│ │ │ │ └── punycode@1.4.1
│ │ │ └── tunnel-agent@0.4.3
│ │ ├── underscore@1.8.3
│ │ ├── uuid@3.1.0 deduped
│ │ ├── validator@3.35.0
│ │ ├─┬ xml2js@0.2.7
│ │ │ └── sax@0.5.2
│ │ └── xmlbuilder@0.4.3
│ ├─┬ debug@2.6.8
│ │ └── ms@2.0.0
│ ├── lodash@4.17.4
│ ├─┬ machina@2.0.0
│ │ └── lodash@3.10.1
│ └── traverse@0.6.6
├─┬ azure-iot-device-amqp@1.1.17
│ ├─┬ azure-iot-amqp-base@1.1.12
│ │ ├─┬ amqp10@3.5.0
│ │ │ ├── bl@1.1.2 deduped
│ │ │ ├── bluebird@3.5.0 deduped
│ │ │ ├── buffer-builder@0.2.0
│ │ │ ├── debug@2.6.8 deduped
│ │ │ ├── lodash@4.17.4 deduped
│ │ │ ├── node-int64@0.4.0
│ │ │ └── stately.js@1.3.0
│ │ ├─┬ amqp10-transport-ws@0.0.5
│ │ │ └── nodejs-websocket@1.7.1
│ │ ├── azure-iot-common@1.1.11 deduped
│ │ ├── bluebird@3.5.0
│ │ ├── debug@2.6.8 deduped
│ │ └── uuid@3.1.0 deduped
│ ├── azure-iot-common@1.1.11 deduped
│ ├── azure-iot-device@1.1.17 deduped
│ ├── debug@2.6.8 deduped
│ ├── machina@2.0.0 deduped
│ └── uuid@3.1.0
├── dblite@0.8.0
├─┬ eslint@4.4.0
│ ├─┬ ajv@5.2.2
│ │ ├── co@4.6.0
│ │ ├── fast-deep-equal@1.0.0
│ │ ├── json-schema-traverse@0.3.1
│ │ └── json-stable-stringify@1.0.1 deduped
│ ├─┬ babel-code-frame@6.22.0
│ │ ├── chalk@1.1.3 deduped
│ │ ├── esutils@2.0.2 deduped
│ │ └── js-tokens@3.0.2
│ ├─┬ chalk@1.1.3
│ │ ├── ansi-styles@2.2.1
│ │ ├── escape-string-regexp@1.0.5
│ │ ├─┬ has-ansi@2.0.0
│ │ │ └── ansi-regex@2.1.1
│ │ ├─┬ strip-ansi@3.0.1
│ │ │ └── ansi-regex@2.1.1 deduped
│ │ └── supports-color@2.0.0
│ ├─┬ concat-stream@1.6.0
│ │ ├── inherits@2.0.3
│ │ ├─┬ readable-stream@2.3.3
│ │ │ ├── core-util-is@1.0.2 deduped
│ │ │ ├── inherits@2.0.3 deduped
│ │ │ ├── isarray@1.0.0 deduped
│ │ │ ├── process-nextick-args@1.0.7 deduped
│ │ │ ├── safe-buffer@5.1.1
│ │ │ ├─┬ string_decoder@1.0.3
│ │ │ │ └── safe-buffer@5.1.1 deduped
│ │ │ └── util-deprecate@1.0.2 deduped
│ │ └── typedarray@0.0.6
│ ├─┬ cross-spawn@5.1.0
│ │ ├─┬ lru-cache@4.1.1
│ │ │ ├── pseudomap@1.0.2
│ │ │ └── yallist@2.1.2
│ │ ├─┬ shebang-command@1.2.0
│ │ │ └── shebang-regex@1.0.0
│ │ └─┬ which@1.3.0
│ │   └── isexe@2.0.0
│ ├── debug@2.6.8 deduped
│ ├─┬ doctrine@2.0.0
│ │ ├── esutils@2.0.2 deduped
│ │ └── isarray@1.0.0
│ ├─┬ eslint-scope@3.7.1
│ │ ├─┬ esrecurse@4.2.0
│ │ │ ├── estraverse@4.2.0 deduped
│ │ │ └── object-assign@4.1.1 deduped
│ │ └── estraverse@4.2.0 deduped
│ ├─┬ espree@3.5.0
│ │ ├── acorn@5.1.1
│ │ └─┬ acorn-jsx@3.0.1
│ │   └── acorn@3.3.0
│ ├─┬ esquery@1.0.0
│ │ └── estraverse@4.2.0 deduped
│ ├── estraverse@4.2.0
│ ├── esutils@2.0.2
│ ├─┬ file-entry-cache@2.0.0
│ │ ├─┬ flat-cache@1.2.2
│ │ │ ├── circular-json@0.3.3
│ │ │ ├─┬ del@2.2.2
│ │ │ │ ├─┬ globby@5.0.0
│ │ │ │ │ ├─┬ array-union@1.0.2
│ │ │ │ │ │ └── array-uniq@1.0.3
│ │ │ │ │ ├── arrify@1.0.1
│ │ │ │ │ ├── glob@7.1.2 deduped
│ │ │ │ │ ├── object-assign@4.1.1 deduped
│ │ │ │ │ ├── pify@2.3.0 deduped
│ │ │ │ │ └── pinkie-promise@2.0.1 deduped
│ │ │ │ ├── is-path-cwd@1.0.0
│ │ │ │ ├─┬ is-path-in-cwd@1.0.0
│ │ │ │ │ └─┬ is-path-inside@1.0.0
│ │ │ │ │   └── path-is-inside@1.0.2 deduped
│ │ │ │ ├── object-assign@4.1.1 deduped
│ │ │ │ ├── pify@2.3.0
│ │ │ │ ├── pinkie-promise@2.0.1 deduped
│ │ │ │ └─┬ rimraf@2.6.1
│ │ │ │   └── glob@7.1.2 deduped
│ │ │ ├── graceful-fs@4.1.11
│ │ │ └─┬ write@0.2.1
│ │ │   └── mkdirp@0.5.1 deduped
│ │ └── object-assign@4.1.1
│ ├── functional-red-black-tree@1.0.1
│ ├─┬ glob@7.1.2
│ │ ├── fs.realpath@1.0.0
│ │ ├─┬ inflight@1.0.6
│ │ │ ├── once@1.4.0 deduped
│ │ │ └── wrappy@1.0.2
│ │ ├── inherits@2.0.3 deduped
│ │ ├── minimatch@3.0.4 deduped
│ │ ├─┬ once@1.4.0
│ │ │ └── wrappy@1.0.2 deduped
│ │ └── path-is-absolute@1.0.1
│ ├── globals@9.18.0
│ ├── ignore@3.3.3
│ ├── imurmurhash@0.1.4
│ ├─┬ inquirer@3.2.1
│ │ ├── ansi-escapes@2.0.0
│ │ ├─┬ chalk@2.1.0
│ │ │ ├─┬ ansi-styles@3.2.0
│ │ │ │ └─┬ color-convert@1.9.0
│ │ │ │   └── color-name@1.1.3
│ │ │ ├── escape-string-regexp@1.0.5 deduped
│ │ │ └─┬ supports-color@4.2.1
│ │ │   └── has-flag@2.0.0
│ │ ├─┬ cli-cursor@2.1.0
│ │ │ └─┬ restore-cursor@2.0.0
│ │ │   ├─┬ onetime@2.0.1
│ │ │   │ └── mimic-fn@1.1.0 deduped
│ │ │   └── signal-exit@3.0.2 deduped
│ │ ├── cli-width@2.1.0
│ │ ├─┬ external-editor@2.0.4
│ │ │ ├── iconv-lite@0.4.18
│ │ │ ├── jschardet@1.5.1
│ │ │ └─┬ tmp@0.0.31
│ │ │   └── os-tmpdir@1.0.2
│ │ ├─┬ figures@2.0.0
│ │ │ └── escape-string-regexp@1.0.5 deduped
│ │ ├── lodash@4.17.4 deduped
│ │ ├── mute-stream@0.0.7
│ │ ├─┬ run-async@2.3.0
│ │ │ └── is-promise@2.1.0
│ │ ├── rx-lite@4.0.8
│ │ ├─┬ rx-lite-aggregates@4.0.8
│ │ │ └── rx-lite@4.0.8 deduped
│ │ ├── string-width@2.1.1 deduped
│ │ ├─┬ strip-ansi@4.0.0
│ │ │ └── ansi-regex@3.0.0
│ │ └── through@2.3.8
│ ├─┬ is-resolvable@1.0.0
│ │ └── tryit@1.0.3
│ ├─┬ js-yaml@3.9.1
│ │ ├─┬ argparse@1.0.9
│ │ │ └── sprintf-js@1.0.3
│ │ └── esprima@4.0.0
│ ├─┬ json-stable-stringify@1.0.1
│ │ └── jsonify@0.0.0
│ ├─┬ levn@0.3.0
│ │ ├── prelude-ls@1.1.2
│ │ └─┬ type-check@0.3.2
│ │   └── prelude-ls@1.1.2 deduped
│ ├── lodash@4.17.4 deduped
│ ├─┬ minimatch@3.0.4
│ │ └─┬ brace-expansion@1.1.8
│ │   ├── balanced-match@1.0.0
│ │   └── concat-map@0.0.1
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ ├── natural-compare@1.4.0
│ ├─┬ optionator@0.8.2
│ │ ├── deep-is@0.1.3
│ │ ├── fast-levenshtein@2.0.6
│ │ ├── levn@0.3.0 deduped
│ │ ├── prelude-ls@1.1.2 deduped
│ │ ├── type-check@0.3.2 deduped
│ │ └── wordwrap@1.0.0
│ ├── path-is-inside@1.0.2
│ ├── pluralize@4.0.0
│ ├── progress@2.0.0
│ ├─┬ require-uncached@1.0.3
│ │ ├─┬ caller-path@0.1.0
│ │ │ └── callsites@0.2.0
│ │ └── resolve-from@1.0.1
│ ├── semver@5.4.1
│ ├── strip-json-comments@2.0.1
│ ├─┬ table@4.0.1
│ │ ├─┬ ajv@4.11.8
│ │ │ ├── co@4.6.0 deduped
│ │ │ └── json-stable-stringify@1.0.1 deduped
│ │ ├── ajv-keywords@1.5.1
│ │ ├── chalk@1.1.3 deduped
│ │ ├── lodash@4.17.4 deduped
│ │ ├── slice-ansi@0.0.4
│ │ └── string-width@2.1.1 deduped
│ └── text-table@0.2.0
├─┬ winston@2.3.1
│ ├── async@1.0.0
│ ├── colors@1.0.3
│ ├── cycle@1.0.3
│ ├── eyes@0.1.8
│ ├── isstream@0.1.2
│ └── stack-trace@0.0.10
└─┬ yargs@8.0.2
  ├── camelcase@4.1.0
  ├─┬ cliui@3.2.0
  │ ├─┬ string-width@1.0.2
  │ │ ├── code-point-at@1.1.0
  │ │ ├─┬ is-fullwidth-code-point@1.0.0
  │ │ │ └── number-is-nan@1.0.1
  │ │ └── strip-ansi@3.0.1 deduped
  │ ├── strip-ansi@3.0.1 deduped
  │ └─┬ wrap-ansi@2.1.0
  │   ├─┬ string-width@1.0.2
  │   │ ├── code-point-at@1.1.0 deduped
  │   │ ├── is-fullwidth-code-point@1.0.0 deduped
  │   │ └── strip-ansi@3.0.1 deduped
  │   └── strip-ansi@3.0.1 deduped
  ├── decamelize@1.2.0
  ├── get-caller-file@1.0.2
  ├─┬ os-locale@2.1.0
  │ ├─┬ execa@0.7.0
  │ │ ├── cross-spawn@5.1.0 deduped
  │ │ ├── get-stream@3.0.0
  │ │ ├── is-stream@1.1.0
  │ │ ├─┬ npm-run-path@2.0.2
  │ │ │ └── path-key@2.0.1
  │ │ ├── p-finally@1.0.0
  │ │ ├── signal-exit@3.0.2
  │ │ └── strip-eof@1.0.0
  │ ├─┬ lcid@1.0.0
  │ │ └── invert-kv@1.0.0
  │ └─┬ mem@1.1.0
  │   └── mimic-fn@1.1.0
  ├─┬ read-pkg-up@2.0.0
  │ ├─┬ find-up@2.1.0
  │ │ └─┬ locate-path@2.0.0
  │ │   ├─┬ p-locate@2.0.0
  │ │   │ └── p-limit@1.1.0
  │ │   └── path-exists@3.0.0
  │ └─┬ read-pkg@2.0.0
  │   ├─┬ load-json-file@2.0.0
  │   │ ├── graceful-fs@4.1.11 deduped
  │   │ ├─┬ parse-json@2.2.0
  │   │ │ └─┬ error-ex@1.3.1
  │   │ │   └── is-arrayish@0.2.1
  │   │ ├── pify@2.3.0 deduped
  │   │ └── strip-bom@3.0.0
  │   ├─┬ normalize-package-data@2.4.0
  │   │ ├── hosted-git-info@2.5.0
  │   │ ├─┬ is-builtin-module@1.0.0
  │   │ │ └── builtin-modules@1.1.1
  │   │ ├── semver@5.4.1 deduped
  │   │ └─┬ validate-npm-package-license@3.0.1
  │   │   ├─┬ spdx-correct@1.0.2
  │   │   │ └── spdx-license-ids@1.2.2
  │   │   └── spdx-expression-parse@1.0.4
  │   └─┬ path-type@2.0.0
  │     └── pify@2.3.0 deduped
  ├── require-directory@2.1.1
  ├── require-main-filename@1.0.1
  ├── set-blocking@2.0.0
  ├─┬ string-width@2.1.1
  │ ├── is-fullwidth-code-point@2.0.0
  │ └─┬ strip-ansi@4.0.0
  │   └── ansi-regex@3.0.0
  ├── which-module@2.0.0
  ├── y18n@3.2.1
  └─┬ yargs-parser@7.0.0
    └── camelcase@4.1.0 deduped

# Description of the issue:
I'm getting the same (or very similar) issue as the issue reporter in #60 , even after updating to to v1.1.17 Device package with npm.

```
NotConnectedError: Cannot putToken while disconnected.
    at Amqp.putToken (<REMOVED>/node_modules/azure-iot-amqp-base/lib/amqp.js:485:50)
    at Amqp.updateSharedAccessSignature (<REMOVED>/node_modules/azure-iot-device-amqp/lib/amqp.js:198:20)
    at constructor.updateSharedAccessSignature (<REMOVED>/node_modules/azure-iot-device/lib/client.js:125:42)
    at constructor.handle (<REMOVED>/node_modules/machina/lib/machina.js:613:25)
    at constructor.Fsm.(anonymous function) [as handle] (<REMOVED>/node_modules/machina/lib/machina.js:466:63)
    at Client._renewSharedAccessSignature (<REMOVED>/node_modules/azure-iot-device/lib/client.js:671:19)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
2017-08-10T22:07:28.282Z - error: Uncaught Exception: Cannot putToken while disconnected.
```

This occurrs some time after a disconnect (sometimes shortly after, sometimes up to ~20 mins) resulting in that a couple of messages couldn't be sent (with error message `"AMQP Transport: Could not send"`). My application then reconnects and starts sending messages successfully again for the 20 minutes before the `NotConnectedError` exception is thrown.

There error seems intermittent and occurs after a disconnect (the "Disconnected from IoT hub" log entry below is printed ```.on``` disconnect: ```this._amqpClient.on('disconnect', () => this._handleDisconnect());```

# Console log of the issue:
```
{"level":"info","message":"Send message status: MessageEnqueued","timestamp":"2017-08-22T15:46:31.222Z"}
{"level":"info","message":"Send message status: MessageEnqueued","timestamp":"2017-08-22T15:46:34.862Z"}
{"level":"info","message":"Send message status: MessageEnqueued","timestamp":"2017-08-22T15:51:31.338Z"}
{"level":"info","message":"Send message status: MessageEnqueued","timestamp":"2017-08-22T15:51:35.199Z"}
{"level":"info","message":"Disconnected from IoT hub","timestamp":"2017-08-22T16:13:12.918Z"}
{"level":"info","message":"Disconnected from IoT hub","timestamp":"2017-08-22T16:13:12.955Z"}
{"level":"error","message":"AMQP Transport: Could not send","timestamp":"2017-08-22T16:13:13.079Z"}
{"level":"error","message":"AMQP Transport: Could not send","timestamp":"2017-08-22T16:13:13.082Z"}
{"level":"error","message":"AMQP Transport: Could not send","timestamp":"2017-08-22T16:13:13.084Z"}
{"message":"AMQP Transport: Could not send","stack":"Error: AMQP Transport: Could not send\n    at Object.translateError (<REMOVED>/node_modules/azure-iot-amqp-base/lib/amqp_common_errors.js:85:25)\n    at
<REMOVED>/node_modules/azure-iot-device-amqp/lib/amqp.js:26:40\n    at <REMOVED>/node_modules/azure-iot-amqp-base/lib/amqp.js:660:51\n    at _combinedTickCallback (internal/process/
next_tick.js:95:7)\n    at process._tickDomainCallback (internal/process/next_tick.js:198:9)","amqpError":{"name":"AmqpProtocolError","message":"amqp:link:detach-forced:detach-forced","condition":"amqp:link:detach-forced","description":"detach-forced"},"__error_callsites":[{},{},{},{},{}],"level":"error","timestamp":"2017-08-22T16:13:13.117Z"}
{"message":"AMQP Transport: Could not send","stack":"Error: AMQP Transport: Could not send\n    at Object.translateError (<REMOVED>/node_modules/azure-iot-amqp-base/lib/amqp_common_errors.js:85:25)\n    at <REMOVED>/node_modules/azure-iot-amqp-base/lib/amqp.js:660:51\n    at _combinedTickCallback (internal/process/next_tick.js:95:7)\n    at process._tickDomainCallback (internal/process/next_tick.js:198:9)","amqpError":{"name":"AmqpProtocolError","message":"amqp:link:detach-forced:detach-forced","condition":"amqp:link:detach-forced","description":"detach-forced"},"__error_callsites":[{},{},{},{},{}],"level":"error","timestamp":"2017-08-22T16:13:13.135Z"}
{"message":"AMQP Transport: Could not send","stack":"Error: AMQP Transport: Could not send\n    at Object.translateError (<REMOVED>/node_modules/azure-iot-amqp-base/lib/amqp_common_errors.js:85:25)\n    at <REMOVED>/node_modules/azure-iot-device-amqp/lib/amqp.js:26:40\n    at <REMOVED>/node_modules/azure-iot-amqp-base/lib/amqp.js:660:51\n    at _combinedTickCallback (internal/process/next_tick.js:95:7)\n    at process._tickDomainCallback (internal/process/next_tick.js:198:9)","amqpError":{"name":"AmqpProtocolError","message":"amqp:link:detach-forced:detach-forced","condition":"amqp:link:detach-forced","description":"detach-forced"},"__error_callsites":[{},{},{},{},{}],"level":"error","timestamp":"2017-08-22T16:13:13.148Z"}
{"level":"info","message":"Terminating scheduled transmissions","timestamp":"2017-08-22T16:13:20.041Z"}
{"level":"info","message":"Connecting to IoT Hub...\nHost: <REMOVED> DeviceId: <REMOVED>","timestamp":"2017-08-22T16:13:20.047Z"}
{"level":"info","message":"Connection to IoT Hub established","timestamp":"2017-08-22T16:13:21.696Z"}
{"level":"info","message":"Starting scheduled transmissions","timestamp":"2017-08-22T16:13:21.735Z"}
{"level":"info","message":"Send message status: MessageEnqueued","timestamp":"2017-08-22T16:13:22.105Z"}
{"level":"info","message":"Send message status: MessageEnqueued","timestamp":"2017-08-22T16:13:22.124Z"}
{"level":"info","message":"Send message status: MessageEnqueued","timestamp":"2017-08-22T16:13:22.130Z"}
{"level":"error","message":"Uncaught Exception: Cannot putToken while disconnected.","timestamp":"2017-08-22T16:14:53.554Z"}
```

**Comment by pierreca** [comment]
Hi @DanielStenis 

there are known issues with that bit of code and we are working on a fix that is part of an upgrade of the SDK to incorporate a retry mechanism. We should have that fix in by the end of the month or the beginning of September.

**Comment by DanielStenis** [comment]
Thank you for your response. Thankfully, I'm using a process manager to keep my application alive on my devices - so occasional exception crashes are handled by restarting the application.

Got to say, I'm finding it challenging to grasp the internal logic of SDK functions and what's going on inside it. Not a Javascript pro here, but some of the things I ask myself about it are:
* The connection seems to be established upon client object creation with clientFromConnectionString without having to call open(). What is open() for then?
* What happens .on 'disconnect'? Are there still things going on inside the SDK, e.g. reconnect handling or connection monitoring? What would be suitable actions here? I try to removeAllListeners and attempt to reconnect with open() (from a periodic connection monitor)
* Does calling sendEvent trigger (re)connection attempts?

**Comment by pierreca** [comment]
> The connection seems to be established upon client object creation with `clientFromConnectionString` without having to call `open()`. What is `open()` for then?

The connection is established with a call to `open()` or a call to any API - `clientFromConnectionString()` will not establish the connection.

> What happens .on 'disconnect'? Are there still things going on inside the SDK, e.g. reconnect handling or connection monitoring? What would be suitable actions here? I try to removeAllListeners, close() and attempt to reconnect with open() (from a periodic connection monitor)

`disconnect` is fired when the socket is closed, so at that point any object pertaining to the connection (connection, session and links in the case of AMQP) are considered in an unknown state and the client state machine reverts to the `disconnected` state - meaning any new operation will open a new connection. with that in mind:
- removing the listeners: will ensure that if you add them again the connection is reestablished. you shouldn't have to do that though. if you leave the listeners subscribed, any call to `open()` will reestablish the proper objects to fire messages and errors again and trigger your listeners.
- `close()` will not do anything (already in a disconnected state) 
- `open()` should reestablish the connection - and hook up the proper logic if you have a 

> Does calling `sendEvent` trigger (re)connection attempts?

Yes.

the change I have incoming is going to push state management down on the transport layer (AMQP in your case) and should dramatically simplify the client code. On top of that we're adding a default retry logic that uses exponential backoff with jitter, and the ability for users to define their own retry policy. that should make your life much easier. ETA is a bit of a moving target since I'm progressing on AMQP, MQTT and Client packages at the same time, but the goal is to make this change non-breaking.

**Comment by DanielStenis** [comment]
Thank you for thorough response Pierre, much appreciated. I actually switched from AMQP to MQTT and got it all working satisfactorily for now. An issue I noted with AMQP was that no new C2D messages could be received after the periodic SAS token update had occurred (e.g. after 45 mins). This was, however, not a problem with MQTT.

Looking forward to the new version then with the new connection handling functionality and hopefully a couple of fixes.

**Comment by pierreca** [comment]
> An issue I noted with AMQP was that no new C2D messages could be received after the periodic SAS token update had occurred (e.g. after 45 mins). This was, however, not a problem with MQTT.

That's concerning, we'll look into it. should definitely restore the links to receive messages.

I'm glad you're unblocked but is there anything that made you pick AMQP over MQTT at first?

**Comment by DanielStenis** [comment]
AMQP seemed to be the default choice in e.g. "simulated device" example code and from what I can gather the protocol has superior built-in security compared to MQTT.

**Comment by pierreca** [comment]
This error should be completely gone now that we've introduced state machines at the transport level. I'd encourage to upgrade to the latest package versions and let us know what you observe.

**Comment by DanielStenis** [comment]
Hi... I'm having a similar issue with MQTT direct method after updating to 1.1.19. After updating SAS, direct method subscription is timing out.

**Comment by pierreca** [comment]
I was talking specifically about the error that is in the title of this issue. if you have other issues (that may or may not be related) with direct methods i'd be super grateful if you could open a separate issue, makes it easier to track for us. Also I would like to understand what you mean when you say the subscription "is timing out".
