### ISSUE TITLE
[Question] How to remove deviceMethod listener?

### ISSUE THREAD

**Issue by cody-lettau** [Azure/azure-iot-sdk-node#78]
I am using ```onDeviceMethod``` and am wondering how I can remove a DeviceMethod listener if necessary? What is the recommended approach?

**Comment by pierreca** [comment]
We do not provide this possibility yet. Right now the only way for a user to achieve that would be to completely close and destroy the client object, and recreate a new one when necessary.

Is it just a general question or do you have a scenario in mind for that feature?

**Comment by cody-lettau** [comment]
Thanks for the quick response.

I was thinking of a scenario where we have multiple services that come online and go offline intermittently. Let's say that when one service is online, I want it to handle a specific method call. But in the case where that service is offline, I don't want to support that method.

Right now, a workaround that I am implementing is to have a generic method handler and maintain a map of registered callbacks. If a method call comes in and there is no callback in the map, I'll simply respond with a 404. I think this would meet my needs, but I'm not sure it's the ideal approach.

**Comment by pierreca** [comment]
I see.
I don't think we have a way to implement a generic method handler with the current API but this is something we have considered. Within the SDK code we are maintaining a map of method names and handlers.

Are you forking and implementing this generic callback yourself directly in the SDK code?

**Comment by cody-lettau** [comment]
I am adding a generic handler at the consumer-level. In my code, I use the same handler for every single method name and then I use the ```methodName``` on the request object to lookup the callback in the callback map that should be called. If it does not exist in the callback map, then I send a 404 on the response.

It's not urgent that support for this be added, as I believe this approach should work for now. Although, it may be useful for others in the future.

**Comment by pierreca** [comment]
Got it - closing based on the fact that Issues are not a good way to track future features but I'll try and remember to update it when we add support for this scenario. Thanks a lot for your feedback!
