### ISSUE TITLE
`mqtt.setTransportOptions` ignores specified options

### ISSUE THREAD

**Issue by ghost** [Azure/azure-iot-sdk-node#794]
# Context

- **OS and version used:** Debian GNU/Linux 9.12
- **Node.js version:** v12.16.3
- **npm version:** 6.14.4
- **list of installed packages:** 
├─┬ azure-iot-provisioning-device@1.8.2
│ ├─┬ azure-iot-common@1.12.2
│ │ ├── debug@4.1.1 deduped
│ │ └─┬ getos@3.2.0
│ │   └── async@3.2.0
│ ├─┬ debug@4.1.1
│ │ └── ms@2.1.2
│ └─┬ machina@4.0.2
│   └── lodash@4.17.15
├─┬ azure-iot-provisioning-device-mqtt@1.7.2
│ ├── azure-iot-common@1.12.2 deduped
│ ├─┬ azure-iot-mqtt-base@1.12.1
│ │ ├── azure-iot-common@1.12.2 deduped
│ │ ├── debug@4.1.1 deduped
│ │ ├── machina@4.0.2 deduped
│ │ └─┬ mqtt@4.0.1
│ │   ├── base64-js@1.3.1
│ │   ├─┬ commist@1.1.0
│ │   │ ├── leven@2.1.0
│ │   │ └── minimist@1.2.5 deduped
│ │   ├─┬ concat-stream@1.6.2
│ │   │ ├── buffer-from@1.1.1
│ │   │ ├── inherits@2.0.4 deduped
│ │   │ ├── readable-stream@2.3.7 deduped
│ │   │ └── typedarray@0.0.6
│ │   ├─┬ end-of-stream@1.4.4
│ │   │ └─┬ once@1.4.0
│ │   │   └── wrappy@1.0.2
│ │   ├─┬ es6-map@0.1.5
│ │   │ ├─┬ d@1.0.1
│ │   │ │ ├── es5-ext@0.10.53 deduped
│ │   │ │ └── type@1.2.0
│ │   │ ├─┬ es5-ext@0.10.53
│ │   │ │ ├── es6-iterator@2.0.3 deduped
│ │   │ │ ├── es6-symbol@3.1.3 deduped
│ │   │ │ └── next-tick@1.0.0
│ │   │ ├─┬ es6-iterator@2.0.3
│ │   │ │ ├── d@1.0.1 deduped
│ │   │ │ ├── es5-ext@0.10.53 deduped
│ │   │ │ └── es6-symbol@3.1.3 deduped
│ │   │ ├─┬ es6-set@0.1.5
│ │   │ │ ├── d@1.0.1 deduped
│ │   │ │ ├── es5-ext@0.10.53 deduped
│ │   │ │ ├── es6-iterator@2.0.3 deduped
│ │   │ │ ├─┬ es6-symbol@3.1.1
│ │   │ │ │ ├── d@1.0.1 deduped
│ │   │ │ │ └── es5-ext@0.10.53 deduped
│ │   │ │ └── event-emitter@0.3.5 deduped
│ │   │ ├─┬ es6-symbol@3.1.3
│ │   │ │ ├── d@1.0.1 deduped
│ │   │ │ └─┬ ext@1.4.0
│ │   │ │   └── type@2.0.0
│ │   │ └─┬ event-emitter@0.3.5
│ │   │   ├── d@1.0.1 deduped
│ │   │   └── es5-ext@0.10.53 deduped
│ │   ├─┬ help-me@1.1.0
│ │   │ ├─┬ callback-stream@1.1.0
│ │   │ │ ├── inherits@2.0.4 deduped
│ │   │ │ └── readable-stream@2.3.7 deduped
│ │   │ ├─┬ glob-stream@6.1.0
│ │   │ │ ├── extend@3.0.2
│ │   │ │ ├─┬ glob@7.1.6
│ │   │ │ │ ├── fs.realpath@1.0.0
│ │   │ │ │ ├─┬ inflight@1.0.6
│ │   │ │ │ │ ├── once@1.4.0 deduped
│ │   │ │ │ │ └── wrappy@1.0.2 deduped
│ │   │ │ │ ├── inherits@2.0.4 deduped
│ │   │ │ │ ├─┬ minimatch@3.0.4
│ │   │ │ │ │ └─┬ brace-expansion@1.1.11
│ │   │ │ │ │   ├── balanced-match@1.0.0
│ │   │ │ │ │   └── concat-map@0.0.1
│ │   │ │ │ ├── once@1.4.0 deduped
│ │   │ │ │ └── path-is-absolute@1.0.1
│ │   │ │ ├─┬ glob-parent@3.1.0
│ │   │ │ │ ├─┬ is-glob@3.1.0
│ │   │ │ │ │ └── is-extglob@2.1.1
│ │   │ │ │ └── path-dirname@1.0.2
│ │   │ │ ├── is-negated-glob@1.0.0
│ │   │ │ ├─┬ ordered-read-streams@1.0.1
│ │   │ │ │ └── readable-stream@2.3.7 deduped
│ │   │ │ ├─┬ pumpify@1.5.1
│ │   │ │ │ ├── duplexify@3.7.1 deduped
│ │   │ │ │ ├── inherits@2.0.4 deduped
│ │   │ │ │ └─┬ pump@2.0.1
│ │   │ │ │   ├── end-of-stream@1.4.4 deduped
│ │   │ │ │   └── once@1.4.0 deduped
│ │   │ │ ├── readable-stream@2.3.7 deduped
│ │   │ │ ├── remove-trailing-separator@1.1.0
│ │   │ │ ├─┬ to-absolute-glob@2.0.2
│ │   │ │ │ ├─┬ is-absolute@1.0.0
│ │   │ │ │ │ ├─┬ is-relative@1.0.0
│ │   │ │ │ │ │ └─┬ is-unc-path@1.0.0
│ │   │ │ │ │ │   └── unc-path-regex@0.1.2
│ │   │ │ │ │ └── is-windows@1.0.2
│ │   │ │ │ └── is-negated-glob@1.0.0 deduped
│ │   │ │ └─┬ unique-stream@2.3.1
│ │   │ │   ├── json-stable-stringify-without-jsonify@1.0.1
│ │   │ │   └─┬ through2-filter@3.0.0
│ │   │ │     ├── through2@2.0.5 deduped
│ │   │ │     └── xtend@4.0.2 deduped
│ │   │ ├─┬ through2@2.0.5
│ │   │ │ ├── readable-stream@2.3.7 deduped
│ │   │ │ └── xtend@4.0.2 deduped
│ │   │ └── xtend@4.0.2 deduped
│ │   ├── inherits@2.0.4
│ │   ├── minimist@1.2.5
│ │   ├─┬ mqtt-packet@6.3.2
│ │   │ ├─┬ bl@1.2.2
│ │   │ │ ├── readable-stream@2.3.7 deduped
│ │   │ │ └── safe-buffer@5.2.1 deduped
│ │   │ ├── debug@4.1.1 deduped
│ │   │ ├── inherits@2.0.4 deduped
│ │   │ ├── process-nextick-args@2.0.1
│ │   │ └── safe-buffer@5.2.1
│ │   ├─┬ pump@3.0.0
│ │   │ ├── end-of-stream@1.4.4 deduped
│ │   │ └── once@1.4.0 deduped
│ │   ├─┬ readable-stream@2.3.7
│ │   │ ├── core-util-is@1.0.2
│ │   │ ├── inherits@2.0.4 deduped
│ │   │ ├── isarray@1.0.0
│ │   │ ├── process-nextick-args@2.0.1 deduped
│ │   │ ├── safe-buffer@5.1.2
│ │   │ ├─┬ string_decoder@1.1.1
│ │   │ │ └── safe-buffer@5.1.2
│ │   │ └── util-deprecate@1.0.2
│ │   ├── reinterval@1.1.0
│ │   ├─┬ split2@3.1.1
│ │   │ └─┬ readable-stream@3.6.0
│ │   │   ├── inherits@2.0.4 deduped
│ │   │   ├─┬ string_decoder@1.3.0
│ │   │   │ └── safe-buffer@5.2.1 deduped
│ │   │   └── util-deprecate@1.0.2 deduped
│ │   ├─┬ websocket-stream@5.5.2
│ │   │ ├─┬ duplexify@3.7.1
│ │   │ │ ├── end-of-stream@1.4.4 deduped
│ │   │ │ ├── inherits@2.0.4 deduped
│ │   │ │ ├── readable-stream@2.3.7 deduped
│ │   │ │ └── stream-shift@1.0.1
│ │   │ ├── inherits@2.0.4 deduped
│ │   │ ├── readable-stream@2.3.7 deduped
│ │   │ ├── safe-buffer@5.2.1 deduped
│ │   │ ├─┬ ws@3.3.3
│ │   │ │ ├── async-limiter@1.0.1
│ │   │ │ ├── safe-buffer@5.1.2
│ │   │ │ └── ultron@1.1.1
│ │   │ └── xtend@4.0.2 deduped
│ │   └── xtend@4.0.2
│ ├── azure-iot-provisioning-device@1.8.2 deduped
│ ├── debug@4.1.1 deduped
│ ├── machina@4.0.2 deduped
│ └── uuid@3.4.0
├─┬ azure-iot-security-x509@1.7.2
│ ├── azure-iot-common@1.12.2 deduped
│ └── debug@4.1.1 deduped
└─┬ https-proxy-agent@5.0.0
  ├─┬ agent-base@6.0.0
  │ └── debug@4.1.1 deduped
  └── debug@4.1.1 deduped

## Description of the issue

I've configured the DPS client to connect to the DPS using a proxy, but the specified proxy settings are ignored by the SDK, thus trying to register the device fails.

I think the problem is [the following line of code](https://github.com/Azure/azure-iot-sdk-node/blob/master/provisioning/transport/mqtt/src/mqtt.ts#L224). It seems that only `pollingInterval` is set on the MQTT client, not `webSocketAgent` which is the one I've configured.

## Code sample exhibiting the issue

```javascript
// This code is basically a copy of https://github.com/Azure-Samples/azure-iot-samples-node/blob/master/provisioning/Samples/device/register_x509.js

"use strict";

var fs = require("fs");
var HttpsProxyAgent = require("https-proxy-agent");

var Transport = require("azure-iot-provisioning-device-mqtt").MqttWs;
var X509Security = require("azure-iot-security-x509").X509Security;
var ProvisioningDeviceClient = require("azure-iot-provisioning-device")
  .ProvisioningDeviceClient;

var idScope = process.env.ID_SCOPE;
if (!idScope) {
  console.error(
    "please set the ID_SCOPE environment variable to the one you want to use."
  );
  process.exit(-1);
}

var registrationId = process.env.REGISTRATION_ID;
if (!registrationId) {
  console.error(
    "please set the REGISTRATION_ID environment variable to the one you want to use."
  );
  process.exit(-1);
}

var proxy = process.env.HTTPS_PROXY;
if (!proxy) {
  console.log("Please set the HTTPS_PROXY environment variable.");
  process.exit(-1);
}

var deviceCert = {
  cert: fs.readFileSync("cert.pem").toString(),
  key: fs.readFileSync("key.pem").toString(),
};

var transport = new Transport();

// THIS IS THE ISSUE: `webSocketAgent` is ignored by the function `setTransportOptions`, thus my connection will fail
transport.setTransportOptions({
  webSocketAgent: new HttpsProxyAgent(proxy),
});

var securityClient = new X509Security(registrationId, deviceCert);
var deviceClient = ProvisioningDeviceClient.create(
  "global.azure-devices-provisioning.net",
  idScope,
  transport,
  securityClient
);

deviceClient.register(function (err, result) {
  if (err) {
    console.log("error registering device: " + err);
    process.exit(-1);
  } else {
    console.log("registration succeeded");
    console.log("assigned hub=" + result.assignedHub);
    console.log("deviceId=" + result.deviceId);
    process.exit(0);
  }
});

```

AB#7366649

**Comment by anthonyvercolano** [comment]
Thank you for raising this issue.

This is an interesting issue.  I will say however that this is not something that will get a lot of time till the summer.

If you wish to submit a PR we would be happy to take a look.  Note that as well as doing the code, PRs need to include fairly good documentation and thorough unit tests that do not decrease the code coverage.  If e2e tests were included that would be nice.  Easy samples to validate the code are helpful also.  We generally don't do much with proxies ourselves, so helpful guides would assist in our evaluation.

**Comment by mattias-kindborg-axis-communications** [comment]
Hi and thank you for the quick feedback!

I don't think I can prioritize this either. But what I can say is that the AMQP DPS transport is supporting proxies, and I would think that one could be inspired by their documentation, as well as their unit/e2e tests. The IoT Hub MQTT transport is also supporting proxies, one can take a look at it as well.

I've opted to use the AMQP transport instead of MQTT. From the perspective of our users it doesn't matter, it's more about my love for the simplicity of MQTT that I'd opt for that protocol.

Anyway, keep up the good work!

**Comment by mattias-kindborg-axis-communications** [comment]
I would still call this a bug though, not an enhancement, since your API is supporting websocket agents, but your implementation isn't.

Wouldn't labeling this as an enhancement decreases the chances of it getting fixed?

Another option is to remove the support for websocket agents from the API, but that is a breaking change and would require a new major version.

Just me 5 cents.

**Comment by YoDaMa** [comment]
wait @mattias-kindborg-axis-communications could you clarify, you're using AMQP because you like the simplicity of MQTT? Just trying to understand that part.

**Comment by YoDaMa** [comment]
@anthonyvercolano I'm seeing in MQTT.js the [following sample that uses proxy settings](https://github.com/mqttjs/MQTT.js/blob/fc6ca1d2f873b6e568506e0e015af8a2931986f5/examples/wss/client_with_proxy.js)

My thought is if we add the configuration for proxy settings, i.e. as @mattias-kindborg-axis-communications said, add support for webSocketAgent below [this line in the mqtt provisioning transport](https://github.com/Azure/azure-iot-sdk-node/blob/master/provisioning/transport/mqtt/src/mqtt.ts#L224), then make sure that is translated correctly in the provisioning transport, and passed into the [baseConfig here](https://github.com/Azure/azure-iot-sdk-node/blob/master/provisioning/transport/mqtt/src/mqtt.ts#L303). When it gets down to the `mqtt-base.ts`, it just needs to then be passed to `wsOptions`, which MQTT.js can ingest. This is just my initial diagnosis of the problem / solution.

**Comment by mattias-kindborg-axis-communications** [comment]
> wait @mattias-kindborg-axis-communications could you clarify, you're using AMQP because you like the simplicity of MQTT? Just trying to understand that part.

Sorry for the confusion. Please let me clarify.

You support a lot of protocols. You support AMQP, AMQP over websockets, MQTT, MQTT over websockets and finally you support HTTPS. Of all these options I'd chosen MQTT over websockets. MQTT because I like the simplicity of the protocol (at least when compared with AMQP), but tunneled over websockets since our proxy only accept outgoing connections on port 80 and 443.

Now, because you have this bug in your MQTT transport where my specified agent isn't respected by your implementations, I've changed my code to use AMQP over websockets instead. You are no longer blocking me, but when this issue is fixed I will go back to use MQTT over websockets again.

Does this explain your question?

**Comment by anthonyvercolano** [comment]
It is not in our plans to fix this issue. We would take a PR.

**Comment by RohitashavSoni** [comment]
Hello @ghost we also faced the same issue but after switching to amqp over websocket its working fine, I have another question in proxy environment how are you performing enrollment ? if you can share a sample code that will really great.
