### ISSUE TITLE
DigitalTwins service SDK errors when used from TypeScript

### ISSUE THREAD

**Issue by ridomin** [Azure/azure-iot-sdk-node#795]
I'd like to use [azure-iot-digitaltwins-service](https://www.npmjs.com/package/azure-iot-digitaltwins-service) from TypeScript, but once I configured my project I got the next tsc errors:

```
node_modules/azure-iot-digitaltwins-service/index.d.ts:1:1 - error TS1191: An import declaration cannot have modifiers.

1 export import { IoTHubTokenCredentials } from './dist/auth/iothub_token_credentials';
  ~~~~~~

node_modules/azure-iot-digitaltwins-service/index.d.ts:2:1 - error TS1191: An import declaration cannot have modifiers.

2 export import { DigitalTwinServiceClient } from './dist/cl/digital_twin_service_client';
  ~~~~~~
```

Repro Steps:
```bash
mkdir repro && cd repro
npm init -y && tsc --init
npm i azure-iot-digitaltwins-service
echo import * as dt from 'azure-iot-digitaltwins-service' > index.ts
tsc
```
**Expected**
I verified the same steps with the package `azure-iot-provisioning-service` with success.

**Observed**
The error above

AB#7366648

**Comment by YoDaMa** [comment]
@ridomin thank you for reporting this bug! Let's investigate the problem.

**Comment by az-iot-builder-01** [comment]
@ridomin, @YoDaMa, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
