### ISSUE TITLE
missing MQTT cleanup on error causes app crash

### ISSUE THREAD

**Issue by BertKleewein** [Azure/azure-iot-sdk-node#807]
I'm using simple_sample_device.js and a bad connection string to repro this, but I've seen this in other scenarios where client.open fails.

to repro: use a symmetric key connection string with mqtt.  change the HostName by 1 character to make it invalid.  Run simple_sample_device.js

result:
```
Could not connect: mqtt.js returned Failure on first connection (Not authorized): getaddrinfo ENOTFOUND REDACTED.azure-devices.net REDACTED.azure-devices.net:8883 error
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND REDACTED.azure-devices.net REDACTED.azure-devices.net:8883
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
Emitted 'error' event at:
    at TLSSocket.streamErrorHandler (/home/bertk/repos/node/common/transport/mqtt/node_modules/mqtt/lib/client.js:342:12)
    at TLSSocket.emit (events.js:203:15)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(horton) bertk@homework:~/repos/node/device/samples$
```

Because the on('error') handler is missing from the TLS stream, the node executable force quits.

One possible fix in is mqtt_base.ts around line 66:
```
        connecting: {
          _onEnter: (connectCallback) => {
            this._connectClient((err, connack) => {
            if (err) {
                // The problem is here
                // This transition skips cleanup.  If you change 'disconnected' to 'disconnecting', things are cleaned up correctly
                this._fsm.transition('disconnected', connectCallback, err);
              } else {

```

AB#7366651

**Comment by anthonyvercolano** [comment]
@BertKleewein what versions of the client stack were you using?  In particular the mqtt-base and mqtt.js?

**Comment by anthonyvercolano** [comment]
@BertKleewein Actually never mind.  I was trying this is some code that was effectively already doing what you suggested.  I'm not a big fan of the code in the _onEnter for the connecting state.  The callback for the ._connectClient call is effectively used as the error event listener/handler from that point forward.  This get set in the ._connectClient call and is never changed.  I am thinking that upon successful return from ._connectClient this handler should be removed and replaced with an error listener/handler that does NOT have a "dependency" on the connectCallback argument to the connecting _onEnter.

**Comment by anthonyvercolano** [comment]
@BertKleewein The current release seems to fix this problem, although oddly, it takes a bit of time after giving you an error for the sample to actually exit.  This is when you simply change the hostname.  If you change the device or the key it fails immediately.  Bit odd so I'm going to keep this open till I figure out what the delay on the hostname case is.

**Comment by anthonyvercolano** [comment]
Determined that the "hang" at close was due to an error in the mqttjs client.  It doesn't clear the timer used to timeout a connack (which will never come).

**Comment by az-iot-builder-01** [comment]
@BertKleewein, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
