### ISSUE TITLE
azure-iot-provisioning-service: cannot set query value

### ISSUE THREAD

**Issue by paolerm** [Azure/azure-iot-sdk-node#814]
- **What version of the SDK are you using?** 1.8.3
- **Do you have a snippet of code that would help us reproduce the bug?**
`
client = ProvisioningServiceClient.fromConnectionString("<DPS-CONNECTION-STRING>);
const query = "SELECT * FROM registrations WHERE registrations.registrationId = 'paermini-real'";
 const queryObj: Query = client.createEnrollmentGroupDeviceRegistrationStateQuery({ query }, 'enrollmentGroupId');
...
queryObj.next(continuationToken, async (err: any, result: any) => {
// filter ignored
});

`
- **Do you have logs showing what's happening?**
https://iothub.kusto.windows.net/IotDps?query=H4sIAAAAAAAEAHWQT2vCQBDF74V%2bh8VTe1iz2WyikVpIdkfZotm4E4WeStClzaGJxGgp9MM31oNeehnmz%2fvxeKP2h1WDcHJ1R%2b7vfsjXh2sdcfXpras%2bHXmekl3ZuXP%2fwBlnlEWUceJHE8YmQTDk44BH8eiRlPXuSj39S4XxLXU1bN2hObZbp3dkOiUDD9cpSqvzQpsMPaZ8SKSKqQAx6wsENGZC0DD25QgiwcOZ71lAs7YS5tasc%2fRya15AFphkhbE603RhZLKg6jVLllpS%2fyzYaAUWvX62Bs2sGCrYaAl4uWHvrbM5gr0sMUmQqhxpFPIU0hGjfsiBCslnNB0HARURAONhrKKQDa7Zmr1ry65q6qzsf3OOtzq69vtGsXRdW23F38269%2brQXYDBL8SD%2fxaeAQAA&web=0

DpsQoSEvent 
| where env_time >= datetime(2020-06-02 16:00:33.2832697) and env_time <= datetime(2020-06-02 16:59:33.2832697)
| where resourceId == "/SUBSCRIPTIONS/0D1EACD9-4E4F-4EE3-9044-591C7E6425F1/RESOURCEGROUPS/PROJECTSANTORINI-LOCAL-DYNAMIC-1/PROVIDERS/MICROSOFT.DEVICES/PROVISIONINGSERVICES/SAAS-DPS-652BEB70-152E-4C2F-B833-46EE0259D650"
| where operationName == "Query"
| where Metric4 == "Registration"

https://github.com/Azure/azure-iot-sdk-node/blob/1339db5bf4de1c12bd13dc8f4b584d0c0713fb47/provisioning/service/src/provisioningserviceclient.ts#L198

I didn't find any example of Registration queries, so I don't know if the query is invalid

AB#7353277

**Comment by anthonyvercolano** [comment]
Basically dps doesn't support the query string.  All you can do is specify an empty string "".

**Comment by az-iot-builder-01** [comment]
@paolerm, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
