### ISSUE TITLE
Failure on first connection (Not authorized) - unhandled exceptions

### ISSUE THREAD

**Issue by a8775** [Azure/azure-iot-sdk-node#817]
# Context

- **OS and version used:** Windows 10
- **Node.js version:** 10.17.0
- **npm version:** 6.14.5
- **list of installed packages:** 
    "azure-iot-device": "^1.16.0",
    "azure-iot-device-mqtt": "^1.14.1",
    "azure-iothub": "^1.12.3",

## Description of the issue

After upgrade azure-iot-sdk-node from v1.14.0 to 1.16.0 I'm experiencing the following unhandled exceptions:

```
(node:30288) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT 13.95.15.251:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
(node:30288) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

(node:30288) UnhandledPromiseRejectionWarning: UnauthorizedError: mqtt.js returned Failure on first connection (Not authorized): connect ETIMEDOUT 13.95.15.251:8883 error
(node:30288) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 87)

(node:30000) UnhandledPromiseRejectionWarning: InternalServerError: Error: 
(node:30000) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 230)
```

and I'm catching exception:
```
UnauthorizedError: mqtt.js returned Failure on first connection (Not authorized): connect ETIMEDOUT 13.95.15.251:8883 error
```

I believe the origin of this exceptions come from #776 v1.15.0

I checked the code and it seems I try-catch every SDK statement. 

AB#7369024

**Comment by az-iot-builder-01** [comment]
@a8775, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
