### ISSUE TITLE
setOptions is destructive and replaces the CA cert used by edge auth (among other things)

### ISSUE THREAD

**Issue by BertKleewein** [Azure/azure-iot-sdk-node#820]
# Code reproducing the issue:
var client=ModuleClient.fromEnvironment(glueUtils.transportFromType("mqtt')
client.setOptions({keepalive: 120})
client.open(callbacsk)

# result:
client cannot connect.  the setOptions call in the second line caused the CA cert that was retrieved in the first line to be discarded. 

# workaround:
I hate doing this and this is not recommended, but I'm going to replace client.setOptions({keepAlive: 120}) with
client._transport._options.keepalive = 120
until a fix is available.   

AB#7422214

**Comment by jebrando** [comment]
Thank you Mr @BertKleewein for the issue, but unfortunately we have not have the bandwidth to fix this issue.  Feel free to submit a PR.  Thank you for your time and patience.

**Comment by az-iot-builder-01** [comment]
@BertKleewein, @jebrando, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
