### ISSUE TITLE
How to detect reconnection to IoT hub? Is there any event?

### ISSUE THREAD

**Issue by K0ertis** [Azure/azure-iot-sdk-node#822]
Hi,
I have trouble to get an event for the connection state on the iotClient.
At the other hand the disconnection works fine:  `client.on('disconnect', callbackDisconnect);`  but I can't detect a connection. 
Debugging is strange, I guess it points to the wrong address because on a `client.on(` it only checks if the eventName === 'message' and none more, but the disconnect callback is registered though.

In the code for azure-iot-device-mqtt/lib/mqtt.js : 215 there is the part for connecting which I guess should emit a connecting/ connected event as it does for disconnect at line 74. But nothing is emitted for connecting/connected state, is this the desired behavior?

Maybe it is relevant to mention that I use the NoRetry() from auzire-iot-common/lib/retry_policy in `client.setRetryPolicy(new NoRetry())`. Does this have an impact at this behavior? 

Using Win10 with versions: 
```
    "azure-iot-common": "^1.12.3",
    "azure-iot-device": "^1.16.0",
    "azure-iot-device-mqtt": "^1.14.1",
    "azure-iot-provisioning-device": "^1.8.0",
    "azure-iot-provisioning-device-mqtt": "^1.7.0",
    "azure-iot-security-symmetric-key": "^1.7.0",
```

AB#7465644

**Comment by anthonyvercolano** [comment]
Well lucky you.  We are adding an event that can be listened on for the connect.  I'll leave this question open for when it happens (which should be quite soon).

**Comment by anthonyvercolano** [comment]
Released

**Comment by az-iot-builder-01** [comment]
@K0ertis, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by jaripenttinen** [comment]
Is it somewhere documented what is that added event? I tried to find, no luck.

I want to use built-in retry mechanism of azure-iot-device, but I need to know when connection drops and when its back on.
I do not seem to get any connected nor disconnected event when this happens. Is there some way to detect this?
