### ISSUE TITLE
Expected expiry time value on C2D message

### ISSUE THREAD

**Issue by paolerm** [Azure/azure-iot-sdk-node#825]
I'm trying to set this value with a custom value (1 day)

https://github.com/Azure/azure-iot-sdk-node/blob/9713b2f4d001c5ac868320b25850cad0481bdf85/common/core/src/message.ts#L32

I've tried to follow this [C2D documentation](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-messages-c2d#cloud-to-device-configuration-options) and I set a valid duration ISO string (P1D) but it looks like client.send function does not return. I've tried also with a Date object and a ISO string date with no success.

What's the expected value for expiryTimeUtc field?

AB#7542162

**Comment by paolerm** [comment]
Found response here: https://github.com/Azure/azure-iot-sdk-node/issues/151

**Comment by az-iot-builder-01** [comment]
@paolerm, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
