### ISSUE TITLE
Remove deprecated dependency `crypto`

### ISSUE THREAD

**Issue by lusentis** [Azure/azure-iot-sdk-node#84]
# Context
- **OS and version used:** n/a
- **Node.js version:** 8.4.0
- **npm version:** 5.3.0
- **list of installed packages:** `azure-iot-common@1.1.11`

# Description of the issue:
The `azure-iot-common` npm package lists [`crypto` as a dependency](https://github.com/Azure/azure-iot-sdk-node/blob/master/common/core/package.json#L10), while this is not needed anymore and generate a deprecation warning on install. The built-in `crypto` module should be used instead.
To replicate, just install this module using `npm`.

# Code sample exhibiting the issue:
```bash
$ npm install azure-iot-common
```

# Console log of the issue:
```
npm WARN deprecated crypto@0.0.3: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
```

**Comment by pierreca** [comment]
Good point. wanted to do that for a while, thanks for motivating that change by opening the issue!

**Comment by Shahanshah-TA** [comment]
crypto is still being used.
