### ISSUE TITLE
Schedule job only works with all parameters given

### ISSUE THREAD

**Issue by Suizi11** [Azure/azure-iot-sdk-node#847]
# Context

- **OS and version used:** macOS 
- **Node.js version:** v13.7.0 
- **npm version:** 6.14.5 
- **list of installed packages:** azure-iothub@1.12.4 

## Description of the issue

There are a few overloaded methods provided by the IoT Hub service as referenced in the docs: https://docs.microsoft.com/en-us/javascript/api/azure-iothub/jobclient?view=azure-node-latest#scheduledevicemethod-string---number--string--devicemethodparams-

For me only the method works where all parameters are specified. If not all parameters are provided the remaining (unset) parameters are set to `null` which leads to the error response shown below.

I've tested it with the REST API where no problem did occur. If I set the "optional" parameters there to `null` then I get the same error response.

## Code sample exhibiting the issue

Default parameters:
```
const methodPayload: DeviceMethodParams = {
            methodName: 'ping',
            payload: 0,
            responseTimeoutInSeconds: 10,
            connectTimeoutInSeconds: 10
        }
const queryCondition = "FROM devices.modules WHERE ModuleId = '$edgeAgent'";
```

Error:
```
this.jobClient.scheduleDeviceMethod('testJobSDK1', queryCondition, methodPayload, (error, job, response) => {
            console.log('error: ' + error);
            console.log('job: ' + job);
            console.log('response: ' + response);
        });
```

OK:
this.jobClient.scheduleDeviceMethod('testJobSDK1', queryCondition, methodPayload, new Date(), 5, (error, job, response) => {
            console.log('error: ' + error);
            console.log('job: ' + job);
            console.log('response: ' + response);
        });

## Console log of the issue

ArgumentError: BadRequest
{"Message":"ErrorCode:GenericBadRequest;BadRequest","ExceptionMessage":"Tracking ID:3d154b347bb3471481c6469ed7786784-G:9-TimeStamp:07/10/2020 06:50:58"}

AB#7708814

**Comment by az-iot-builder-01** [comment]
@Suizi11, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
