### ISSUE TITLE
[Technical Question] AMQP Transport: Could not get feedback receiver

### ISSUE THREAD

**Issue by donniekerr** [Azure/azure-iot-sdk-node#857]
What does this feedback error mean?  I google it and can't find anything. Thanks

AMQP Transport: Could not get feedback receiver

I'm using this exact code inside an Azure Function 
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-node-node-c2d#send-a-cloud-to-device-message

AB#7764617

**Comment by anthonyvercolano** [comment]
What type of hub are you using?  Basic s1 s2?

**Comment by donniekerr** [comment]
S1 Standard

**Comment by anthonyvercolano** [comment]
Is this happening all the time? Or were you only seeing this occasionally?

The exact same code as the link?

What it means is that an attempt to setup a connection to the feedback endpoint didn't go so well.  Perhaps the message could be a bit more helpful.

Well, there are some things that you might supply at this point like version of the azure-iothub client.

In addition, If you can manage to get logs in the azure function you might give that a try.

To enable debug logs set the environment variable DEBUG to "azure*,rhea*". 

set DEBUG="azure*,rhea*"

**Comment by anthonyvercolano** [comment]
If you have support, they might be able to look at hub logs and give you an idea about what occurred.

**Comment by donniekerr** [comment]
Thanks @anthonyvercolano .  Appreciate the help. 
Happens all the time.  Yes, exact same code in the sample. Only difference is that the node is running in an Azure Function. 
I installed the latest version of azure-iothub as of yesterday. 

I will provide more details.  Initially I was just wondering what the error meant because the error doesn't even point me a direction to look. Can the feedback provide more verbose errors?  Because all azure function is doing is returning the error from the sdk.

**Comment by elhorton** [comment]
We are closing this issue because it would have to be an investment in AMQP which is not prioritized. If others would like to see this improvement, please add a comment in support and file/upvote on our [Azure Feedback Page](https://feedback.azure.com/forums/321918-azure-iot). Thank you!

**Comment by az-iot-builder-01** [comment]
@donniekerr, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
