### ISSUE TITLE
DPS X.509 Registration: UnauthorizedError

### ISSUE THREAD

**Issue by ancarda** [Azure/azure-iot-sdk-node#869]
I'm having some trouble getting the [register X509 sample code](https://github.com/Azure/azure-iot-sdk-node/blob/master/provisioning/device/samples/register_x509.js) to work. I'm running it with the following environmental variables:

```
PROVISIONING_REGISTRATION_ID=DPS-TestDevice001
PROVISIONING_HOST=AnExampleDPS.azure-devices-provisioning.net
PROVISIONING_IDSCOPE=[redacted]
CERTIFICATE_FILE=/path/to/cert.pem
KEY_FILE=/path/to/key.pem
```

Some things that may be good to know:

* The certificate's common name matches the registration ID.
* There's an individual enrollment of the same name, setup to statically assign to a specific IoT Hub.
* The CA that signed it has been uploaded to DPS and the linked IoT Hub and is verified on both.

However, I just get an unauthorized error. Do I need additional env vars or setup for authentication?

What am I'm doing wrong? I'd appreciate some ideas on how to move forward! 😄

AB#7830631

**Comment by anthonyvercolano** [comment]
@ancarda Just a thought, it's been a while since I looked at this.

Try setting PROVISIONING_HOST to global.azure-devices-provisioning.net

**Comment by ancarda** [comment]
Thanks, @anthonyvercolano 

I tried that but both domains give me the same error:

```json
{
  "errorCode": 401000,
  "trackingId": "xxxxxxxx-xxxx-4xxx-xxxx-xxxxxxxxxxxx",
  "message": "Unauthorized",
  "timestampUtc": "2020-07-29T15:29:17.8581268Z"
}
```

**Comment by anthonyvercolano** [comment]
hmm.  Well I suspect that something is wrong with your cert chain.

You've been able to register a device with symmetric key?

**Comment by ancarda** [comment]
Regarding the cert chain, I'm just doing CA -> leaf cert, though it's accepted by OpenSSL:

```
$ openssl verify -CAfile /path/to/ca-cert.pem cert.pem 
cert.pem: OK
```

The CA was uploaded to both IoT Hub and DPS, and I've validated it on both.

Does Azure require the use of intermediate certs? I can make a new cert chain if necessary.

**Comment by jebrando** [comment]
@ancarda DPS does not require intermediate certs you can just use the individual leaf certificate.  How did you create the certificate that you are using?

**Comment by ancarda** [comment]
I generated the leaf cert by making an RSA key and a CSR from that:

    openssl genrsa -out key.pem 2048
    openssl req -new -key key.pem -subj req -new -out csr.pem -subj "/C=GB/ST=XXX/L=XXX/O=XXXX/CN=DPS-TestDevice001"

Then I signed it like so:

    openssl ca -config openssl.cnf -infiles csr.pem

Which produced the following:

    Certificate:
        Data:
            Version: 3 (0x2)
            Serial Number: 17233682126254611135 (0xef2a5695fb679abf)
        Signature Algorithm: ecdsa-with-SHA1
            Issuer: C=GB, ST=XXX, O=XXX, CN=ca.invalid
            Validity
                Not Before: Jul 29 12:05:11 2020 GMT
                Not After : Jul 29 12:05:11 2021 GMT
            Subject: C=GB, ST=XXX, O=XXX, CN=DPS-TestDevice001
            Subject Public Key Info:
                Public Key Algorithm: rsaEncryption
                    Public-Key: (2048 bit)
                    Modulus:
                        00:c4:08:da:39:ba:20:e7:8e:14:54:34:9a:99:a5:
                        d8:53:ca:07:7a:67:57:aa:cb:6f:d3:e7:f1:5c:a6:
                        07:cd:c4:90:2c:98:86:24:fb:86:6f:82:91:ed:4c:
                        83:40:3d:1d:d7:94:2b:f0:e8:f7:b4:53:85:57:20:
                        1c:53:dc:c5:82:67:19:9b:ea:b1:8a:da:58:77:96:
                        b1:11:50:e8:4c:79:71:f9:58:24:4b:19:2e:4c:4f:
                        15:d1:9b:fd:89:bc:07:c8:e3:db:83:67:7b:27:10:
                        a9:8d:a7:0f:65:34:af:83:73:1f:a2:43:cb:2b:c2:
                        74:44:34:91:48:b2:3a:25:7b:27:d4:8d:19:1f:f1:
                        c1:8a:50:5f:d7:0e:52:ef:71:69:57:58:03:21:4c:
                        cd:e7:77:52:c6:2c:cd:70:92:4b:65:bf:46:a1:61:
                        0a:a8:60:1b:12:b8:e7:21:26:8f:43:44:ab:18:ab:
                        9d:2a:67:26:53:8e:54:77:5b:7e:71:a5:d9:55:b9:
                        6f:97:08:09:3a:15:a2:51:cd:e8:30:61:24:0b:6e:
                        c0:8a:33:be:aa:a1:25:9f:b5:f5:e4:6c:cd:5b:3e:
                        66:3a:79:84:98:70:a8:3b:5c:0e:30:be:1a:30:8d:
                        ee:c3:78:5d:cb:b9:a7:d5:8c:91:f2:53:f1:ba:b5:
                        ea:21
                    Exponent: 65537 (0x10001)
            X509v3 extensions:
                X509v3 Basic Constraints:
                    CA:FALSE
                X509v3 Subject Key Identifier:
                    FC:13:BB:F4:BC:78:33:0A:89:A2:97:23:63:F1:B4:70:04:F9:6F:DD
                X509v3 Authority Key Identifier:
                    keyid:24:97:8E:9D:5A:3E:25:B1:FA:0E:DB:B9:E6:D6:AE:AA:8D:C7:3E:16

        Signature Algorithm: ecdsa-with-SHA1
            30:44:02:20:0d:d9:82:ad:42:87:2a:be:31:cf:35:4f:78:04:
            2f:6b:29:af:09:5f:a6:41:16:89:09:23:f1:2a:a9:09:ce:f1:
            02:20:53:1e:c4:d2:59:5a:3c:fa:c3:30:26:f7:b7:66:ba:09:
            f3:95:5b:18:fc:1d:1b:a7:b3:d7:7e:67:a9:c9:ba:5e

A few things that popout:

 * SHA-1 was used for signing, does DPS/IoT Hub require SHA-256?
 * The CA uses ECDSA, whereas the root uses RSA. Is this a problem?

**Comment by ancarda** [comment]
I've generated a new certificate using elliptic curves and SHA-256:

    Certificate:
        Data:
            Version: 3 (0x2)
            Serial Number: 17233682126254611138 (0xef2a5695fb679ac2)
        Signature Algorithm: ecdsa-with-SHA256
            Issuer: C=GB, ST=XXX, O=XXX, CN=ca.invalid
            Validity
                Not Before: Jul 30 09:15:31 2020 GMT
                Not After : Jul 30 09:15:31 2021 GMT
            Subject: C=GB, ST=XXX, O=XXX, CN=DPS-TestDevice001
            Subject Public Key Info:
                Public Key Algorithm: id-ecPublicKey
                    Public-Key: (256 bit)
                    pub: 
                        04:ca:88:be:c3:d5:dd:20:8f:a2:f1:f0:9a:36:cd:
                        0d:a8:f1:7a:fe:c3:f1:93:1d:0e:24:c8:fa:3b:c6:
                        26:4a:23:9a:e5:66:96:c1:29:43:be:4a:5a:e5:89:
                        40:1e:45:81:ce:06:67:d1:84:51:0e:0d:f1:2e:cc:
                        99:24:43:a5:5c
                    ASN1 OID: prime256v1
                    NIST CURVE: P-256
            X509v3 extensions:
                X509v3 Basic Constraints: 
                    CA:FALSE
                X509v3 Subject Key Identifier: 
                    1F:FF:0D:79:DD:EB:E3:9B:A9:04:65:D6:7E:58:75:DD:3D:6A:84:4D
                X509v3 Authority Key Identifier: 
                    keyid:24:97:8E:9D:5A:3E:25:B1:FA:0E:DB:B9:E6:D6:AE:AA:8D:C7:3E:16

        Signature Algorithm: ecdsa-with-SHA256
            30:46:02:21:00:9a:9c:a4:98:80:a5:25:77:75:84:bb:b4:56:
            12:45:67:62:92:97:a8:30:52:4f:47:4f:6b:1b:47:13:2e:79:
            e5:02:21:00:86:10:cd:e1:56:bb:79:b4:7d:c3:20:54:0d:75:
            7d:cf:2d:2e:a4:ca:c7:74:29:4b:f3:e2:8d:8e:14:42:d5:00

The CA remains signed with SHA-1. I can make a new CA if necessary?

**Comment by anthonyvercolano** [comment]
This is the leaf cert that I made yesterday to test things out.  It worked.

```
Certificate:
    Data:
        Version: 1 (0x0)
        Serial Number: 313033648 (0x12a883b0)
    Signature Algorithm: ecdsa-with-SHA256
        Issuer:
            commonName                = Azure IoT SDK Test Root CA
        Validity
            Not Before: Jul 29 17:45:31 2020 GMT
            Not After : Jul 29 17:45:31 2021 GMT
        Subject:
            commonName                = bigkahuna
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:d7:7d:c7:43:76:df:15:03:b1:9a:52:29:ce:2b:
                    5c:56:ca:65:84:2e:63:e4:f6:1a:4d:f8:c5:77:15:
                    79:19:7f:f1:d5:36:29:9e:62:60:33:ca:fc:44:81:
                    6e:b4:b5:54:3f:04:84:5a:62:a5:bc:f6:80:0c:33:
                    01:4f:f7:de:71:3e:1e:fe:f0:33:56:67:8c:6b:af:
                    47:a3:dd:7f:84:63:c6:37:dc:91:c3:7a:0a:52:6f:
                    1d:08:71:db:db:1a:c8:2c:54:7d:95:1e:34:3b:38:
                    c0:8e:05:85:c5:fa:c8:04:49:7f:ff:8b:c2:d3:28:
                    ac:52:2c:ce:f4:c2:74:89:59:90:c7:e0:cd:92:26:
                    ff:cc:83:b9:80:6d:1f:7d:b8:57:92:b8:ab:21:74:
                    68:92:d5:8d:bd:0b:3b:60:60:bd:46:48:2e:f1:78:
                    cc:b4:c0:68:4c:37:95:fb:23:88:95:24:f4:06:13:
                    14:90:f3:c2:b3:9c:01:49:7c:1e:c7:d4:a5:c0:4f:
                    ab:b2:81:15:5c:72:c7:7c:c3:b8:c2:5b:f8:89:62:
                    c1:c4:d7:56:55:d5:1a:60:27:0d:4f:9e:8a:1a:36:
                    1b:28:68:8f:85:55:91:3b:c0:91:36:38:13:4d:08:
                    e8:40:b1:c3:5a:71:77:b2:c5:cc:f8:7d:81:8e:1d:
                    38:9f
                Exponent: 65537 (0x10001)
    Signature Algorithm: ecdsa-with-SHA256
         30:46:02:21:00:96:d7:e0:98:c9:77:68:c3:97:f6:46:55:d7:
         52:e3:a7:68:1c:3d:c5:aa:f7:d9:3a:9a:81:87:d7:bb:c3:61:
         ac:02:21:00:aa:28:6a:bc:43:9c:51:3a:93:9b:fd:9f:8e:ff:
         38:5b:03:75:b1:17:7c:6d:ce:58:e5:f4:62:e8:5d:7d:98:01
-----BEGIN CERTIFICATE-----
MIIB8DCCAZUCBBKog7AwCgYIKoZIzj0EAwIwJTEjMCEGA1UEAwwaQXp1cmUgSW9U
IFNESyBUZXN0IFJvb3QgQ0EwHhcNMjAwNzI5MTc0NTMxWhcNMjEwNzI5MTc0NTMx
WjAUMRIwEAYDVQQDDAliaWdrYWh1bmEwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw
ggEKAoIBAQDXfcdDdt8VA7GaUinOK1xWymWELmPk9hpN+MV3FXkZf/HVNimeYmAz
yvxEgW60tVQ/BIRaYqW89oAMMwFP995xPh7+8DNWZ4xrr0ej3X+EY8Y33JHDegpS
bx0IcdvbGsgsVH2VHjQ7OMCOBYXF+sgESX//i8LTKKxSLM70wnSJWZDH4M2SJv/M
g7mAbR99uFeSuKshdGiS1Y29CztgYL1GSC7xeMy0wGhMN5X7I4iVJPQGExSQ88Kz
nAFJfB7H1KXAT6uygRVccsd8w7jCW/iJYsHE11ZV1RpgJw1PnooaNhsoaI+FVZE7
wJE2OBNNCOhAscNacXeyxcz4fYGOHTifAgMBAAEwCgYIKoZIzj0EAwIDSQAwRgIh
AJbX4JjJd2jDl/ZGVddS46doHD3FqvfZOpqBh9e7w2GsAiEAqihqvEOcUTqTm/2f
jv84WwN1sRd8bc5Y5fRi6F19mAE=
-----END CERTIFICATE-----
```

I pulled the following code together from our e2e tests and a cert tool in build/tools to produce the cert.  It assumes that openssl is on the system.  Amusingly enough, the pem package (at least on windows) really does end up invoking the openssl command via a spawned processes.

The two environment variables contain the CA cert and key pems base64 encoded so they can be put in environment variables.  (It's a test system thing.)

```
'use strict';

var pem = require('pem');
var fs = require('fs');
var CARootCert = Buffer.from(process.env.IOTHUB_CA_ROOT_CERT, 'base64').toString('ascii');
var CARootCertKey = Buffer.from(process.env.IOTHUB_CA_ROOT_CERT_KEY, 'base64').toString('ascii');

var argv = require('yargs')
           .usage('Usage: $0 --deviceId <DEVICE ID> --daysValid <number of days valid>')
           .demand(['deviceId'])
           .default('daysValid', 1)
           .describe('deviceId', 'Unique identifier for the device that shall be created')
           .describe('daysValid', 'Number of days the certificate will remain valid')
           .argv;


function createCACertDevice(deviceId, done) {

  pem.createCSR( { commonName: deviceId }, function (err, csrResult) {
    if (err) {
      done(err);
    } else {
      pem.createCertificate(
        {
          csr: csrResult.csr,
          clientKey: csrResult.clientKey,
          serviceKey: CARootCertKey,
          serviceCertificate: CARootCert,
          serial: Math.floor(Math.random() * 1000000000),
          days: argv.daysValid
        }, function (err, certConstructionResult) {
        if (err) {
          done(err);
        } else {
          fs.writeFileSync(deviceId + '-cert.pem', certConstructionResult.certificate);
          fs.writeFileSync(deviceId + '-key.pem', certConstructionResult.clientKey);
        }
      });
    }
  });
}

createCACertDevice(argv.deviceId, (err) => {
 if (err) {
   console.log('error from cert creation:' + err.message);
 }
});
```

I note that you have some v3 extensions that I don't.

Perhaps Jelani might jump in about our ECC support.  I know that we support ECC but with some limits.  At least a couple of years ago I recall that a client connection that required ONLY ecc algorithms from start to finish couldn't be supported.

Check out ssllabs.com server check web tool on your fqdn for the hub.  It should give all the various supported suites.

**Comment by ancarda** [comment]
Thanks a lot @anthonyvercolano! The certificate you have made looks pretty similar to mine, and SSL Test seems to suggest Azure should accept `secp256r1`. I am starting to wonder if it's not the certificate...

Could you go over exactly what you did to make DPS accept your certificate? I'm wondering if perhaps I've misunderstood the documentation. I have been doing the following:

* Generate, upload, and verify a CA on DPS.
* Link an IoT Hub with the same uploaded and verified CA.
* Create an Individual Enrollment that uses X.509 CA Signed certs.
* Generate a leaf cert from the CA with the same common name as the individual enrollment.

Is that enough? Or are there more steps required / something I am doing wrong?

**Comment by torntrousers** [comment]
Hello @anthonyvercolano / anyone else who could help. I work with @ancarda and we are completely blocked with this not working. Can you help with those questions above? Any other suggestions for what we could try?
Thanks!

**Comment by anthonyvercolano** [comment]
I did exactly what you just said with the certs that we used previously in this issue.  It worked.

Does you have a cert chain or do you have just the root and the leaf (signed by that root).

**Comment by torntrousers** [comment]
Thanks. Any chance you could share with us the certificates and keys you used so we can try those?

**Comment by anthonyvercolano** [comment]
Sorry, can't do that.  The root is in use in our test infrastructure, and sharing the leaf would therefore be useless.

**Comment by torntrousers** [comment]
Ok what about we give you our certificates and keys for our CA and device so you can try them so at least we'll narrow down if they are ok?

**Comment by anthonyvercolano** [comment]
This is our root ca:

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            58:ca:09:6e:90:d0:a0:86:4a:31:22:16:12:c4:3b:55
    Signature Algorithm: ecdsa-with-SHA256
        Issuer:
            commonName                = Azure IoT SDK Test Root CA
        Validity
            Not Before: Jul 17 22:50:22 2017 GMT
            Not After : Jul 17 23:00:22 2027 GMT
        Subject:
            commonName                = Azure IoT SDK Test Root CA
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub: 
                    04:ef:29:72:42:0d:ee:1c:7a:43:4f:07:e5:23:21:
                    67:6c:fb:81:09:a3:04:6a:51:b6:b1:0e:02:b7:da:
                    64:b1:4b:cb:c8:df:eb:ea:11:e0:91:7e:cc:a3:28:
                    d6:b8:7b:d7:8b:88:77:b1:42:d6:de:a7:a5:12:30:
                    3e:b1:a7:fc:55
                ASN1 OID: prime256v1
        X509v3 extensions:
            X509v3 Key Usage: critical
                Certificate Sign
            X509v3 Extended Key Usage: 
                TLS Web Client Authentication, TLS Web Server Authentication
            X509v3 Subject Alternative Name: 
                DNS:CN=Azure IoT SDK Test Root CA
            X509v3 Subject Key Identifier: 
                D5:96:32:73:B0:DC:A4:11:1B:13:2F:E6:C6:C5:55:78:F1:32:D1:D9
    Signature Algorithm: ecdsa-with-SHA256
         30:44:02:20:23:cb:c4:19:63:7a:2a:a8:87:60:ae:83:eb:0e:
         0f:3f:e7:c0:a4:4c:66:4d:92:ca:69:98:5c:d5:e8:23:94:df:
         02:20:1f:38:39:be:ba:ba:ef:41:cc:52:3c:91:c2:fe:df:16:
         ae:92:1a:8a:dd:ed:ba:00:74:72:64:7d:ba:e8:60:b8
-----BEGIN CERTIFICATE-----
MIIBwTCCAWigAwIBAgIQWMoJbpDQoIZKMSIWEsQ7VTAKBggqhkjOPQQDAjAlMSMw
IQYDVQQDDBpBenVyZSBJb1QgU0RLIFRlc3QgUm9vdCBDQTAeFw0xNzA3MTcyMjUw
MjJaFw0yNzA3MTcyMzAwMjJaMCUxIzAhBgNVBAMMGkF6dXJlIElvVCBTREsgVGVz
dCBSb290IENBMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE7ylyQg3uHHpDTwfl
IyFnbPuBCaMEalG2sQ4Ct9pksUvLyN/r6hHgkX7MoyjWuHvXi4h3sULW3qelEjA+
saf8VaN6MHgwDgYDVR0PAQH/BAQDAgIEMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggr
BgEFBQcDATAoBgNVHREEITAfgh1DTj1BenVyZSBJb1QgU0RLIFRlc3QgUm9vdCBD
QTAdBgNVHQ4EFgQU1ZYyc7DcpBEbEy/mxsVVePEy0dkwCgYIKoZIzj0EAwIDRwAw
RAIgI8vEGWN6KqiHYK6D6w4PP+fApExmTZLKaZhc1egjlN8CIB84Ob66uu9BzFI8
kcL+3xaukhqK3e26AHRyZH266GC4
-----END CERTIFICATE-----
```

You'll note that I created it a few years ago.  I have to remember what I did.

Additionally you'll note a few of the V3 extended properties.

**Comment by ancarda** [comment]
Thank you for all your help, @anthonyvercolano! I'm happy to say this is now working! 🎉

-----

Should this be useful to [anyone else reading this thread](https://xkcd.com/979/), the key part seemed to be making a new CA with the following extensions:

```
X509v3 extensions:
    X509v3 Key Usage: critical
        Certificate Sign
    X509v3 Extended Key Usage: 
        TLS Web Server Authentication, TLS Web Client Authentication
    X509v3 Subject Key Identifier: 
        DF:65:E1:48:53:49:3E:62:8A:C0:81:91:C7:99:9D:95:9B:22:D8:EB
```

I dropped `Basic Constraints` and added `Key Usage` and `Extended Key Usage`.

I strongly suspect `CA:TRUE` and `CA:FALSE` weren't causing any problems, but rather the lack of constraints. I also seem to have dropped `Authority Key Identifier`, but I don't believe that is an issue either -- it's present in the leaf cert which has these extensions:

```
X509v3 extensions:
    X509v3 Subject Key Identifier: 
        07:8A:33:6B:47:6B:5F:2A:6F:31:21:B7:06:82:F4:75:94:95:73:56
    X509v3 Authority Key Identifier: 
        keyid:DF:65:E1:48:53:49:3E:62:8A:C0:81:91:C7:99:9D:95:9B:22:D8:EB
```

With these extensions in place, everything else worked! Both CA and leaf cert were using ECDSA (prime256v1/P-256) and SHA-256. No issues with that.

**Comment by az-iot-builder-01** [comment]
@ancarda, @jebrando, @torntrousers, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by anthonyvercolano** [comment]
@ancarda I'm glad you're moving forward.  Thanks for the xkcd link!

**Comment by PradeepKiruvale** [comment]
Have the same issue here as well. Below is my device certificate. Enrollment to dps is fine but registration fails. It says not authorized.

Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 42 (0x2a)
        Signature Algorithm: ecdsa-with-SHA256
        Issuer: CN = tbr
        Validity
            Not Before: Feb 14 14:38:41 2021 GMT
            Not After : May 16 14:38:41 2021 GMT
        Subject: CN = tbr
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    04:44:e0:57:f3:fd:f7:8d:ca:7d:1c:f1:41:e0:26:
                    82:47:30:65:97:a1:c4:2d:bb:cb:59:6b:db:25:7e:
                    67:c4:6e:5d:2c:0d:c1:c7:10:aa:e7:54:e0:cf:84:
                    ba:17:03:9c:a8:fb:42:ce:72:2e:35:dd:37:7b:f3:
                    2a:8d:fb:ff:0d
                ASN1 OID: prime256v1
                NIST CURVE: P-256
        X509v3 extensions:
            X509v3 Subject Key Identifier:
                C4:01:11:22:D7:92:13:04:F7:23:81:E5:24:D0:E5:68:10:32:7E:44
            X509v3 Basic Constraints: critical
                CA:TRUE
    Signature Algorithm: ecdsa-with-SHA256
         30:46:02:21:00:fe:53:a9:0d:53:eb:55:e1:37:24:c6:9c:10:
         72:00:66:f6:10:d6:05:11:ed:0e:c3:f6:88:0f:77:e0:ad:54:
         88:02:21:00:9a:d8:84:98:52:17:8a:56:bb:c1:39:c3:01:35:
         b6:74:96:25:67:77:bf:ba:b3:f9:54:cd:5d:b4:62:51:0d:6d

**Comment by khilscher** [comment]
If the above cert is for a device, CA should be FALSE

Here's a script to quickly generate some certs for DPS...https://github.com/khilscher/openssl_stuff/blob/main/create_certs.sh
