### ISSUE TITLE
IoT-Device Messages default encoding

### ISSUE THREAD

**Issue by KamalAman** [Azure/azure-iot-sdk-node#872]
IoT Device messages should default to `application/json` content type and `UTF-8` encoding.

```
    const message = new Message(JSON.stringify(data));
    message.contentEncoding = "utf-8";
    message.contentType = "application/json";
```

Currently users need to manually specify the default encoding and type to use things such as message routing in IoTHub based on the `$body`.

AB#7901112

**Comment by anthonyvercolano** [comment]
I would suggest that you make this request via user voice.

Not the first to ask this question.  Essentially though this would be viewed as a breaking change.  That does NOT stand much of chance of happening.

**Comment by az-iot-builder-01** [comment]
@KamalAman, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
