### ISSUE TITLE
Documentation for Identity Translation in Azure IoT Edge

### ISSUE THREAD

**Issue by ThomasPe** [Azure/azure-iot-sdk-node#882]
I'm using the Node SKD for Azure IoT in my IoT Edge Module to relay Blueooth messages as an IoT Device.
For this I'm currenlty setting the device connection string through the environment variables 

    const Transport = require('azure-iot-device-mqtt').Mqtt;
    const ModuleClient = require('azure-iot-device').ModuleClient;
    const Message = require('azure-iot-device').Message;
    const DeviceClient = require('azure-iot-device').Client;

    deviceClient = DeviceClient.fromConnectionString(sensorClientConnectionString, Transport);
    const json = JSON.stringify(messageFromBluetoothDevice, null, '\t')
    const sensorMsg = new Message(json);
    deviceClient.sendEvent(sensorMsg);

If I understand correctly this is not really the correct approach within IoT Edge runtime since this will directly send the message to the IoT Hub and I won't benefit wrong the runtime features like offline caching and batching - right? Does the Node SDK support this scenario currently?

What's the correct way to wrap a message in a iot device identity and then pass it back to the runtime like you would to with the module?

```
ModuleClient.fromEnvironment(Transport, function (err, moduleClient) {
    moduleClient.sendOutputEvent('output1', outputMsg, printResultFor('Sending received message'));`
});
```

AB#8109882

**Comment by anthonyvercolano** [comment]
@ThomasPe I would raise this in the Edge repo.  My edge skills are pitiful.

**Comment by anthonyvercolano** [comment]
Let me add that the node sdk itself only supports batching with the http protocol.  Offline caching is not a feature either.  If the connection goes down we will queue up internally the send as we attempt to re-establish, but I don't really think of this as caching.

**Comment by anthonyvercolano** [comment]
@ThomasPe I am assuming that you've raised this issue over with Edge.

**Comment by az-iot-builder-01** [comment]
@ThomasPe, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
