### ISSUE TITLE
Fix the dead links in the documentation

### ISSUE THREAD

**Issue by mrarmyant** [Azure/azure-iot-sdk-node#884]
In the main readme there are dozens of dead links to read mes and various other issues.  Remove them or update them.

AB#8139316

**Comment by elhorton** [comment]
Hi @mrarmyant , thanks for the heads up! Checking in a fix for these dead links now. Can you provide any more details on the "various other issues"? Would be great to improve the readme based on your feedback.

**Comment by elhorton** [comment]
Thanks @mrarmyant for the feedback! Let us know if you have additional thoughts. Closing this issue with a fix checked in: https://github.com/Azure/azure-iot-sdk-node/pull/886

**Comment by az-iot-builder-01** [comment]
@mrarmyant, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
