### ISSUE TITLE
[Technical Question] Device provision using custom allocation policy

### ISSUE THREAD

**Issue by amit12cool** [Azure/azure-iot-sdk-node#888]
I need to allocate my device using custom allocation policy for DPS. I have set up the infrastructure that is the enrollment group, Azure function and my device. I'm abe to send the custom payload to Azure function. But below are some issues I need help into:-

1) Is there any reference for NodeJS Azure function which handles the DPS custom allocation policy logic? I found for C# only in Azure docs.

2) Is it possible I parse the relevant payload in my Azure function and reassign the policy to say Evenly distributed thus IoT Hub for device registration will be chosen by DPS. 

3) Do you have any example to update the initial twin of the DPS in Azure function in Nodejs?

4) Also could you guide me to link in service sdk to create the parent chile relationship between edge device and leaf device.

Note:- Using custom allocation policy I just need to fetch the payload and update the initial twin of device only.

AB#8208968

**Comment by amit12cool** [comment]
@anthonyvercolano  Did you get a chance to look at this? 
I did an initial set up of Azure function in Nodejs as below:-
```
module.exports = async function (context, req) {
    const regId = req.body.deviceRuntimeContext.registrationId;
    console.log('regId is', regId);
    const response = {
        status: 200,
        message: 'Device registered successfully'
    };
    if (!regId)
    {
        response.status = 500
    }
    console.log('req is', JSON.stringify(req.body));
    const requestCustomPayload = req.body.deviceRuntimeContext.payload;
    console.log('edgeDeviceId is', req.body.deviceRuntimeContext.payload.edgeDeviceId);
    console.log('hubName is', req.body.deviceRuntimeContext.payload.hubName);
    context.res = {
        iotHubHostName: req.body.deviceRuntimeContext.payload.hubName
    };
}
```
In the above code I'm finding it difficult to update the twin state. Does the device provisioning service sdk for node js provides an api to update the initial twin like c# does [here](https://docs.microsoft.com/en-us/azure/iot-dps/how-to-use-custom-allocation-policies#create-the-custom-allocation-function).

**Comment by YoDaMa** [comment]
Hi @amit12cool, this question seems to be related to your other issue, #893. Thanks for your patience with both. To respond to your questions: 

> Is there any reference for NodeJS Azure function which handles the DPS custom allocation policy logic? I found for C# only in Azure docs.

No there is currently not. This is a helpful suggestion though and we will look into writing a Node.js specific guide for DPS custom allocation policy, in concert with the DPS team.

> Is it possible I parse the relevant payload in my Azure function and reassign the policy to say Evenly distributed thus IoT Hub for device registration will be chosen by DPS.

If you are creating a custom allocation policy you are [overriding the default allocation policy (evely weighted distribution)](https://docs.microsoft.com/en-us/azure/iot-dps/about-iot-dps#features-of-the-device-provisioning-service). Is this what you are referring to?

> Do you have any example to update the initial twin of the DPS in Azure function in Nodejs?

No. We will consider writing one.

> Also could you guide me to link in service sdk to create the parent chile relationship between edge device and leaf device.

Here is a guide, "Connect a downstream device to an Azure IoT Edge gateway", [linked here](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-connect-downstream-device?view=iotedge-2018-06#prepare-a-downstream-device).

**Comment by amit12cool** [comment]
@elhorton Apologies for delay in response. Most of you answers are clear except one to which I would like to discuss further:-

 -> If you are creating a custom allocation policy you are overriding the default allocation policy (evenly weighted distribution). Is this what you are referring to?
I need to fallback to the evenly distributed policy of DPS after parsing my payload in Azure function. Is this feasible through Azure function code?

**Comment by YoDaMa** [comment]
> ---->I need to fallback to the evenly distributed policy of DPS after parsing my payload in Azure function. Is this feasible through Azure function code?

This to me is confusing. You'll have to clarify your use case. Are you saying you want to set up a custom allocation policy, which uses the built in evenly weighted distribution? That sounds like you just want to use the default allocation policy, so I'm not sure why you would need a custom allocation policy set up via an Azure Function.

**Comment by amit12cool** [comment]
In my Azure function I just want to use the custom payload being sent by device and update the initial twin of the device only rest the iot hub returned from the Azure function should be based on evenly distributed algorithm.


________________________________

**Comment by rajeevmv** [comment]
If the allocation policy in DPS is set to custom allocation, it cannot fallback to the evenly weighted distribution policy based on the response from the custom function. When using custom allocation, you take on the functionality of selecting the Hub where the device should be placed.

**Comment by amit12cool** [comment]
Ok..Thanks that answers my question.

**Comment by nberdy** [comment]
Hi Amit. You can use whatever algo you like in your code. I recommend you hash by registration ID, but if that doesn't work for you then you can use one that gives you the distribution characteristics you are looking for.

**Comment by YoDaMa** [comment]
ok with that I will be closing this thread, since it has contained alot of different questions. If you would like to ask another question feel free to open another issue. For questions aligned toward the device provisioning service your best bet is to reach out to them directly, since the expertise of the maintainers of this repository is focused on the code in this repository.
