### ISSUE TITLE
Attestation Type assigned wrongly in IoTHub for DPS custom allocation policy

### ISSUE THREAD

**Issue by amit12cool** [Azure/azure-iot-sdk-node#893]
Use case:-

I have created a individual enrollment group in DPS using the self signed primary certificate. I'm using a Azure function for custom allocation policy in that individual enrollment group. Below is the code for Azure function:-
```
module.exports = async function (context, req) {
    const regId = req.body.deviceRuntimeContext.registrationId;
    context.log('Im here');
    context.log(JSON.stringify(req.body));
    if(req && req.body && req.body.deviceRuntimeContext && req.body.deviceRuntimeContext.payload && req.body.deviceRuntimeContext.registrationId) {
        const requestCustomPayload = req.body.deviceRuntimeContext.payload;
        context.res = {
            body: {
                iotHubHostName: req.body.deviceRuntimeContext.payload.hubName,
                initialTwin: {
                    authenticationType: 'selfSigned',
                    tags: {
                        iotScope: {
                            parentDeviceId: req.body.deviceRuntimeContext.payload.edgeDeviceId
                        }
                    },
                    properties: {
                        Desired: {}
                    }
                }
            }
        };
    } else {
        context.res = {
            status: 500,
            message: `Somethig went wrong. Req object is ${JSON.stringify(req)}`
        }
    }
}
```
Now, when I print the request body above I'm getting the correct body with attestation field as x509.
```
"attestation": {
      "type": "x509"
}
```
At this point everything is correct. Now, when the device is registered on the IoT hub and i see the same in portal it shows attestation type as ```sas```.

**Observation**:-
If I don't use custom allocation policy, it shows the correct attestation type in IoTHub i.e. X509

This seems to be a possible bug to me.
Please have a look at it on priority.

AB#8352832

**Comment by YoDaMa** [comment]
Hey @amit12cool, thanks for your patience. 

Can you provide some clarification on this issue? We've taken a look at it and are not sure on a few things you brought up. 

1) Are you using an individual enrollment or a group enrollment? 
2) Are you still able to repro this bug? If so could you provide the activity id, device id, dps info via a customer support request so we can investigate further? 

Because this is internal routing issues with Azure Functions, it is unlikely this is a DPS Client bug. If there was a bug it would show up when you don't use the custom allocation policy. So we will need to be able to see the backend logs, which require the information asked.

**Comment by elhorton** [comment]
Hi @amit12cool , do you need any more assistance? We will close this issue after 14 days of inactivity. [Here is also a blog post](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fyoseph-maguire.medium.com%2Fso-you-want-to-use-a-custom-allocation-policy-in-azure-iots-device-provisioning-service-and-c48ec9e2c366&data=04%7C01%7CElena.Horton%40microsoft.com%7C6d5d54a53efe448a5a1508d8c953d427%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637480709166175703%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=pwzqdRVMYcvYxOLn6NI9mjogLm%2F3F233Qzi0qorlPf4%3D&reserved=0) that may enjoy-- hope this helps!

**Comment by YoDaMa** [comment]
closing since issue is considered stale. If you have further questions with DPS feel free to open a new issue.
