### ISSUE TITLE
Make storage root key optional for TypeScript in provisioning service

### ISSUE THREAD

**Issue by Suizi11** [Azure/azure-iot-sdk-node#895]
# Context

- **list of installed packages:** azure-iot-provisioning-service: ^1.8.5 

## Description of the issue

I'd like to create an individual enrollment using the provisioning service SDK. I'm using the method `createOrUpdateIndividualEnrollment` of the `ProvisioningServiceClient` instance. If an `IndividualEnrollment` object will be created using **tpm** attestation type the storageRootKey is a required value when using TypeScript. When the individual enrollment is created in the Azure portal directly the root key can't be entered and isn't even shown anywhere.
For me it makes no sense to provide the storage root key, completely unnecessary, isn't it?

If the storage root key is provided as an empty string, I've to provide further properties (which I can't provide of course when creating an enrollment):
* registrationState
* iotHubHostName
* initialTwin
* etag
* provisioningStatus
* createdDateTimeUtc
* lastUpdatedDateTimeUtc
* iotHubs

## Code sample exhibiting the issue

```
let enrollment: IndividualEnrollment = {
                registrationId: gatewayId,
                deviceId: edgeDeviceId,
                attestation: {
                    type: 'tpm',
                    tpm: {
                        endorsementKey: value
                    }
                },
                capabilities: {
                    iotEdge: true
                }
            };
```

## Console log of the issue

![Screen Shot 2020-09-23 at 18 06 42](https://user-images.githubusercontent.com/11649054/94039113-9480a700-fdc7-11ea-8f03-6726e6d1f391.png)

AB#8376654

**Comment by jebrando** [comment]
I will look at this and reply back

**Comment by Suizi11** [comment]
Tank you @jebrando .

I've investigated on more issue related to this ticket.
In the Azure portal the re-provisioning setting is a required field, otherwise I can't save manual changes. If the registration enrollment is created without this setting (code snippet above) the portal shows a blank field. In the SDK the setting declared is optional, so I suppose any default setting is considered during the creation. Unfortunately, no value is set with the example from above.

In the type definition file of the SDK it's documented as following - but as mentioned above no default values are set:
```
/**
 * The behavior the service should adopt when a device is re-provisioned to another IoT Hub.
 */
export interface ReprovisionPolicy {
    /**
     * When set to true (default) the Device Provisioning Service will evaluate the device's hub assignment and update it if necessary
     * for any provisioning request beyond the first from a given device. If set to false the device will stay assigned to its current IoT hub.
     */
    updateHubAssignment: boolean;
    /**
     * When set to true (default) the Device Provisioning Service will migrate the device data (twin, device capabilities and device id)
     * from one hub to another during an IoT hub assignment update. If set to false the Device Provisioning Service will reset the device data to its
     * initial configuration stored in its corresponding enrollment.
     */
    migrateDeviceData: boolean;
}
```

**Comment by anthonyvercolano** [comment]
The error seen in the OP is returned by the provisioning service itself.  The SDK performs no validation of the enrollment object.  This is a policy decision.  We don't want two different sets of software deciding what's good or not.  So since the service side is going to do it anyway, we leave it to the service.

As for the second issue, when doing any update you should always to a get on the enrollment record and change the result and then send that object to the update.
