### ISSUE TITLE
Updated properties are not reflected in device-twin query

### ISSUE THREAD

**Issue by chdalski** [Azure/azure-iot-sdk-node#899]
I'm writing tests with Jest an Azure IoT-Hub and encountered a timing problem when updating the reported properties of a device twin, followed by querying the same twin to see if the changed properties are reflected in the result.

I use the following function to update the device properties:
```typescript
const updateDeviceTwinProperties = async (
  device: Client,
  properties: Object
) => {
  device.open();
  const twin = await device.getTwin();
  const updateProperties = promisify(twin.properties.reported.update);
  const result = await updateProperties(properties);
  device.close();
  return result;
};
```
And the following function to query the changed properties:
```typescript
const twinsByQueryFromIotHub = async (queryString: string) => {
  const query = registry.createQuery(queryString);
  const queryResponse = await query.nextAsTwin();
  return Promise.all(Array.from(queryResponse.result));
};
```
If the query follows directly after updating the properties the change is not reflected in the query.

I created a sample to test the issue, which can be found here:
https://github.com/chdalski/azure-iot-hub-jest-sample

AB#8436746

**Comment by jebrando** [comment]
@chdalski Thanks you for the issue.  When you update the twin there is a time to wait before it's reflected on the hub.  How long did you wait to query the twin?  How long till the twin change is reflected?

**Comment by chdalski** [comment]
@jebrando I've written 2 Tests - each updating the properties of the 2 devices. 
The first one has no wait and fails because the properties of the second update are not reflected in time.
The second one waits for 600 milliseconds after changing both devices properties and works as expected.
Please note that these 600 ms have no special meaning - it just works with it but i haven't tested if is less is possible or if more is needed in other cases.

**Comment by jebrando** [comment]
Let me talk to the hub to see if there a time-frame that would work for this.  I shall reply back

**Comment by BertKleewein** [comment]
@chdalski - In my experience, 600 ms is fast.  I don't know if there's a guaranteed delivery time, but I've had to write code to re-query every 2 seconds and I've seen it take 4-6 seconds in some cases.  I'm going off of an old memory, but I don't think anything "special" was happening with my code.  Your mileage may vary.

**Comment by chdalski** [comment]
@BertKleewein thank you for your thoughts and insights. 
I'm perfectly fine if it takes time for the properties to be updated and if that time varies. 
My problem is that I can't say when querying the properties will be successful or not because the function to update the properties comes back even if the updated properties are not available for query.
So I need to foresee how long it might take for the updated properties to be available for querying.
I had hoped that the function would come back after it assured that the update was successful and the properties are ready to be queried.

**Comment by anthonyvercolano** [comment]
This is really more of a service issue.  There is nothing that an SDK can do to help.

**Comment by anthonyvercolano** [comment]
Hiimm this doesn't actually report closed

**Comment by anthonyvercolano** [comment]
Closing it again
