### ISSUE TITLE
Messages properties not supported on MQTT

### ISSUE THREAD

**Issue by stewartadam** [Azure/azure-iot-sdk-node#9]
Opening this to continue tracking lack of support for sending message properties from MQTT, per https://github.com/Azure/azure-iot-sdks/issues/414.

I recently came across that issue page after wasting lots of time trying to debug why configured IoT Hub routes were not triggering after using the sample included in the device SDK and adding a simple `message.properties.add("level", "critical");` line to it, per the [C# sample](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-csharp-csharp-process-d2c).

This limitation (and any other similar gaps) should be documented and **visible** until resolved.

**Comment by pierreca** [comment]
Thanks a lot for raising this issue. We are aware of this limitation and have it in our backlog to fix this, I'll try and raise the priority of this task.

**Comment by stewartadam** [comment]
Thanks, I'll keep an eye on the issue for updates.

I would suggest that we note known incomplete features like this in a section in the README or a known issues document. In this case, it might make sense to throw if the properties dictionary was mutated & sent over MQTT until this is resolved -- this would help avoid the silent failure.

**Comment by pierreca** [comment]
Took care of it: https://github.com/Azure/azure-iot-sdk-node/commit/784f5dc195534d0a6be765d457509c2aa04d12fc

you can test it by checking out the develop branch, it'll be pushed to public packages for our next release in the next few days.

**Comment by stewartadam** [comment]
Thanks! Looking forward to testing it when it's out on npm.

**Comment by pierreca** [comment]
Packages have been released to npm (version 1.1.3). Thanks!
