### ISSUE TITLE
"AMQP Transport: Could not send message" error sending a C2D message

### ISSUE THREAD

**Issue by paolerm** [Azure/azure-iot-sdk-node#907]
# Context

- **list of installed packages:** 1.9.5

## Description of the issue

IoTC side we encountered a transient issue sending C2D message to one IoThub tenant between 2020-10-04 17:44 UTC and 2020-10-05 04:20 UTC

It auto-resolved after a while, but we would like to know the root cause of this issue.

## Code sample exhibiting the issue

[IoTC repo](https://msazure.visualstudio.com/One/_git/azure-iots-saas?path=%2Fservice-iothubmgmt%2Fsrc%2Fservice%2Fservices%2Fdevice%2FtwinService.ts&version=GBdevelop&line=385&lineEnd=386&lineStartColumn=1&lineEndColumn=1&lineStyle=plain)

## Console log of the issue

{
  "stack": "Error: AMQP Transport: Could not send message\n    at Object.translateError (/app/node_modules/azure-iot-amqp-base/lib/amqp_common_errors.js:99:17)\n    at Object.translateError (/app/node_modules/azure-iothub/lib/amqp_service_errors.js:21:39)\n    at /app/node_modules/azure-iothub/lib/amqp.js:34:43\n    at /app/node_modules/azure-iothub/lib/amqp.js:114:33\n    at constructor._onEnter (/app/node_modules/azure-iothub/lib/amqp.js:93:33)\n    at constructor.transition (/app/node_modules/machina/lib/machina.js:653:28)\n    at constructor.Fsm.<computed> [as transition] (/app/node_modules/machina/lib/machina.js:466:63)\n    at /app/node_modules/azure-iothub/lib/amqp.js:166:44\n    at /app/node_modules/azure-iot-amqp-base/lib/amqp.js:769:51\n    at processTicksAndRejections (internal/process/task_queues.js:79:11)",
  "message": "AMQP Transport: Could not send message",
  "amqpError": {
    "name": "NotConnectedError"
  }
}

AB#8579385

**Comment by jebrando** [comment]
It looks like there was a network disruption in the communication from hub to device.  To get more information from this situation you can open a ticket on the IoTHub Service to get an RCA.

**Comment by az-iot-builder-01** [comment]
@paolerm, @jebrando, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by elhorton** [comment]
closing this because RCA analysis must be done through an IoT Hub service ticket, data will not be available now
