### ISSUE TITLE
Support for Layered Deployments

### ISSUE THREAD

**Issue by KamalAman** [Azure/azure-iot-sdk-node#913]
I am trying to adopt layered deployments in our IoTHub solution, however it does not seem like this SDK has any support for uploading a layered deployment. 

Is layered deployment management functionality on your near term roadmap? 

AB#8802130

**Comment by YoDaMa** [comment]
Hey @KamalAman. I honestly don't know what layered deployments are outside of IoT Edge. Can you add some more context? Are you trying to use the SDK with IoT Edge, or seeing if we have some version of automated updates that would be pushed to your device from the SDK?

**Comment by KamalAman** [comment]
Hi @YoDaMa,

I was trying to upload a layered deployment manifest to IoT Hub, and expecting that I would have needed to somehow specify an equivalent for `--layered`. 

However, after further testing it seems like IoT Hub automatically detects if a deployment manifest is a Layered Deployment when it is uploaded. This automatically occurs when a partial manifest if uploaded.

**Comment by az-iot-builder-01** [comment]
@YoDaMa, @KamalAman, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
