### ISSUE TITLE
Allow devices to add custom metadata to uploaded files

### ISSUE THREAD

**Issue by djosemartine** [Azure/azure-iot-sdk-node#916]
It would be very convenient to allow the devices to set custom metadata to the uploaded file.
Some options that cross my mind:

1. [Setting metadata to the blob resource](https://docs.microsoft.com/en-us/rest/api/storageservices/setting-and-retrieving-properties-and-metadata-for-blob-resources)
2. Enriching the [file upload notification](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-file-upload#file-upload-notifications)

thoughts?

**Comment by elhorton** [comment]
Hi @djosemartine , thanks for the feedback! Would you mind elaborating a bit more on your scenario so we can better understand the limitation? What "enrichment" are you thinking of when it comes to the file upload notification? Thanks!

**Comment by djosemartine** [comment]
> Hi @djosemartine , thanks for the feedback! Would you mind elaborating a bit more on your scenario so we can better understand the limitation? What "enrichment" are you thinking of when it comes to the file upload notification? Thanks!

**Comment by az-iot-builder-01** [comment]
@djosemartine, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by djosemartine** [comment]
Hi @elhorton, thanks for writing back. I closed the issue by mistake but I could reopen it again. Let me explain better the feature request:
The [Device Client](https://github.com/Azure/azure-iot-sdk-node/blob/master/device/core/src/device_client.ts#L164) does not support to add [metadata](https://docs.microsoft.com/en-us/rest/api/storageservices/setting-and-retrieving-properties-and-metadata-for-blob-resources) to the files to be uploaded. Iw would be very helpful if the upload-to-blob method had an option to set that metadata, something like:
 uploadToBlob(blobName: string, blobMetadata: Map<string, string>, stream: Stream, streamLength: number): Promise<void>;
 The metadata is really useful to process the file once it is uploaded.
 
 On other hand, It would be also helpful to add the blob metadata to the [file notification message](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-file-upload#file-upload-notifications), such as:
{
    "deviceId":"mydevice",
    "blobUri":"https://{storage account}.blob.core.windows.net/{container name}/mydevice/myfile.jpg",
    "blobName":"mydevice/myfile.jpg",
    "blobMetadata": {
       "key": "value"
     }
    "lastUpdatedTime":"2016-06-01T21:22:41+00:00",
    "blobSizeInBytes":1234,
    "enqueuedTimeUtc":"2016-06-01T21:22:43.7996883Z"
}

What do you think?

**Comment by elhorton** [comment]
got it, thanks @djosemartine ! That makes sense, and agreed that the enrich option is unfortunately outside the scope of the SDK. Adding metadata is feasible-- I've added it to our feature backlog and will keep this issue updated as we evaluate this in the new year.

**Comment by YoDaMa** [comment]
Hi @djosemartine, taking a look at this issue. We have an API for more fine grained use of the uploadToBlob. See the example: https://github.com/Azure/azure-iot-sdk-node/blob/master/device/samples/upload_to_blob_advanced.js 

Because it's just getting the information from IoT hub to communicate with the storage blob api it gives you more control over using custom metadata.

**Comment by anthonyvercolano** [comment]
This is something that would just go in your  application logic.

**Comment by djosemartine** [comment]
> This is something that would just go in your application logic.

It works. Thanks
