### ISSUE TITLE
How to receive the telemetry data from IoT Hub by using SDK?

### ISSUE THREAD

**Issue by AshokPeddakotla-MSFT** [Azure/azure-iot-sdk-node#917]
This query was raised by @MaxKinny.

This [tutorial](https://docs.microsoft.com/en-us/learn/modules/remotely-monitor-devices-with-azure-iot-hub/) only teaches us how to send and receive telemetry data directly using Azure IoT SDK. In the tutorial, the virtual devices directly use the client.sendEvent() method.

However, in the case of the IoT Edge device, we use IoT Edge Hub to route this telemetry message to IoT Hub. Concretely, define the route: From <module output source> INTO $upstream, in which $upstream refers to IoT Hub. In this case, how can we use the SDK to receive this module's telemetry data from IoT Hub? Could you please show me a code snippet example? Thank you very much!

Ref issue: https://github.com/MicrosoftDocs/azure-docs/issues/68403

**Comment by elhorton** [comment]
Hi @AshokPeddakotla-MSFT , it sounds like you need to use the Event Hub SDK for this. That is how to read telemetry data from an IoT Hub. [Here's an overview and code snippets](https://docs.microsoft.com/en-us/javascript/api/overview/azure/event-hubs-readme?view=azure-node-latest). Does this address your question?

**Comment by AshokPeddakotla-MSFT** [comment]
@MaxKinny Please check the above response and let us know if that answers your query.

**Comment by MaxKinny** [comment]
Yes, you're right @elhorton, thank you very much @AshokPeddakotla-MSFT @elhorton !!

**Comment by elhorton** [comment]
great to hear, thanks @MaxKinny ! I'll close this issue now.
