### ISSUE TITLE
EnrollmentGroup in the provisioning service SDK is missing the capabilities option

### ISSUE THREAD

**Issue by jlorich** [Azure/azure-iot-sdk-node#922]
In the Provisioning Service SDK, [IndividualEnrollment](https://docs.microsoft.com/en-us/javascript/api/azure-iot-provisioning-service/individualenrollment?view=azure-node-latest) provides an option for `capabilities` which allows you to specify that a device is an IoT Edge device.  However, [EnrollmentGroup](https://docs.microsoft.com/en-us/javascript/api/azure-iot-provisioning-service/enrollmentgroup?view=azure-node-latest) does not provide this option even though being able to make Edge Device Enrollment Groups is something we support in the portal, API, and other SDKs.

**Is your feature request related to a problem? Please describe.**
This feature request is for a missing API capability in the SDK.

**Describe the solution you'd like**
Add `capabilities` to `EnrollmentGroup` so groups can have Edge devices configured from the Node SDK.

**Describe alternatives you've considered**
Bypassing the SDK and using the HTTP API directly or using the .NET SDK.

**Additional context**
This feature is [already supported by the .NET SDK](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.provisioning.service.enrollmentgroup.capabilities?view=azure-dotnet#Microsoft_Azure_Devices_Provisioning_Service_EnrollmentGroup_Capabilities)

**Comment by anthonyvercolano** [comment]
@jlorich We will get this fixed the first week of February.  We are looking to push a new patch release next week so this will be part of that.
