### ISSUE TITLE
getBlobSharedAccessSignature calls on device_client.js failing with connection timeout error behind a corporate HTTP proxy.

### ISSUE THREAD

**Issue by ksin63** [Azure/azure-iot-sdk-node#925]
As an alternate to uploadToBlob method to save SAS token quota from IotHub. I am directly using **_getBlobSharedAccessSignature_** and **_notifyBlobUploadStatus_** method to control when to acquire token or reuse existing token in case of file upload failure/retry scenario. My workflow is described below

1. Use IoT SDK to acquire SAS token:
2. Use Azure Storage SDK to upload file:
3. Again use IoT SDK to notify IoT Hub about success or failure:

This works perfectly in normal environment with edge having direct internet connectivity, though it fails when the edge-proxy is running behind the corporate firewall with below error.
**_Encountered unrecoverable error: Error: connect ETIMEDOUT 13.79.172.43:443_** 

After a quick glance on the source code it seems the developer in this [PR-Add proxy support to blob file upload in Device SDK](https://github.com/Azure/azure-iot-sdk-node/pull/589) missed to apply setOptions for **_FileUploadApi_**. 

A quick fix should go as below
```
setOptions(options: DeviceClientOptions, done?: Callback<results.TransportConfigured>): Promise<results.TransportConfigured> | void {
    if (!options) throw new ReferenceError('options cannot be falsy.');
    if (this._blobUploadClient) {
      /*Codes_SRS_NODE_DEVICE_CLIENT_99_103: [The `setOptions` method shall set `blobUploadClient` options.]*/
      this._blobUploadClient.setOptions(options);
    }
    /* Implicit call of setOption for fileUploadApi here*/
    if (this._fileUploadApi) {
       /* [The `setOptions` method shall set `fileUploadApi` options.]*/
       this._fileUploadApi.setOptions(options);
    }
    return super.setOptions(options, done);
  }
```

**Comment by abossard** [comment]
Would it be possible to backport the fix also to version `1.17.0-lts0720up1`?

**Comment by YoDaMa** [comment]
@abossard we unfortunately only backport security issue patches to LTS releases. Bug fixes like this are the purpose of the main branch.

**Comment by anthonyvercolano** [comment]
@abossard Is this blocking production?
