### ISSUE TITLE
Node.js v12 support for azure-iot-security-tpm

### ISSUE THREAD

**Issue by steinera** [Azure/azure-iot-sdk-node#930]
At the moment it is not possible to use azure-iot-security-tpm with Node.js version 12 or higher. This is because the dependency build of the used ref-package fails.
```
C:\<repo>\node_modules\ref>if not defined npm_config_node_gyp (node "C:\Users\<user>\AppData\Roaming\nvm\v12.16.1\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\<user>\AppData\Roaming\nvm\v12.16.1\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  binding.cc
  win_delay_load_hook.cc
..\src\binding.cc(222): error C2661: 'v8::Value::BooleanValue': no overloaded function takes 0 arguments [C:\<repo>\node_modules\ref\build\binding.vc
xproj]
...
```

**Comment by steinera** [comment]
We like to continue our work with azure-iot-security-tpm, but at the moment we are unsure if it would make sense to wait for a fix. Does someone work on it and if so how long will it take until the fix is merged to the latest master? A rough estimation will be sufficient, are we talking about days, weeks or even months. 

Thanks

**Comment by anthonyvercolano** [comment]
@steiner We were talking about weeks.

**Comment by anthonyvercolano** [comment]
@Steiner 
We need to do the following:
We need to change the tss javascript library to use the newest version of ffi-napi.  going from 2.4.3 -> 4.0.3
This could produce incompatible changes.  I have yet to see.
I will then have to release a new version of that library (tss.js).  I am not the owner of the repo.
Need to validate the various scenarios with this library.
Then release a new node SDK using the new tss.js
Node is ready to release at any moment once we get these first few issues done.
I am looking at a couple of days without interruption to get first part done.  Looking at a few days to getting to a release of tss.js.  Unless there are incompatible changes.  (Incompatible changes could easily add a week.)
Couple of days of validation.
Couple of hours to release the SDK.

**Comment by schumajs** [comment]
Hello @anthonyvercolano, is there any update on this?

**Comment by anthonyvercolano** [comment]
Fixed in release of 09/09/21
