### ISSUE TITLE
When is the Node-RED node's next release? [feature request] 

### ISSUE THREAD

**Issue by dzeyelid** [Azure/azure-iot-sdk-node#953]
**Is your feature request related to a problem? Please describe.**

I revise a book that is how to use Node-RED and I introduce how to connect to Azure IoT Hub using Node-RED node `node-red-contrib-azureiothubnode` in the book. I would like to continue using the node but the node has a problem that sends telemetry as converted base64.

So I requested small changes about that in this PR #947 and that was merged. Thank you, I appreciate the approval and merge.

And I would like to make the update in time for the deadline of our revise. If the update is not available in time, I have to change the way to connect IoT Hub and I would guess it is disappointed we miss the opportunity that Node-RED users can use this official node.

**Describe the solution you'd like**
So I would just like to hear the release schedule of Node-RED node `node-red-contrib-azureiothubnode` with the update.

**Describe alternatives you've considered**
If the update is not available in time, I will stop using the node and replace it.

**Additional context**

FYI, see for details about the book. We revise the book again to follow today's tech.

- http://www.kohgakusha.co.jp/books/detail/978-4-7775-2053-4
- https://www.amazon.co.jp/dp/4777520536/

**Comment by anthonyvercolano** [comment]
Well, we haven't done anything with Node-RED in quite a while.  I would have mostly said it's not really supported. BUT, you made a change that will help you.

I have a release planned in the next week or so.  I will publish the package on this next release.

**Comment by dzeyelid** [comment]
Thank you so much!

**Comment by kazuhitoyokoi** [comment]
I'm looking forward to reading the book. 👍
