### ISSUE TITLE
[Technical Question]how to let the device retry infinitely until the network comes back

### ISSUE THREAD

**Issue by sunhubs** [Azure/azure-iot-sdk-node#967]
hi there,
    I encounter an issue that the device only retry 5 times even if i set the RetryPolicy. My scenario is below:
    **_1, I need to use a proxy server to setup connection.
    2, at the beginning proxy server is started, create the iot connection successfully. Then set the retry policy for device client.
    3, then stop the proxy server, the device client detect the disconnection, and then device try to reconnect, the retry interval is as defined in retry policy. but the retry stopped after 5 retries._** 
     my code script  is as below:
    `    
        // create connection

         this.client.open()
          // set retry policy
          const retry_policy = {
            shouldRetry: (error) => {
              // decide depending on err if you would like to retry or not - should return true or false.
              // retry for all errors
              this.logger.error(`retry policy handler says iot connection encounters error ${error.toString()}`)
              return true
            },
            nextRetryTimeout: (retry_count, throttled) => {
              // should return an integer that is the number of milliseconds to wait before the next retry
              // based on the current count of retries (retryCount)
              // and if the IoT Hub is asking clients to throttle their calls (throttled, boolean)
              this.logger.info(`retry policy handler says iot connection will retry after 1 minute, current retry count ${retry_count}`)
              return 60 * 1000
            }
          }
          this.client.setRetryPolicy(retry_policy)
`
    my device behavior after proxy server is stopped is as below:
`
May 13 02:04:23 sg-controller[1] INFO:  iot connection set up successfully

May 13 02:07:23 sg-controller[1] ERROR: retry policy handler says iot connection encounters error NotConnectedError: Connection to the server has been closed.
May 13 02:07:23 sg-controller[1] ERROR: retry policy handler says iot connection encounters error NotConnectedError: Connection to the server has been closed.
May 13 02:07:23 sg-controller[1] ERROR: retry policy handler says iot connection encounters error NotConnectedError: connect ECONNREFUSED 192.168.131.1:8080
May 13 02:07:23 sg-controller[1] INFO:  retry policy handler says iot connection will retry after 1 minute, current retry count 1
May 13 02:08:23 sg-controller[1] ERROR: retry policy handler says iot connection encounters error NotConnectedError: connect ECONNREFUSED 192.168.131.1:8080
May 13 02:08:23 sg-controller[1] INFO:  retry policy handler says iot connection will retry after 1 minute, current retry count 2
May 13 02:09:23 sg-controller[1] ERROR: retry policy handler says iot connection encounters error NotConnectedError: connect ECONNREFUSED 192.168.131.1:8080
May 13 02:09:23 sg-controller[1] INFO:  retry policy handler says iot connection will retry after 1 minute, current retry count 3
May 13 02:10:23 sg-controller[1] ERROR: retry policy handler says iot connection encounters error NotConnectedError: connect ECONNREFUSED 192.168.131.1:8080
May 13 02:10:23 sg-controller[1] INFO:  retry policy handler says iot connection will retry after 1 minute, current retry count 4
May 13 02:11:23 sg-controller[1] ERROR: retry policy handler says iot connection encounters error NotConnectedError: connect ECONNREFUSED 192.168.131.1:8080
May 13 02:11:23 sg-controller[1] INFO:  retry policy handler says iot connection will retry after 1 minute, current retry count 5
May 13 02:11:23 sg-controller[1] ERROR: iot client eddy-iot-device-2 connection is down. will reconnect
`
     as you see, the retry interval is as defined in retry policy, but why only 5 retries? As I want a continuous retry, is there some way to change the retry count?

**Comment by sunhubs** [comment]
if there is other practice guide for connection recovery, it is appreciate that you can provide a sample code. Thanks

**Comment by anthonyvercolano** [comment]
@sunhubs
Try enabling debugs with the environment variable, DEBUG="azure*"
That should give a lot more information about what the client is attempting to do.

**Comment by anthonyvercolano** [comment]
@sunhubs   Actually you could also try DEBUG="azure-iot-common:RetryOperation".  That should give you significantly less debugs.

**Comment by sunhubs** [comment]
@anthonyvercolano thanks for your suggestion, I did see the debugs that there is retryoperations in SDK by default, but it is not infinitely and will stop after a few tries. so I have turned to disable the retry in SDK and use setInterval to do retry in my own control.
