### ISSUE TITLE
IoTHub returning different format error when Device Not Found

### ISSUE THREAD

**Issue by InteliCare** [Azure/azure-iot-sdk-node#971]
# Context

any platform.
azure-iothub@1.14.0 (also tried rolling back to 1.13.1)

## Description of the issue

Azure IoTHub suddenly started sending a different format 404 error that is not handled correctly by the azure-iot-http-base method parseErrorBody. 

## Code sample exhibiting the issue

await Registry.getTwin('nonexistanttwin') 
throws 'Not found' instead of previous 'DeviceNotFoundError'

in rest_api_client.ts:

```
      case 404:
        if (errorContent && errorContent.code === 'DeviceNotFound') {
        /*Codes_SRS_NODE_IOTHUB_REST_API_CLIENT_16_018: [`translateError` shall return an `DeviceNotFoundError` if the HTTP response status code is `404` and if the error code within the body of the error response is `DeviceNotFound`.]*/
          error = new errors.DeviceNotFoundError(message);
        } else if (errorContent && errorContent.code === 'IotHubNotFound') {
          /*Codes_SRS_NODE_IOTHUB_REST_API_CLIENT_16_017: [`translateError` shall return an `IotHubNotFoundError` if the HTTP response status code is `404` and if the error code within the body of the error response is `IotHubNotFound`.]*/
          error = new errors.IotHubNotFoundError(message);
        } else {
          error = new Error('Not found');
        }
        break;
```

Issue is fixed for us internally by handling the "Not found" error.message as well as the previous DeviceNotFound error.message value. Thought it would be a good idea to create this bug issue anyway.

**Comment by Compaurum** [comment]
the same issue

**Comment by vishnureddy17** [comment]
@InteliCare Thanks for bringing this issue to our attention. We expect a fix from the service coming within the next three weeks. Apologies for any issues this may cause.

**Comment by InteliCare** [comment]
@vishnureddy17 Thanks, it shouldn't cause us any further problems, it only really turned a warning into an error which meant it had to be addressed. Cheers.

**Comment by vishnureddy17** [comment]
Closing this issue as the fix to the service has been rolled out.
