### ISSUE TITLE
Need the list of device Id and iothub name from sdk

### ISSUE THREAD

**Issue by vikas-mundra** [Azure/azure-iot-sdk-node#972]
Is there any method in node service SDK to get **Registration Records** from the enrollment group?
I am able to fetch Registration Records from the below command 

**az iot dps registration list --dps-name xxxx --enrollment-id xxxx --resource-group xxxxx**

And got the following response that is below.
[{
    "assignedHub": "xxxxx.azure-devices.net",
    "createdDateTimeUtc": "2021-04-14T15:00:18.8535608Z",
    "deviceId": "xxxxx",
    "etag": "xxxxx",
    "lastUpdatedDateTimeUtc": "2021-04-14T15:00:19.1458556Z",
    "registrationId": "xxxxx",
    "status": "assigned",
    "substatus": "initialAssignment"
  },
  {
    "assignedHub": "xxxx.azure-devices.net",
    "createdDateTimeUtc": "2021-03-26T10:36:27.6608167Z",
    "deviceId": "xxxxx",
    "etag": "xxxxxx",
    "lastUpdatedDateTimeUtc": "2021-03-26T10:36:28.2834046Z",
    "registrationId": "xxx",
    "status": "assigned",
    "substatus": "initialAssignment"
  }]

But I need to get Registration Records using nodeJs service SDK.
let me know what is the way to do it.

**Comment by anthonyvercolano** [comment]
[Query registrations samples
](https://github.com/Azure/azure-iot-sdk-node/blob/master/provisioning/service/samples/query.js#L54)
