### ISSUE TITLE
WS dependency fails npm audit

### ISSUE THREAD

**Issue by DaveDHitachi** [Azure/azure-iot-sdk-node#979]
- **OS and version used:** <VERSION>  Windows 10
- **Node.js version:** <VERSION> v14.17.0
- **npm version:** <VERSION> 6.14.13

After running 'npm audit' in my project I get the following error:

=== npm audit security report ===                        
                                                                                
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ ws                                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=7.4.6                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ azure-iothub                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ azure-iothub > azure-iot-amqp-base > ws                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1748                            │
└───────────────┴──────────────────────────────────────────────────────────────┘

**Comment by anthonyvercolano** [comment]
Patch should be going out this coming Monday.

**Comment by anthonyvercolano** [comment]
@DaveDHitachi  Might take an extra day or two.  Unless your application is actually creating it's own service as well as being a device, you shouldn't be subject to this vulnerability.

**Comment by anthonyvercolano** [comment]
Released
