### ISSUE TITLE
event not triggered when file is sent with Iothub SDK

### ISSUE THREAD

**Issue by mjeannin2** [Azure/azure-iot-sdk-node#983]
# Context

SDK IOTHUB on nodeJS 
Windows 10.x
"azure-iothub": "^1.12.0"
https://www.npmjs.com/package/azure-iothub
Node.js v14.15.3

## Description of the issue

Step to reproduce :
Send message using the nodeJS IOTHUB API 

subscribe to the receiver notification

serviceClient = Client.fromConnectionString(connectionString, Amqp);
serviceClient.getFileNotificationReceiver(...)

Expected result : an event is triggered each time a file is received by IOTHUB
Observed result : Sometime, the event is not triggered.

**Comment by anthonyvercolano** [comment]
Have looking logs after setting the environment variable DEBUG="azure*" helped any?

You service client (1.12.0) is fairly old.  Older than all the LTS's.

You might consider updating.

**Comment by anthonyvercolano** [comment]
Closed due to inactivity.  Feel free to open with further information.
