### ISSUE TITLE
azure-iothub dependencies failure

### ISSUE THREAD

**Issue by hihigupt** [Azure/azure-iot-sdk-node#985]
Failing build because of dependencies missing.

> ts-e2e@1.0.0 build
> tsc

node_modules/azure-iothub/dist/amqp.d.ts:7:29 - error TS2307: Cannot find module '@azure/core-http' or its corresponding type declarations.

7 import { AccessToken } from '@azure/core-http';
                              ~~~~~~~~~~~~~~~~~~

node_modules/azure-iothub/dist/client.d.ts:8:33 - error TS2307: Cannot find module '@azure/core-http' or its corresponding type declarations.

8 import { TokenCredential } from '@azure/core-http';
                                  ~~~~~~~~~~~~~~~~~~

node_modules/azure-iothub/dist/job_client.d.ts:5:33 - error TS2307: Cannot find module '@azure/core-http' or its corresponding type declarations.

5 import { TokenCredential } from '@azure/core-http';
                                  ~~~~~~~~~~~~~~~~~~

node_modules/azure-iothub/dist/registry.d.ts:9:33 - error TS2307: Cannot find module '@azure/core-http' or its corresponding type declarations.

9 import { TokenCredential } from '@azure/core-http';
                                  ~~~~~~~~~~~~~~~~~~

node_modules/azure-iothub/node_modules/azure-iot-http-base/dist/rest_api_client.d.ts:3:46 - error TS2307: Cannot find module '@azure/core-http' or its corresponding type declarations.

3 import { AccessToken, TokenCredential } from '@azure/core-http';
                                               ~~~~~~~~~~~~~~~~~~


Found 5 errors.


My package.json looks like:

  "dependencies": {
    "@azure/core-http": "^1.2.5",
    "@azure/identity": "1.2.5",
    "@azure/event-hubs": "^1.0.8",
    "@azure/ms-rest-js": "^2.0.5",
    "@types/mocha": "^7.0.2",
    "@types/node": "^13.9.0",
    "azure-iot-common": "^1.12.9",
    "azure-iot-provisioning-service": "1.8.8",
    "azure-iothub": "^1.14.1",
    "chai": "^4.2.0",
    "minimist": "^1.2.5",
    "mocha": "^7.1.1",
    "terminate": "^2.1.2",
    "typescript": "^3.8.3",
    "yargs": "^15.3.0"
  },

**Comment by anthonyvercolano** [comment]
Updated the dependencies for the hub and updated the version for provisioning.
